### PR TITLE
cleanup: resolves gofumpt issues in e2e

### PR DESCRIPTION
**Pull request by yati1998**
This commit resolves gofumpt issues in
e2e folder.

Updates: #1586
Depends-on: #2265

### CODE REVIEW

**Review by nixpanic — DISMISSED** [review]

**Comment by yati1998** [comment]
> /retest ci/centos/k8s-e2e-external-storage/1.21

`X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute`

**Review by Madhu-1 — DISMISSED** [review]

**Review by pkalever — APPROVED** [review]

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e/k8s-1.21

@pkalever this failed at the following rbd-nbd test:
```console
[1mSTEP[0m: restart rbd-nbd process on nodeplugin and continue IO after nodeplugin restart
Jul 14 15:18:46.956: INFO: Running '/usr/bin/kubectl --server=https://192.168.39.7:8443 --kubeconfig=/root/.kube/config --namespace=cephcsi-e2e-12c0684b --namespace=cephcsi-e2e-12c0684b delete -f -'
Jul 14 15:18:47.094: INFO: stderr: "warning: deleting cluster-scoped resources, not scoped to the provided namespace\n"
Jul 14 15:18:47.094: INFO: stdout: "storageclass.storage.k8s.io \"csi-rbd-sc\" deleted\n"
Jul 14 15:18:47.101: INFO: ExecWithOptions {Command:[/bin/sh -c ceph fsid] Namespace:rook-ceph PodName:rook-ceph-tools-7467d8bf8-4grv2 ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
Jul 14 15:18:47.101: INFO: >>> kubeConfig: /root/.kube/config
Jul 14 15:18:49.211: INFO: Waiting up to &PersistentVolumeClaim{ObjectMeta:{rbd-pvc  rbd-694    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Spec:PersistentVolumeClaimSpec{AccessModes:[ReadWriteOnce],Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},},VolumeName:,Selector:nil,StorageClassName:*csi-rbd-sc,VolumeMode:nil,DataSource:nil,},Status:PersistentVolumeClaimStatus{Phase:,AccessModes:[],Capacity:ResourceList{},Conditions:[]PersistentVolumeClaimCondition{},},} to be in Bound state
Jul 14 15:18:49.211: INFO: waiting for PVC rbd-pvc (0 seconds elapsed)
Jul 14 15:18:51.214: INFO: waiting for PVC rbd-pvc (2 seconds elapsed)
Jul 14 15:18:51.220: INFO: Waiting for PV pvc-4016b8c9-f533-4a60-b15a-5e6e105d1f4a to bind to PVC rbd-pvc
Jul 14 15:18:51.220: INFO: Waiting up to timeout=10m0s for PersistentVolumeClaims [rbd-pvc] to have phase Bound
Jul 14 15:18:51.223: INFO: PersistentVolumeClaim rbd-pvc found and phase=Bound (2.261673ms)
Jul 14 15:18:51.223: INFO: Waiting up to 10m0s for PersistentVolume pvc-4016b8c9-f533-4a60-b15a-5e6e105d1f4a to have phase Bound
Jul 14 15:18:51.225: INFO: PersistentVolume pvc-4016b8c9-f533-4a60-b15a-5e6e105d1f4a found and phase=Bound (2.447668ms)
Jul 14 15:18:51.236: INFO: Waiting up to csi-rbd-demo-pod to be in Running state
Jul 14 15:19:11.250: INFO: ExecWithOptions {Command:[/bin/sh -c rbd ls --format=json --pool=replicapool] Namespace:rook-ceph PodName:rook-ceph-tools-7467d8bf8-4grv2 ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
Jul 14 15:19:11.250: INFO: >>> kubeConfig: /root/.kube/config
Jul 14 15:19:12.096: INFO: LabelSelector for csi-rbdplugin daemonsets in namespace cephcsi-e2e-12c0684b: app=csi-rbdplugin
Jul 14 15:19:12.100: INFO: ExecWithOptions {Command:[/bin/sh -c uname -a] Namespace:cephcsi-e2e-12c0684b PodName:csi-rbdplugin-4bgwj ContainerName:csi-rbdplugin Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
Jul 14 15:19:12.101: INFO: >>> kubeConfig: /root/.kube/config
Jul 14 15:19:12.285: INFO: uname -a: Linux minikube 4.19.182 #1 SMP Wed Jun 9 00:54:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Jul 14 15:19:12.289: INFO: ExecWithOptions {Command:[/bin/sh -c rpm -qa | grep rbd-nbd] Namespace:cephcsi-e2e-12c0684b PodName:csi-rbdplugin-4bgwj ContainerName:csi-rbdplugin Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
Jul 14 15:19:12.289: INFO: >>> kubeConfig: /root/.kube/config
Jul 14 15:19:13.004: INFO: rbd-nbd package version: rbd-nbd-16.2.5-0.el8.x86_64

Jul 14 15:19:13.010: INFO: ExecWithOptions {Command:[/bin/sh -c ps -eo 'cmd' | grep [r]bd-nbd] Namespace:cephcsi-e2e-12c0684b PodName:csi-rbdplugin-4bgwj ContainerName:csi-rbdplugin Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
Jul 14 15:19:13.010: INFO: >>> kubeConfig: /root/.kube/config
Jul 14 15:19:13.227: INFO: map command running before restart, mapCmd: /usr/bin/rbd-nbd --id cephcsi-rbd-node -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789 --keyfile=/tmp/csi/keys/keyfile-489654471 map replicapool/csi-vol-6867b248-e4ae-11eb-8f34-5e368018a2d6 --try-netlink --reattach-timeout=180

Jul 14 15:19:13.234: INFO: ExecWithOptions {Command:[/bin/sh -c ceph auth get-key client.cephcsi-rbd-node] Namespace:rook-ceph PodName:rook-ceph-tools-7467d8bf8-4grv2 ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
Jul 14 15:19:13.234: INFO: >>> kubeConfig: /root/.kube/config
Jul 14 15:19:15.259: INFO: Running '/usr/bin/kubectl --server=https://192.168.39.7:8443 --kubeconfig=/root/.kube/config --namespace=cephcsi-e2e-12c0684b delete po -l app=csi-rbdplugin --ignore-not-found=false'
Jul 14 15:19:27.569: INFO: stderr: ""
Jul 14 15:19:27.569: INFO: stdout: "pod \"csi-rbdplugin-4bgwj\" deleted\n"
Jul 14 15:19:27.569: INFO: Waiting up to 10m0s for all daemonsets in namespace 'cephcsi-e2e-12c0684b' to start
Jul 14 15:19:27.597: INFO: 0 / 1 pods ready in namespace 'cephcsi-e2e-12c0684b' in daemonset 'csi-rbdplugin' (0 seconds elapsed)
Jul 14 15:19:29.604: INFO: 0 / 1 pods ready in namespace 'cephcsi-e2e-12c0684b' in daemonset 'csi-rbdplugin' (2 seconds elapsed)
Jul 14 15:19:31.603: INFO: 1 / 1 pods ready in namespace 'cephcsi-e2e-12c0684b' in daemonset 'csi-rbdplugin' (4 seconds elapsed)
Jul 14 15:19:31.603: INFO: attach command to run after restart, attachCmd: /usr/bin/rbd-nbd --id cephcsi-rbd-node -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789 --keyfile=/tmp/csi/keys/keyfile-test attach --device /dev/nbd0 replicapool/csi-vol-6867b248-e4ae-11eb-8f34-5e368018a2d6 --try-netlink --reattach-timeout=180

Jul 14 15:19:31.607: INFO: ExecWithOptions {Command:[/bin/sh -c echo AQB98e5g8pkfExAAch6khBKh0wxIOEGQOG/Lgg== > /tmp/csi/keys/keyfile-test] Namespace:cephcsi-e2e-12c0684b PodName:csi-rbdplugin-99ljc ContainerName:csi-rbdplugin Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
Jul 14 15:19:31.607: INFO: >>> kubeConfig: /root/.kube/config
Jul 14 15:19:31.787: INFO: ExecWithOptions {Command:[/bin/sh -c /usr/bin/rbd-nbd --id cephcsi-rbd-node -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789 --keyfile=/tmp/csi/keys/keyfile-test attach --device /dev/nbd0 replicapool/csi-vol-6867b248-e4ae-11eb-8f34-5e368018a2d6 --try-netlink --reattach-timeout=180
] Namespace:cephcsi-e2e-12c0684b PodName:csi-rbdplugin-99ljc ContainerName:csi-rbdplugin Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
Jul 14 15:19:31.787: INFO: >>> kubeConfig: /root/.kube/config
Jul 14 15:19:32.143: INFO: ExecWithOptions {Command:[/bin/sh -c ps -eo 'cmd' | grep [r]bd-nbd] Namespace:cephcsi-e2e-12c0684b PodName:csi-rbdplugin-99ljc ContainerName:csi-rbdplugin Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
Jul 14 15:19:32.143: INFO: >>> kubeConfig: /root/.kube/config
Jul 14 15:19:32.340: INFO: attach command running after restart, runningAttachCmd: /usr/bin/rbd-nbd --id cephcsi-rbd-node -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789 --keyfile=/tmp/csi/keys/keyfile-test attach --device /dev/nbd0 replicapool/csi-vol-6867b248-e4ae-11eb-8f34-5e368018a2d6 --try-netlink --reattach-timeout=180

Jul 14 15:19:32.344: INFO: ExecWithOptions {Command:[/bin/sh -c echo 'Hello World' > /var/lib/www/html/test] Namespace:rbd-694 PodName:csi-rbd-demo-pod ContainerName:web-server Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
Jul 14 15:19:32.344: INFO: >>> kubeConfig: /root/.kube/config
Jul 14 15:19:45.532: INFO: stdErr occurred: /bin/sh: 1: cannot create /var/lib/www/html/test: Read-only file system

Jul 14 15:19:45.532: FAIL: failed to write IO, err: command terminated with exit code 2, stdErr: /bin/sh: 1: cannot create /var/lib/www/html/test: Read-only file system
```
[The logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.21/detail/mini-e2e_k8s-1.21/303/pipeline) may give some more details, if needed. I wonder if this happens more often, and if a retry (preferred) or some timeout would be needed?

**Comment by pkalever** [comment]
> The logs may give some more details, if needed. I wonder if this happens more often, and if a retry (preferred) or some timeout would be needed?

@nixpanic thanks for reporting, we have an issue filed for this https://github.com/ceph/ceph-csi/issues/2204

Yes, maybe we need to poll for some timeout value to fix it. I will consider sending a patch for this soon.

**Comment by nixpanic** [comment]
@mergifyio rebase

Some CI jobs seems to have been aborted (infra issue/maintenance?), and other changes have been merged since.

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.21

I think this failed because the API server returned some weird errors ([logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.21/detail/mini-e2e-helm_k8s-1.21/309/pipeline)):
```
Jul 15 07:57:59.127: INFO: waiting for PVC rbd-80810 (86 seconds elapsed)
Jul 15 07:58:00.108: INFO: Error getting pvc "rbd-80810" in namespace "rbd-8081": rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field
Jul 15 07:58:00.108: INFO: failed to create PVC (rbd-80810): failed to get pvc: rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field
Jul 15 07:58:00.108: FAIL: creating PVCs failed, 1 errors were logged
```

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.21

Failed to start minikube VM #2264

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.21

Failed to start minikube VM again ([logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.21/detail/mini-e2e-helm_k8s-1.21/323/pipeline)), #2264

**Review by Madhu-1 — DISMISSED** [review]

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.20

Failed again with #2264

**Comment by Yuggupta27** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.20

```
Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute
```

**Comment by nixpanic** [comment]
@mergifyio refresh

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
Trying out the `Depends-on: ` mergify feature. This PR will only get merged once the dependency is met.

See https://docs.mergify.io/actions/merge/#queue-depends-on for details.

**Comment by nixpanic** [comment]
@mergifyio rebase

**Review by humblec — APPROVED** [review]

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.19

CI job failed to create namespace ([logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.19/detail/mini-e2e-helm_k8s-1.19/2109/pipeline)):
```
+ ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@n27.dusty.ci.centos.org 'kubectl create namespace '\''cephcsi-e2e-1f346f7c7e38'\'''
Warning: Permanently added 'n27.dusty.ci.centos.org,172.19.2.91' (ECDSA) to the list of known hosts.
Error from server: etcdserver: request timed out
```

**Pull request merged**
