### PR TITLE
Avoid logging secrets when Logging Replication GRPC requests

### PR DESCRIPTION
**Pull request by Madhu-1**
This PR uses the helper function StripReplicationSecrets from replication-lib-utils to avoid the logging of secrets in Replication GRPC request.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Review by nixpanic — APPROVED** [review]

**Review by agarwal-mudit — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio refresh

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.19

Failed to deploy rook #1636 
```
Error from server: error when creating "/tmp/tmp.mYPVfII4SK/cluster-test.yaml": etcdserver: request timed out
```

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.19
> /retest ci/centos/upgrade-tests-rbd

Jenkins lost its connection to the test systems?

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.20
> /retest ci/centos/mini-e2e

These jobs were affected as well.

**Pull request merged**
