### PR TITLE
ci: remove the rules for backport on unsupported versions

### PR DESCRIPTION
**Pull request by humblec**
CSI version v3.3.0 and above are the supported versions now and this
patch also adjust the mergify rules according to that, ie the backport
rules are removed for all unsupported versions here.

Updates #2438 

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Review by nixpanic — APPROVED** [review]
This probably should `Updates: #2438`?

**Review by yati1998 — APPROVED** [review]

**Review by Yuggupta27 — CHANGES_REQUESTED** [review]
Just a quick question, are we removing support of v3.1 and v3.2 as well?

**Review by Yuggupta27 — APPROVED** [review]
Updates #2440

**Comment by humblec** [comment]
@mergifyio rebase

**Comment by humblec** [comment]
Merging this as it need manual merge. Thanks !

**Pull request merged**
