### PR TITLE
rbd: rename `setImageOptions()` to `constructImageOptions()`

### PR DESCRIPTION
**Pull request by nixpanic**
A function called `setImageOptions()` is expected to set the passed
options on the volume. However, the passed options parameter is only
filled with the options that should get set on the RBD-image at the time
of creation.

The naming of the function, and it's parameter is confusing. Rename the
function to `constructImageOptions()` and return the ImageOptions to
make it easier to understand.

Depends-on: #4835

### CODE REVIEW

**Review by iPraveenParihar — APPROVED** [review]
LGTM

**Review by Madhu-1 — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio queue

**Comment by nixpanic** [comment]
@mergifyio requeue

**Comment by Madhu-1** [comment]
depends on #4835

**Pull request merged**
