### PR TITLE
Fix mountpoint issue in rbd helm template

### LINKED ISSUE #884: csi-snapshotter is failing using deploy sh script ; helm - /run/mount error
# Describe the bug #
Following examples readme document, deploying csi-rbd-plugin its failing cause of csi-snapshotter is crashed. If using helm, I got /run/mount error.
# Environment details #

- Image/version of Ceph CSI driver: 2.0.1
- helm chart version: v3.0.0 
- Kubernetes cluster version: Rancher v1.17
- Logs
plugin-deploy.sh:

`E0322 23:05:46.444030 1 leaderelection.go:330] error retrieving resource lock ceph/rbd-csi-ceph-com: leases.coordination.k8s.io "rbd-csi-ceph-com" is forbidden: User "system:serviceaccount:ceph:rbd-csi-provisioner" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "ceph"
I0322 23:05:46.444050 1 leaderelection.go:246] failed to acquire lease ceph/rbd-csi-ceph-com`

`I0322 23:05:32.742465 1 main.go:89] Version: v1.2.2-0-gd5da3c1e
F0322 23:05:32.755964 1 create_crd.go:50] failed to create VolumeSnapshotResource: &v1beta1.CustomResourceDefinition{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:v1beta1.CustomResourceDefinitionSpec{Group:"", Version:"", Names:v1beta1.CustomResourceDefinitionNames{Plural:"", Singular:"", ShortNames:[]string(nil), Kind:"", ListKind:"", Categories:[]string(nil)}, Scope:"", Validation:(*v1beta1.CustomResourceValidation)(nil), Subresources:(*v1beta1.CustomResourceSubresources)(nil), Versions:[]v1beta1.CustomResourceDefinitionVersion(nil), AdditionalPrinterColumns:[]v1beta1.CustomResourceColumnDefinition(nil), Conversion:(*v1beta1.CustomResourceConversion)(nil)}, Status:v1beta1.CustomResourceDefinitionStatus{Conditions:[]v1beta1.CustomResourceDefinitionCondition(nil), AcceptedNames:v1beta1.CustomResourceDefinitionNames{Plural:"", Singular:"", ShortNames:[]string(nil), Kind:"", ListKind:"", Categories:[]string(nil)}, StoredVersions:[]string(nil)}}, err: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:""}, Status:"Failure", Message:"customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:ceph:rbd-csi-provisioner\" cannot create resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope", Reason:"Forbidden", Details:(*v1.StatusDetails)(0xc0003b6060), Code:403}}`

helm:

`(Did not use that cause it is failing as well with error: Error: DaemonSet.apps "ceph-rbd-ceph-csi-rbd-nodeplugin" is invalid: spec.template.spec.containers[1].volumeMounts[3].mountPath: Invalid value: "/run/mount": must be unique)`

# Actual results #

Thus, I could not use deploy script either helm chart to deploy plugin in k8s cluster. However, when using helm chart csi-snapshotter is not failing but there is no  csi-rbdplugin deployed.

### PR DESCRIPTION
**Pull request by Madhu-1**
closes #884

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by humblec** [comment]
lgtm.. approved..

**Comment by nixpanic** [comment]
@humblec this needs manual merging because it targets the release-2.0 branch.

**Comment by humblec** [comment]
Yep. Done!

**Comment by kfox1111** [comment]
Any plans on getting a new helm package out there?

**Comment by Madhu-1** [comment]
sure @kfox1111 will plan for 2.0.2 with this Fix this weekend

@humblec can we do ceph-csi 2.0.2 release with the above fix?

**Comment by kfox1111** [comment]
Thanks! :)

**Comment by nixpanic** [comment]
@Mergifyio backport release-v2.0

**Comment by Madhu-1** [comment]
@nixpanic its already in release-v2.0 branch, no need to backport

**Pull request merged**
