### PR TITLE
doc: fixed broken links

### PR DESCRIPTION
**Pull request by seadog007**
# Describe what this PR does #

Fixed broken links for documents in 4 files.

## Is there anything that requires special attention ##

Do you have any questions?
No

Is the change backward compatible?
No

Are there concerns around backward compatibility?
No

Provide any external context for the change, if any.
N/A

## Related issues ##
Broken when #4907 merged
See also https://github.com/ceph/ceph-csi/commit/a6f1af49c649f90047f466423785ed006190e247

## Future concerns ##
N/A

**Checklist:**

* [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#commit-messages).
* [x] Reviewed the developer guide on [Submitting a Pull Request](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#development-workflow)
* [x] [Pending release notes](https://github.com/ceph/ceph-csi/blob/devel/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next major release.
* [x] Documentation has been updated, if necessary.
* [ ] Unit tests have been added, if necessary.
* [ ] Integration tests have been added, if necessary.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

* `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

### CODE REVIEW

**Review by nixpanic — DISMISSED** [review]
Great, thanks!

**Comment by iPraveenParihar** [comment]
Thanks for the PR.
Can you please fix the broken links at places as mentioned below? 

1. https://github.com/ceph/ceph-csi/blob/925ea1970c4cde5aa76dfb875a778edcc211d50a/charts/ceph-csi-cephfs/README.md?plain=1#L177

2. https://github.com/ceph/ceph-csi/blob/925ea1970c4cde5aa76dfb875a778edcc211d50a/charts/ceph-csi-rbd/README.md?plain=1#L190

3. https://github.com/ceph/ceph-csi/blob/925ea1970c4cde5aa76dfb875a778edcc211d50a/docs/resource-cleanup.md?plain=1#L30-L31

4. https://github.com/ceph/ceph-csi/blob/925ea1970c4cde5aa76dfb875a778edcc211d50a/docs/resource-cleanup.md?plain=1#L59

there was doc folder restructure PR https://github.com/ceph/ceph-csi/pull/4907, @yati1998 can you please check for any other broken links that might need updating beyond those listed here?

**Review by yati1998 — DISMISSED** [review]
LGTM

**Comment by iPraveenParihar** [comment]
@seadog007 Can you please squash your commits into one?

**Comment by seadog007** [comment]
The commit has been squash into one

**Review by iPraveenParihar — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio queue

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
@Mergifyio queue

**Pull request merged**
