### PR TITLE
Rename "master" branch to "devel"

### PR DESCRIPTION
**Pull request by nixpanic**
This PR renames all occasions of "master" to "devel" where the reference is relevant to Ceph-CSI.

Once this PR is merged, an admin of the GitHub project will need to rename the branch before next PRs can get merged. The GitHub documentation describes that all the existing PRs for the "master" branch will automatically be updated to the new "devel" branch.

A 2nd PR is filed to update the "ci/centos" branch (PR #1891), so that the CI jobs use the new branch name.

See-also: https://docs.github.com/en/github/administering-a-repository/renaming-a-branch
Updates: #1193

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

**Comment by humblec** [comment]
Thanks @nixpanic .. commitlint error out in this version of the patch.

**Comment by humblec** [comment]
One other suggestion I have here is,  imo, its good to document about this change for history with details on why we do that..etc. What do you think ?

**Comment by nixpanic** [comment]
> Thanks @nixpanic .. commitlint error out in this version of the patch.

**commitlint** failed because it tries to use the `devel` branch now, and that does not exist. Please review the commits manually.

**Comment by nixpanic** [comment]
> One other suggestion I have here is, imo, its good to document about this change for history with details on why we do that..etc. What do you think ?

That can be expanded in #1193 if you think that is not sufficient. I do not think we need to document it in the repository itself?

**Review by humblec — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Comment by Madhu-1** [comment]
Merging the PR manually

**Comment by Madhu-1** [comment]
@mergifyio backport release-v3.2

**Comment by Madhu-1** [comment]
@nixpanic can you please backport this to release-3.2 branch? as a change from this is missing in release-v3.2 branch CI is failing at https://github.com/ceph/ceph-csi/pull/2041

**Comment by humblec** [comment]
> @nixpanic can you please backport this to release-3.2 branch? as a change from this is missing in release-v3.2 branch CI is failing at #2041

May be to all previous releases ?

**Comment by nixpanic** [comment]
> @nixpanic can you please backport this to release-3.2 branch? as a change from this is missing in release-v3.2 branch CI is failing at #2041

Sure, will do!

**Comment by nixpanic** [comment]
> > @nixpanic can you please backport this to release-3.2 branch? as a change from this is missing in release-v3.2 branch CI is failing at #2041
> 
> May be to all previous releases ?

What other older releases are still maintained?

**Pull request merged**
