### PR TITLE
merge csiv1.0 branch to master

### PR DESCRIPTION
**Pull request by Madhu-1**

### CODE REVIEW

**Comment by Madhu-1** [comment]
@rootfs @ShyamsundarR @gman0 @j-griffith @humblec PTAL,

This PR makes csiv1.0 branch as master with preserving  git history from csiv1.0 branch

**Comment by Madhu-1** [comment]
updates issue #266

**Comment by humblec** [comment]
@Madhu-1 will be on this soon.

**Comment by ShyamsundarR** [comment]
An clarification question, instead of the merge can we not delete and rename csi-v1.0 branch as the master? Or, do we intend to leave the csi-v1.0 branch as is and never delete that branch?

**Comment by Madhu-1** [comment]
> An clarification question, instead of the merge can we not delete and rename csi-v1.0 branch as the master? Or, do we intend to leave the csi-v1.0 branch as is and never delete that branch?

@ShyamsundarR  I thought of doing only if I face any issue in merging csi-v1.0 into master and also I felt deleting a branch is kind of risky for me.

so the current plan is to merge the csi-v1.0 changes to the master and delete csi-v1.0 branch(make master as the default branch) any comments on this approach?

**Comment by humblec** [comment]
One option would be, branchoff from current `v1.0` branch and create `v1.0-backup`. Then delete and rename `v1.0` as the master. Then rename `v1.0-backup` to v1.0.  No PR Merges in between this process. I think that would be better than merging .

Any thoughts @gman0 @ShyamsundarR @j-griffith @Madhu-1 ?

**Comment by Madhu-1** [comment]
> One option would be, branchoff from current `v1.0` branch and create `v1.0-backup`. Then delete and rename `v1.0` as the master. Then rename `v1.0-backup` to v1.0. No PR Merges in between this process. I think that would be better than merging .
> 
> Any thoughts @gman0 @ShyamsundarR @j-griffith @Madhu-1 ?

whats the intention of keeping v1.0 branch? are we going to merge PR to  csiv1.0 branch and do a release from it?

if we come to an agreement soon enough so that we have a master branch with v1.0.0.

**Comment by ShyamsundarR** [comment]
Just checked a branch diff between this PR and csi-v1.0 branch it is clean. I would vote to not prolong this, by taking other alternatives (like delete/rename), as the bulk of the work is done. I cannot say if commits will bisect well or not (I think our merge strategy also defeats the bisection unless PR owners ensure their commits are bisect-able (individually work)).

I was more curious as to why this option/route was taken to ensure we have master caught up with the current 1.0 branch.

BUT, I do want to discuss what we do with csi-v1.0 branch post this merge, IMO,
- We need to delete csi-v1.0 branch, till we are ready to make a 1.0 release from the master branch
- Start releasing 'canary' images for every PR merge from master as 1.0 till we are ready branch and release 1.0

**Comment by humblec** [comment]
lgtm. 
@gman0 can you take a look at this PR and do the needful ? :)

**Comment by Madhu-1** [comment]
@gman0 @rootfs can we merge this one on top priority?

**Pull request merged**
