### PR TITLE
Fix return error codes

### PR DESCRIPTION
**Pull request by Madhu-1**

### CODE REVIEW

**Comment by Madhu-1** [comment]
@humblec PTAL

**Comment by ShyamsundarR** [comment]
@Madhu-1 Are we attempting to standardize on error handling as prescribed in "github.com/pkg/errors"? would like to understand the direction and reasoning, to use the new error scheme, so that future code can comply to the same. Thanks!

**Comment by Madhu-1** [comment]
am trying to return the error codes as expected in CSI spec.
in a few cases, we are just returning the error msg but not the error codes, with  these changes it returns both error code and the message

**Comment by gman0** [comment]
@ShyamsundarR we definitely should adhere to correct error codes

**Comment by gman0** [comment]
LGTM

**Comment by humblec** [comment]
LGTM. Thanks @Madhu-1

**Pull request merged**
