### PR TITLE
rebase: update ceph to reef

### PR DESCRIPTION
**Pull request by Madhu-1**
Testing Reef and seeing everything works.

### CODE REVIEW

**Comment by nixpanic** [comment]
The CI job tries to pull this:
```
Trying to pull registry-ceph-csi.apps.ocp.cloud.ci.centos.org/ceph/ceph:v18...
```

The mirror contains this image:
```
going to copy docker://quay.io/ceph/ceph:v18 to docker://registry-ceph-csi.apps.ocp.cloud.ci.centos.org/quay.io/ceph/ceph:v18
Getting image source signatures
Copying blob sha256:66286c37fba202f94836d18ed3ea1efa02816e6db632ec78297328694bed0b94
Copying blob sha256:a20960ea1b02448618d7cdee5e657e6b83404689ca4ce4555251aeada11b5a7a
Copying config sha256:ff9c8d7de4ca37ca64a34818fa8d6e7b4e6be435e4f8f54ed2e00827f8fa3d31
Writing manifest to image destination
Storing signatures
```

The mirror contains `quay.io` in the image name, but it seems to have been stripped by the CI job.

PR #4031 should probably not include the `quay.io/` part in the 2nd column with "short names".

**Comment by nixpanic** [comment]
#4032 has been created, the mirroring runs nightly, so after merging the PR, a new `/test ...` can be done to see if the Ceph Reef image can be used in the CI job.

**Comment by Madhu-1** [comment]
```
  Aug  7 07:49:45.556: INFO: ExecWithOptions: execute(POST https://192.168.49.2:8443/api/v1/namespaces/rook-ceph/pods/rook-ceph-tools-757999d6c7-c4v5d/exec?command=%2Fbin%2Fsh&command=-c&command=ceph+osd+pool+create+.nfs+128&container=rook-ceph-tools&container=rook-ceph-tools&stderr=true&stdout=true)

  Aug  7 07:49:46.063: INFO: stdErr occurred: pool names beginning with . are not allowed



  Aug  7 07:49:46.068: INFO: ExecWithOptions {Command:[/bin/sh -c ceph osd pool set .nfs size 1 --yes-i-really-mean-it] Namespace:rook-ceph PodName:rook-ceph-tools-757999d6c7-c4v5d ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}

  Aug  7 07:49:46.068: INFO: >>> kubeConfig: /root/.kube/config

  Aug  7 07:49:46.068: INFO: ExecWithOptions: Clientset creation

  Aug  7 07:49:46.068: INFO: ExecWithOptions: execute(POST https://192.168.49.2:8443/api/v1/namespaces/rook-ceph/pods/rook-ceph-tools-757999d6c7-c4v5d/exec?command=%2Fbin%2Fsh&command=-c&command=ceph+osd+pool+set+.nfs+size+1+--yes-i-really-mean-it&container=rook-ceph-tools&container=rook-ceph-tools&stderr=true&stdout=true)

  Aug  7 07:49:46.572: INFO: failed to execute command: command terminated with exit code 2

  Aug  7 07:49:46.572: INFO: stdErr occurred: Error ENOENT: unrecognized pool '.nfs'
```

@nixpanic NFS pool creation failing, anything changed in Ceph Reef version?

**Comment by Madhu-1** [comment]
https://docs.ceph.com/en/reef/rados/operations/pools/#pool-names mentions its reserved and we should not use it

**Comment by nixpanic** [comment]
> @nixpanic NFS pool creation failing, anything changed in Ceph Reef version?

It seems like Reef has some changes with respect to pool creation... Rook usually creates the `.nfs` pool, I think. But it requires redundancy. I do not know how Rook creates the `.nfs` pool in Reef, maybe we need to pass an extra option to the `ceph osd` command?

https://github.com/rook/rook/blob/7aaf46e11243b21df4d4f088fc80b949019559b0/pkg/operator/ceph/nfs/nfs.go#L319

**Comment by Madhu-1** [comment]
> > @nixpanic NFS pool creation failing, anything changed in Ceph Reef version?
> 
> It seems like Reef has some changes with respect to pool creation... Rook usually creates the `.nfs` pool, I think. But it requires redundancy. I do not know how Rook creates the `.nfs` pool in Reef, maybe we need to pass an extra option to the `ceph osd` command?
> 
> https://github.com/rook/rook/blob/7aaf46e11243b21df4d4f088fc80b949019559b0/pkg/operator/ceph/nfs/nfs.go#L319

@nixpanic Yes you are correct we were missing extra flag to create pool in cephcsi e2e, added missing flag now.

**Comment by Madhu-1** [comment]
```
#7 45.98   Running scriptlet: nfs-ganesha-5.5-1.el8s.x86_64                        11/12 
#7 45.99 error: nfs-ganesha-selinux-5.4-1.el8s.noarch: erase skipped
#7 45.99 /var/tmp/rpm-tmp.FjPzqW: line 2: /etc/selinux/config: No such file or directory
#7 45.99 warning: %posttrans(nfs-ganesha-5.5-1.el8s.x86_64) scriptlet failed, exit status 1
#7 45.99 
#7 45.99 Error in POSTTRANS scriptlet in rpm package nfs-ganesha
#7 45.99   Running scriptlet: nfs-ganesha-5.4-1.el8s.x86_64                        11/12 
#7 46.11   Verifying        : nfs-ganesha-5.5-1.el8s.x86_64                         1/12 
#7 46.11   Verifying        : nfs-ganesha-5.4-1.el8s.x86_64                         2/12 
#7 46.11   Verifying        : nfs-ganesha-ceph-5.5-1.el8s.x86_64                    3/12 
#7 46.11   Verifying        : nfs-ganesha-ceph-5.4-1.el8s.x86_64                    4/12 
#7 46.11   Verifying        : nfs-ganesha-rados-grace-5.5-1.el8s.x86_64             5/12 
#7 46.11   Verifying        : nfs-ganesha-rados-grace-5.4-1.el8s.x86_64             6/12 
#7 46.11   Verifying        : nfs-ganesha-rados-urls-5.5-1.el8s.x86_64              7/12 
#7 46.11   Verifying        : nfs-ganesha-rados-urls-5.4-1.el8s.x86_64              8/12 
#7 46.11   Verifying        : nfs-ganesha-rgw-5.5-1.el8s.x86_64                     9/12 
#7 46.11   Verifying        : nfs-ganesha-rgw-5.4-1.el8s.x86_64                    10/12 
#7 46.11   Verifying        : nfs-ganesha-selinux-5.5-1.el8s.noarch                11/12 
#7 46.11   Verifying        : nfs-ganesha-selinux-5.4-1.el8s.noarch                12/12Error: Transaction failed
#7 46.51  
#7 46.51 
#7 46.51 Upgraded:
#7 46.51   nfs-ganesha-5.5-1.el8s.x86_64                                                 
#7 46.51   nfs-ganesha-ceph-5.5-1.el8s.x86_64                                            
#7 46.51   nfs-ganesha-rados-grace-5.5-1.el8s.x86_64                                     
#7 46.51   nfs-ganesha-rados-urls-5.5-1.el8s.x86_64                                      
#7 46.51   nfs-ganesha-rgw-5.5-1.el8s.x86_64                                             
#7 46.51 Failed:
#7 46.51   nfs-ganesha-selinux-5.4-1.el8s.noarch  nfs-ganesha-selinux-5.5-1.el8s.noarch 
#7 46.51 
#7 ERROR: process "/bin/sh -c dnf -y update        && dnf clean all        && rm -rf /var/cache/yum" did not complete successfully: exit code: 1
------
 > [updated_base 3/3] RUN dnf -y update        && dnf clean all        && rm -rf /var/cache/yum:
46.51 
46.51 Upgraded:
46.51   nfs-ganesha-5.5-1.el8s.x86_64                                                 
46.51   nfs-ganesha-ceph-5.5-1.el8s.x86_64                                            
46.51   nfs-ganesha-rados-grace-5.5-1.el8s.x86_64                                     
46.51   nfs-ganesha-rados-urls-5.5-1.el8s.x86_64                                      
46.51   nfs-ganesha-rgw-5.5-1.el8s.x86_64                                             
46.51 Failed:
46.51   nfs-ganesha-selinux-5.4-1.el8s.noarch  nfs-ganesha-selinux-5.5-1.el8s.noarch 
46.51 
```

it looks like ceph v18 image is broken today and not able to build cephcsi image like yesterday 🤕

**Review by riya-singhal31 — DISMISSED** [review]

**Review by nixpanic — CHANGES_REQUESTED** [review]
Looks good, but please fix the typos in the commit messages :mag:

**Comment by Madhu-1** [comment]
> Looks good, but please fix the typos in the commit messages 🔍

Thanks @nixpanic done. PTAL

**Review by riya-singhal31 — APPROVED** [review]

**Review by yati1998 — APPROVED** [review]
LGTM

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio queue

**Comment by Madhu-1** [comment]
@mergifyio queue

**Comment by nixpanic** [comment]
Both CI jobs failed with:
```
  [FAILED] failed to resize filesystem PVC: context deadline exceeded
  In [It] at: /go/src/github.com/ceph/ceph-csi/e2e/rbd.go:852 @ 08/23/23 08:11:07.519
```
This isn't a test that I have seen sporadically fail, so it may point to a change related to the Ceph version.

**Comment by Madhu-1** [comment]
> Both CI jobs failed with:
> 
> ```
>   [FAILED] failed to resize filesystem PVC: context deadline exceeded
>   In [It] at: /go/src/github.com/ceph/ceph-csi/e2e/rbd.go:852 @ 08/23/23 08:11:07.519
> ```
> 
> This isn't a test that I have seen sporadically fail, so it may point to a change related to the Ceph version.

CI passed on 1.25,1.26. and 1.27 not sure is it something to do with ceph version, let me check on that one

**Comment by nixpanic** [comment]
> CI passed on 1.25,1.26. and 1.27 not sure is it something to do with ceph version, let me check on that one

Other PRs seem to fail in the same way with RBD resizing on Kubernetes 1.28. It is not only this PR :cry:

**Comment by nixpanic** [comment]
@mergifyio rebase

**Pull request merged**
