### PR TITLE
ci: avoid preleased bits

### PR DESCRIPTION
**Pull request by pkalever**
# Describe what this PR does #

Skip testing with prereleased content, for example
v1.23.0-alpha.4
v1.23.0-alpha.3
v1.23.0-alpha.2
v1.23.0-alpha.1
v1.22.0-rc.0
v1.22.0-beta.2
v1.22.0-beta.1
v1.22.0-beta.0
v1.22.0-alpha.3
v1.22.0-alpha.2

Signed-off-by: Prasanna Kumar Kalever \<prasanna.kalever@redhat.com\>

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

**Comment by nixpanic** [comment]
What is the reason to skip testing with pre-releases? We usually do want to test with pre-releases for the next Kubernetes version. The script should pick the most recent release by default, and not some older release (pre-release, or minor release for that matter).

**Comment by pkalever** [comment]
> What is the reason to skip testing with pre-releases? We usually do want to test with pre-releases for the next Kubernetes version. The script should pick the most recent release by default, and not some older release (pre-release, or minor release for that matter).

Picking prerelease bits means we are attempting to run ceph-csi on non-stable k8s branches. Which is testing a PR on a non-stable k8s branch.

I think running new PRs on non-stable k8s versions doesn't make sense to me. We should rather consider running nightly or weekly jobs with ceph-csi `devel` (merged ones) to catch any anomalies or changes in k8s.

**Comment by nixpanic** [comment]
> The script should pick the most recent release by default, and not some older release (pre-release, or minor release for that matter).

:point_up: is important. The script prints out the version that it detected and configured for testing. If it detects a pre-release version where a stable version is available, we need to check why that happens.

For upcoming kubernetes versions, there are only alpha/beta/rc releases, so we do need to be able to test with those.

**Comment by Madhu-1** [comment]
@pkalever we need to test with the most recent release(pre/patch/rc etc)  to catch the bugs earlier. say for example if we have 1.22.0 release but if we still testing with 1.22.0 pre or RC release then it's a problem? this PR is addressing this issue?

**Comment by pkalever** [comment]
> @pkalever we need to test with the most recent release(pre/patch/rc etc) to catch the bugs earlier. say for example if we have 1.22.0 release but if we still testing with 1.22.0 pre or RC release then it's a problem? this PR is addressing this issue?

With these changes, if a k8s release is marked as prerelease like beta, alpha, and RC it will not be picked. My intention was to avoid testing ceph-csi new PRs with unstable k8s releases so that any anomalies in k8s might make us think it could be an issue with the new PR submitted at ceph-csi.

IMHO the k8s vs ceph-csi compatibility issues need to be checked with nightly or weekly jobs but not with regular PR-based checks.

**Comment by nixpanic** [comment]
We only enable automatic testing of PRs with Kubernetes versions that are released. The CI jobs can be triggered manually with Kubernetes versions that are in alpha/beta/rc.

Automated CI runs, and required CI job passing should always use stable versions of Kubernetes. If you have seen occasions where this is not the case, we need to investigate why/how that happened. In that case, please link to jobs where non-stable releases were used.

**Comment by pkalever** [comment]
Closing this based on https://github.com/ceph/ceph-csi/pull/2638#issuecomment-971347649

Will keep track for any non-stable k8s installations in the test beds.

Thanks @nixpanic & @Madhu-1

**Pull request closed without merging**
