### PR TITLE
ci: define `i` as type `int` in for loop

### PR DESCRIPTION
**Pull request by nixpanic**
The output of the for loop seemt to be `groovy.lang.IntRange`, which is
not very useful. Maybe it is required to define the variable of type
`int`?

### CODE REVIEW

**Comment by nixpanic** [comment]
I don't know why **ci/centos/jjb-validate** fails, this PR is not related to it.

**Review by Madhu-1 — APPROVED** [review]

**Comment by nixpanic** [comment]
I hope I fixed the CI issue, but that can only be tested once the PR is merged :crossed_fingers:

**Pull request merged**
