### PR TITLE
e2e: update rook ceph cluster image version

### PR DESCRIPTION
**Pull request by pkalever**
# Describe what this PR does #

use pacific release for ROOK_CEPH_CLUSTER_IMAGE

Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

### CODE REVIEW

**Review by nixpanic — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Pull request merged**
