### PR TITLE
util: replace klog with util logger

### PR DESCRIPTION
**Pull request by Madhu-1**
Replaced klog with util logger in pending packages.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Review by nixpanic — DISMISSED** [review]
The 2nd commit does not have an empty line before `Signed-off-by:`. Commitlint might fail due to that.

**Comment by Madhu-1** [comment]
> The 2nd commit does not have an empty line before `Signed-off-by:`. Commitlint might fail due to that.

Thanks @nixpanic Fixed now

**Comment by Madhu-1** [comment]
@nixpanic as its logging change isnt it good to add ready-to-merge label?

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
> @nixpanic as its logging change isnt it good to add ready-to-merge label?

Yeah, I guess that's fine

**Comment by nixpanic** [comment]
Noooo! Wrong button pressed :sob:

**Pull request merged**
