### PR TITLE
ci: update minikube to latest release

### PR DESCRIPTION
**Pull request by Madhu-1**
update minikube to latest release i.e 1.25.0

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Review by yati1998 — APPROVED** [review]

**Review by humblec — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Pull request merged**
