### PR TITLE
Revert back kuberenetes 1.18 changes

### PR DESCRIPTION
**Pull request by Madhu-1**
Current code dependency is moved to kubernetes 1.18. but for v3.0.0 we need to import snapshotter client in E2E which is still on Kubernetes 1.17, we need to revert back the kubernetes changes till csi-snapshotter updated to kube 1.18 and it makes a release.

To get unblocked or our working am reverting
back the Kubernetes 1.18 changes to 1.17.2

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by nixpanic** [comment]
Is there a schedule or issue where the progress of the csi-snapshotter side-car can be tracked?

**Comment by Madhu-1** [comment]
here it is https://github.com/kubernetes-csi/external-snapshotter/pull/286, once https://github.com/kubernetes-csi/external-snapshotter/pull/286 is merged and snapshotter makes a new release we can update the kube to 1.18

**Comment by nixpanic** [comment]
It looks like kubernetes-csi/external-snapshotter#286 can get addressed soon. I would prefer to assist @humblec with that, before considering reverting the k8s 1.18 rebase.

**Comment by Madhu-1** [comment]
> It looks like [kubernetes-csi/external-snapshotter#286](https://github.com/kubernetes-csi/external-snapshotter/pull/286) can get addressed soon. I would prefer to assist @humblec with that, before considering reverting the k8s 1.18 rebase.

Merging PR wont unblock, we need to get csi-snapshotter release. 

@humblec any suggestions on this to unblock cephcsi snapshotter work?

**Comment by humblec** [comment]
@Madhu-1 that PR will be `IN` soon. So, lets not revert.

**Comment by humblec** [comment]
> @Madhu-1 that PR will be `IN` soon. So, lets not revert.

**Comment by nixpanic** [comment]
> Merging PR wont unblock, we need to get csi-snapshotter release.

We can use a side-car image that is not released/versioned yet, and update the version once an official release is available (should be done before v3.0).

**Comment by Madhu-1** [comment]
> @Madhu-1 that PR will be `IN` soon. So, lets not revert.

just a note, will be blocked on https://github.com/ceph/ceph-csi/pull/924 as I discussed earlier with you

will wait till new snapshotter release is out.

**Comment by Madhu-1** [comment]
> > Merging PR wont unblock, we need to get csi-snapshotter release.
> 
> We can use a side-car image that is not released/versioned yet, and update the version once an official release is available (should be done before v3.0).

its not about sidecar image. we will be depending on snapshotter client which will be in snapshotter master code base in your E2E to create snapshots.

**Comment by humblec** [comment]
> > @Madhu-1 that PR will be `IN` soon. So, lets not revert.
> 
> just a note, will be blocked on #924 as I discussed earlier with you
> 
> will wait till new snapshotter release is out.

Just to make it clear only e2e testing is the concern here, Isnt it ? codewise we could proceed.

**Comment by Madhu-1** [comment]
> > > @Madhu-1 that PR will be `IN` soon. So, lets not revert.
> > 
> > 
> > just a note, will be blocked on #924 as I discussed earlier with you
> > will wait till new snapshotter release is out.
> 
> Just to make it clear only e2e testing is the concern here, Isnt it ? codewise we could proceed.

yes we cannot merge #924 without E2E passing #924 is pending for review

**Comment by humblec** [comment]
> > > > @Madhu-1 that PR will be `IN` soon. So, lets not revert.
> > > 
> > > 
> > > just a note, will be blocked on #924 as I discussed earlier with you
> > > will wait till new snapshotter release is out.
> > 
> > 
> > Just to make it clear only e2e testing is the concern here, Isnt it ? codewise we could proceed.
> 
> yes we cannot merge #924 without E2E passing #924 is pending for review

Yeah, e2e wont pass ...true.. will review the PR soon.

**Comment by nixpanic** [comment]
@Madhu-1 I think this can be closed now?

**Pull request closed without merging**
