### PR TITLE
build:  update templates for v3.1.1 release

### PR DESCRIPTION
**Pull request by Madhu-1**
updated required templates for v3.1.1 release.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
update: Preparation of v3.1.1 draft release is done

**Review by nixpanic — APPROVED** [review]
I **really** hate these PRs, at one point it should all be automated

**Comment by Madhu-1** [comment]
> I **really** hate these PRs, at one point it should all be automated

Yes, we need to automate it with Travis CI or GitHub actions or centos CI :dagger:

**Comment by humblec** [comment]
@Madhu-1 can we have a release issue with the details of the release ?

**Review by humblec — APPROVED** [review]

**Comment by nixpanic** [comment]
This needs manual merging as there are no Mergify rules for non-automated backports in the release-* branches.

**Comment by Madhu-1** [comment]
Manually Merging this one as we have 2 approvals

**Pull request merged**
