### PR TITLE
doc: move nbd to beta support

### LINKED ISSUE #2323: rbd-nbd: moving towards Beta support
# Describe the feature you'd like to have #

This is an issue to track the missing gaps that we have identified to move the rbd-nbd userspace mounter from Alpa to Beta support.

Here is the list:

- Must
  - [x] https://github.com/ceph/ceph-csi/issues/2262
  - [x] https://github.com/ceph/ceph-csi/issues/2221
  - [ ] https://github.com/ceph/ceph-csi/issues/2204

- Other Features
  - [x] https://github.com/ceph/ceph-csi/issues/2235
  - [x] https://github.com/ceph/ceph-csi/issues/2234
  - [x] https://github.com/ceph/ceph-csi/issues/2237
  - [x] https://github.com/ceph/ceph-csi/issues/2018
  
  Feel free to update the list with any latest findings.

### PR DESCRIPTION
**Pull request by pkalever**
# Describe what this PR does #
Move nbd to beta support

## Related issues ##
Fixes: #2323

## Future concerns ##
* Need https://github.com/ceph/ceph-csi/issues/2018
* Also, we need to take a call on https://github.com/ceph/ceph-csi/issues/2204

Signed-off-by: Prasanna Kumar Kalever \<prasanna.kalever@redhat.com\>

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

**Comment by nixpanic** [comment]
@pkalever this is labelled as `[DNM]`, but also scheduled for inclusion in 3.5.0 (this week). Can you fix the status of this PR?

**Comment by pkalever** [comment]
> @pkalever this is labelled as `[DNM]`, but also scheduled for inclusion in 3.5.0 (this week). Can you fix the status of this PR?

Yes @nixpanic for that we need to take a call on https://github.com/ceph/ceph-csi/issues/2204#issuecomment-979733845
Basically, we have two options
1. support nbd only on Kernel >= 5.4(Edited)
2. get the rbd-nbd PR https://github.com/ceph/ceph/pull/42609

Thanks!

**Comment by nixpanic** [comment]
> > @pkalever this is labelled as `[DNM]`, but also scheduled for inclusion in 3.5.0 (this week). Can you fix the status of this PR?
> 
> Yes @nixpanic for that we need to take a call on [#2204 (comment)](https://github.com/ceph/ceph-csi/issues/2204#issuecomment-979733845) Basically, we have two options
> 
>     1. support nbd only on Kernel >= 5.14
> 
>     2. get the rbd-nbd PR [rbd-nbd: add ability to quiesce on signal ceph#42609](https://github.com/ceph/ceph/pull/42609)

It seems that until Linux kernel 5.14 is mainstream, we need ceph/ceph#42609. Neither seems ready in time for the 3.5 release, so this can be moved out.

**Comment by pkalever** [comment]
> > > @pkalever this is labelled as `[DNM]`, but also scheduled for inclusion in 3.5.0 (this week). Can you fix the status of this PR?
> > 
> > 
> > Yes @nixpanic for that we need to take a call on [#2204 (comment)](https://github.com/ceph/ceph-csi/issues/2204#issuecomment-979733845) Basically, we have two options
> > ```
> > 1. support nbd only on Kernel >= 5.14
> > 
> > 2. get the rbd-nbd PR [rbd-nbd: add ability to quiesce on signal ceph#42609](https://github.com/ceph/ceph/pull/42609)
> > ```
> 
> It seems that until Linux kernel 5.14 is mainstream, we need [ceph/ceph#42609](https://github.com/ceph/ceph/pull/42609). Neither seems ready in time for the 3.5 release, so this can be moved out.

oops! @nixpanic that was a typo

s/5.14/5.4/

**Comment by pkalever** [comment]
@nixpanic restoring the milestone tracker as release-3.5.0, assuming we still need to take a call on this.

Thanks!

**Comment by nixpanic** [comment]
> @nixpanic restoring the milestone tracker as release-3.5.0, assuming we still need to take a call on this.

Minikube still comes with Linux kernel 4.19, so we need ceph/ceph#42609 to have regular testing, or minikube updates its kernel. Until then, I would not feel comfortable to mark rbd-nbd as beta (fully functional, only minor changes needed).

**Comment by pkalever** [comment]
> Minikube still comes with Linux kernel 4.19, so we need [ceph/ceph#42609](https://github.com/ceph/ceph/pull/42609) to have regular testing, or minikube updates its kernel. Until then, I would not feel comfortable to mark rbd-nbd as beta (fully functional, only minor changes needed).

Additionally, it would be great if we can beta NBD with healer controller with the ceph-addons specifications.
This is something that I'm currently working on, will post the detailed document next week.

**Comment by Madhu-1** [comment]
Hello there! There hasn't been any activity on this PR for quite some time, so I have removed the "keepalive" label. To avoid it being closed as stale shortly, please revisit and give it some attention. Thank you!

**Pull request closed without merging**
