### PR TITLE
rbd: remove false error check in getDeviceSize

### PR DESCRIPTION
**Pull request by humblec**
this removed err condition will be always false as error is always nil.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Review by Rakshith-R — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Comment by humblec** [comment]
@Mergifyio requeue

**Comment by nixpanic** [comment]
PR was rebased, need to remove/add the `ok-to-test` label (see #3509 for automation around this)

**Comment by humblec** [comment]
@Mergifyio requeue

**Pull request merged**
