### PR TITLE
csi-snapshotter update

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@Madhu-1 please review :) .. Thanks !

**Comment by humblec** [comment]
@ShyamsundarR @poornimag PTAL .

**Comment by humblec** [comment]
> scripts that populate minikube instance with images needs an update as well `scripts/minikube.sh`:

Done. PTAL .

**Comment by Madhu-1** [comment]
This new image will be used if the kube version is greater than 1.14 right? we need to make version configurable via ENV

**Comment by humblec** [comment]
> am fine with the changes we need a follow-up PR to make this tag configurable

Yep.! Thanks

**Pull request merged**
