### PR TITLE
ci: remove checks for k8s 1.24 ci tests

### PR DESCRIPTION
**Pull request by Rakshith-R**
K8s 1.24 will be End of Life on 2023-07-28.
Therefore, removing checks for ci tests on
that version.

refer:
https://kubernetes.io/releases/#release-v1-24

### CODE REVIEW

**Review by Madhu-1 — COMMENTED** [review]
@Rakshith-R are you planning to make changes in Readme and Mergify for it later?

**Comment by Rakshith-R** [comment]
> @Rakshith-R are you planning to make changes in Readme and Mergify for it later?

This pr takes care of mergify configuration changes. 
We can edit Readme when we do 3.9 release ? 
https://github.com/ceph/ceph-csi#known-to-work-co-platforms

**Comment by Madhu-1** [comment]
> > @Rakshith-R are you planning to make changes in Readme and Mergify for it later?
> 
> This pr takes care of mergify configuration changes. We can edit Readme when we do 3.9 release ? https://github.com/ceph/ceph-csi#known-to-work-co-platforms

can you remove it from here as well https://github.com/ceph/ceph-csi/blob/devel/.github/workflows/pull-request-commentor.yaml#L20?

**Comment by Rakshith-R** [comment]
> can you remove it from here as well https://github.com/ceph/ceph-csi/blob/devel/.github/workflows/pull-request-commentor.yaml#L20?

done, thanks for pointing that out.
ptal

**Comment by Rakshith-R** [comment]
@mergifyio rebase

**Review by Madhu-1 — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio queue

**Pull request merged**
