### PR TITLE
e2e: correct log format in execCommandInPod()

### PR DESCRIPTION
**Pull request by nixpanic**
# Describe what this PR does #

`execCommandInPod()` does not use a correct formatting of the log message. This might get logged with the warning `%!(EXTRA string=`:
```
Aug 30 09:25:35.633: INFO: stdErr occurred 
%!(EXTRA string=unable to get monitor info from DNS SRV with service name: ceph-mon
[errno 2] error connecting to the cluster
```

### CODE REVIEW

**Comment by humblec** [comment]
LGTM.

**Comment by nixpanic** [comment]
@humblec unrelated CI failures... Could this get merged soon?

**Comment by Madhu-1** [comment]
@nixpanic we avoid manual merging for  PR's in cephcsi

**Comment by nixpanic** [comment]
On Wed, Sep 04, 2019 at 01:57:54AM -0700, Madhu Rajanna wrote:
> @nixpanic we avoid manual merging for  PR's in cephcsi

Ok, that is fine!

**Comment by Madhu-1** [comment]
@nixpanic need rebase

**Comment by Madhu-1** [comment]
@ShyamsundarR @humblec PTAL

**Pull request merged**
