### PR TITLE
ci: update mergify rules for kubernetes 1.29

### PR DESCRIPTION
**Pull request by riya-singhal31**
[1] - This updates the mergify rules for devel branch to consider testing with kubernetes - 1.29

[2] - This updates the mergify rules for newer releases to test with k8s-1.29 but exclude 1.29 testing for CephCSI <= 3.10 

depends-on: https://github.com/ceph/ceph-csi/pull/4354

### CODE REVIEW

**Comment by nixpanic** [comment]
Should we consider skipping Kubernetes 1.26 for the devel branch? That version will be maintained for 2 more months (https://kubernetes.io/releases/), which ends before we would release Ceph-CSI 3.11.

@Rakshith-R what do you think?

**Comment by riya-singhal31** [comment]
> Should we consider skipping Kubernetes 1.26 for the devel branch? That version will be maintained for 2 more months (https://kubernetes.io/releases/), which ends before we would release Ceph-CSI 3.11.
> 
> @Rakshith-R what do you think?

I agree, 
@Rakshith-R waiting for your reply.

**Comment by Rakshith-R** [comment]
> > Should we consider skipping Kubernetes 1.26 for the devel branch? That version will be maintained for 2 more months (https://kubernetes.io/releases/), which ends before we would release Ceph-CSI 3.11.
> > @Rakshith-R what do you think?
> 
> I agree, @Rakshith-R waiting for your reply.


sorry for the delay. 
Yes, I think we can remove k8s-1.26 testing for devel branch.

**Review by nixpanic — APPROVED** [review]

**Review by yati1998 — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio queue

**Pull request merged**
