### PR TITLE
ci: enable debug logs in kubelet

### PR DESCRIPTION
**Pull request by Madhu-1**
enable debug logs in kubelet for better debugging.

### CODE REVIEW

**Review by nixpanic — COMMENTED** [review]
I guess this is mostly done for #4073? Do you want to keep the level (4) in any case?

**Comment by Madhu-1** [comment]
@nixpanic yes keeping it to `4 will help in debugging any CI issues.

**Comment by nixpanic** [comment]
> /test ci/centos/mini-e2e/k8s-1.27

Wondering if the canary resize image works with Kubernetes 1.27 too.

**Comment by riya-singhal31** [comment]
CI passed on 1.28

**Comment by nixpanic** [comment]
> Wondering if the canary resize image works with Kubernetes 1.27 too.

Seems to be fine :partying_face:

**Comment by riya-singhal31** [comment]
> /test ci/centos/mini-e2e-helm/k8s-1.28

This too passed!

**Review by nixpanic — DISMISSED** [review]
We at least need this in the `devel` branch for now. Hopefully a csi-resizer release is planned soon.

**Comment by nixpanic** [comment]
@mergifyio rebase

**Review by riya-singhal31 — DISMISSED** [review]

**Comment by nixpanic** [comment]
Even with the label, it is running the full **multi-arch-build** instead of the single arch one. The arm64 repository from CentOS or Ceph has some inconsistency. Yesterday that was the case for amd64 too, but that seems to have been resolved.

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
Added the `ci/e2e/skip` label as only the Dockerfile for the multi-arch-build has been modified. The e2e tests did pass without that change already, no need to run them again.

**Review by riya-singhal31 — APPROVED** [review]

**Pull request merged**
