### PR TITLE
snapshotter sidecar updated to v6.0.1

### PR DESCRIPTION
**Pull request by humblec**
External snapshotter released v6.0.1 which addressed some of the issues with v6.0.0

Ref # https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v6.0.1

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Review by nixpanic — DISMISSED** [review]
as mentioned before, it is fine to rebase a version like this in a single commit.

**Review by Madhu-1 — APPROVED** [review]

**Review by Rakshith-R — APPROVED** [review]

**Comment by humblec** [comment]
@Mergifyio rebase

**Comment by humblec** [comment]
@Mergifyio refresh

**Pull request merged**
