### PR TITLE
fix: ErrWaitTimeout is deprecated in k8s 1.27

### PR DESCRIPTION
**Pull request by riya-singhal31**
replaced ErrWaitTimeout with Interrupted

### CODE REVIEW

**Comment by nixpanic** [comment]
Maybe this is only available when the dependencies are updated to k8s-1.27?

https://github.com/ceph/ceph-csi/actions/runs/4762693968/jobs/8465215176?pr=3763
image

**Comment by riya-singhal31** [comment]
> Maybe this is only available when the dependencies are updated to k8s-1.27?
> 
> https://github.com/ceph/ceph-csi/actions/runs/4762693968/jobs/8465215176?pr=3763 image

Yes, right.
Required for - https://github.com/ceph/ceph-csi/pull/3752

**Comment by Madhu-1** [comment]
Please feel free to close this and make the same change in  https://github.com/ceph/ceph-csi/pull/3752 or CI will not pass.

**Comment by riya-singhal31** [comment]
>> Please feel free to close this and make the same change in #3752 or CI will not pass.

Sure, closing this and made the same changes in #3752. Thanks.

**Pull request closed without merging**
