### PR TITLE
e2e: various corrections in e2e code

### PR DESCRIPTION
**Pull request by humblec**
This PR covers below items in e2e code and travis CI scripts

correct createORDeleteCephfsResources() function name for both cephfs and rbd
e2e: correct gosec marker for credentials rule
e2e: use proper variable name for rbdmountoptions
cleanup: fix codespell error in internal/utils package
cleanup: correct typo in travis scripts

Closes: #2167
Closes: #2168

### CODE REVIEW

**Comment by humblec** [comment]
@Madhu-1 @nixpanic ptal .

**Review by yati1998 — COMMENTED** [review]
LGTM

**Comment by nixpanic** [comment]
Can you update the PR description with the PRs that have the changes in the `devel` branch?
Ideally the commits are cherry-picked with `-x` so that they include the commit-id from the changes in the `devel` branch too.

**Comment by nixpanic** [comment]
The number of commits that are backported like #2167 and #2168 differs. Maybe I am missing something, or referred to incorrect backports. Please check and update the PR description.

**Comment by humblec** [comment]
@nixpanic iic nothing is missing except this change https://github.com/ceph/ceph-csi/pull/2168/files#diff-bfe7fe7ada8a43a75c21ddfd9535e10f37d6e55e9a3006ce5a1872f73f3ae198R916 where `defaultSCName` is an arg in `devel` branch but not in `release-3.3`. 
however a second pair of eyes is good to make sure I didnt miss any.

The commits are consolidated from #2153 and #2167

**Review by nixpanic — DISMISSED** [review]
> The commits are consolidated from #2153 and #2167

Could you please just cherry-pick them like we usually do? This added more work for you, and makes reviewing more complex for everyone else.

**Comment by humblec** [comment]
> > The commits are consolidated from #2153 and #2167
> 
> Could you please just cherry-pick them like we usually do? This added more work for you, and makes reviewing more complex for everyone else.

It was anyway about taking care of conflict. 
I have refreshed the PRs with all the commits separately.   @nixpanic ptal.

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e/k8s-1.20

failed due to #1969 :
```
Jun 17 17:17:32.134: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
```

**Review by yati1998 — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Pull request merged**
