### PR TITLE
rbd: fix encryption of rbd image with VaultToken

### PR DESCRIPTION
**Pull request by Madhu-1**
This PR fixes the below issues in the KMS encryption.

* Unmarshal the configuration only we read from the file
* Fix error check when reading vaultCAFromSecret
* Fix incorrect reading of client cert key
* Store VaultCAVerify as a string
* Set tenant in kms object
* Change key in secret for cert and tls

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Review by nixpanic — DISMISSED** [review]

**Review by nixpanic — APPROVED** [review]

**Comment by Madhu-1** [comment]
@nixpanic can we add ready-to-merge label?

**Pull request merged**
