### PR TITLE
helm: support adding annotations to StorageClasses

### PR DESCRIPTION
**Pull request by lshmouse**
# Describe what this PR does #

Support adding annotations to StorageClasses in helm charts

## Is there anything that requires special attention ##

Do you have any questions?

Is the change backward compatible?
Yes

Are there concerns around backward compatibility?
No

Provide any external context for the change, if any.

For example:

* Kubernetes links that explain why the change is required
* CSI spec related changes/catch-up that necessitates this patch
* golang related practices that necessitates this change

## Related issues ##

Mention any github issues relevant to this PR. Adding below line
will help to auto close the issue once the PR is merged.

Fixes: #issue_number

## Future concerns ##

List items that are not part of the PR and do not impact it's
functionality, but are work items that can be taken up subsequently.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

**Review by nixpanic — CHANGES_REQUESTED** [review]
This looks reasonable to me. Please note that the subject of the commit should contain a topic, you currently have
```
Support annotation config for cepth storage class in helm charts
```
and you should probably change it to something like
```
helm: support adding annotations to StorageClasses
```

Thanks!

**Review by Madhu-1 — COMMENTED** [review]
Need documentation update for the change in https://github.com/ceph/ceph-csi/tree/devel/charts/ceph-csi-rbd#configuration and https://github.com/ceph/ceph-csi/tree/devel/charts/ceph-csi-cephfs#configuration

**Comment by lshmouse** [comment]
> This looks reasonable to me. Please note that the subject of the commit should contain a topic, you currently have
> 
> ```
> Support annotation config for cepth storage class in helm charts
> ```
> 
> and you should probably change it to something like
> 
> ```
> helm: support adding annotations to StorageClasses
> ```
> 
> Thanks!

Thanks for your review~ I will update the PR topic~

**Comment by lshmouse** [comment]
> Need documentation update for the change in https://github.com/ceph/ceph-csi/tree/devel/charts/ceph-csi-rbd#configuration and https://github.com/ceph/ceph-csi/tree/devel/charts/ceph-csi-cephfs#configuration

Thanks for your review. I will update the doc~

**Review by nixpanic — APPROVED** [review]
Thanks for the update!

**Comment by humblec** [comment]
lgtm.. Thanks for the contribution @lshmouse :+1:

**Review by Madhu-1 — APPROVED** [review]

**Review by yati1998 — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

Something went wrong while testing, GitHub seemed to be unavailable for cloning the repository and reporting results.

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e/k8s-1.22

Failed with #2264 ([logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.22/detail/mini-e2e_k8s-1.22/847/pipeline/))

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e/k8s-1.20

Failed with #2204 ([logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.20/detail/mini-e2e_k8s-1.20/2929/pipeline))

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.21

some intermediate failure connecting to the api-server ([logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.21/detail/mini-e2e-helm_k8s-1.21/1573/pipeline)):
```
/go/src/github.com/ceph/ceph-csi/e2e/rbd.go:196
  Test RBD CSI
  /go/src/github.com/ceph/ceph-csi/e2e/rbd.go:343
    Test RBD CSI [It]
    /go/src/github.com/ceph/ceph-csi/e2e/rbd.go:344
    Oct 28 13:39:00.014: failed to create PVC with error failed to get pvc: rpc error: code = Unavailable desc = transport is closing
    /go/src/github.com/ceph/ceph-csi/e2e/utils.go:786
```

**Comment by nixpanic** [comment]
> /retest ci/centos/upgrade-tests-rbd

Failed with #2264 ([logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/upgrade-tests-rbd/detail/upgrade-tests-rbd/3494/pipeline))

**Pull request merged**
