### PR TITLE
e2e: remove claimRef after deleting the PVC

### PR DESCRIPTION
**Pull request by Madhu-1**
Instead of patching the PV to update the persistentVolumeReclaimPolicy and the claimRef before deleting the PVC.
Patch PV persistentVolumeReclaimPolicy to Retain to retain the PV after deleting the PVC. Remove the claimRef on the PV after deleting the PVC so that claim can be attached to a new PVC.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
> /retest ci/centos/upgrade-tests-rbd
> /retest ci/centos/mini-e2e-helm/k8s-1.21

Both failed while deploying Rook

**Review by humblec — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by humblec** [comment]
@Madhu-1 all e2e are failing on checkout part.. restarting jenkins has been done ?

**Comment by Madhu-1** [comment]
> @Madhu-1 all e2e are failing on checkout part.. restarting jenkins has been done ?

After the plugins update seems like Jenkins is broken checking with @nixpanic [here](https://cephcsi.slack.com/archives/C0128PSNB0V/p1649742767388459)

**Comment by nixpanic** [comment]
**ci/centos/mini-e2e-helm/k8s-1.22** failed with
```
Apr 12 08:51:48.196: FAIL: backend images not matching kubernetes resource count,image count 22 kubernetes resource count 21
```
https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.22/detail/mini-e2e-helm_k8s-1.22/2573/pipeline

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio requeue

**Pull request merged**
