### PR TITLE
build: update ceph image and rook version

### PR DESCRIPTION
**Pull request by Madhu-1**
Updating ceph image version to build cephcsi and updating rook version to latest release

Depends-on: #4735

### CODE REVIEW

**Review by Rakshith-R — DISMISSED** [review]

**Comment by nixpanic** [comment]
The new Ceph image will be available in the CI mirror tomorrow.

**Review by nixpanic — APPROVED** [review]

**Review by Rakshith-R — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio queue

**Comment by nixpanic** [comment]
@mergifyio dequeue

**Review by nixpanic — APPROVED** [review]

**Review by black-dragon74 — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
@mergifyio queue

**Pull request merged**
