### PR TITLE
doc: make sure configmap object referred or documented correctly

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@nixpanic @Madhu-1 ptal.

**Comment by humblec** [comment]
> One place missed [here](https://github.com/ceph/ceph-csi/blob/master/docs/deploy-rbd.md#deployment-with-kubernetes)

Addressing it. thanks

**Comment by humblec** [comment]
@agarwal-mudit done.. addressed the comment.

**Comment by nixpanic** [comment]
Mudit approved, added `ready-to-merge`

**Pull request merged**
