### PR TITLE
cleanup: various source code comment corrections

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Review by Madhu-1 — DISMISSED** [review]

**Comment by humblec** [comment]
@Madhu-1 one more small change in the last commit. ptal

**Review by Yuggupta27 — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Comment by humblec** [comment]
@Madhu-1 can we add `ready-to-merge` label here?

**Pull request merged**
