### PR TITLE
build: prune go.sum of old versions

### PR DESCRIPTION
**Pull request by nixpanic**
When manually changing go.mod and running `go mod tidy`, the command suggests that references to old versions may not be needed anymore:

```
If reproducibility with go 1.16 is not needed:
	go mod tidy -compat=1.17
```

The above command modifies `go.sum` only.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

**Review by Madhu-1 — DISMISSED** [review]

**Comment by nixpanic** [comment]
@Madhu-1 conflicts have been resolved, please review again.

**Review by humblec — APPROVED** [review]

**Comment by humblec** [comment]
@nixpanic did you perform `go mod vendor` after this change?

**Review by Madhu-1 — APPROVED** [review]

**Comment by nixpanic** [comment]
> @nixpanic did you perform `go mod vendor` after this change?

yes, it seems nothing changed under `vendor/`.

**Comment by humblec** [comment]
> > @nixpanic did you perform `go mod vendor` after this change?
> 
> yes, it seems nothing changed under `vendor/`.

ok.. thanks for confirming.

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
> /test ci/centos/upgrade-tests-cephfs

This job did not get started for some reason?

**Pull request merged**
