### PR TITLE
deploy: update rook to 1.6.2 and disable liveness probe on mon,mds,mgr

### PR DESCRIPTION
**Pull request by Rakshith-R**
# Describe what this PR does #

- update rook to 1.6.2 
- update e2e upgrade-version to v3.3.1
- disable liveness probe on mon,mds,mgr

### CODE REVIEW

**Comment by Madhu-1** [comment]
@Rakshith-R has cherry-picked commits from https://github.com/ceph/ceph-csi/pull/1998 and added a commit on top of it to make CI happy.  @humblec PTAL

**Comment by humblec** [comment]
> @Rakshith-R has cherry-picked commits from #1998 and added a commit on top of it to make CI happy. @humblec PTAL

@Rakshith-R @Madhu-1 disabling livenessprobe is not the correct approach, Isnt it?

**Comment by Madhu-1** [comment]
> > @Rakshith-R has cherry-picked commits from #1998 and added a commit on top of it to make CI happy. @humblec PTAL
> 
> @Rakshith-R @Madhu-1 disabling livenessprobe is not the correct approach, Isnt it?

Am fine with this hack to keep PR's Moving. @humblec anything else on your mind to fix this one?

**Comment by humblec** [comment]
> > > @Rakshith-R has cherry-picked commits from #1998 and added a commit on top of it to make CI happy. @humblec PTAL
> > 
> > 
> > @Rakshith-R @Madhu-1 disabling livenessprobe is not the correct approach, Isnt it?
> 
> Am fine with this hack to keep PR's Moving. @humblec anything else on your mind to fix this one?

We can do that, but as we all were discussing in #1998 , instead of hacking, we were interested to find the actual root cause. The problem with the liveness probe disablement is that, we dont know exactly the rook cluster is fine or not. Regarding, what we can do to fix the issue is that, I believe we have to work with Rook Team considering the fact that, the rook cluster deployment fails with a combination of `minikube+ kube+ rook version` here but succeed in their setup.

**Comment by Madhu-1** [comment]
> > > > @Rakshith-R has cherry-picked commits from #1998 and added a commit on top of it to make CI happy. @humblec PTAL
> > > 
> > > 
> > > @Rakshith-R @Madhu-1 disabling livenessprobe is not the correct approach, Isnt it?
> > 
> > 
> > Am fine with this hack to keep PR's Moving. @humblec anything else on your mind to fix this one?
> 
> We can do that, but as we all were discussing in #1998 , instead of hacking, we were interested to find the actual root cause. 


IMO we should not block the PR's getting merged because of this one. It's good if someone can continue the debugging on a separate PR to find a root cause. 

>The problem with the liveness probe disablement is that, we dont know exactly the rook cluster is fine or not. Regarding, what we can do to fix the issue is that, I believe we have to work with Rook Team considering the fact that, the rook cluster deployment fails with a combination of `minikube+ kube+ rook version` here but succeed in their setup.

Rook uses Github actions for their testing.

**Review by Madhu-1 — APPROVED** [review]

**Comment by humblec** [comment]
Thanks @Rakshith-R for opening the issue as discussed. Lets get our PR merge rolling for now as discussed and continue analysing the issues in a sidechannel , thanks :+1:  lgtm.

**Review by humblec — APPROVED** [review]

**Pull request merged**
