### PR TITLE
doc: add note for cephfs snapshot limitation

### PR DESCRIPTION
**Pull request by Madhu-1**
added a note for cephfs snapshot limitation

updates #1242

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
@MergifyIO rebase

**Comment by Madhu-1** [comment]
Just did rebase commitlint bot was failing

**Comment by zalsader** [comment]
Where does the 400 snapshot limit come from? I don't see it in the code.

**Comment by zalsader** [comment]
It seems that this problem was resolved in octopus: https://github.com/ceph/ceph/pull/38553

**Comment by Madhu-1** [comment]
@zalsader Thanks for noticing it, we need to remove that from our doc, if we don't have that limitation with ceph

**Pull request merged**
