### PR TITLE
Upgrade: csi-node-driver-registrar from v1.1.0 to v1.2.0

### PR DESCRIPTION
**Pull request by hswong3i**
Upgrade: csi-node-driver-registrar from v1.1.0 to v1.2.0

See https://github.com/kubernetes-csi/node-driver-registrar/releases/tag/v1.2.0
See https://github.com/kubernetes-csi/node-driver-registrar/blob/v1.2.0/CHANGELOG-1.2.md

### CODE REVIEW

**Comment by hswong3i** [comment]
> same changes required in minikube.sh and helm charts

Updated.

**Comment by hswong3i** [comment]
> LGTM @hswong3i if possible can you please squash the commit in this PR as well as in other PR's as well?

Done

**Comment by hswong3i** [comment]
Code rebased

**Comment by Madhu-1** [comment]
@hswong3i can you please update commit message based on #773

**Comment by hswong3i** [comment]
> @hswong3i can you please update commit message based on #773

Done

**Comment by humblec** [comment]
@hswong3i can you please rebase ?

**Comment by hswong3i** [comment]
Rebased

**Pull request merged**
