### PR TITLE
ci: only add `/test ..` comment if the branch for the PR matches

### PR DESCRIPTION
**Pull request by nixpanic**
By adding an if-statement for each step of the matrix job, only those steps are executed where the base ref of the PR matches the branch in the matrix parameters.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

### CODE REVIEW

**Review by Madhu-1 — APPROVED** [review]

**Review by riya-singhal31 — APPROVED** [review]

**Comment by Madhu-1** [comment]
@nixpanic we need to adjust the mergify rules as per the new change. for now i started some tests manually in some PR as mergify still needs all checks to be passed

**Pull request merged**
