### PR TITLE
cmd: remove old command main files

### PR DESCRIPTION
**Pull request by phlogistonjohn**
Now that the unified binary has its own main file under "cmd/"
we no longer need the split main.go files.

Signed-off-by: John Mulligan <jmulligan@redhat.com>

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
Note: I noticed that that github tried to make "csi-v1.0" the parent branch, which wasn't what I used (master), so I changed it. However, if PRs are supposed to be  filed against the csi-v1.0 branch first please let me know and I'll duplicate this. If not, we should consider changing the settings of the repo.

**Comment by ShyamsundarR** [comment]
> Note: I noticed that that github tried to make "csi-v1.0" the parent branch, which wasn't what I used (master), so I changed it. However, if PRs are supposed to be filed against the csi-v1.0 branch first please let me know and I'll duplicate this. If not, we should consider changing the settings of the repo.

The move to master is pending on PR #302 but all new PRs are to be posted against master.

**Comment by ShyamsundarR** [comment]
@Madhu-1 @humblec @gman0 @leseb Request a review and if appropriate add the second approval for a merge. Thanks.

**Comment by humblec** [comment]
@phlogistonjohn we have makefile targets `all: rbdplugin cephfsplugin` in place but I dont see targets. Dont we need to clean it up as well ?

**Comment by phlogistonjohn** [comment]
Hi @humblec that issue was not introduced by this PR. It was introduced by one of my previous PRs and needs fixing but shouldn't block this pr. I will follow up with more fixes for the "unified" build approach.

**Pull request merged**
