### PR TITLE
cleanup: avoid comparing errors directly

### PR DESCRIPTION
**Pull request by humblec**
Go 1.13 contains support for error wrapping. To support wrapping,
    fmt.Errorf now has a %w verb for creating wrapped errors, and three
    new functions in the errors package ( errors.Unwrap, errors.Is and
    errors.As) simplify unwrapping and inspecting wrapped errors.
    
    With this change, If we currently compare errors using ==, we have to
    use errors.Is instead. Example:
    
    if err == io.ErrUnexpectedEOF
    
    becomes
    
    if errors.Is(err, io.ErrUnexpectedEOF)
    
    https://tip.golang.org/doc/go1.13#error_wrapping

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by nixpanic** [comment]
Why is this wrong?

**Comment by humblec** [comment]
> Why is this wrong?

@nixpanic please check the commit message and I believe that will answer.

**Comment by humblec** [comment]
@Madhu-1 @nixpanic ptal

**Comment by humblec** [comment]
> Thanks for updating the commit message!
> 
> There are a few more occasions, do you not want to address them all in this PR?

sure. I can do that. revisiting the PR. @nixpanic

**Comment by humblec** [comment]
> Still missing changes to internal/util/cephcmds.go and internal/util/connection.go.

@nixpanic if you are referring the instances like `err == rados.ErrNotFound` in above mentioned files, we cannot use it directly as these are Error Constants and not error objects.
I am looking into the lint failure

**Comment by nixpanic** [comment]
> > Still missing changes to internal/util/cephcmds.go and internal/util/connection.go.
> 
> @nixpanic if you are referring the instances like `err == rados.ErrNotFound` in above mentioned files, we cannot use it directly as these are Error Constants and not error objects.
> I am looking into the lint failure

Ah, ok. Let me know when this is ready for review then.

**Comment by nixpanic** [comment]
> I am looking into the lint failure

As you're using some linter, please make sure to link this PR with the issue that is expected to add/update the CI.

**Comment by humblec** [comment]
> > I am looking into the lint failure
> 
> As you're using some linter, please make sure to link this PR with the issue that is expected to add/update the CI.

@nixpanic this is good for review. In previous travis run there was a lint failure which I corrected and linter is not complaining any more.. So this is good to go !
@Madhu-1

**Comment by humblec** [comment]
@Madhu-1 ptal.

**Pull request merged**
