### PR TITLE
cleanup: use common logging functions in the util package

### PR DESCRIPTION
**Pull request by nixpanic**
# Describe what this PR does #

Introduce additional log functions in the util package, so that `klog.Errorf()`, `klog.Fatalf()` and `klog.Warningf()` can be replaced by our own common logging functions. In the end, this makes us less dependent on the klog package, so upgrading becomes easier.

## Future concerns ##

Other parts of the code need replacing the klog package too. This can be done is multiple follow-up PRs.

### CODE REVIEW

**Comment by Madhu-1** [comment]
@nixpanic CI failure

**Comment by nixpanic** [comment]
An incorrect push closed this... I can not "reopen and comment" on this PR, so I'll create a new one.

**Pull request closed without merging**
