### PR TITLE
Migrate from dep to go module

### LINKED ISSUE #854: Migrate from dep to go modules
Migrate from dep to go modules for  package management

### PR DESCRIPTION
**Pull request by Madhu-1**
Migrate from dep to go module

fixes #854
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
This is up for review.

**Comment by humblec** [comment]
LGTM. Thanks for pulling this . Approved. @Madhu-1 can you also create an issue for this in to track it under `release 2.1.0` and mark #fix label here in the description ?

**Comment by humblec** [comment]
@nixpanic can you please review this ?

**Comment by humblec** [comment]
@Madhu-1 lets please track this via an issue against `release 2.1.0`.

**Comment by humblec** [comment]
@nixpanic et al. can you review this please?

**Comment by Madhu-1** [comment]
> @Madhu-1 lets please track this via an issue against `release 2.1.0`.

its already done please check https://github.com/ceph/ceph-csi/issues/854

**Comment by humblec** [comment]
@nixpanic @ShyamsundarR any review comments here ?

**Comment by humblec** [comment]
LGTM. Approving.

**Pull request merged**
