### PR TITLE
e2e: adjust e2e test to run on kubernetes 1.25

### LINKED ISSUE #3358: Failed to create kubernetes 1.25.0 cluster with minikube.sh
```
$ /var/lib/minikube/binaries/v1.25.0/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime=remote --container-runtime-endpoint=/var/run/cri-dockerd.sock --feature-gates=ReadWriteOncePod=true,PodSecurity=false,RecoverVolumeExpansionFailure=true --hostname-override=minikube --image-service-endpoint=/var/run/cri-dockerd.sock --kubeconfig=/etc/kubernetes/kubelet.conf --node-ip=192.168.39.150 --read-only-port=10255 --resolv-conf=/run/systemd/resolve/resolv.conf --runtime-request-timeout=15m
Flag --container-runtime has been deprecated, will be removed in 1.27 as the only valid value is 'remote'
Flag --feature-gates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --read-only-port has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --runtime-request-timeout has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
E0830 04:42:33.556879   28061 run.go:74] "command failed" err="failed to set feature gates from initial flags-based config: cannot set feature gate PodSecurity to false, feature is locked to true"
```

The above is the logs when I run kubelet manually from the node. Due to the PodSecurity flag, we cannot deploy Kubernetes 1.25.0 with cephcsi minikube.sh script.

After Removing PodSecurity flag I can deploy kubernetes 1.25.0 cluster

```
E0830 10:17:45.307164 3628334 pod_ready.go:66] WaitExtra: waitPodCondition: error getting pod "coredns-565d847f94-q9kq4" in "kube-system" namespace (skipping!): pods "coredns-565d847f94-q9kq4" not found
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
Kubernetes control plane is running at https://192.168.39.64:8443
CoreDNS is running at https://192.168.39.64:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
[🎩︎]mrajanna@fedora ceph-csi $]kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:38:15Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by Madhu-1**
removed podsecurity feature-gate and adjusted e2e tests to use privileged pod security for the e2e namespace

Depends-On: #3365

### CODE REVIEW

**Comment by Madhu-1** [comment]
This is a replacement for https://github.com/ceph/ceph-csi/pull/3359 to allow running tests on kubernetes 1.25 and will adjust all pod security and pod templates later to not run e2e with privileged access

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Review by Rakshith-R — DISMISSED** [review]

**Comment by Madhu-1** [comment]
@nixpanic, we dont have a CI job for 1.25 yet. let me send PR for it.

**Comment by Madhu-1** [comment]
https://github.com/ceph/ceph-csi/pull/3365 should allow us to run tests on 1.25

**Comment by Madhu-1** [comment]
https://github.com/ceph/ceph-csi/pull/3372 is required as Rook deployment fails on kubernetes 1.25

**Comment by nixpanic** [comment]
> #3372 is required as Rook deployment fails on kubernetes 1.25

Note that syncing images is done nightly, so the image will be available tomorrow.

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
>+ ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@n9.dusty.ci.centos.org 'podman pull --authfile=~/.podman-auth.json registry-ceph-csi.apps.ocp.ci.centos.org/rook/ceph:v1.10.0 && podman tag registry-ceph-csi.apps.ocp.ci.centos.org/rook/ceph:v1.10.0 rook/ceph:v1.10.0 docker.io/rook/ceph:v1.10.0'
Trying to pull registry-ceph-csi.apps.ocp.ci.centos.org/rook/ceph:v1.10.0...
Error: initializing source docker://registry-ceph-csi.apps.ocp.ci.centos.org/rook/ceph:v1.10.0: reading manifest v1.10.0 in registry-ceph-csi.apps.ocp.ci.centos.org/rook/ceph: manifest unknown: manifest unknown
script returned exit code 125

@nixpanic looks like the images are not pushed to internal registry yet?

**Comment by nixpanic** [comment]
> @nixpanic looks like the images are not pushed to internal registry yet?

Not sure whats up with this... The CronJob in OCP shows the following images for rook:
```
going to copy docker://docker.io/rook/ceph:v1.9.8 to docker://registry-ceph-csi.apps.ocp.ci.centos.org/rook/ceph:v1.9.8
going to copy docker://docker.io/rook/ceph:v1.8.2 to docker://registry-ceph-csi.apps.ocp.ci.centos.org/rook/ceph:v1.8.2
going to copy docker://docker.io/rook/ceph:v1.6.2 to docker://registry-ceph-csi.apps.ocp.ci.centos.org/rook/ceph:v1.6.2
going to copy docker://docker.io/rook/ceph:v1.4.9 to docker://registry-ceph-csi.apps.ocp.ci.centos.org/rook/ceph:v1.4.9
```

I'll try to find out why v1.10 isn't included there.

**Comment by nixpanic** [comment]
Building the images in the OCP environment might have failed, even though the CI shows green:
 - https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/jjb-deploy/detail/jjb-deploy/140/pipeline/10

The OCP Console confirms the image was not rebuilt after #3372:
image

Building failed, some image is still pulling from docker:
image

Running a manual rebuild now, hope it works and not Docker Hub rate limit is hit.

**Comment by nixpanic** [comment]
Image building inside OCP is somehow stuck, many image builds are still in New or Pending state, since the end of last month.

Now manually copied the Rook v1.10.0 image to the internal CI mirror. Testing can continue!

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
Seems there is an issue in the `block-pool-ec.yaml` file:

```
Error from server (BadRequest): error when creating "./block-pool-ec.yaml": CephBlockPool in version "v1" cannot be handled as a CephBlockPool: strict decoding error: unknown field "spec.annotations"
Mon Sep 26 07:59:53 BST 2022: 'kubectl_retry create -f ./block-pool-ec.yaml' try #0 failed, checking errors
```

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
> /retest all

retesting all as all tests failed to reserve machines

**Comment by nixpanic** [comment]
> /retest all

Note that the project can "only" run 10 jobs in the CentOS CI at the same time. Additional jobs will get queued for a while, but they will time out at one point if no VMs become available. It is more efficient to request Mergify to rebase once an other PR is merged. Or, run a single job for testing.

**Comment by Madhu-1** [comment]
ci/centos/mini-e2e-helm/k8s-1.25

**Comment by Madhu-1** [comment]
1.25 CI is passing this is ready for review.

**Review by nixpanic — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio refresh

**Comment by nixpanic** [comment]
image
GitHub branch protection (required for securing repositories) makes the `ready-to-merge` label useless. At least 2 approvals are needed because of it.

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Review by Rakshith-R — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
@Mergifyio refresh

**Pull request merged**
