### PR TITLE
ci: enable 1.24 test validation

### PR DESCRIPTION
**Pull request by humblec**
Enable 1.24 tests by default or without explicit request as we
already updated our dependencies to 1.24.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
@humblec are we able to deploy kubernetes 1.24 in our CI. do you see any successful runs anywhere?

**Review by nixpanic — CHANGES_REQUESTED** [review]
At the very least you need to have "Kubernetes 1.24" in the subject, I was wondering what 1.24 version is enabled. Link to test-runs where this job worked well. I thought it required a minikube update?

**Review by nixpanic — CHANGES_REQUESTED** [review]
Please disable running on 1.21 too.

**Comment by nixpanic** [comment]
@mergifyio rebase

Just wondering what's missing from #3255

**Comment by humblec** [comment]
> Please disable running on 1.21 too.

well, https://github.com/ceph/ceph-csi/pull/3255 got merged minutes back, regardless of the mention of it carry the same commit here :eyes:

**Pull request closed without merging**
