### PR TITLE
ci: skip kube 1.25 check for devel branch

### LINKED ISSUE #4079: Update mergify actions to skip checking with k1.25 for devel branch and to skip testing on 1.28 for current releases.
Update mergify actions to skip checking with k1.25 for devel branch and to skip testing on 1.28 for current releases.

### PR DESCRIPTION
**Pull request by riya-singhal31**
This PR adds the commit to skip 1.25 check for the PRs going to devel branch. 

fixes: #4079

### CODE REVIEW

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

**Review by Madhu-1 — APPROVED** [review]

**Pull request merged**
