### PR TITLE
cephfs: fix network fencing admin id

### LINKED ISSUE #4315: cephfs: network fence does not work for cephfs
# Describe the bug #

network fence for cephfs does not work 
```yaml
rakshithr4:kubernetes-csi-addons$ k get networkfences.csiaddons.openshift.io -o yaml
apiVersion: v1
items:
- apiVersion: csiaddons.openshift.io/v1alpha1
  kind: NetworkFence
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"csiaddons.openshift.io/v1alpha1","kind":"NetworkFence","metadata":{"annotations":{},"name":"network-fence-sample"},"spec":{"cidrs":["10.90.89.66/32","11.67.12.42/32"],"driver":"rook-ceph.cephfs.csi.ceph.com","fenceState":"Unfenced","parameters":{"clusterID":"rook-ceph"},"secret":{"name":"rook-csi-cephfs-provisioner","namespace":"rook-ceph"}}}
    creationTimestamp: "2023-12-12T06:26:08Z"
    finalizers:
    - csiaddons.openshift.io/network-fence
    generation: 1
    name: network-fence-sample
    resourceVersion: "24785"
    uid: 0660c36d-f2cc-444a-a058-785344eb8f0f
  spec:
    cidrs:
    - 10.90.89.66/32
    - 11.67.12.42/32
    driver: rook-ceph.cephfs.csi.ceph.com
    fenceState: Unfenced
    parameters:
      clusterID: rook-ceph
    secret:
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph
  status:
    message: 'rpc error: code = InvalidArgument desc = missing ID field ''userID''
      in secrets'
    result: Failed
kind: List
metadata:
  resourceVersion: "
```
# Environment details #

- Image/version of Ceph CSI driver : 3.10.0
- Helm chart version : -
- Kernel version : -
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : -
- Kubernetes cluster version : -
- Ceph cluster version : -

# Steps to reproduce #

1. Setup details: setup csiaddons and rook-ceph with latest cephcsi 3.10.0
1. Create network fence CR for cephfs
1. See error

# Actual results #

The container expects `UserID` while cephfs secrets contain `AdminID`.

# Expected behavior #

NetworkFence is successful

# Logs #

```
2023-12-12T06:26:13.727Z        ERROR   failed to fence cluster network {"controller": "networkfence", "controllerGroup": "csiaddons.openshift.io", "controllerKind": "NetworkFence", "NetworkFence": {"name":"network-fence-sample"}, "namespace": "", "name": "network-fence-sample", "reconcileID": "de23838d-d52d-48de-9099-afbf5d75a52f", "DriverName": "rook-ceph.cephfs.csi.ceph.com", "CIDRs": ["10.90.89.66/32", "11.67.12.42/32"], "error": "rpc error: code = InvalidArgument desc = missing ID field 'userID' in secrets"}
github.com/csi-addons/kubernetes-csi-addons/controllers/csiaddons.(*NetworkFenceReconciler).Reconcile
        /workspace/go/src/github.com/csi-addons/kubernetes-csi-addons/controllers/csiaddons/networkfence_controller.go:148
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /workspace/go/src/github.com/csi-addons/kubernetes-csi-addons/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:118
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /workspace/go/src/github.com/csi-addons/kubernetes-csi-addons/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:314
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /workspace/go/src/github.com/csi-addons/kubernetes-csi-addons/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:265
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /workspace/go/src/github.com/csi-addons/kubernetes-csi-addons/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:226
```

```
I1212 06:28:52.526483       1 utils.go:164] ID: 43 GRPC call: /fence.FenceController/UnfenceClusterNetwork
I1212 06:28:52.526732       1 utils.go:165] ID: 43 GRPC request: {"cidrs":[{"cidr":"10.90.89.66/32"},{"cidr":"11.67.12.42/32"}],"parameters":{"clusterID":"rook-ceph"},"secrets":"***stripped***"}
E1212 06:28:52.526762       1 utils.go:169] ID: 43 GRPC error: rpc error: code = InvalidArgument desc = missing ID field 'userID' in secrets
```

cc @nixpanic @riya-singhal31

### PR DESCRIPTION
**Pull request by riya-singhal31**
closes: https://github.com/ceph/ceph-csi/issues/4315

### CODE REVIEW

**Comment by riya-singhal31** [comment]
riyasinghal@rsinghal-mac examples % kubectl get networkfences.csiaddons.openshift.io -o yaml                          
apiVersion: v1
items:
- apiVersion: csiaddons.openshift.io/v1alpha1
  kind: NetworkFence
  metadata:
    creationTimestamp: "2023-12-12T14:14:54Z"
    generation: 1
    name: network-fence-sample
    resourceVersion: "46073"
    uid: da427fd3-edf7-44bf-a0e5-dee0795c9399
  spec:
    cidrs:
    - 10.90.89.66/32
    - 11.67.12.42/24
    driver: rook-ceph.cephfs.csi.ceph.com
    fenceState: Fenced
    parameters:
      clusterID: rook-ceph
    secret:
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph
kind: List
metadata:
  resourceVersion: ""
riyasinghal@rsinghal-mac examples % kubectl get networkfences.csiaddons.openshift.io                                  
NAME                   DRIVER                          CIDRS                                 FENCESTATE   AGE   RESULT
network-fence-sample   rook-ceph.cephfs.csi.ceph.com   ["10.90.89.66/32","11.67.12.42/24"]   Fenced       23s

**Review by nixpanic — APPROVED** [review]

**Review by parth-gr — APPROVED** [review]

**Review by yati1998 — APPROVED** [review]

**Comment by riya-singhal31** [comment]
Should we backport this fix to 3.10? 
@nixpanic , @Rakshith-R

**Comment by riya-singhal31** [comment]
@Mergifyio queue

**Comment by Rakshith-R** [comment]
> riyasinghal@rsinghal-mac examples % kubectl get networkfences.csiaddons.openshift.io -o yaml apiVersion: v1 items:
> 
> * apiVersion: csiaddons.openshift.io/v1alpha1
>   kind: NetworkFence
>   metadata:
>   creationTimestamp: "2023-12-12T14:14:54Z"
>   generation: 1
>   name: network-fence-sample
>   resourceVersion: "46073"
>   uid: da427fd3-edf7-44bf-a0e5-dee0795c9399
>   spec:
>   cidrs:
>   
>   * 10.90.89.66/32
>   * 11.67.12.42/24
>     driver: rook-ceph.cephfs.csi.ceph.com
>     fenceState: Fenced
>     parameters:
>     clusterID: rook-ceph
>     secret:
>     name: rook-csi-cephfs-provisioner
>     namespace: rook-ceph
>     kind: List
>     metadata:
>     resourceVersion: ""
>     riyasinghal@rsinghal-mac examples % kubectl get networkfences.csiaddons.openshift.io
>     NAME                   DRIVER                          CIDRS                                 FENCESTATE   AGE   RESULT
>     network-fence-sample   rook-ceph.cephfs.csi.ceph.com   ["10.90.89.66/32","11.67.12.42/24"]   Fenced       23s

@riya-singhal31 

There's no status/result field printed in this ! 
Please add the logs as requested in the associated issue.

cc @nixpanic

**Comment by riya-singhal31** [comment]
```
riyasinghal@rsinghal-mac examples % kubectl get networkfences.csiaddons.openshift.io 
NAME                   DRIVER                          CIDRS                                 FENCESTATE   AGE   RESULT
network-fence-sample   rook-ceph.cephfs.csi.ceph.com   ["10.90.89.66/32","11.67.12.42/24"]   Fenced       76s   


```
```
riyasinghal@rsinghal-mac examples % kubectl logs csi-cephfsplugin-provisioner-89696fcb6-md4j8 -c csi-addons -n rook-ceph
I1214 12:44:06.005375       1 client.go:79] Probing CSI driver for readiness
I1214 12:44:06.021437       1 server.go:90] Listening for CSI-Addons requests on address: [::]:9070
```
```
riyasinghal@rsinghal-mac examples % kubectl logs csi-cephfsplugin-provisioner-89696fcb6-md4j8 -c csi-provisioner -n rook-ceph
I1214 12:44:06.337282       1 csi-provisioner.go:154] Version: v3.6.2
I1214 12:44:06.337440       1 csi-provisioner.go:177] Building kube configs for running in cluster...
I1214 12:44:06.338375       1 common.go:138] Probing CSI driver for readiness
I1214 12:44:06.341137       1 csi-provisioner.go:302] CSI driver does not support PUBLISH_UNPUBLISH_VOLUME, not watching VolumeAttachments
I1214 12:44:06.341684       1 leaderelection.go:250] attempting to acquire leader lease rook-ceph/rook-ceph-cephfs-csi-ceph-com...
```
```

riyasinghal@rsinghal-mac examples % kubectl logs csi-cephfsplugin-provisioner-89696fcb6-md4j8 -c csi-cephfsplugin -n rook-ceph

```
The logs looks cleaner
cc: @Rakshith-R

**Pull request merged**
