### PR TITLE
cephfs: Avoid hanging lock in volume mutex lock

### LINKED ISSUE #4715: Ensure ceph-lock is always released when staging encrypted cephfs volume
### Issue:
The current implementation of unlocking an encrypted filesystem in the NodeServer leaves a "hanging lock" (timeout duration will eventually clean this) if fscrypt fails to unlock. This causes unnecessary delays and negatively impact performance as this could be easily be avoided by pushing the unlocking of the lock directly to the defer stack after the lock has been acquired.

### Solution:
For more information on the issue and potential solution please see this comment chain in the original PR: https://github.com/ceph/ceph-csi/pull/4697#pullrequestreview-2176187779

### PR DESCRIPTION
**Pull request by Sunnatillo**
# Describe what this PR does #
This PR allows to avoid hanging mutex lock scenario when fscrypt fails to unlock. Prevents uncessary delay

## Related issues ##

Follow up improvement to #4697 

Fixes: #4715

**Checklist:**

* [x] **Commit Message Formatting**: Commit titles and messages follow
  guidelines in the [developer
  guide](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#commit-messages).
* [x] Reviewed the developer guide on [Submitting a Pull
  Request](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#development-workflow)
* [ ] [Pending release
  notes](https://github.com/ceph/ceph-csi/blob/devel/PendingReleaseNotes.md)
  updated with breaking and/or notable changes for the next major release.
* [ ] Documentation has been updated, if necessary.
* [ ] Unit tests have been added, if necessary.
* [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by nixpanic — DISMISSED** [review]
thanks! looks good to me

**Review by yati1998 — DISMISSED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

**Review by nixpanic — APPROVED** [review]

**Review by iPraveenParihar — APPROVED** [review]

**Review by yati1998 — APPROVED** [review]

**Comment by nixpanic** [comment]
> /retest ci/centos/upgrade-tests

Somehow these jobs keep pulling the old CentOS Stream 8 base images, eventhough the tag for the container-image was updated. I guess the images are cached somewhere, other jobs run fine, retrying again :crossed_fingers:

**Comment by nixpanic** [comment]
> /retest ci/centos/upgrade-tests

This should work now. The `ceph:v18` image is used from 2 different locations on the CI mirror. Both locations now have the updated image.

**Pull request merged**
