### PR TITLE
update kubernetes dep to 1.31.0

### PR DESCRIPTION
**Pull request by Madhu-1**
Updating the kubernetes dependency to 1.31 release

### CODE REVIEW

**Comment by nixpanic** [comment]
Looks like there is a conflict with controller-runtime?

**Comment by Madhu-1** [comment]
> Looks like there is a conflict with controller-runtime?

Yes we need new release of it, We can keep this on hold for now. let me check this later

**Comment by Madhu-1** [comment]
Added backport to 3.12 to avoid merge conflicts as this changing lot of things on the vendor side.

**Comment by Rakshith-R** [comment]
> Added backport to 3.12 to avoid merge conflicts as this changing lot of things on the vendor side.

We don't usual backport dependency changes to previous releases so it should be fine ? 
I think its a big change(risky too) to backport. 
3.12.0 will be using k8s v1.30. apis while 3.12.1 will be using k8s v1.31 apis

**Comment by Madhu-1** [comment]
> > Added backport to 3.12 to avoid merge conflicts as this changing lot of things on the vendor side.
> 
> We don't usual backport dependency changes to previous releases so it should be fine ? I think its a big change(risky too) to backport. 3.12.0 will be using k8s v1.30. apis while 3.12.1 will be using k8s v1.31 apis

am fine for with that, as long as we don't have problem with solving merge conflict.

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
> > > Added backport to 3.12 to avoid merge conflicts as this changing lot of things on the vendor side.
> > 
> > 
> > We don't usual backport dependency changes to previous releases so it should be fine ? I think its a big change(risky too) to backport. 3.12.0 will be using k8s v1.30. apis while 3.12.1 will be using k8s v1.31 apis
> 
> am fine for with that, as long as we don't have problem with solving merge conflict.

If really needed, we can always backport this at a later time.

**Review by Rakshith-R — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio queue

**Comment by Madhu-1** [comment]
@mergifyio refresh

**Pull request merged**
