### PR TITLE
doc: update documentation for v3.7.2 release

### PR DESCRIPTION
**Pull request by Madhu-1**
updated readme and upgrade doc for v3.7.2 release.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Review by pkalever — APPROVED** [review]
LGTM

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
Added ready to merge as its only doc PR

**Comment by Madhu-1** [comment]
> Added ready to merge as its only doc PR

maintainer approval is still required.

**Review by yati1998 — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Pull request merged**
