### PR TITLE
deploy: update templates to v3.9.0

### PR DESCRIPTION
**Pull request by Rakshith-R**
This commit updates templates new
v3.9.0 release.

depends-on: https://github.com/ceph/ceph-csi/pull/3937

### CODE REVIEW

**Review by riya-singhal31 — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Comment by Rakshith-R** [comment]
@mergifyio queue

**Comment by Rakshith-R** [comment]
> /retest all

all runs had the same error,
lost connections to centos machines .
```
+ ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@n27-31-0.pool.ci.centos.org ./system-status.sh

ssh: connect to host n27-31-0.pool.ci.centos.org port 22: Connection refused

script returned exit code 255
```

**Comment by Rakshith-R** [comment]
@mergifyio requeue

**Comment by Rakshith-R** [comment]
Restarted since all ci tests were stuck before

https://jenkins-ceph-csi.apps.ocp.cloud.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.26/detail/mini-e2e-helm_k8s-1.26/409/pipeline/6

**Comment by Madhu-1** [comment]
@Rakshith-R i think there is a CI outage going on.

**Comment by nixpanic** [comment]
@mergifyio queue

**Comment by Rakshith-R** [comment]
> /retest ci/centos/k8s-e2e-external-storage/1.23

The run was not found in the link
https://jenkins-ceph-csi.apps.ocp.cloud.ci.centos.org/job/k8s-e2e-external-storage-1.23/3226/display/redirect

Edit;

Forgot this version ci is not required, 
please ignore this :facepalm:

**Pull request merged**
