### PR TITLE
Update mergify for 2 approvals/review for a PR.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@gman0 @Madhu-1 PTAL

**Comment by ShyamsundarR** [comment]
Arn't we closing this branch down in favor of master once we settle on #302 ? Asking, to understand why we are continuing to push PRs to this branch?

**Comment by Madhu-1** [comment]
till that we PR can be merged on master with one approval, so we should take this PR in

**Comment by ShyamsundarR** [comment]
> till that PR can be merged on master with one approval, so we should take this PR in

The question is more around weather we should be working on this branch at all, rather than the approval counts and such.

**Comment by Madhu-1** [comment]
> > till that PR can be merged on master with one approval, so we should take this PR in
> 
> The question is more around weather we should be working on this branch at all, rather than the approval counts and such.

as csiv1.0 is default branch which  will be used for `mergify`
till we make master as default branch  we should  take PR related to build on this branch

**Comment by ShyamsundarR** [comment]
> > > till that PR can be merged on master with one approval, so we should take this PR in
> > 
> > 
> > The question is more around weather we should be working on this branch at all, rather than the approval counts and such.
> 
> as csiv1.0 is default branch which will be used for `mergify`
> till we make master as default branch we should take PR related to build on this branch

I would say remove mergify on the 1.0 branch and not take any more PRs as we are introducing breaking changes in the code that are not backward compatible. I believe we have discussed the same in a few forums. So, continuing the 1.0 branch and accepting PRs does not seem like the right thing to do.

**Comment by rootfs** [comment]
we currently don't have enough people with approval right, let's revisit this once we have enough reviewers

**Comment by humblec** [comment]
@Madhu-1 @ShyamsundarR Isnt it worh revisiting this PR ?

**Comment by Madhu-1** [comment]
@humblec AFAIK mergify works with default branch (master), we can  leave this one

@ShyamsundarR any thoughts?

**Comment by ShyamsundarR** [comment]
> @humblec AFAIK mergify works with default branch (master), we can leave this one

Yes, case in point PR #346 where [Mergify](https://github.com/ceph/ceph-csi/runs/136918681) waited for 2 approvals before a merge.

So I would say we can leave this out.

**Comment by Madhu-1** [comment]
closing as this is not required.

**Pull request closed without merging**
