### PR TITLE
build: [WIP] update k8s dependecies to v1.19.2

### PR DESCRIPTION
**Pull request by Yuggupta27**
To get better code available from the dependency chain,
update kube version to v1.19.2

Signed-off-by: Yug <yuggupta27@gmail.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
@humblec is already had a PR https://github.com/ceph/ceph-csi/pull/1380 for the same. why duplicate the work here?

**Comment by Yuggupta27** [comment]
> @humblec already had a PR #1380 for the same. why duplicate the work here?

My apologies for the duplicacy, I just wanted to discuss some of the failures on updating the versions, had to create a separate PR as couldn't add a commit on his PR.

**Comment by Yuggupta27** [comment]
Added a minor change in docker file to install golang v1.15 in place of v1.14

**Comment by humblec** [comment]
@Yuggupta27 if it works, you could top up existing commit (1380) in the PR @Madhu-1 mentioned. If you are really struggling to do that, you can continue here.

**Comment by humblec** [comment]
@Yuggupta27 are you revisiting this PR ?

**Pull request closed without merging**
