### PR TITLE
rm example documents about unsupported block volume

### LINKED ISSUE #329: Branch 'csi-v0.3' does not support block volume, should remove block-pvc example
I found this https://github.com/ceph/ceph-csi/commit/3b74bff6b6d099ac517064f9a9dbf58168c3f6b5 commit is merged into branch 'csi-v0.3', but this https://github.com/ceph/ceph-csi/pull/132/commits PR has not merged into branch 'csi-v0.3'. 

So actually branch 'csi-v0.3' does not support block volume, but we still can find the 'pvc-block.yaml' and README in examples dir. I think we should delete the content about block volume in examples.

### PR DESCRIPTION
**Pull request by lxs137**
FIX #329

### CODE REVIEW

**Comment by humblec** [comment]
@lxs137 Why are we removing block mode support ? Its supported afaict.

**Comment by humblec** [comment]
Adding `DNM` for now.

**Comment by lxs137** [comment]
> @lxs137 Why are we removing block mode support ? Its supported afaict.

In Branch: csi-v0.3, I can not found the commit 'https://github.com/ceph/ceph-csi/pull/132/commits' which supported Block Volume, such as: `rbd-plugin` pod not mount host volumeDevices dir; `NodePublishVolume` not have code to check whether a block volume ...

**Comment by j-griffith** [comment]
Works for me

**Pull request merged**
