### PR TITLE
ci: automatically run k8s-e2e-external-storage/1.22 job

### PR DESCRIPTION
**Pull request by nixpanic**
The job is currently stable and passes usually. It can now be used for
validation.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

**Review by Madhu-1 — COMMENTED** [review]
any specific reason not to consider running tests on 1.20 as default as well? currently, we are running tests on all 3 different Kubernetes versions

**Comment by nixpanic** [comment]
> any specific reason not to consider running tests on 1.20 as default as well? currently, we are running tests on all 3 different Kubernetes versions

No, not really. Just didn't try running it again. We made some changes to the tests to allow skipping things, not sure if that was included in 1.20 or 1.21.

**Review by pkalever — APPROVED** [review]
LGTM

**Comment by Madhu-1** [comment]
> > any specific reason not to consider running tests on 1.20 as default as well? currently, we are running tests on all 3 different Kubernetes versions
> 
> No, not really. Just didn't try running it again. We made some changes to the tests to allow skipping things, not sure if that was included in 1.20 or 1.21.

If the flag is not present means the tests will not be executed and all the tests are passing currently.

**Review by Madhu-1 — APPROVED** [review]

**Pull request merged**
