### PR TITLE
created struct for keeping the state of a staging transaction

### PR DESCRIPTION
**Pull request by skoef**
# Describe what this PR does #

As a follow-up on #758 I did some cleaning up on the way `NodeStageVolume` transactions can be rolled back if they fail halfway staging. By using a struct keeping state of the transaction, the code is a little cleaner and can be extended in the future more easily.

## Future concerns ##

I think a lot more cleaning up can be done to normalise code paths in the future.

### CODE REVIEW

**Comment by skoef** [comment]
@Madhu-1 I also noticed a piece of [unreachable code](https://github.com/ceph/ceph-csi/blob/master/pkg/cephfs/controllerserver.go#L58), shall I removed that too?

**Comment by Madhu-1** [comment]
Yes please

**Comment by skoef** [comment]
Some other thing that I noticed, in  `CreateVolume`, the volume's size is [passed](https://github.com/ceph/ceph-csi/blob/master/pkg/rbd/controllerserver.go#L186) to `createBackingImage` as well as the `rbdVolume` itself. `createBackingImage` doesn't do anything with the size except passing it to `createImage`, again alongside the `rbdVolume` itself. 

I suggest we remove the `volSize` parameter from both `createBackingImage` and `createImage` and just use `rbdVolume.VolSize` (called `pOpts.VolSize` in `createImage`) to round and format the size to pass to the RBD command.

**Comment by skoef** [comment]
`resizeRBDImage` had the same redundant parameter as `createBackingImage` and `createImage`, fixed that as well.

**Comment by Madhu-1** [comment]
@skoef Thanks for the cleanup

**Comment by Madhu-1** [comment]
@ShyamsundarR PTAL

**Comment by humblec** [comment]
@skoef thanks for the PR ! nice cleanup. The PR looks good to me! lgtm.  However I will wait may be some more for others to chime in.

**Comment by humblec** [comment]
There is no point to wait any more as we are nearing code freeze. Approving this.

**Pull request merged**
