### PR TITLE
e2e: add test for validation of fuseMountOptions and kernelMountOptions

### LINKED ISSUE #3083: Cephfs: Add validation for fuseMountOptions and kernelMountOptions
This is a tracker to add the E2E validation for the kernelMountOptions and fuseMountOptions for the cephfs. after mount the cephfs subvolumes we should verify that the required options exists at the mount points.

Steps to validate
* Create SC with fuseMountOptions/kernelMountOptions
* Create the PVC
* Mount PVC to application
* exec into the cephfsplugin pod and verify the options.

### PR DESCRIPTION
**Pull request by riya-singhal31**
fixes: #3083

### CODE REVIEW

**Review by nixpanic — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio queue

**Pull request merged**
