### PR TITLE
ci(mergify): don't dismiss review if PR has not merged

### PR DESCRIPTION
**Pull request by sileht**
Pull requests are not going to be queued if at the same time the pull request review are dismiss

### CODE REVIEW

**Review by Rakshith-R — DISMISSED** [review]

**Review by yati1998 — DISMISSED** [review]

**Review by nixpanic — CHANGES_REQUESTED** [review]
Many thanks for the improvements @sileht!

We follow a subject convention for commits, could you `git commit --ammend` the change and update the subject to something like `ci: don't dismiss review if PR has not merged`?

The commit also misses your `Signed-off-by:` line, can you include that as well?

In case you prefer that one of the maintainers takes care of this for you, let us know!

**Comment by Madhu-1** [comment]
@sileht ping,can you please reply to above query?

**Comment by sileht** [comment]
Sorry, my PR was just a suggestion, I don't have time to take care of it, you can take over it.

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
> Sorry, my PR was just a suggestion, I don't have time to take care of it, you can take over it.

Updated the commit and pushed it to your branch. Thanks for your contribution!

**Review by Madhu-1 — APPROVED** [review]

**Comment by nixpanic** [comment]
@humblec please check and merge manually if you are OK with the changes. This PR replaces one of your mergify configuration updates.

**Comment by humblec** [comment]
> @humblec please check and merge manually if you are OK with the changes. This PR replaces one of your mergify configuration updates.

Sure.. Lets get this in.. Thanks :+1:

**Review by humblec — APPROVED** [review]

**Pull request merged**
