### PR TITLE
deploy: update csi sidecars to latest versions

### PR DESCRIPTION
**Pull request by riya-singhal31**
CSI Sidecars releases occurred last week, Updating the following csi sidecars to their latest release versions.

CSI_NODE_DRIVER_REGISTRAR_VERSION=v2.9.3
CSI_PROVISIONER_VERSION=v3.6.3
CSI_RESIZER_VERSION=v1.9.3
CSI_SNAPSHOTTER_VERSION=v6.3.3
CSI_ATTACHER_VERSION=v4.4.3

### CODE REVIEW

**Review by nixpanic — APPROVED** [review]

**Review by yati1998 — APPROVED** [review]

**Comment by riya-singhal31** [comment]
@mergifyio queue

**Pull request merged**
