### PR TITLE
rebase: update to latest snapshotter

### PR DESCRIPTION
**Pull request by humblec**
- [x] this commit update the snapshotter client to v6.1.0
- [x] go version mention in go.mod has changed to v1.18

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
Added ok-to-test as there is no other jobs in the CI.

**Comment by Rakshith-R** [comment]
> Added ok-to-test as there is no other jobs in the CI.
@humblec 
It was decided to add ok-to-test label after a pr has the required approvals, in a FIFO fashion. 

Can you mention go version update in commit too ? 
and do we need to update go version here too https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#workspace-and-repository-setup?

**Comment by humblec** [comment]
> > Added ok-to-test as there is no other jobs in the CI.
> > @humblec
> > It was decided to add ok-to-test label after a pr has the required approvals, in a FIFO fashion.
> 
> Can you mention go version update in commit too ? 

done.

>and do we need to update go version here too https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#workspace-and-repository-setup?
>

not really. even if its 1.17 its compatible,

**Review by Rakshith-R — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Comment by Madhu-1** [comment]
@nixpanic looks like mergify configuration is not working as expected, mergify added ok-to-test label at wrong time

**Pull request merged**
