### PR TITLE
Remove PSP related templates (once Kubernetes 1.25 is released)

### LINKED ISSUE #1988: Remove PSP from kubernetes templates
PSP is deprecated in kubernetes 1.21 and will be removed in kubernetes 1.25 https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/ . as it's deprecated, we need to take into consideration when to remove the PSP templates from the cephcsi repo.

### PR DESCRIPTION
**Pull request by Madhu-1**
PSP is deprecated in kubernetes 1.21 and will be removed in kubernetes 1.25 https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/ . as it's deprecated removing the same from the cephcsi repo.

resolves #1988 

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by nixpanic** [comment]
> /test ci/centos/mini-e2e-helm/k8s-1.21

There should not be any issues with this, but we need a couple of runs to verify that the CI job is stable (#1963).

**Review by nixpanic — CHANGES_REQUESTED** [review]
The 2nd commit does not look related to the PSP removal? It ideally should be its own PR.

When PSP is dropped from our repository, will we not be able to run on Kubernetes < 1.21.0? Maybe not delete, but keep everything around until Kubernetes completely removed their PSP support too?

**Comment by humblec** [comment]
@Madhu-1 shall we keep this unmerged till we get `v1.21` in this repo?

**Comment by Madhu-1** [comment]
> The 2nd commit does not look related to the PSP removal? It ideally should be its own PR.
> 
> When PSP is dropped from our repository, will we not be able to run on Kubernetes < 1.21.0? Maybe not delete, but keep everything around until Kubernetes completely removed their PSP support too?

Yes, this should not block the deployment of cephcsi less than 1.21, if they have enabled PSP then we need it. as PSP is deprecated maybe we can remove it.

**Comment by Madhu-1** [comment]
> @Madhu-1 shall we keep this unmerged till we get `v1.21` in this repo?

Not a blocker, both are not dependent as PSP is not enabled by default in kubernetes.

**Comment by Madhu-1** [comment]
> /test ci/centos/mini-e2e-helm/k8s-1.20

Deploy Rook failed

**Comment by nixpanic** [comment]
> > The 2nd commit does not look related to the PSP removal? It ideally should be its own PR.
> > When PSP is dropped from our repository, will we not be able to run on Kubernetes < 1.21.0? Maybe not delete, but keep everything around until Kubernetes completely removed their PSP support too?
> 
> Yes, this should not block the deployment of cephcsi less than 1.21, if they have enabled PSP then we need it. as PSP is deprecated maybe we can remove it.

Deprecated means that current users are informed to move away from the feature. I think it might be useful for users that have PSP enabled, to keep the support for it available until Kubernetes removes it.

**Comment by Madhu-1** [comment]
> > > The 2nd commit does not look related to the PSP removal? It ideally should be its own PR.
> > > When PSP is dropped from our repository, will we not be able to run on Kubernetes < 1.21.0? Maybe not delete, but keep everything around until Kubernetes completely removed their PSP support too?
> > 
> > 
> > Yes, this should not block the deployment of cephcsi less than 1.21, if they have enabled PSP then we need it. as PSP is deprecated maybe we can remove it.
> 
> Deprecated means that current users are informed to move away from the feature. I think it might be useful for users that have PSP enabled, to keep the support for it available until Kubernetes removes it.

Sounds good!. Let's keep it open and merge once kubernetes 1.25 is out.

**Comment by nixpanic** [comment]
Marking `DNM` for now. We'll wait until Kubernetes 1.25 is released.

**Comment by Madhu-1** [comment]
@humblec @nixpanic as kubernetes 1.25 is the next release, this is ready for review.

**Review by nixpanic — APPROVED** [review]

**Review by yati1998 — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio refresh

**Pull request merged**
