### PR TITLE
doc: correct mdlinter errors on doc

### PR DESCRIPTION
**Pull request by humblec**
mdlinter errors are fixed with this patch.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@Madhu-1 @nixpanic ptal.

**Comment by nixpanic** [comment]
Which errors are these? Do you know why the static-check does not report them?

**Comment by humblec** [comment]
> @humblec can you please check why CI didn't catch this one?

@Madhu-1 @nixpanic I can check why it was not caught on CI. However as long as this change looks good we could let this get in.

**Comment by nixpanic** [comment]
It would help if you can at least include the error messages from the linter. I am not sure the changes are correct/required.

**Pull request closed without merging**
