### PR TITLE
e2e: test vgs beta api

### PR DESCRIPTION
**Pull request by Madhu-1**
testing vgs beta api

### CODE REVIEW

**Comment by iPraveenParihar** [comment]
@Madhu-1  We need to update apiVersion in examples? 
https://github.com/ceph/ceph-csi/blob/7731a913e981731f00a0d5c03ffc45b7e95ac651/examples/cephfs/groupsnapshotclass.yaml#L2

**Comment by Madhu-1** [comment]
> @Madhu-1 We need to update apiVersion in examples?
> 
> https://github.com/ceph/ceph-csi/blob/7731a913e981731f00a0d5c03ffc45b7e95ac651/examples/cephfs/groupsnapshotclass.yaml#L2

required for manual testing, we dont use examples yamls in the e2e test thats why not updated it

**Comment by iPraveenParihar** [comment]
> > @Madhu-1 We need to update apiVersion in examples?
> > https://github.com/ceph/ceph-csi/blob/7731a913e981731f00a0d5c03ffc45b7e95ac651/examples/cephfs/groupsnapshotclass.yaml#L2
> 
> required for manual testing, we dont use examples yamls in the e2e test thats why not updated it


I think it is used here -> TestVolumeGroupSnapshot() -> testVolumeGroupSnapshot() -> GetVolumeGroupSnapshotClass()
https://github.com/ceph/ceph-csi/blob/7731a913e981731f00a0d5c03ffc45b7e95ac651/e2e/volumegroupsnapshot.go#L50-L55

**Comment by Madhu-1** [comment]
> > > @Madhu-1 We need to update apiVersion in examples?
> > > https://github.com/ceph/ceph-csi/blob/7731a913e981731f00a0d5c03ffc45b7e95ac651/examples/cephfs/groupsnapshotclass.yaml#L2
> > 
> > 
> > required for manual testing, we dont use examples yamls in the e2e test thats why not updated it
> 
> I think it is used here -> TestVolumeGroupSnapshot() -> testVolumeGroupSnapshot() -> GetVolumeGroupSnapshotClass()
> 
> https://github.com/ceph/ceph-csi/blob/7731a913e981731f00a0d5c03ffc45b7e95ac651/e2e/volumegroupsnapshot.go#L50-L55

only the content will be copied.

**Comment by nixpanic** [comment]
> /test ci/centos/mini-e2e/k8s-1.31

This job was stared before the change from #4990 was deployed, it may still run into the 120 minute timeout.

**Comment by nixpanic** [comment]
#4990 extended the test time with 30 minutes, from 120 to 150. This is not enough yet, it seems :hourglass:

**Comment by Madhu-1** [comment]
> #4990 extended the test time with 30 minutes, from 120 to 150. This is not enough yet, it seems ⌛

I will adjust/remove pod creation and reduce the number in loop and push the changes again

**Comment by Madhu-1** [comment]
closing this as i have a new PR for it https://github.com/ceph/ceph-csi/pull/5021

**Pull request closed without merging**
