### PR TITLE
doc: add upgrade documentation for v3.1.0

### PR DESCRIPTION
**Pull request by Madhu-1**
added upgrade documentation to upgrade from v3.0.0 to v3.1.0

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
@mergifyIO rebase

**Comment by humblec** [comment]
@mergify rebase

**Comment by nixpanic** [comment]
> /test commitlint

The updated commitlint test does still not work with the mergify rebase-merge-commits. Maybe #1365 helps with it :thinking:

**Comment by Madhu-1** [comment]
@mergifyIO rebase

**Comment by humblec** [comment]
@Madhu-1 this would be the last PR for the release.

**Comment by Madhu-1** [comment]
@Mergifyio rebase

**Pull request merged**
