### PR TITLE
deploy: configurable podSecurityContexts in ceph-csi-cephfs chart

### LINKED ISSUE #4663: allow podSecurityContexts to be set in `nodeplugin` and `provisioner` of chart `ceph-csi-cephfs`
# Describe the feature you'd like to have #

Allow the pod-level security contexts to be configurable via helm values.yaml for `ceph-csi-cephfs` for both the `nodeplugin` and `provisioner`.

# What is the value to the end user? (why is it a priority?) #

End users can configure their securityContexts per environment. This is particularly important if you have an admission controller like opa or kyverno running with strict security configurations.(e.g. seccomp profile, selinux options).

# How will we know we have a good solution? (acceptance criteria) #

As I end user I can configure the pod-level security contexts for both the `nodeplugin` and `provisioner`.

# Additional context #

Proposed solution would be something along the lines of the below: with a default of no securityContext set to prevent breaking changes in end user. This allows for the flexibility to specify any of the `podSecurityContext` options.

```yaml
# values.yaml
nodeplugin:
  podSecurityContext: {}
provisioner:
  podSecurityContext: {}
---
# charts/ceph-csi-cephfs/templates/node-plugin-daemonset.yaml
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ include "ceph-csi-cephfs.nodeplugin.fullname" . }}
...
  template:
    metadata:
    spec:
     securityContext: {{ toYaml .Values.nodeplugin.podSecurityContext | nindent 8 }}
...
---
```

### PR DESCRIPTION
**Pull request by 1602077**
# Describe what this PR does #

* Pod level security context are configurable via helm values.yaml for provisioner `deployment` and nodeplugin `daemonset` with a default of no securityContext specified.

Fixes: #4663

**Checklist:**

* [x] **Commit Message Formatting**: Commit titles and messages follow
  guidelines in the [developer
  guide](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#commit-messages).
* [x] Reviewed the developer guide on [Submitting a Pull
  Request](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#development-workflow)
* [x] [Pending release
  notes](https://github.com/ceph/ceph-csi/blob/devel/PendingReleaseNotes.md)
  updated with breaking and/or notable changes for the next major release.
* [x] Documentation has been updated, if necessary.
* [x] Unit tests have been added, if necessary.
* [x] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by nixpanic — DISMISSED** [review]

**Comment by nixpanic** [comment]
Looks good to me, thanks for the PR!

**Review by Rakshith-R — DISMISSED** [review]

**Review by Madhu-1 — DISMISSED** [review]
@1602077 LGTM, can you add the same for RBD as well in followup PR?

**Comment by 1602077** [comment]
Cheers for the quick review much appreciated!

Have replicated changes for rbd in follow up [PR](https://github.com/ceph/ceph-csi/pull/4668).

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio queue

**Comment by nixpanic** [comment]
oh no, ` PendingReleaseNotes.md` was modified by an other PR, and now there is a conflict :sob:

@1602077 could you address the conflict, and force-push the change to your branch to update this PR?

**Comment by 1602077** [comment]
@nixpanic sure thing - have updated. let me know if you need anything else from me. same thing is going to happen for the [rbd PR](https://github.com/ceph/ceph-csi/pull/4668). once this is merged in I will address the conflicts on that one too

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
> @nixpanic sure thing - have updated. let me know if you need anything else from me. same thing is going to happen for the [rbd PR](https://github.com/ceph/ceph-csi/pull/4668). once this is merged in I will address the conflicts on that one too

Thanks! I'll have the CI run against this PR now, once the jobs passed and there is a 2nd approved review, this PR should get merged automatically.

**Review by Madhu-1 — APPROVED** [review]

**Comment by 1602077** [comment]
@nixpanic Okay sounds good - the CI looks to be stuck in an infinite loop when trying to request the required infra to run the e2e tests

**Comment by nixpanic** [comment]
> @nixpanic Okay sounds good - the CI looks to be stuck in an infinite loop when trying to request the required infra to run the e2e tests

Not sure why there were issues in the CI, but after upgrading Jenkins and cleaning up stuck jobs all seems to be working again :partying_face:

**Comment by nixpanic** [comment]
> > @nixpanic Okay sounds good - the CI looks to be stuck in an infinite loop when trying to request the required infra to run the e2e tests
> 
> Not sure why there were issues in the CI, but after upgrading Jenkins and cleaning up stuck jobs all seems to be working again 🥳

Oh.... maybe not all. Still some intermediate internal networking issues pulling container images :sob:

**Comment by 1602077** [comment]
Hey @nixpanic - Is there currently a planned release data for v3.12 of ceph-csi-cephfs? 

We would like to include this in our september release as part of a wider effort to enable selinux policies within our environments.

Cheers,
Jack

**Pull request merged**
