### PR TITLE
WIP node server: don't persist vol

### PR DESCRIPTION
**Pull request by rootfs**
@sbezverk

### CODE REVIEW

**Comment by sbezverk** [comment]
@rootfs Create and Delete Volume gets from CSI volume name, but Node Publish/Unpublish operates with Volume IDs, if we do not persist volume information how you can build relation then? Also CSI spec expects in case of a plugin/kubelet failure to be able to recover previously created volumes, without persistent info, how it can be done? Even in k8s CSI core side, there is a persistent storage. Another thing about CSI RPC LIST_VOLUMES, with the persistent info it is fiarly easy to do.

**Comment by rootfs** [comment]
controller still keeps the persistent json, but node doesn't need it. Node can figure out what device to unmap from mountpath.

**Comment by sbezverk** [comment]
@rootfs still how about the recovery scenario? For un-publish you get target_path and volume id, to get device for rbd unmap you will need to do an expensive search(on prod cluster there might be lots of mounted devices), instead of just a quick search in the persistent storage file.

**Comment by rootfs** [comment]
@sbezverk searching device path is what kubernetes rbd/iscsi do in this case too.

**Comment by sbezverk** [comment]
@rootfs right, I know and I heard negative feedback of doing so, I do not see the optimization of going back to this way. Appreciate if you could provide the benefits.

**Comment by rootfs** [comment]
@sbezverk we have to parse /proc/mount in either case - rbd images can only be safely detached if there is no more mountpoint.

**Pull request merged**
