### PR TITLE
cleanup: [WIP] address golangci warnings

### PR DESCRIPTION
**Pull request by Yuggupta27**
Package name should be util_test instead of
util. util package needs to be imported
seperately.

Issue Reported:
internal/util/csiconfig_test.go:17:9: package should be `util_test` instead of `util` (testpackage)
package util

Updates: #1184 

Signed-off-by: Yug Gupta <ygupta@redhat.com>

### CODE REVIEW

**Comment by nixpanic** [comment]
Note that we can not change the package name for all packages. See #1185 for a description. As an alternative to that PR, it is also possible to mark a `package util` file with `// nolint:testpackage // we're testing internals of the package`. More tests are valuable, and dropping them or reworking them in awkward ways would not be beneficial.

**Comment by Yuggupta27** [comment]
> Note that we can not change the package name for all packages. See #1185 for a description. As an alternative to that PR, it is also possible to mark a `package util` file with `// nolint:testpackage // we're testing internals of the package`. More tests are valuable, and dropping them or reworking them in awkward ways would not be beneficial.
Oh my bad, I tried to directly resolve the warnings. Should we then no lint on all test packages?

**Comment by nixpanic** [comment]
> Should we then no lint on all test packages?

If there are `*_test.go` files where it works without too much re-working, then you can rename the package. For tests that use internals of the package, you can add the `// nolint:....` comment. I opted for disabling the `testpackage` linter completely, but that might not be the best approach (I did not try anything else).

**Comment by Yuggupta27** [comment]
> > Should we then no lint on all test packages?
> 
> If there are `*_test.go` files where it works without too much re-working, then you can rename the package. For tests that use internals of the package, you can add the `// nolint:....` comment. I opted for disabling the `testpackage` linter completely, but that might not be the best approach (I did not try anything else).

Thanks, I'll try to rectify the issues wherever feasible, and nolint otherwise.

**Comment by Yuggupta27** [comment]
@humblec , these commits can be used now to reduce some of the warnings.

**Comment by humblec** [comment]
@Yuggupta27 this can be closed right ?

**Comment by Yuggupta27** [comment]
> @Yuggupta27 this can be closed right ?

Yes Humble. I'll close it.

**Comment by Yuggupta27** [comment]
Closing as changes are included in #1157 .

**Pull request closed without merging**
