### PR TITLE
rebase: update minikube to v1.26.0

### LINKED ISSUE #3221: krbd map fails on minikube 1.26.0 [kernel 5.10.57]
# Describe the bug #

krbd mapping fails with `mapOptions: "lock_on_read,queue_depth=1024"`
```
[pkalever@localhost ceph-csi]$ minikube version
minikube version: v1.26.0
commit: f4b412861bb746be73053c9f6d2895f12cf78565
[pkalever@localhost ceph-csi]$ minikube ssh "uname -a"
Linux minikube 5.10.57 #1 SMP Thu Jun 16 23:36:20 UTC 2022 x86_64 GNU/Linux
[pkalever@localhost ceph-csi]$ 
```
**csi-rbdplugin logs**
```
I0628 09:04:21.259047  197131 utils.go:193] ID: 57 Req-ID: 0001-0009-rook-ceph-0000000000000001-38e1b282-f6c1-11ec-bfa2-62e4dc6f7dcf GRPC call: /csi.v1.Node/NodeStageVolume                                                              
I0628 09:04:21.262321  197131 utils.go:197] ID: 57 Req-ID: 0001-0009-rook-ceph-0000000000000001-38e1b282-f6c1-11ec-bfa2-62e4dc6f7dcf GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.
io/csi/rook-ceph.rbd.csi.ceph.com/1ad7beac78089b6f40036343427b2915ef9dfb81373d7808a028e723f8c4ef3b/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":7}},"volume_context":{"clusterID":"ro
ok-ceph","imageFeatures":"layering","imageFormat":"2","imageName":"csi-vol-38e1b282-f6c1-11ec-bfa2-62e4dc6f7dcf","journalPool":"replicapool","mapOptions":"lock_on_read,queue_depth=1024","pool":"replicapool","storage.kubernetes.io/csiP
rovisionerIdentity":"1656405716966-8081-rook-ceph.rbd.csi.ceph.com","unmapOptions":"force"},"volume_id":"0001-0009-rook-ceph-0000000000000001-38e1b282-f6c1-11ec-bfa2-62e4dc6f7dcf"}                                                      
I0628 09:04:21.265773  197131 rbd_util.go:1273] ID: 57 Req-ID: 0001-0009-rook-ceph-0000000000000001-38e1b282-f6c1-11ec-bfa2-62e4dc6f7dcf setting disableInUseChecks: false image features: [layering] mounter: rbd                        
I0628 09:04:21.276485  197131 omap.go:88] ID: 57 Req-ID: 0001-0009-rook-ceph-0000000000000001-38e1b282-f6c1-11ec-bfa2-62e4dc6f7dcf got omap values: (pool="replicapool", namespace="", name="csi.volume.38e1b282-f6c1-11ec-bfa2-62e4dc6f7d
cf"): map[csi.imageid:15f27351b880 csi.imagename:csi-vol-38e1b282-f6c1-11ec-bfa2-62e4dc6f7dcf csi.volname:pvc-8e108a2a-fa1d-4046-bb8e-46acdec2b849 csi.volume.owner:default]                                                              
I0628 09:04:21.398055  197131 rbd_util.go:350] ID: 57 Req-ID: 0001-0009-rook-ceph-0000000000000001-38e1b282-f6c1-11ec-bfa2-62e4dc6f7dcf checking for ImageFeatures: [layering]                                                            
I0628 09:04:21.486852  197131 cephcmds.go:105] ID: 57 Req-ID: 0001-0009-rook-ceph-0000000000000001-38e1b282-f6c1-11ec-bfa2-62e4dc6f7dcf command succeeded: rbd [device list --format=json --device-type krbd]                             
I0628 09:04:21.547333  197131 rbd_attach.go:420] ID: 57 Req-ID: 0001-0009-rook-ceph-0000000000000001-38e1b282-f6c1-11ec-bfa2-62e4dc6f7dcf rbd: map mon 10.103.209.73:6789                                                                 
I0628 09:04:21.951198  197131 cephcmds.go:98] ID: 57 Req-ID: 0001-0009-rook-ceph-0000000000000001-38e1b282-f6c1-11ec-bfa2-62e4dc6f7dcf an error (exit status 22) occurred while running rbd args: [--id csi-rbd-node -m 10.103.209.73:6789
 --keyfile=***stripped*** map replicapool/csi-vol-38e1b282-f6c1-11ec-bfa2-62e4dc6f7dcf --device-type krbd --options noudev --options lock_on_read,queue_depth=1024]                                                                       
W0628 09:04:21.952324  197131 rbd_attach.go:469] ID: 57 Req-ID: 0001-0009-rook-ceph-0000000000000001-38e1b282-f6c1-11ec-bfa2-62e4dc6f7dcf rbd: map error an error (exit status 22) occurred while running rbd args: [--id csi-rbd-node -m 
10.103.209.73:6789 --keyfile=***stripped*** map replicapool/csi-vol-38e1b282-f6c1-11ec-bfa2-62e4dc6f7dcf --device-type krbd --options noudev --options lock_on_read,queue_depth=1024], rbd output: rbd: sysfs write failed                
rbd: map failed: (22) Invalid argument                                                                                                                                                                                                    
E0628 09:04:21.953827  197131 utils.go:202] ID: 57 Req-ID: 0001-0009-rook-ceph-0000000000000001-38e1b282-f6c1-11ec-bfa2-62e4dc6f7dcf GRPC error: rpc error: code = Internal desc = rbd: map failed with error an error (exit status 22) oc
curred while running rbd args: [--id csi-rbd-node -m 10.103.209.73:6789 --keyfile=***stripped*** map replicapool/csi-vol-38e1b282-f6c1-11ec-bfa2-62e4dc6f7dcf --device-type krbd --options noudev --options lock_on_read,queue_depth=1024]
, rbd error output: rbd: sysfs write failed                                                                                                                                                                                               
rbd: map failed: (22) Invalid argument                                                                                                                                                                                                    
```
**dmesg**
```
[Tue Jun 28 09:04:21 2022] libceph: mon0 (1)10.103.209.73:6789 session established              
[Tue Jun 28 09:04:21 2022] libceph: mon0 (1)10.103.209.73:6789 socket closed (con state OPEN)   
[Tue Jun 28 09:04:21 2022] libceph: mon0 (1)10.103.209.73:6789 session lost, hunting for new mon
[Tue Jun 28 09:04:21 2022] libceph: mon0 (1)10.103.209.73:6789 session established              
[Tue Jun 28 09:04:21 2022] libceph: client5824 fsid 96c1dd8a-cb81-4563-a03a-7be3e7cb7761        
[Tue Jun 28 09:04:21 2022] rbd: rbd0: exclusive-lock feature is not enabled
[...]
[Tue Jun 28 09:06:33 2022] libceph: mon0 (1)10.103.209.73:6789 session established
[Tue Jun 28 09:06:33 2022] libceph: mon0 (1)10.103.209.73:6789 socket closed (con state OPEN)
[Tue Jun 28 09:06:33 2022] libceph: mon0 (1)10.103.209.73:6789 session lost, hunting for new mon
[Tue Jun 28 09:06:33 2022] libceph: mon0 (1)10.103.209.73:6789 session established
[Tue Jun 28 09:06:33 2022] libceph: client5890 fsid 96c1dd8a-cb81-4563-a03a-7be3e7cb7761
[Tue Jun 28 09:06:33 2022] rbd: rbd0: exclusive-lock feature is not enabled
```

**Ceph version**
```
[pkalever@localhost ~]$  krc exec -it pod/rook-ceph-tools-68f89f79f9-tl2rx -- ceph version
ceph version 17.2.1 (ec95624474b1871a821a912b8c3af68f8f8e7aa1) quincy (stable)
```

**Other details**
When we try to reproduce the same mapping issue on minikube v1.25.0 with same ceph image version and map options, we couldn't hit the issue

```
[pkalever@localhost ~]$ minikube version
minikube version: v1.25.0
commit: 3edf4801f38f3916c9ff96af4284df905a347c86
[pkalever@localhost ~]$ minikube ssh "uname -a"
Linux minikube 4.19.202 #1 SMP Thu Dec 23 10:44:17 UTC 2021 x86_64 GNU/Linux
[pkalever@localhost ~]$ krc exec -it pod/rook-ceph-tools-f87879d85-mxhrf -- ceph version
ceph version 17.2.1 (ec95624474b1871a821a912b8c3af68f8f8e7aa1) quincy (stable)
[pkalever@localhost ~]$ kubectl exec -it pod/csirbd-demo-pod -- df -Th
Filesystem     Type     Size  Used Avail Use% Mounted on
overlay        overlay   28G  4.6G   22G  18% /
tmpfs          tmpfs     64M     0   64M   0% /dev
tmpfs          tmpfs    2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/vda1      ext4      28G  4.6G   22G  18% /etc/hosts
shm            tmpfs     64M     0   64M   0% /dev/shm
/dev/rbd0      ext4     976M  2.6M  958M   1% /var/lib/www/html
tmpfs          tmpfs    3.9G   12K  3.9G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs          tmpfs    2.0G     0  2.0G   0% /proc/acpi
tmpfs          tmpfs    2.0G     0  2.0G   0% /proc/scsi
tmpfs          tmpfs    2.0G     0  2.0G   0% /sys/firmware
[pkalever@localhost ~]$ kubectl exec -it pod/csirbd-demo-pod -- ls /var/lib/www/html
lost+found
[pkalever@localhost ~]$ 
```

**logs**
[dmesg.log](https://github.com/ceph/ceph-csi/files/9000007/dmesg.log)
[csi-rbdplugin.log](https://github.com/ceph/ceph-csi/files/9000009/csi-rbdplugin.log)

### PR DESCRIPTION
**Pull request by pkalever**
# Describe what this PR does #

A new stable release of minikube is available, let's switch to it.
https://github.com/kubernetes/minikube/releases/tag/v1.26.0

Signed-off-by: Prasanna Kumar Kalever \<prasanna.kalever@redhat.com\>

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

**Review by Madhu-1 — DISMISSED** [review]

**Review by humblec — DISMISSED** [review]

**Review by Rakshith-R — DISMISSED** [review]

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by pkalever** [comment]
@Mergifyio rebase

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.23

```
Jun 24 16:51:14.647: INFO: Deleting PersistentVolumeClaim csi-cephfs-pvc on namespace cephfs-4728
Jun 24 16:51:14.665: INFO: waiting for PVC csi-cephfs-pvc in state &PersistentVolumeClaimStatus{Phase:Bound,AccessModes:[ReadWriteMany],Capacity:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},Conditions:[]PersistentVolumeClaimCondition{},AllocatedResources:ResourceList{},ResizeStatus:nil,} to be deleted (0 seconds elapsed)
Jun 24 16:51:16.674: INFO: waiting for PVC csi-cephfs-pvc in state &PersistentVolumeClaimStatus{Phase:Bound,AccessModes:[ReadWriteMany],Capacity:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},Conditions:[]PersistentVolumeClaimCondition{},AllocatedResources:ResourceList{},ResizeStatus:nil,} to be deleted (2 seconds elapsed)
Jun 24 16:51:18.674: INFO: waiting for PVC csi-cephfs-pvc in state &PersistentVolumeClaimStatus{Phase:,AccessModes:[],Capacity:ResourceList{},Conditions:[]PersistentVolumeClaimCondition{},AllocatedResources:ResourceList{},ResizeStatus:nil,} to be deleted (4 seconds elapsed)
...
Jun 24 17:01:14.674: INFO: waiting for PVC csi-cephfs-pvc in state &PersistentVolumeClaimStatus{Phase:,AccessModes:[],Capacity:ResourceList{},Conditions:[]PersistentVolumeClaimCondition{},AllocatedResources:ResourceList{},ResizeStatus:nil,} to be deleted (600 seconds elapsed)
Jun 24 17:01:14.681: INFO: waiting for PVC csi-cephfs-pvc in state &PersistentVolumeClaimStatus{Phase:,AccessModes:[],Capacity:ResourceList{},Conditions:[]PersistentVolumeClaimCondition{},AllocatedResources:ResourceList{},ResizeStatus:nil,} to be deleted (600 seconds elapsed)
Jun 24 17:01:14.687: FAIL: failed to delete PVC and Deployment: timed out waiting for the condition
```

#3213 attempts to address this

**Comment by nixpanic** [comment]
> /retest ci/centos/k8s-e2e-external-storage/1.21

```
Summarizing 1 Failure:

[Fail] External Storage [Driver: cephfs.csi.ceph.com] [Testpattern: Dynamic PV (default fs)] subPath [It] should support restarting containers using file as subpath [Slow][LinuxOnly] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/framework/volume_resource.go:296
```

[logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/k8s-e2e-external-storage-1.21/detail/k8s-e2e-external-storage-1.21/4064/pipeline)

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.23

```
Jun 27 07:46:55.114: FAIL: backend images not matching kubernetes resource count,image count 22 kubernetes resource count 21
backend image Info:
 [csi-vol-d7c3caf6-f5e4-11ec-bca9-5a782f967c4b csi-vol-d9b2dff0-f5e4-11ec-bca9-5a782f967c4b csi-vol-d9b2dff0-f5e4-11ec-bca9-5a782f967c4b-temp csi-vol-d9d6073d-f5e4-11ec-bca9-5a782f967c4b csi-vol-d9d6073d-f5e4-11ec-bca9-5a782f967c4b-temp csi-vol-d9f09142-f5e4-11ec-bca9-5a782f967c4b-temp csi-vol-da0ec429-f5e4-11ec-bca9-5a782f967c4b csi-vol-da0ec429-f5e4-11ec-bca9-5a782f967c4b-temp csi-vol-da698d85-f5e4-11ec-bca9-5a782f967c4b csi-vol-da698d85-f5e4-11ec-bca9-5a782f967c4b-temp csi-vol-da8a4169-f5e4-11ec-bca9-5a782f967c4b csi-vol-da8a4169-f5e4-11ec-bca9-5a782f967c4b-temp csi-vol-da9f0682-f5e4-11ec-bca9-5a782f967c4b csi-vol-da9f0682-f5e4-11ec-bca9-5a782f967c4b-temp csi-vol-dabd0587-f5e4-11ec-bca9-5a782f967c4b csi-vol-dabd0587-f5e4-11ec-bca9-5a782f967c4b-temp csi-vol-dd64a9fd-f5e4-11ec-bca9-5a782f967c4b csi-vol-dd64a9fd-f5e4-11ec-bca9-5a782f967c4b-temp csi-vol-dd9919ff-f5e4-11ec-bca9-5a782f967c4b csi-vol-dd9919ff-f5e4-11ec-bca9-5a782f967c4b-temp csi-vol-e0023603-f5e4-11ec-bca9-5a782f967c4b csi-vol-e0023603-f5e4-11ec-bca9-5a782f967c4b-temp]
```

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.23

Mapping an RBD image failed consistently:
```
I0627 09:35:53.538823  178730 utils.go:193] ID: 29 Req-ID: 0001-0024-79f197f6-03b0-4955-b8a5-505895831002-0000000000000002-81c01f51-f5fc-11ec-aa23-628dd86099ac GRPC call: /csi.v1.Node/NodeStageVolume
I0627 09:35:53.538950  178730 utils.go:197] ID: 29 Req-ID: 0001-0024-79f197f6-03b0-4955-b8a5-505895831002-0000000000000002-81c01f51-f5fc-11ec-aa23-628dd86099ac GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f25173f0-a449-45d3-8edd-c26240305cfa/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["discard"]}},"access_mode":{"mode":7}},"volume_context":{"clusterID":"79f197f6-03b0-4955-b8a5-505895831002","imageFeatures":"layering","imageName":"csi-vol-81c01f51-f5fc-11ec-aa23-628dd86099ac","journalPool":"replicapool","mapOptions":"lock_on_read,queue_depth=1024","pool":"replicapool","storage.kubernetes.io/csiProvisionerIdentity":"1656322500953-8081-rbd.csi.ceph.com","unmapOptions":"force"},"volume_id":"0001-0024-79f197f6-03b0-4955-b8a5-505895831002-0000000000000002-81c01f51-f5fc-11ec-aa23-628dd86099ac"}
I0627 09:35:53.539201  178730 rbd_util.go:1273] ID: 29 Req-ID: 0001-0024-79f197f6-03b0-4955-b8a5-505895831002-0000000000000002-81c01f51-f5fc-11ec-aa23-628dd86099ac setting disableInUseChecks: false image features: [layering] mounter: rbd
I0627 09:35:53.540371  178730 omap.go:88] ID: 29 Req-ID: 0001-0024-79f197f6-03b0-4955-b8a5-505895831002-0000000000000002-81c01f51-f5fc-11ec-aa23-628dd86099ac got omap values: (pool="replicapool", namespace="", name="csi.volume.81c01f51-f5fc-11ec-aa23-628dd86099ac"): map[csi.imageid:1aec8b6bd717 csi.imagename:csi-vol-81c01f51-f5fc-11ec-aa23-628dd86099ac csi.volname:pvc-f25173f0-a449-45d3-8edd-c26240305cfa csi.volume.owner:rbd-8081]
I0627 09:35:53.554946  178730 rbd_util.go:350] ID: 29 Req-ID: 0001-0024-79f197f6-03b0-4955-b8a5-505895831002-0000000000000002-81c01f51-f5fc-11ec-aa23-628dd86099ac checking for ImageFeatures: [layering]
I0627 09:35:53.583853  178730 cephcmds.go:105] ID: 29 Req-ID: 0001-0024-79f197f6-03b0-4955-b8a5-505895831002-0000000000000002-81c01f51-f5fc-11ec-aa23-628dd86099ac command succeeded: rbd [device list --format=json --device-type krbd]
I0627 09:35:53.600207  178730 rbd_attach.go:420] ID: 29 Req-ID: 0001-0024-79f197f6-03b0-4955-b8a5-505895831002-0000000000000002-81c01f51-f5fc-11ec-aa23-628dd86099ac rbd: map mon rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789
I0627 09:35:53.691143  178730 cephcmds.go:98] ID: 29 Req-ID: 0001-0024-79f197f6-03b0-4955-b8a5-505895831002-0000000000000002-81c01f51-f5fc-11ec-aa23-628dd86099ac an error (exit status 22) occurred while running rbd args: [--id cephcsi-rbd-node -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789 --keyfile=***stripped*** map replicapool/csi-vol-81c01f51-f5fc-11ec-aa23-628dd86099ac --device-type krbd --options noudev --options lock_on_read,queue_depth=1024]
W0627 09:35:53.691224  178730 rbd_attach.go:469] ID: 29 Req-ID: 0001-0024-79f197f6-03b0-4955-b8a5-505895831002-0000000000000002-81c01f51-f5fc-11ec-aa23-628dd86099ac rbd: map error an error (exit status 22) occurred while running rbd args: [--id cephcsi-rbd-node -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789 --keyfile=***stripped*** map replicapool/csi-vol-81c01f51-f5fc-11ec-aa23-628dd86099ac --device-type krbd --options noudev --options lock_on_read,queue_depth=1024], rbd output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument
E0627 09:35:53.691455  178730 utils.go:202] ID: 29 Req-ID: 0001-0024-79f197f6-03b0-4955-b8a5-505895831002-0000000000000002-81c01f51-f5fc-11ec-aa23-628dd86099ac GRPC error: rpc error: code = Internal desc = rbd: map failed with error an error (exit status 22) occurred while running rbd args: [--id cephcsi-rbd-node -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789 --keyfile=***stripped*** map replicapool/csi-vol-81c01f51-f5fc-11ec-aa23-628dd86099ac --device-type krbd --options noudev --options lock_on_read,queue_depth=1024], rbd error output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument
```

[logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.23/detail/mini-e2e-helm_k8s-1.23/2285/pipeline)

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.23

Failed again with RBD mapping:
```

I0627 11:29:24.496111  182244 utils.go:193] ID: 19 Req-ID: 0001-0024-082ada3e-9744-43c7-86bc-784aee083ed0-0000000000000002-5fea7f9e-f60c-11ec-a1f8-76be5a087fa7 GRPC call: /csi.v1.Node/NodeStageVolume
I0627 11:29:24.496223  182244 utils.go:197] ID: 19 Req-ID: 0001-0024-082ada3e-9744-43c7-86bc-784aee083ed0-0000000000000002-5fea7f9e-f60c-11ec-a1f8-76be5a087fa7 GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-1db25b9a-226e-4a52-ad82-8e73aa1aee10/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["discard"]}},"access_mode":{"mode":7}},"volume_context":{"clusterID":"082ada3e-9744-43c7-86bc-784aee083ed0","imageFeatures":"layering","imageName":"csi-vol-5fea7f9e-f60c-11ec-a1f8-76be5a087fa7","journalPool":"replicapool","mapOptions":"lock_on_read,queue_depth=1024","pool":"replicapool","storage.kubernetes.io/csiProvisionerIdentity":"1656329315536-8081-rbd.csi.ceph.com","unmapOptions":"force"},"volume_id":"0001-0024-082ada3e-9744-43c7-86bc-784aee083ed0-0000000000000002-5fea7f9e-f60c-11ec-a1f8-76be5a087fa7"}
I0627 11:29:24.496427  182244 rbd_util.go:1273] ID: 19 Req-ID: 0001-0024-082ada3e-9744-43c7-86bc-784aee083ed0-0000000000000002-5fea7f9e-f60c-11ec-a1f8-76be5a087fa7 setting disableInUseChecks: false image features: [layering] mounter: rbd
I0627 11:29:24.497564  182244 omap.go:88] ID: 19 Req-ID: 0001-0024-082ada3e-9744-43c7-86bc-784aee083ed0-0000000000000002-5fea7f9e-f60c-11ec-a1f8-76be5a087fa7 got omap values: (pool="replicapool", namespace="", name="csi.volume.5fea7f9e-f60c-11ec-a1f8-76be5a087fa7"): map[csi.imageid:1b098d46804a csi.imagename:csi-vol-5fea7f9e-f60c-11ec-a1f8-76be5a087fa7 csi.volname:pvc-1db25b9a-226e-4a52-ad82-8e73aa1aee10 csi.volume.owner:rbd-8081]
I0627 11:29:24.517290  182244 rbd_util.go:350] ID: 19 Req-ID: 0001-0024-082ada3e-9744-43c7-86bc-784aee083ed0-0000000000000002-5fea7f9e-f60c-11ec-a1f8-76be5a087fa7 checking for ImageFeatures: [layering]
I0627 11:29:24.548386  182244 cephcmds.go:105] ID: 19 Req-ID: 0001-0024-082ada3e-9744-43c7-86bc-784aee083ed0-0000000000000002-5fea7f9e-f60c-11ec-a1f8-76be5a087fa7 command succeeded: rbd [device list --format=json --device-type krbd]
I0627 11:29:24.565887  182244 rbd_attach.go:420] ID: 19 Req-ID: 0001-0024-082ada3e-9744-43c7-86bc-784aee083ed0-0000000000000002-5fea7f9e-f60c-11ec-a1f8-76be5a087fa7 rbd: map mon rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789
I0627 11:29:24.669029  182244 cephcmds.go:98] ID: 19 Req-ID: 0001-0024-082ada3e-9744-43c7-86bc-784aee083ed0-0000000000000002-5fea7f9e-f60c-11ec-a1f8-76be5a087fa7 an error (exit status 22) occurred while running rbd args: [--id cephcsi-rbd-node -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789 --keyfile=***stripped*** map replicapool/csi-vol-5fea7f9e-f60c-11ec-a1f8-76be5a087fa7 --device-type krbd --options noudev --options lock_on_read,queue_depth=1024]
W0627 11:29:24.669079  182244 rbd_attach.go:469] ID: 19 Req-ID: 0001-0024-082ada3e-9744-43c7-86bc-784aee083ed0-0000000000000002-5fea7f9e-f60c-11ec-a1f8-76be5a087fa7 rbd: map error an error (exit status 22) occurred while running rbd args: [--id cephcsi-rbd-node -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789 --keyfile=***stripped*** map replicapool/csi-vol-5fea7f9e-f60c-11ec-a1f8-76be5a087fa7 --device-type krbd --options noudev --options lock_on_read,queue_depth=1024], rbd output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument
E0627 11:29:24.669453  182244 utils.go:202] ID: 19 Req-ID: 0001-0024-082ada3e-9744-43c7-86bc-784aee083ed0-0000000000000002-5fea7f9e-f60c-11ec-a1f8-76be5a087fa7 GRPC error: rpc error: code = Internal desc = rbd: map failed with error an error (exit status 22) occurred while running rbd args: [--id cephcsi-rbd-node -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789 --keyfile=***stripped*** map replicapool/csi-vol-5fea7f9e-f60c-11ec-a1f8-76be5a087fa7 --device-type krbd --options noudev --options lock_on_read,queue_depth=1024], rbd error output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument
```
[logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.23/detail/mini-e2e-helm_k8s-1.23/2287/pipeline)

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.23

```
Jun 27 13:31:49.591: FAIL: backend images not matching kubernetes resource count,image count 22 kubernetes resource count 21
backend image Info:
 [csi-vol-076714d2-f615-11ec-84df-7a9b287d5ac3 csi-vol-076714d2-f615-11ec-84df-7a9b287d5ac3-temp csi-vol-07a92b95-f615-11ec-84df-7a9b287d5ac3 csi-vol-07a92b95-f615-11ec-84df-7a9b287d5ac3-temp csi-vol-07c43076-f615-11ec-84df-7a9b287d5ac3 csi-vol-07c43076-f615-11ec-84df-7a9b287d5ac3-temp csi-vol-07e149de-f615-11ec-84df-7a9b287d5ac3-temp csi-vol-08016b5c-f615-11ec-84df-7a9b287d5ac3 csi-vol-08016b5c-f615-11ec-84df-7a9b287d5ac3-temp csi-vol-084a88ba-f615-11ec-84df-7a9b287d5ac3 csi-vol-084a88ba-f615-11ec-84df-7a9b287d5ac3-temp csi-vol-0882dac9-f615-11ec-84df-7a9b287d5ac3 csi-vol-0882dac9-f615-11ec-84df-7a9b287d5ac3-temp csi-vol-089c29ea-f615-11ec-84df-7a9b287d5ac3 csi-vol-089c29ea-f615-11ec-84df-7a9b287d5ac3-temp csi-vol-08afc1f3-f615-11ec-84df-7a9b287d5ac3 csi-vol-08afc1f3-f615-11ec-84df-7a9b287d5ac3-temp csi-vol-1710f516-f615-11ec-84df-7a9b287d5ac3 csi-vol-1710f516-f615-11ec-84df-7a9b287d5ac3-temp csi-vol-181d16c3-f615-11ec-84df-7a9b287d5ac3 csi-vol-181d16c3-f615-11ec-84df-7a9b287d5ac3-temp csi-vol-ff73dfd7-f614-11ec-84df-7a9b287d5ac3]
```
[logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.23/detail/mini-e2e-helm_k8s-1.23/2288/pipeline)

**Comment by nixpanic** [comment]
**ci/centos/mini-e2e-helm/k8s-1.23** failed again with the RBD image mapping error:
```
Jun 27 15:46:43.535: INFO: At 2022-06-27 15:36:52 +0100 BST - event for csi-rbd-demo-pod: {kubelet minikube} FailedMount: MountVolume.MountDevice failed for volume "pvc-45150a3c-6658-4df3-870f-01cef6b10c2b" : rpc error: code = Internal desc = rbd: map failed with error an error (exit status 22) occurred while running rbd args: [--id cephcsi-rbd-node -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789 --keyfile=***stripped*** map replicapool/csi-vol-8f4f16db-f626-11ec-a004-a2d215a0be2c --device-type krbd --options noudev --options lock_on_read,queue_depth=1024], rbd error output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument
```

There might have been a Ceph base-image update that causes this to fail now?

**Comment by Rakshith-R** [comment]
again
https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/rest/organizations/jenkins/pipelines/mini-e2e-helm_k8s-1.23/runs/2289/nodes/99/log/?start=0
```
Jun 27 15:46:43.535: INFO: At 2022-06-27 15:36:52 +0100 BST - event for csi-rbd-demo-pod: {kubelet minikube} FailedMount: MountVolume.MountDevice failed for volume "pvc-45150a3c-6658-4df3-870f-01cef6b10c2b" : rpc error: code = Internal desc = rbd: map failed with error an error (exit status 22) occurred while running rbd args: [--id cephcsi-rbd-node -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789 --keyfile=***stripped*** map replicapool/csi-vol-8f4f16db-f626-11ec-a004-a2d215a0be2c --device-type krbd --options noudev --options lock_on_read,queue_depth=1024], rbd error output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument
```

**Comment by Madhu-1** [comment]
> again https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/rest/organizations/jenkins/pipelines/mini-e2e-helm_k8s-1.23/runs/2289/nodes/99/log/?start=0
> 
> ```
> Jun 27 15:46:43.535: INFO: At 2022-06-27 15:36:52 +0100 BST - event for csi-rbd-demo-pod: {kubelet minikube} FailedMount: MountVolume.MountDevice failed for volume "pvc-45150a3c-6658-4df3-870f-01cef6b10c2b" : rpc error: code = Internal desc = rbd: map failed with error an error (exit status 22) occurred while running rbd args: [--id cephcsi-rbd-node -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789 --keyfile=***stripped*** map replicapool/csi-vol-8f4f16db-f626-11ec-a004-a2d215a0be2c --device-type krbd --options noudev --options lock_on_read,queue_depth=1024], rbd error output: rbd: sysfs write failed
> rbd: map failed: (22) Invalid argument
> ```

Looks like it's due to the latest v17 release. checking dmesg logs might help to identify the issue

**Comment by Madhu-1** [comment]
Removing retry label until we find what is the exact issue with map failure

**Comment by nixpanic** [comment]
@pkalever, I have added commit **e2e: use `exclusive-lock` together with `lock_on_read`** to this PR. Please have a look and let me know if you think it is not correct (or update it yourself, of course).

**Comment by pkalever** [comment]
> @pkalever, I have added commit **e2e: use `exclusive-lock` together with `lock_on_read`** to this PR. Please have a look and let me know if you think it is not correct (or update it yourself, of course).

Thanks @nixpanic, sorry couldn't get to your previous comment, was busy with something from the morning!

**Review by nixpanic — APPROVED** [review]

**Comment by pkalever** [comment]
@Mergifyio rebase

**Review by Madhu-1 — APPROVED** [review]

**Comment by Madhu-1** [comment]
We need to backport it to 3.6 right?

**Comment by pkalever** [comment]
> We need to backport it to 3.6 right?

Would be good to have it on 3.6.

**Review by humblec — APPROVED** [review]

**Pull request merged**
