### PR TITLE
ci: update minikube to v1.24.0

### PR DESCRIPTION
**Pull request by Madhu-1**
update minikube version to latest available version i.e 1.24.0

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Review by yati1998 — APPROVED** [review]

**Review by Yuggupta27 — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Review by humblec — APPROVED** [review]

**Comment by Madhu-1** [comment]
@Mergifyio rebase

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
@Mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.21

From the [logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.21/detail/mini-e2e-helm_k8s-1.21/1852/pipeline):
```
    Nov 18 06:43:11.431: failed to create PVC with error failed to get pvc: rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field
```

Seems similar to #2615, will need a retry as well.

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Pull request merged**
