### PR TITLE
Fix error string as per golang standard

### PR DESCRIPTION
**Pull request by Madhu-1**
Error string should not be capatalized
https://github.com/golang/go/wiki/CodeReviewComments#error-strings

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by ShyamsundarR** [comment]
I was hoping this would wait for #312 before being pushed, as it enforces the same be fixed in the other PR before a merge.

Can it wait?

**Comment by Madhu-1** [comment]
@humblec PTAL

**Comment by humblec** [comment]
@Madhu-1 I think its better to include https://github.com/ceph/ceph-csi/pull/415 too in this PR.

**Comment by Madhu-1** [comment]
@humblec done

**Comment by humblec** [comment]
Thanks @Madhu-1

**Pull request merged**
