### PR TITLE
use filesystem-test.yaml in e2e

### PR DESCRIPTION
**Pull request by Madhu-1**
the filesystem is created by using `filesystem-test.yaml` same file as to be used to delete the `filesystem` during the cleanup
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
@humblec PTAL

**Comment by humblec** [comment]
@Madhu-1 CI is failing .

**Comment by Madhu-1** [comment]
@humblec working on fixing CI

**Comment by Madhu-1** [comment]
@humblec CI passed PTAL

**Pull request merged**
