### PR TITLE
rebase: use latest kubernetes version

### PR DESCRIPTION
**Pull request by humblec**
This commit rebase the kubernetes version to 1.24.4 tree to make
sure we are using latest available bug fix release.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Review by Rakshith-R — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]
This does not look like a critical update to me. Not sure if delaying v3.7 for this is reasonable.

**Comment by humblec** [comment]
@Mergifyio refresh

**Comment by humblec** [comment]
@Mergifyio requeue

**Pull request merged**
