### PR TITLE
Upgrade: csi-snapshotter from v1.2.1 to v1.2.2

### PR DESCRIPTION
**Pull request by hswong3i**
Upgrade: csi-snapshotter from v1.2.1 to v1.2.2

See https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v1.2.2
See https://github.com/kubernetes-csi/external-snapshotter/blob/v1.2.2/CHANGELOG-1.2.md

### CODE REVIEW

**Comment by hswong3i** [comment]
> same changes need to be done in 2 places
> 
> https://github.com/ceph/ceph-csi/blob/master/scripts/minikube.sh#L121
> https://github.com/ceph/ceph-csi/blob/master/charts/ceph-csi-rbd/values.yaml#L213

Updated.

**Comment by Madhu-1** [comment]
@hswong3i please squash the commits

**Comment by hswong3i** [comment]
> @hswong3i please squash the commits

Done

**Comment by hswong3i** [comment]
> Shouldn't we change the v1.13 deployment manifests as well for this? v1.2.2 csi-snapshotter calls out minimum kubernetes version as 1.13, so this should be feasible. I do understand there is a different PR #764 is working towards removing 1.13, but till then keeping 1.13 in sync with 1.14+ would be preferable.
> 
> Also, @hswong3i request that the PR description/commit message remove the template strings, that are inadvertently copied. (everything below "Is there anything that requires special attention" in the message)

Done

**Comment by Madhu-1** [comment]
@hswong3i can you please update commit message based on #773

**Comment by hswong3i** [comment]
> @hswong3i can you please update commit message based on #773

Done

**Comment by hswong3i** [comment]
Rebased

**Comment by Madhu-1** [comment]
@humblec PTAL

**Comment by hswong3i** [comment]
Rebased

**Pull request merged**
