### PR TITLE
remove unused make-containerized-build job

### PR DESCRIPTION
**Pull request by nixpanic**
# Describe what this PR does #

The containerized-tests job is more advanced than, and replaced the
make-containerized-build job.

## Is there anything that requires special attention ##

The job has already been deleted in the CI, it can be removed from this repository too.

### CODE REVIEW

**Comment by nixpanic** [comment]
@Yuggupta27 new jobs should also include a `.yaml` file, and maybe get mentioned in the README.md too.

**Comment by Yuggupta27** [comment]
> @Yuggupta27 new jobs should also include a `.yaml` file, and maybe get mentioned in the README.md too.
Should we add it now or when e2e is functional?

**Comment by nixpanic** [comment]
> > @Yuggupta27 new jobs should also include a `.yaml` file, and maybe get mentioned in the README.md too.
> 
> Should we add it now or when e2e is functional?

Add it in the PR where you are working on the e2e test :)

**Comment by Yuggupta27** [comment]
> > > @Yuggupta27 new jobs should also include a `.yaml` file, and maybe get mentioned in the README.md too.
> > 
> > Should we add it now or when e2e is functional?
> 
> Add it in the PR where you are working on the e2e test :)

Sure. Will do :)

**Pull request merged**
