### PR TITLE
rebase: use v6.0.1 of snapshot client

### PR DESCRIPTION
**Pull request by humblec**
eventhough the snapshotter is of 6.0.1 the client libraries
are of 6.0.0 and this commit update the same.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Review by Madhu-1 — APPROVED** [review]

**Review by yati1998 — APPROVED** [review]

**Comment by humblec** [comment]
@Mergifyio rebase

**Comment by humblec** [comment]
@Mergifyio refresh

**Comment by humblec** [comment]
@Mergifyio refresh

**Comment by humblec** [comment]
@Mergifyio rebase

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.21

Some weird Jenkins error "Bad Message 431"

**Pull request merged**
