### PR TITLE
cleanup: fix spellcheck errors

### PR DESCRIPTION
**Pull request by Madhu-1**
fixed spellcheck errors caught in CI.

### CODE REVIEW

**Comment by riya-singhal31** [comment]
The commit message has typo "utils" -> util

**Review by riya-singhal31 — APPROVED** [review]
Thanks!

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
This needs to be fixed before other PRs can get tested.

@mergifyio queue

**Comment by nixpanic** [comment]
@mergifyio queue

**Pull request merged**
