### PR TITLE
cephfs/rbd: add port sections to helm templates

### PR DESCRIPTION
**Pull request by ghost**
This PR adds port sections to both CephFS and RBD Helm chart templates for nodeplugin daemonsets and provisioner deployments to have more information on what ports are exposed by the containers.

Related https://github.com/ceph/ceph-csi/issues/2855

### CODE REVIEW

**Comment by humblec** [comment]
@kerossin Thanks for the PR  :+1: , can you please correct the DCO error ?

**Comment by ghost** [comment]
> @kerossin Thanks for the PR +1 , can you please correct the DCO error ?

Fixed

**Comment by nixpanic** [comment]
There are two issues with this PR:

1. The commit message should use a known component instead of `cephfs/rbd: ` as prefix. It is the easiest to reword the commit message and start with `helm: ` as prefix.

2. The new port seems to cause failures while deploying in the CI:
```
15m         Warning   FailedCreate        daemonset/csi-cephfsplugin                              Error creating: pods "csi-cephfsplugin-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[4]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[5]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[6]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[7]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[8]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[1].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[1].securityContext.capabilities.add: Invalid value: "SYS_ADMIN": capability may not be added spec.containers[1].securityContext.allowPrivilegeEscalation: Invalid value: true: Allowing privilege escalation for containers is not allowed spec.containers[2].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[2].hostPort: Invalid value: 8081: Host port 8081 is not allowed to be used. Allowed ports: [] spec.containers[2].hostPort: Invalid value: 8081: Host port 8081 is not allowed to be used. Allowed ports: []]
```
See the [logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/rest/organizations/jenkins/pipelines/mini-e2e-helm_k8s-1.23/runs/595/nodes/103/log/?start=0) for more details (these will be kept only for a few days).

**Comment by ghost** [comment]
> There are two issues with this PR:
> 
>     1. The commit message should use a known component instead of `cephfs/rbd: ` as prefix. It is the easiest to reword the commit message and start with `helm: ` as prefix.

I changed the prefix in the commit message to helm.
 
>     2. The new port seems to cause failures while deploying in the CI:
> 
> 
> ```
> 15m         Warning   FailedCreate        daemonset/csi-cephfsplugin                              Error creating: pods "csi-cephfsplugin-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[4]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[5]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[6]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[7]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[8]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[1].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[1].securityContext.capabilities.add: Invalid value: "SYS_ADMIN": capability may not be added spec.containers[1].securityContext.allowPrivilegeEscalation: Invalid value: true: Allowing privilege escalation for containers is not allowed spec.containers[2].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[2].hostPort: Invalid value: 8081: Host port 8081 is not allowed to be used. Allowed ports: [] spec.containers[2].hostPort: Invalid value: 8081: Host port 8081 is not allowed to be used. Allowed ports: []]
> ```
> 
> See the [logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/rest/organizations/jenkins/pipelines/mini-e2e-helm_k8s-1.23/runs/595/nodes/103/log/?start=0) for more details (these will be kept only for a few days).

This seems like a problem with your CI, particularly your PodSecurityPolicy seems too strict. Besides the ports, it complains about things like hostPath volumes, hostNetwork and other settings that weren't changed in this PR.

`pods "csi-cephfsplugin-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used`
`spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed`

**Comment by nixpanic** [comment]
> This seems like a problem with your CI, particularly your PodSecurityPolicy seems too strict. Besides the ports, it complains about things like hostPath volumes, hostNetwork and other settings that weren't changed in this PR.

The error is indeed a little obscure. But what I think it means, is that the 8081 port is not permitted to be used. There are several PodSecutityPolicies that may need correcting for the port? I am not very familiar with PodSecutityPolicies, but I guess adding the port to `charts/ceph-csi-rbd/templates/nodeplugin-psp.yaml` and similar files might be needed.

**Comment by ghost** [comment]
> > This seems like a problem with your CI, particularly your PodSecurityPolicy seems too strict. Besides the ports, it complains about things like hostPath volumes, hostNetwork and other settings that weren't changed in this PR.
> 
> The error is indeed a little obscure. But what I think it means, is that the 8081 port is not permitted to be used. There are several PodSecutityPolicies that may need correcting for the port? I am not very familiar with PodSecutityPolicies, but I guess adding the port to `charts/ceph-csi-rbd/templates/nodeplugin-psp.yaml` and similar files might be needed.

I've just added allowed host ports to nodeplugin PSPs, still not sure why it was complaining for things like hostPath volumes since those things were already allowed in PSPs.

**Review by nixpanic — DISMISSED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

Thanks for the quick updates! I think after a rebase (fixes building images) everything should work. Mergify will take care o that now, I hope there is no need to do anything more from your end.

**Comment by Madhu-1** [comment]
```
commitlint --verbose --from origin/devel
⧗   input: helm: add port sections to helm templates

to show what ports containers are exposing add port sections to nodeplugin and provisioner helm templates

Signed-off-by: Deividas Burškaitis <deividas.burskaitis@oxylabs.io>
✖   body's lines must not be longer than 80 characters [body-max-line-length]

✖   found 1 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

make: *** [Makefile:153: commitlint] Error 1
make: *** [Makefile:199: containerized-test] Error 2
```
commitlint is failing. @kerossin can you please fix this issue?

**Comment by Madhu-1** [comment]
@kerossin looks like the helm deployment is failing with this change in all CI tests related to helm. can you please check

**Comment by ghost** [comment]
@Madhu-1 I fixed the commit message length but I'm not really sure why the CI is failing.

```
Feb  7 09:02:47.149: INFO: deployment error: deployments.apps "csi-rbdplugin-provisioner" not found

Feb  7 09:02:47.149: FAIL: timeout waiting for deployment csi-rbdplugin-provisioner: error waiting for deployment "csi-rbdplugin-provisioner" status to match desired state: deployments.apps "csi-rbdplugin-provisioner" not found
```

**Comment by Madhu-1** [comment]
> @Madhu-1 I fixed the commit message length but I'm not really sure why the CI is failing.
> 
> ```
> Feb  7 09:02:47.149: INFO: deployment error: deployments.apps "csi-rbdplugin-provisioner" not found
> 
> Feb  7 09:02:47.149: FAIL: timeout waiting for deployment csi-rbdplugin-provisioner: error waiting for deployment "csi-rbdplugin-provisioner" status to match desired state: deployments.apps "csi-rbdplugin-provisioner" not found
> ```

Failure from https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.21/detail/mini-e2e-helm_k8s-1.21/2740/pipeline/93
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(PodSecurityPolicy.spec.hostPorts[0]): invalid type for io.k8s.api.policy.v1beta1.HostPortRange: got "number", expected "map"

Checking Deployment status for label app=ceph-csi-cephfs in Namespace cephcsi-e2e-c49e7b533d03
```

**Comment by ghost** [comment]
> > @Madhu-1 I fixed the commit message length but I'm not really sure why the CI is failing.
> > ```
> > Feb  7 09:02:47.149: INFO: deployment error: deployments.apps "csi-rbdplugin-provisioner" not found
> > 
> > Feb  7 09:02:47.149: FAIL: timeout waiting for deployment csi-rbdplugin-provisioner: error waiting for deployment "csi-rbdplugin-provisioner" status to match desired state: deployments.apps "csi-rbdplugin-provisioner" not found
> > ```
> 
> Failure from https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.21/detail/mini-e2e-helm_k8s-1.21/2740/pipeline/93
> 
> ```
> Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(PodSecurityPolicy.spec.hostPorts[0]): invalid type for io.k8s.api.policy.v1beta1.HostPortRange: got "number", expected "map"
> 
> Checking Deployment status for label app=ceph-csi-cephfs in Namespace cephcsi-e2e-c49e7b533d03
> ```

My bad, the PSP's hostPort should have min and max values instead of a list of ports. Will fix soon.

**Review by Madhu-1 — APPROVED** [review]

**Review by Madhu-1 — CHANGES_REQUESTED** [review]
@kerossin can you please squash 2 commits into 1. Requesting changes to avoid accidental merge.

**Comment by nixpanic** [comment]
> @kerossin can you please squash 2 commits into 1. Requesting changes to avoid accidental merge.

@mergify rebase

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergify rebase

**Comment by nixpanic** [comment]
> @kerossin can you please squash 2 commits into 1. Requesting changes to avoid accidental merge.

Mergify should be able to do this for us too :crossed_fingers:

**Review by Madhu-1 — APPROVED** [review]

**Review by humblec — APPROVED** [review]

**Pull request merged**
