### PR TITLE
rebase: update vault to v1.8.2 release

### PR DESCRIPTION
**Pull request by Madhu-1**
updating dependent vault package to latest available release version

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.22

`X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute`

**Comment by Madhu-1** [comment]
```
🎩︎]mrajanna@fedora ceph-csi $]go mod verify
all modules verified
[🎩︎]mrajanna@fedora ceph-csi $]echo $?
0
```
go mod verify is working fine locally

**Comment by humblec** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
>go: github.com/libopenstorage/secrets@v0.0.0-20210709082113-dde442ea20ec requires
	github.com/hashicorp/vault@v1.4.2 requires
	github.com/hashicorp/go-discover@v0.0.0-20201029210230-738cb3105cd0 requires
	github.com/tencentcloud/tencentcloud-sdk-go@v3.0.83+incompatible: reading github.com/tencentcloud/tencentcloud-sdk-go/go.mod at revision v3.0.83: unknown revision v3.0.8

Due to inter dependencies this cannot be point to v1.8.2 closing it for now.

**Pull request closed without merging**
