### PR TITLE
deploy: added json field tags for csi config map

### PR DESCRIPTION
**Pull request by iPraveenParihar**
# Describe what this PR does #

This commit adds the json field tags for csi config map for encoding and decoding JSON.
missed in #4278 

**Checklist:**

* [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#commit-messages).
* [x] Reviewed the developer guide on [Submitting a Pull Request](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#development-workflow)
* [ ] [Pending release notes](https://github.com/ceph/ceph-csi/blob/devel/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next major release.
* [ ] Documentation has been updated, if necessary.
* [ ] Unit tests have been added, if necessary.
* [ ] Integration tests have been added, if necessary.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

* `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

### CODE REVIEW

**Comment by Rakshith-R** [comment]
@mergifyio rebase

**Review by Rakshith-R — APPROVED** [review]
Thanks

**Comment by nixpanic** [comment]
Could you explain why this is needed? If it is required, why was there no failure in a CI job? Can you make sure that this is now tested well, and if someone modified the code, the test catches it?

**Comment by iPraveenParihar** [comment]
> Could you explain why this is needed? If it is required, why was there no failure in a CI job? Can you make sure that this is now tested well, and if someone modified the code, the test catches it?

Yes, my bad
I created the struct in #4278 but forgot to use in that pr.

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio queue

**Pull request merged**
