### PR TITLE
deploy: update resizer to 1.4.0

### PR DESCRIPTION
**Pull request by Madhu-1**
updating external resizer image version from 1.3.0 to the latest available release i.e 1.4.0

1.4.0 changelog https://github.com/kubernetes-csi/external-resizer/blob/master/CHANGELOG/CHANGELOG-1.4.md

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Review by yati1998 — DISMISSED** [review]

**Review by humblec — DISMISSED** [review]
please add changelog url

**Review by Rakshith-R — COMMENTED** [review]
```
[rakshith@fedora ~]$ docker pull k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
Error response from daemon: manifest for k8s.gcr.io/sig-storage/csi-resizer:v1.4.0 not found: manifest unknown: Failed to fetch "v1.4.0" from request "/v2/sig-storage/csi-resizer/manifests/v1.4.0".
```

The image is not yet pushed to registry.

**Comment by Madhu-1** [comment]
> ```
> [rakshith@fedora ~]$ docker pull k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
> Error response from daemon: manifest for k8s.gcr.io/sig-storage/csi-resizer:v1.4.0 not found: manifest unknown: Failed to fetch "v1.4.0" from request "/v2/sig-storage/csi-resizer/manifests/v1.4.0".
> ```
> 
> The image is not yet pushed to registry.

checking with @gnufied on CSI slack

**Review by nixpanic — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
> > ```
> > [rakshith@fedora ~]$ docker pull k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
> > Error response from daemon: manifest for k8s.gcr.io/sig-storage/csi-resizer:v1.4.0 not found: manifest unknown: Failed to fetch "v1.4.0" from request "/v2/sig-storage/csi-resizer/manifests/v1.4.0".
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The image is not yet pushed to registry.
> 
> checking with @gnufied on CSI slack

image is available , requesting for review

**Review by humblec — APPROVED** [review]

**Review by Rakshith-R — APPROVED** [review]

**Comment by Madhu-1** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.23

failed due to know bug

```
  backend image Info:

     [csi-vol-ca8ddce5-7dcb-11ec-8fec-7e4798a45518 csi-vol-d5327c7a-7dcb-11ec-8fec-7e4798a45518 csi-vol-d5327c7a-7dcb-11ec-8fec-7e4798a45518-temp csi-vol-d55212b1-7dcb-11ec-8fec-7e4798a45518 csi-vol-d55212b1-7dcb-11ec-8fec-7e4798a45518-temp csi-vol-d56b7ce6-7dcb-11ec-8fec-7e4798a45518-temp csi-vol-d5886cd2-7dcb-11ec-8fec-7e4798a45518 csi-vol-d5886cd2-7dcb-11ec-8fec-7e4798a45518-temp csi-vol-d5a6f4cd-7dcb-11ec-8fec-7e4798a45518 csi-vol-d5a6f4cd-7dcb-11ec-8fec-7e4798a45518-temp csi-vol-d5fcf924-7dcb-11ec-8fec-7e4798a45518 csi-vol-d5fcf924-7dcb-11ec-8fec-7e4798a45518-temp csi-vol-d6209f86-7dcb-11ec-8fec-7e4798a45518 csi-vol-d6209f86-7dcb-11ec-8fec-7e4798a45518-temp csi-vol-d63a9f75-7dcb-11ec-8fec-7e4798a45518 csi-vol-d63a9f75-7dcb-11ec-8fec-7e4798a45518-temp csi-vol-d646485e-7dcb-11ec-8fec-7e4798a45518 csi-vol-d646485e-7dcb-11ec-8fec-7e4798a45518-temp csi-vol-db7f5f02-7dcb-11ec-8fec-7e4798a45518 csi-vol-db7f5f02-7dcb-11ec-8fec-7e4798a45518-temp csi-vol-dbe36d43-7dcb-11ec-8fec-7e4798a45518 csi-vol-dbe36d43-7dcb-11ec-8fec-7e4798a45518-temp]

```

**Comment by Madhu-1** [comment]
@mergifyio refresh

**Comment by nixpanic** [comment]
@mergifyio refresh

**Pull request merged**
