### PR TITLE
rebase: update csi-snapshotter to v6

### PR DESCRIPTION
**Pull request by Madhu-1**
as we have [v6.0.0](https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v6.0.0) of the external snapshotter updating the dependency for the same.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Review by yati1998 — DISMISSED** [review]

**Comment by Madhu-1** [comment]
```
May 24 05:37:51.413: FAIL: backend images not matching kubernetes resource count,image count 23 kubernetes resource count 21
backend image Info:
 [csi-vol-24a8e6ac-db1b-11ec-a2b4-fabca1168889 csi-vol-2c295e80-db1b-11ec-a2b4-fabca1168889 csi-vol-2c295e80-db1b-11ec-a2b4-fabca1168889-temp csi-vol-2c373e57-db1b-11ec-a2b4-fabca1168889 csi-vol-2c373e57-db1b-11ec-a2b4-fabca1168889-temp csi-vol-2c573f97-db1b-11ec-a2b4-fabca1168889 csi-vol-2c573f97-db1b-11ec-a2b4-fabca1168889-temp csi-vol-2c82bf92-db1b-11ec-a2b4-fabca1168889 csi-vol-2c82bf92-db1b-11ec-a2b4-fabca1168889-temp csi-vol-2cd3c2f9-db1b-11ec-a2b4-fabca1168889 csi-vol-2cd3c2f9-db1b-11ec-a2b4-fabca1168889-temp csi-vol-2d026e8e-db1b-11ec-a2b4-fabca1168889 csi-vol-2d026e8e-db1b-11ec-a2b4-fabca1168889-temp csi-vol-2d37eba4-db1b-11ec-a2b4-fabca1168889 csi-vol-2d37eba4-db1b-11ec-a2b4-fabca1168889-temp csi-vol-320df9b5-db1b-11ec-a2b4-fabca1168889 csi-vol-320df9b5-db1b-11ec-a2b4-fabca1168889-temp csi-vol-3230dc5a-db1b-11ec-a2b4-fabca1168889 csi-vol-3230dc5a-db1b-11ec-a2b4-fabca1168889-temp csi-vol-3274befa-db1b-11ec-a2b4-fabca1168889 csi-vol-3274befa-db1b-11ec-a2b4-fabca1168889-temp csi-vol-3723ded4-db1b-11ec-a2b4-fabca1168889 csi-vol-3723ded4-db1b-11ec-a2b4-fabca1168889-temp]
```

**Review by nixpanic — DISMISSED** [review]

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Rakshith-R** [comment]
@Madhu-1 
all e2e tests are failing PTAL
https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.22/detail/mini-e2e_k8s-1.22/3153/pipeline
```
go test -tags=quincy,ceph_preview,ceph_ci_untested -mod=vendor -c ./e2e

e2e/nfs.go:26:2: cannot find package "." in:

	/go/src/github.com/ceph/ceph-csi/vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1

make: *** [Makefile:163: e2e.test] Error 1

make: *** [Makefile:196: containerized-build] Error 2

script returned exit code 2
```

**Comment by Madhu-1** [comment]
@mergifyio  rebase

**Comment by Madhu-1** [comment]
@Mergifyio rebase

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Review by yati1998 — APPROVED** [review]

**Comment by Madhu-1** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.22

```
Jun  8 07:28:11.551: backend images not matching kubernetes resource count,image count 22 kubernetes resource count 21

    backend image Info:

     [csi-vol-1437b21e-e6f4-11ec-aa8b-aef89112151d csi-vol-160b08f5-e6f4-11ec-aa8b-aef89112151d csi-vol-160b08f5-e6f4-11ec-aa8b-aef89112151d-temp csi-vol-1648db54-e6f4-11ec-aa8b-aef89112151d csi-vol-1648db54-e6f4-11ec-aa8b-aef89112151d-temp csi-vol-1666914d-e6f4-11ec-aa8b-aef89112151d csi-vol-1666914d-e6f4-11ec-aa8b-aef89112151d-temp csi-vol-1684bb11-e6f4-11ec-aa8b-aef89112151d-temp csi-vol-16a469c5-e6f4-11ec-aa8b-aef89112151d csi-vol-16a469c5-e6f4-11ec-aa8b-aef89112151d-temp csi-vol-16cdcb88-e6f4-11ec-aa8b-aef89112151d csi-vol-16cdcb88-e6f4-11ec-aa8b-aef89112151d-temp csi-vol-16fdec66-e6f4-11ec-aa8b-aef89112151d csi-vol-16fdec66-e6f4-11ec-aa8b-aef89112151d-temp csi-vol-171bf645-e6f4-11ec-aa8b-aef89112151d csi-vol-171bf645-e6f4-11ec-aa8b-aef89112151d-temp csi-vol-17338e07-e6f4-11ec-aa8b-aef89112151d csi-vol-17338e07-e6f4-11ec-aa8b-aef89112151d-temp csi-vol-1ae54194-e6f4-11ec-aa8b-aef89112151d csi-vol-1ae54194-e6f4-11ec-aa8b-aef89112151d-temp csi-vol-1b2f7139-e6f4-11ec-aa8b-aef89112151d csi-vol-1b2f7139-e6f4-11ec-aa8b-aef89112151d-temp]
```

**Review by nixpanic — APPROVED** [review]

**Comment by Madhu-1** [comment]
@Mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
```
Jun 10 09:58:21.855: FAIL: backend images not matching kubernetes resource count,image count 12 kubernetes resource count 11
backend image Info:
 [csi-snap-6f76ba48-e89b-11ec-b7c0-52fedbe037a9 csi-snap-6f93891a-e89b-11ec-b7c0-52fedbe037a9 csi-snap-6fb25714-e89b-11ec-b7c0-52fedbe037a9 csi-snap-6fd0848d-e89b-11ec-b7c0-52fedbe037a9 csi-snap-6fef9e64-e89b-11ec-b7c0-52fedbe037a9 csi-snap-700eb2af-e89b-11ec-b7c0-52fedbe037a9 csi-snap-73540bf3-e89b-11ec-b7c0-52fedbe037a9 csi-snap-736ee52b-e89b-11ec-b7c0-52fedbe037a9 csi-snap-738da45f-e89b-11ec-b7c0-52fedbe037a9 csi-snap-73ae9ec4-e89b-11ec-b7c0-52fedbe037a9 csi-snap-73cb2d10-e89b-11ec-b7c0-52fedbe037a9 csi-vol-662e5b2c-e89b-11ec-b7c0-52fedbe037a9]
```

**Comment by pkalever** [comment]
@Mergifyio unqueue

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by pkalever** [comment]
@Mergifyio rebase

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Pull request merged**
