### PR TITLE
update travis.yml and deploy.sh

### PR DESCRIPTION
**Pull request by Madhu-1**
updated travis and deploy to have new branch
name

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
@humblec @rootfs @gman0 @j-griffith @ShyamsundarR  PTAL

**Comment by ktdreyer** [comment]
I'm confused, what is going on with making `master` the default?

**Comment by Madhu-1** [comment]
@ktdreyer we are working on making csv1.0 branch as master branch
cc @humblec

**Comment by humblec** [comment]
@ktdreyer  we have cut a branch from master called `v0.3` which is the v0.3 spec. The next AI is to make master updated with v1.0 branch. 
if you are looking for building something from latest before the migration , even now you can do it with pulling `v1.0` branch ..

**Pull request merged**
