### PR TITLE
update registration directory name

### PR DESCRIPTION
**Pull request by Madhu-1**
updated cephfs registration directory name to match with rbd implementation

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
@humblec @ShyamsundarR PTAL

**Comment by humblec** [comment]
@Madhu-1 dont we need this for rbd ?

**Comment by Madhu-1** [comment]
not required for rbd.

**Comment by Madhu-1** [comment]
@humblec @poornimag @nixpanic PTAL

**Comment by humblec** [comment]
@Madhu-1 does this need change in rook ? also do we have to backport to 1.2 branch?

**Comment by Madhu-1** [comment]
> @Madhu-1 does this need change in rook ? also do we have to backport to 1.2 branch?

changes are required in rook, but this is not a blocker. its already tagged for backporting

**Comment by Madhu-1** [comment]
https://github.com/rook/rook/pull/4070

**Pull request merged**
