### PR TITLE
update csi-lib and external resizer sidecar to latest releases

### PR DESCRIPTION
**Pull request by humblec**
external-resizer: v1.3.0
csi-lib : v0.10.0

Depends-on: kubernetes-csi/external-resizer#171
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Review by Rakshith-R — APPROVED** [review]
LGTM, 
@humblec, call mergifyio rebase on this since external-resizer is released now?

**Review by yati1998 — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Review by Madhu-1 — APPROVED** [review]

**Comment by humblec** [comment]
interesting local pull fails : 
```
docker pull k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
Error response from daemon: manifest for k8s.gcr.io/sig-storage/csi-resizer:v1.3.0 not found: manifest unknown: Failed to fetch "v1.3.0" from request "/v2/sig-storage/csi-resizer/manifests/v1.3.0".
```

**Comment by nixpanic** [comment]
> interesting local pull fails :
> 
> ```
> docker pull k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
> Error response from daemon: manifest for k8s.gcr.io/sig-storage/csi-resizer:v1.3.0 not found: manifest unknown: Failed to fetch "v1.3.0" from request "/v2/sig-storage/csi-resizer/manifests/v1.3.0".
> ```

v1.3.0 does not seem to exist?

```
$ skopeo inspect docker://k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
FATA[0000] Error parsing image name "docker://k8s.gcr.io/sig-storage/csi-resizer:v1.3.0": Error reading manifest v1.3.0 in k8s.gcr.io/sig-storage/csi-resizer: manifest unknown: Failed to fetch "v1.3.0" from request "/v2/sig-storage/csi-resizer/manifests/v1.3.0". 
$ skopeo inspect docker://k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
{
    "Name": "k8s.gcr.io/sig-storage/csi-resizer",
...
```

**Comment by Madhu-1** [comment]
@humblec created issue for the same https://github.com/kubernetes-csi/external-resizer/issues/171

**Comment by humblec** [comment]
It is working now, so retesting .. thanks !

```
v1.3.0: Pulling from sig-storage/csi-resizer
0d7d70899875: Pull complete 
abcc7cea51b2: Pull complete 
Digest: sha256:6e0546563b18872b0aa0cad7255a26bb9a87cb879b7fc3e2383c867ef4f706fb
Status: Downloaded newer image for k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
```

**Pull request merged**
