### PR TITLE
ci: update the upgrade_version

### PR DESCRIPTION
**Pull request by karthik-us**
Setting the CSI_UPGRADE_VERSION to the latest release.

### CODE REVIEW

**Review by nixpanic — APPROVED** [review]

**Review by Rakshith-R — APPROVED** [review]

**Comment by riya-singhal31** [comment]
@mergifyio queue

**Comment by Madhu-1** [comment]
@mergifyio refresh

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio queue

**Pull request merged**
