### PR TITLE
rbd: add support for network namespaces (Multus CNI)

### PR DESCRIPTION
**Pull request by idryomov**
Depends on https://github.com/ceph/ceph/pull/36927, see discussion in https://github.com/ceph/ceph-csi/issues/1323.

Only compile tested at this point.

### CODE REVIEW

**Comment by idryomov** [comment]
E2E tests are failing with
```
rbd: unknown map option 'noudev'
rbd: couldn't parse map options
```
as expected.

**Comment by humblec** [comment]
@idryomov we could add this mount option to example SC of RBD in `e2e` directory.

**Comment by Madhu-1** [comment]
> We could add this mount option to example SC of RBD in `e2e` directory if its going to a default mount options for a particular mounter ( krbd, rbd-nbd). Also we could have different SC examples in E2E for different mounters.. Just a suggestion.

This is not a mount option, this is the rbd map specific options passed when we mapping and unmapping the rbd devices

**Comment by humblec** [comment]
> > We could add this mount option to example SC of RBD in `e2e` directory if its going to a default mount options for a particular mounter ( krbd, rbd-nbd). Also we could have different SC examples in E2E for different mounters.. Just a suggestion.
> 
> This is not a mount option, this is the rbd map specific options passed when we are mapping and unmapping the rbd devices

Ah.. Discard.. I read `noudev` with `nodev` mount option :( ..

**Comment by leseb** [comment]
Once we get the backport in Octopus, we can temporarily switch the Ceph base image for ceph-csi to use: `ceph/daemon-base:latest-octopus-devel` to validate a few things.

**Comment by idryomov** [comment]
@leseb As mentioned elsewhere, I would like to get the whole thing smoke tested with Multus before merging https://github.com/ceph/ceph/pull/36927 into master and release branches.

**Comment by idryomov** [comment]
@leseb Did you mean nautilus instead of octopus?

**Comment by dillaman** [comment]
> @leseb Did you mean nautilus instead of octopus?

Upstream pulls from the `ceph/ceph:v14.2` tag

**Comment by humblec** [comment]
Side note to this PR: Currently the mount options can be passed and its adjusted dynamically , but we dont have a mechanism to have map options for rbd mapping . We have to hardcode it for now.  Ideally this should be configurable .

**Comment by Madhu-1** [comment]
> Side note to this PR: Currently the mount options can be passed and its adjusted dynamically , but we dont have a mechanism to have map options for rbd mapping . We have to hardcode it for now. Ideally this should be configurable .

the issue already exists to provide support for map options https://github.com/ceph/ceph-csi/issues/291

**Comment by Madhu-1** [comment]
@dillaman @idryomov currently cephcsi is using **v15** as the base image https://github.com/ceph/ceph-csi/blob/f2edc926cf3c471feb27600b6f62c73957b5c308/build.env#L13

**Comment by leseb** [comment]
> @dillaman @idryomov currently cephcsi is using **v15** as the base image
> 
> https://github.com/ceph/ceph-csi/blob/f2edc926cf3c471feb27600b6f62c73957b5c308/build.env#L13

@idryomov that's why I said Octopus devel :)

**Comment by leseb** [comment]
> @leseb As mentioned elsewhere, I would like to get the whole thing smoke tested with Multus before merging [ceph/ceph#36927](https://github.com/ceph/ceph/pull/36927) into master and release branches.

We would need this PR for that or a ceph-csi build of that branch. Also, ceph-csi needs to be able to detect that it's being configured with Multus, we can check the pod annotations for that. And if multus then we map with `noudev`. We still this logic in this PR.

I don't want to disrupt too much ceph-csi with this that's why it's probably best to map with `noudev` only when Multus is configured and not make it a default yet.

**Comment by idryomov** [comment]
> @idryomov that's why I said Octopus devel :)

OK, I'll prepare the octopus backport.

(As mentioned elsewhere, the nautilus backport is at https://github.com/ceph/ceph-ci/commit/6b5a85102272ef5f73261b41a985c851e3000293, but the container didn't get built because nautilus
container builds have been disabled by https://github.com/ceph/ceph-build/pull/1607, pending the merge of https://github.com/ceph/ceph-container/pull/1706 and https://github.com/ceph/ceph-build/pull/1628.)

**Comment by idryomov** [comment]
> I don't want to disrupt too much ceph-csi with this that's why it's probably best to map with `noudev` only when Multus is configured and not make it a default yet.

I hard-coded `noudev` without conditioning it Multus or anything else because I don't want to bifurcate.  If it suits Multus, it should be enabled for all CSI mappings.

I don't see a reason to wait for Multus to become fully supported before rolling out `noudev`, but I want to make sure it actually works in a Multus environment because it's a little subtle (e.g. `noudev` requires  the network namespace to be owned by the initial user namespace, etc).

**Comment by humblec** [comment]
> > I don't want to disrupt too much ceph-csi with this that's why it's probably best to map with `noudev` only when Multus is configured and not make it a default yet.
> 
> I hard-coded `noudev` without conditioning it Multus or anything else because I don't want to bifurcate. If it suits Multus, it should be enabled for all CSI mappings.
> 

Sure, as long as `noudev` does not impact non multus setups, we can make it default.  We will wrap a better mechanism later with multus configured or not or better configurable options for RBD map options based on input..etc. 


> I don't see a reason to wait for Multus to become fully supported before rolling out `noudev`, but I want to make sure it actually works in a Multus environment because it's a little subtle (e.g. `noudev` requires the network namespace to be owned by the initial user namespace, etc).

Sure. That would be good.

**Comment by idryomov** [comment]
Yeah, making it possible to supply custom `rbd map` and `rbd unmap` options as per https://github.com/ceph/ceph-csi/issues/291 is good, but by default, we should be striving for as much uniformity as possible.

**Comment by idryomov** [comment]
The octopus backport is at https://github.com/ceph/ceph-ci/commit/21998a2e5c94b08650921a080fa85c35fd0bfe36 and the container is at quay.ceph.io/ceph-ci/ceph:wip-krbd-noudev-octopus.

**Comment by rohan47** [comment]
Tested out `madhupr001/cephcsi:multus` and It works perfectly @Madhu-1 @idryomov

**Comment by Madhu-1** [comment]
> Tested out `madhupr001/cephcsi:multus` and It works perfectly @Madhu-1 @idryomov

@rohan47 Thanks for testing it out.

**Comment by leseb** [comment]
Now I believe this should detect whether Multus annotations are present, if so, then we turn on the noudev flag on mapping.

**Comment by idryomov** [comment]
No, I think CSI should default to `noudev`.  In case of breakage, users will be able to revert through `mapOptions` and `unmapOptions` storage class parameters.  I'll rebase on top of #1460 once it merges to make that possible.

**Comment by humblec** [comment]
Thanks @rohan47 for testing this out! hopefully we can get this in soon! Thanks @idryomov for the `noudev` support to enable Multus :+1:

**Comment by humblec** [comment]
> No, I think CSI should default to `noudev` (see discussion above). In case of breakage, users will be able to revert through `mapOptions` and `unmapOptions` storage class parameters. I'll rebase on top of #1460 once it merges to make that possible.

@idryomov the RBD map option PR has  merged, so you should be able to rebase now :)

**Comment by Madhu-1** [comment]
@idryomov do we need a new ceph release(or some updated base image)?

**Comment by idryomov** [comment]
Yes.  `ceph/ceph:v15` is currently at v15.2.5.  The octopus backport (https://github.com/ceph/ceph/pull/37285) has merged, but it will be a while before v15.2.6 is cut.

@leseb suggested temporarily switching the base image to `ceph/daemon-base:latest-octopus-devel`.  If you agree, I'll do that in this PR once `latest-octopus-devel` is rolled forward.

**Comment by Madhu-1** [comment]
> Yes. `ceph/ceph:v15` is currently at v15.2.5. The octopus backport ([ceph/ceph#37285](https://github.com/ceph/ceph/pull/37285)) has merged, but it will be a while before v15.2.6 is cut.
> 
> @leseb suggested temporarily switching the base image to `ceph/daemon-base:latest-octopus-devel`. If you agree, I'll do that in this PR once `latest-octopus-devel` is rolled forward.

Yes as its a master branch that should be fine(hope we don't get any regression due to base image change as it keeps getting updated). just open an issue to revert back the base image once we have ceph release

cc @ShyamsundarR @humblec @nixpanic

**Comment by ShyamsundarR** [comment]
> > Yes. `ceph/ceph:v15` is currently at v15.2.5. The octopus backport ([ceph/ceph#37285](https://github.com/ceph/ceph/pull/37285)) has merged, but it will be a while before v15.2.6 is cut.
> > @leseb suggested temporarily switching the base image to `ceph/daemon-base:latest-octopus-devel`. If you agree, I'll do that in this PR once `latest-octopus-devel` is rolled forward.
> 
> Yes as its a master branch that should be fine(hope we don't get any regression due to base image change as it keeps getting updated). just open an issue to revert back the base image once we have ceph release
> 
> cc @ShyamsundarR @humblec @nixpanic

`ceph/daemon-base:latest-octopus-devel` should be fine. Thanks @idryomov

**Comment by idryomov** [comment]
Looks like using `ceph/daemon-base:latest-octopus-devel` images won't work: apart from unrelated failures in e2e jobs, there is a problem with `scripts/build-multi-arch-image.sh` because they are x86-only.

It appears that `ceph/daemon-base:v5.0.Z-stable-5.0-octopus-centos-8` images are multi-arch, so we could probably just wait for v5.0.4?

```
$ DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect ceph/daemon-base:v5.0.3-stable-5.0-octopus-centos-8
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 743,
         "digest": "sha256:a745e681cb4d0122848beaf471046787ea5e186fcf1f0ff7f17a907d3098fee3",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 743,
         "digest": "sha256:a087772387386a4486769c9522d55f1e66e60c6b71e0049b7cc78ba1c8bcc551",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
```

**Comment by Madhu-1** [comment]
> Looks like using `ceph/daemon-base:latest-octopus-devel` images won't work: apart from unrelated failures in e2e jobs, there is a problem with `scripts/build-multi-arch-image.sh` because they are x86-only.
> 
> It appears that `ceph/daemon-base:v5.0.Z-stable-5.0-octopus-centos-8` images are multi-arch, so we could probably just wait for v5.0.4?
>

@idryomov when is v5.0.4 planned? is it possible to get multi-arch build for `ceph/daemon-base:latest-octopus-devel` image also (it might be useful for the users who want to use latest containers for their testing?)
cc @leseb 

> ```
> $ DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect ceph/daemon-base:v5.0.3-stable-5.0-octopus-centos-8
> {
>    "schemaVersion": 2,
>    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
>    "manifests": [
>       {
>          "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
>          "size": 743,
>          "digest": "sha256:a745e681cb4d0122848beaf471046787ea5e186fcf1f0ff7f17a907d3098fee3",
>          "platform": {
>             "architecture": "arm64",
>             "os": "linux",
>             "variant": "v8"
>          }
>       },
>       {
>          "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
>          "size": 743,
>          "digest": "sha256:a087772387386a4486769c9522d55f1e66e60c6b71e0049b7cc78ba1c8bcc551",
>          "platform": {
>             "architecture": "amd64",
>             "os": "linux"
>          }
> ```

**Comment by idryomov** [comment]
@dsavineau Can we expect `ceph/daemon-base:v5.0.4-stable-5.0-octopus-centos-8` build soon?  If not, could you please generate one with https://github.com/ceph/ceph/pull/37285 included?  We need a multi-arch build to keep ceph-csi CI happy...

**Comment by dsavineau** [comment]
> @dsavineau Can we expect `ceph/daemon-base:v5.0.4-stable-5.0-octopus-centos-8` build soon? If not, could you please generate one with [ceph/ceph#37285](https://github.com/ceph/ceph/pull/37285) included? We need a multi-arch build to keep ceph-csi CI happy...

No because
  - there's nothing new on the stable-5.0 branch so it doesn't make sense to create a 5.0.4 tag.
  - The container image tags based on the ceph-container tags are only using the ceph stable release (15.2.5 for octopus, 14.2.11 for nautilus ATM) and not the unreleased code.

> is it possible to get multi-arch build for ceph/daemon-base:latest-octopus-devel image also (it might be useful for the users who want to use latest containers for their testing?)

No it's not possible because the `-devel` container image tag are based on the shaman builds which don't provide arm64 builds, but only x86_64.
That's why the `-devel` container image tags aren't multi arch.

**Comment by idryomov** [comment]
I was trying to get everything else to pass and rebased to get Niels' docker vs podman fixup.  Some jobs get to the actual E2E tests now, but fail with "failed to validate pvc and application binding with error timed out waiting for the condition" for both RBD and CephFS PVCs.

Could someone please look at [1] as an example?  It seems to be looping trying to connect to the cluster:

```
failed to get connection: connecting failed: rados: ret=-22, Invalid argument
```

If it's not another CI issue, it could be a problem with the `ceph/daemon-base` image.  Do these jobs gather Ceph logs?

[1] https://jenkins-ceph-csi.apps.ocp.ci.centos.org/job/mini-e2e_k8s-1.19/141

**Comment by Madhu-1** [comment]
>I0928 13:16:09.121073       1 rbd_util.go:773] ID: 17 Req-ID: pvc-3600fe21-a2d2-4f5a-a580-c0741203d82d setting disableInUseChecks on rbd volume to: false
unable to parse addrs in 'rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789'
E0928 13:16:09.135366       1 controllerserver.go:246] ID: 17 Req-ID: pvc-3600fe21-a2d2-4f5a-a580-c0741203d82d failed to connect to volume : failed to get connection: connecting failed: rados: ret=-22, Invalid argument
E0928 13:16:09.135427       1 utils.go:163] ID: 17 Req-ID: pvc-3600fe21-a2d2-4f5a-a580-c0741203d82d GRPC error: rpc error: code = Internal desc = failed to get connection: connecting failed: rados: ret=-22, Invalid argument

looks like are getting an error for parsing mon address (not sure why it's not working with this image)


>I0928 13:15:35.260345   27569 rbd_util.go:773] ID: 17 Req-ID: 0001-0024-a9f2288a-3d55-406f-98b5-464e0424039a-0000000000000003-6df855ae-018c-11eb-aac1-0242ac110013 setting disableInUseChecks on rbd volume to: false
unable to parse addrs in 'rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789'
E0928 13:15:35.271806   27569 nodeserver.go:191] ID: 17 Req-ID: 0001-0024-a9f2288a-3d55-406f-98b5-464e0424039a-0000000000000003-6df855ae-018c-11eb-aac1-0242ac110013 failed to establish cluster connection: failed to get connection: connecting failed: rados: ret=-22, Invalid argument
E0928 13:15:35.271961   27569 utils.go:173] panic occurred: runtime error: invalid memory address or nil pointer dereference
goroutine 59 [running]:
runtime/debug.Stack(0xad, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
github.com/ceph/ceph-csi/internal/csi-common.panicHandler.func1(0xc0000c38c8)
	/go/src/github.com/ceph/ceph-csi/internal/csi-common/utils.go:174 +0xd1
panic(0x14cad20, 0x22c8c10)
	/usr/local/go/src/runtime/panic.go:969 +0x175
github.com/ceph/ceph-csi/internal/rbd.(*NodeServer).NodeStageVolume(0xc000202080, 0x184a660, 0xc00021a630, 0xc00007e2a0, 0x0, 0x0, 0x0)
	/go/src/github.com/ceph/ceph-csi/internal/rbd/nodeserver.go:192 +0xe35
github.com/container-storage-interface/spec/lib/go/csi._Node_NodeStageVolume_Handler.func1(0x184a660, 0xc00021a630, 0x15cc320, 0xc00007e2a0, 0x413300, 0xa0, 0x8, 0x20a9d42)
	/go/src/github.com/ceph/ceph-csi/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5941 +0x89
github.com/ceph/ceph-csi/internal/csi-common.panicHandler(0x184a660, 0xc00021a630, 0x15cc320, 0xc00007e2a0, 0xc00000e160, 0xc00000e180, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/ceph/ceph-csi/internal/csi-common/utils.go:178 +0x96
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x184a660, 0xc00021a630, 0x15cc320, 0xc00007e2a0, 0xc000493960, 0x1, 0x1, 0xc00021a630)

We need to fix this panic in code (this is not related to  this PR)

**Comment by idryomov** [comment]
@Madhu-1 Just for my education, how did you get that panic stack trace?

**Comment by Madhu-1** [comment]
@idryomov panic is present in https://jenkins-ceph-csi.apps.ocp.ci.centos.org/job/upgrade-tests-rbd/48/consoleFull but it's not happening in all E2E tests

**Comment by Madhu-1** [comment]
@idryomov do we also need to remove the hostNetworking from cephcsi rbd templates?

* Are we going to face any  issue if we move away from hostNetworking by default (any performance issues?)
* If yes do we have to provide an  option to override `noudev` option

**Comment by idryomov** [comment]
> @idryomov do we also need to remove the hostNetworking from cephcsi rbd templates?
> 
>     * Are we going to face any  issue if we move away from hostNetworking by default (any performance issues?)

I'm not sure.  Since rook is going to remove `hostNetwork: true` in https://github.com/rook/rook/pull/6310, we probably need to as well.  It doesn't make sense to have different defaults.

> 
>     * If yes do we have to provide an  option to override `noudev` option

`noudev` isn't really related to host networking and can be used with and without it.  If we encounter networking issues, we can flip `hostNetwork` back on.  If we encounter issues caused by `noudev`, it should be possible to override it using the new storage class parameters from https://github.com/ceph/ceph-csi/pull/1460: `mapOptions: udev` + `unmapOptions: udev`, in addition to flipping `hostNetwork` back on of course.

**Comment by Madhu-1** [comment]
> > @idryomov do we also need to remove the hostNetworking from cephcsi rbd templates?
> > ```
> > * Are we going to face any  issue if we move away from hostNetworking by default (any performance issues?)
> > ```
> 
> I'm not sure. Since rook is going to remove `hostNetwork: true` in [rook/rook#6310](https://github.com/rook/rook/pull/6310), we probably need to as well. It doesn't make sense to have different defaults.
> 
> > ```
> > * If yes do we have to provide an  option to override `noudev` option
> > ```
> 
> `noudev` isn't really related to host networking and can be used with and without it. If we encounter networking issues, we can flip `hostNetwork` back on. If we encounter issues caused by `noudev`, it should be possible to override it using the new storage class parameters from #1460: `mapOptions: udev` + `unmapOptions: udev`, in addition to flipping `hostNetwork` back on of course.

if the `udev` is  passed in mapOptions don't we need to skip adding `noudev` to --options flag am  i correct

* dont set noudev if user is passing `noudev` in mapOptions/unMapOptions
* if udev is set in mapOptions/unMapOptions dont add `noudev` to `--option` 

@idryomov Thanks for the information can you please confirm above enhancements are required( i can work on enhancements)

 @leseb do we need to have the same option in rook also to host networking?

**Comment by idryomov** [comment]
> if the `udev` is passed in mapOptions don't we need to skip adding `noudev` to --options flag am i correct
> 
>     * dont set noudev if user is passing `noudev` in mapOptions/unMapOptions
> 
>     * if udev is set in mapOptions/unMapOptions dont add `noudev` to `--option`
> 
> 
> @idryomov Thanks for the information can you please confirm above enhancements are required( i can work on enhancements)

For `noudev`, nothing beyond what is already in this PR should be required -- rbd tool will handle the override.

For host networking, I'll switch it off in this PR if everybody agrees it should be off by default.  I'd like to get the CI more green first though, ideally everything but `continuous-integration/travis-ci/pr` which requires a multi-arch container image.

**Comment by leseb** [comment]
Just to sum up why we did all of that. @idryomov did the `noudev` map option because of hostnetworking. So I believe that hostnetworking became a requirement only based on that when ceph-csi started.
Now, that we don't need it, since `noudev` is the default, I don't see why hostnetworking still has to be around. It is an unnecessary high privileged being given to the container.

If we believe hostnetworking is still required or disabling it might have side effects, we need to investigate that or else I'd just vote for removing it.

Makes sense?

**Comment by humblec** [comment]
>For host networking, I'll switch it off in this PR if everybody agrees it should be off by default. I'd like to get the CI more green first though, ideally everything but continuous-integration/travis-ci/pr which requires a multi-arch container image.

@idryomov The `hostnetworking` removal can be a separate PR altogether, we dont have to mix up with the `noudev` introduction here.. That gives a checkpoint to revert if we face some issues due to the change of hostnetworking..etc.
I do think we should try to make it `off` by default though. At the same time,  I am not sure what corner issues it can bring in , for example: "performance" impact it brings. Do we have any data so far on the performance while we switch the hostnetworking off? 
Also, this change is for `RBD` ( noudev is a rbd map option) ,  what  about CephFS, that said, does enabling multus have any functional issues with cephfs ?  have we tested it @rohan47

**Comment by leseb** [comment]
> > For host networking, I'll switch it off in this PR if everybody agrees it should be off by default. I'd like to get the CI more green first though, ideally everything but continuous-integration/travis-ci/pr which requires a multi-arch container image.
> 
> @idryomov The `hostnetworking` removal can be a separate PR altogether, we dont have to mix up with the `noudev` introduction here.. That gives a checkpoint to revert if we face some issues due to the change of hostnetworking..etc.

+1 to remove hostnetworking in a separate commit/PR.

> I do think we should try to make it `off` by default though. At the same time, I am not sure what corner issues it can bring in , for example: "performance" impact it brings. Do we have any data so far on the performance while we switch the hostnetworking off?

Turning on hostnetworking was a mere "hack/workaround" to get `rbd map` working. All the communications with the Ceph were done through the SDN (first interface in the container) anyway.
Ceph daemons were already listening on the SDN nic unless the cluster was deployed with hostnetworking. That's the only issue I can think of at this point.
So disabling hostnetworking won't work if the Ceph cluster is deployed with hostnetworking enabled.
But in the case of Rook we can work around it since we deploy CSI.

> Also, this change is for `RBD` ( noudev is a rbd map option) , what about CephFS, that said, does enabling multus have any functional issues with cephfs ? have we tested it @rohan47

Yes cephfs has been validated and has never been a problem.

**Comment by humblec** [comment]
> > I do think we should try to make it `off` by default though. At the same time, I am not sure what corner issues it can bring in , for example: "performance" impact it brings. Do we have any data so far on the performance while we switch the hostnetworking off?
> 
> Turning on hostnetworking was a mere "hack/workaround" to get `rbd map` working. All the communications with the Ceph were done through the SDN (first interface in the container) anyway.
> Ceph daemons were already listening on the SDN nic unless the cluster was deployed with hostnetworking. That's the only issue I can think of at this point.
> So disabling hostnetworking won't work if the Ceph cluster is deployed with hostnetworking enabled.
> But in the case of Rook we can work around it since we deploy CSI.

Considering the CSI can be deployed alone or without Rook or in case admin already configured a ceph cluster,  may be we have to validate the CSI deployment without hostnetworking too.  

> 
> > Also, this change is for `RBD` ( noudev is a rbd map option) , what about CephFS, that said, does enabling multus have any functional issues with cephfs ? have we tested it @rohan47
> 
> Yes cephfs has been validated and has never been a problem.

Cool. thanks for confirming @leseb :+1:

**Comment by idryomov** [comment]
> > For host networking, I'll switch it off in this PR if everybody agrees it should be off by default. I'd like to get the CI more green first though, ideally everything but continuous-integration/travis-ci/pr which requires a multi-arch container image.
> 
> @idryomov The `hostnetworking` removal can be a separate PR altogether, we dont have to mix up with the `noudev` introduction here.. That gives a checkpoint to revert if we face some issues due to the change of hostnetworking..etc.

It will be a separate commit, just as easy to revert (particularly given that the repo is set up such that all PRs are rebased prior to merging, there are no merge commits).  Since the code that allows to remove host networking is added in this PR, I think it's only logical to remove host networking in it, rather than linking it from somewhere else.

**Comment by rohan47** [comment]
Is there anythning missing?
How can we move forward with this?

**Comment by idryomov** [comment]
We are waiting for an octopus point release, which should arrive in a couple of weeks.

**Comment by leseb** [comment]
> We are waiting for an octopus point release, which should arrive in a couple of weeks.

It's there https://hub.docker.com/layers/ceph/ceph/v15.2.6-20201119/images/sha256-141b4b84a5a9fc64579f9c233cc6b729c9d300371ec2aac90ed1ea01c2e9920a?context=explore

**Comment by idryomov** [comment]
At this point we need v15.2.7, but v15.2.6-20201119 should do in the meantime -- it is multi-arch and very close to what v15.2.7 would be.  Let's see how it does in E2E tests.

**Comment by idryomov** [comment]
Looks like it is trying to pull from registry-ceph-csi.apps.ocp.ci.centos.org and v15.2.6-20201119 is not there.  This registry is not public, so I can't see what is actually there...

**Comment by Madhu-1** [comment]
@idryomov due to the docker late limit we have manually pushed the docker images to the internal CI registry, @nixpanic can you please help here?

**Comment by idryomov** [comment]
Rebased on master to try to unconfuse the recently enabled commitlint which picked up the wrong commit range.

**Comment by idryomov** [comment]
@nixpanic ping

**Comment by mykaul** [comment]
Should the title still be prefixed by '[DNM]' ?

**Comment by idryomov** [comment]
@mykaul Yes, because we don't have an octopus point release with the change that this PR depends on.  It was supposed to be released in 15.2.6, but that ended up being hotfix for a replay attack CVE.  And now, 15.2.7 is going to be another hotfix for a data corrupting bug in rgw.

**Comment by idryomov** [comment]
I rebased on top of @nixpanic's build.env tweak.  The jobs still can't pull that v15.2.6-20201119 tag, but it turns out it actually doesn't matter because v15.2.6-20201119 doesn't have the rbd change.  @leseb pointed me at it and I just assumed (based on the date) that it did have the rbd change and only checked whether it was multi-arch or not.  Sorry for the noise...

**Comment by idryomov** [comment]
The bottom line is that this is going to need to wait for 15.2.8, unless someone produces a multi-arch container (either based on octopus branch or just 15.2.6 + rbd change) that ceph-csi CI can be temporarily switched to.  We have an x86 container which was successfully used by multiple people for testing and benchmarking, but ceph-csi CI needs a multi-arch (x86 + arm64) one.

**Comment by idryomov** [comment]
So 15.2.8 is out, but I'm hitting the same issue: it's there on docker.io but not in registry-ceph-csi.apps.ocp.ci.centos.org.  In fact, the internal registry is still on 15.2.6, meaning we missed 15.2.7 -- it looks like @nixpanic's bdf8fe7f93e0 ("build: use docker.io/ceph/ceph:v15 as BASE_IMAGE") change isn't working (or maybe I'm misinterpreting it)...

Is pushing images to the internal registry really supposed to be a manual process?  Why not set it up to act as a cache?

**Comment by idryomov** [comment]
@nixpanic Ping, can we get ceph v15.2.8 pushed to registry-ceph-csi.apps.ocp.ci.centos.org?

**Comment by nixpanic** [comment]
> @nixpanic Ping, can we get ceph v15.2.8 pushed to registry-ceph-csi.apps.ocp.ci.centos.org?

Done! ceph/ceph:v15.2.8 has been pushed, and ceph/ceph:v15 has been updated too.

**Comment by nixpanic** [comment]
> Is pushing images to the internal registry really supposed to be a manual process? Why not set it up to act as a cache?

There were (and possibly still are) issues when using a registry mirror, as that connects to Docker Hub a lot too, and caused failures since Docker reduced the image-pull limits. Doing this manual is a pain, and I hope we can setup an automated job that checks for updated images (daily or so).

**Comment by idryomov** [comment]
With ceph:v15.2.8 pushed, this is good to go!

**Review by nixpanic — APPROVED** [review]

**Review by leseb — APPROVED** [review]
LGTM, unit tests for `appendDeviceTypeAndOptions()` would have certainly been a good addition but I'm not familiar enough with the repo to request them.

**Comment by joed96** [comment]
Hi all, I believe I've run into a race condition resulting in data loss following this patch whereby, when re-attaching a PVC with `volumeMode: Filesystem`, the `csi-rbdplugin` re-runs `mkfs` and deletes my data.

The basic idea of the race condition is that:

* `csi-rbdplugin` maps the RBD image successfully, with the `noudev` option
* `csi-rbdplugin` runs `blkid` to determine if the RBD image is formatted.  However, `udev` has not yet created the `/dev/rbd*` device.  `blkid` exists with an error code, and so the plugin believes the image is not formatted.
* `udev` catches up and creates the `/dev/rbd*` device
* `csi-rbdplugin` runs `mkfs` which successfully re-formats the RBD image, deleting the previously existing data.

Detailed diagnostics are in Issue #1820.

I am new to ceph-csi, so could be missing something obvious.  Please feel free to challenge my test cases and diagnostics.

**Comment by idryomov** [comment]
Replied in #1820.

**Pull request merged**
