### PR TITLE
ci: add optional Kubernetes 1.21 job

### PR DESCRIPTION
**Pull request by nixpanic**
To test a PR with Kubernetes 1.21, leave a comment in the PR like:

    /test ci/centos/mini-e2e-helm/k8s-1.21

The status of the job will be recorded in the PR, but running this job
is not required (yet).

Updates: #1963

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

**Comment by humblec** [comment]
@nixpanic do we have any requirement at this stage for checking against 1.21 Kube ?

**Comment by Madhu-1** [comment]
@nixpanic as kubernetes 1.21 already released. can we remove 1.19 and make 1.21 results mandatory?

**Comment by humblec** [comment]
> @nixpanic as kubernetes 1.21 already released. can we remove 1.19 and make 1.21 results mandatory?

it could be a test bed for next major release of ceph csi too.

**Comment by nixpanic** [comment]
> @nixpanic do we have any requirement at this stage for checking against 1.21 Kube ?

No, not yet. That needs an update to the mergify configuration.

**Comment by nixpanic** [comment]
> @nixpanic as kubernetes 1.21 already released. can we remove 1.19 and make 1.21 results mandatory?

We could, but I prefer to do some test runs before. Maybe Kubernetes 1.21 requires more resources and we need to tune the minikube VM/deployment for it.

**Review by Madhu-1 — APPROVED** [review]

**Review by humblec — APPROVED** [review]

**Comment by humblec** [comment]
> > @nixpanic as kubernetes 1.21 already released. can we remove 1.19 and make 1.21 results mandatory?
> 
> We could, but I prefer to do some test runs before. Maybe Kubernetes 1.21 requires more resources and we need to tune the minikube VM/deployment for it.

Sure. Than resource side, regression or something like that is what we have to check mainly :)

**Pull request merged**
