### PR TITLE
util: remove unused CSI server initialization functions

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Review by nixpanic — CHANGES_REQUESTED** [review]
Can you add a note in the commit since when/why these are not needed anymore?

Also note that CI in not stable at the moment, #1599 attempts to fix that, no need to retry tests before that one is merged (and this PR is rebased)

**Comment by nixpanic** [comment]
> /retest all

Could you please address the request I made, and rebase this PR afterwards? Without the rebase, it is very likely that this keeps failing.

**Comment by pkalever** [comment]
The go static-check tool is supposed to catch it. Not sure if it's an issue with the tool or we just ignoring the warnings from CI?

**Comment by nixpanic** [comment]
> The go static-check tool is supposed to catch it. Not sure if it's an issue with the tool or we just ignoring the warnings from CI?

What do you mean, what should it catch? If you are talking about detecting functions that are not used, the problem is that these functions are exported in the package (start with a Captial case), so other non-local packages could use them.

**Comment by pkalever** [comment]
> > The go static-check tool is supposed to catch it. Not sure if it's an issue with the tool or we just ignoring the warnings from CI?
> 
> What do you mean, what should it catch? If you are talking about detecting functions that are not used, the problem is that these functions are exported in the package (start with a Captial case), so other non-local packages could use them.

Oops! sorry, I thought this is the dead code used within the repository.

**Comment by nixpanic** [comment]
> Oops! sorry, I thought this is the dead code used within the repository.

It is! But tools will have difficulties detecting it. If there are any tools that can help with that, we should definitely look into that.

**Comment by humblec** [comment]
@nixpanic 
>
Can you add a note in the commit since when/why these are not needed anymore?
>
@nixpanic  I dont know .. Its been there for an year or so. Its an unused functions so I dont know how to answer `why these are not needed anymore` ?

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

**Review by Madhu-1 — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio refresh

**Pull request merged**
