### PR TITLE
util: fix tracevol.py to work with dynamic value of volumeNamePrefix

### PR DESCRIPTION
**Pull request by agarwal-mudit**
tracevol.py works on static value of volumeNamePrefix, fixed it to work on the dynamic vale of the same.

Signed-off-by: Mudit Agarwal <muagarwa@redhat.com>

Fixes: #1143

### CODE REVIEW

**Comment by agarwal-mudit** [comment]
Please restart, it failed here: ssh: Could not resolve hostname n43.dusty.ci.centos.org: Name or service not known

**Comment by Madhu-1** [comment]
> Please restart, it failed here: ssh: Could not resolve hostname n43.dusty.ci.centos.org: Name or service not known

we have an issue with centos CI, centos team is working on it.

**Pull request merged**
