### PR TITLE
cleanup: resolves gocritic linter issues

### LINKED ISSUE #2250: resolve gocritic linter
This issue is to track the gocritic linter errors.
In reference to the issue:  #1586

### PR DESCRIPTION
**Pull request by yati1998**
This commit resolves gocritic linter errors.

Fixes: #2250

Signed-off-by: Yati Padia <ypadia@redhat.com>

### CODE REVIEW

**Review by nixpanic — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Comment by nixpanic** [comment]
If this PR should automatically close issue #2250, use `Fixes: #2250` in the PR description instead of `Updates: `.

**Pull request merged**
