### PR TITLE
e2e/rbd: add ROX test

### PR DESCRIPTION
**Pull request by nixpanic**
# Describe what this PR does #

Add an e2e test case where two pods use the same PVC in read-only mode.

## Is there anything that requires special attention ##

The e2e tests currently run on a single node, unsure how valid this test is.

## Related issues ##

Updates: #914

### CODE REVIEW

**Comment by Madhu-1** [comment]
@nixpanic currently cephcsi is not supporting rox . Am working on this feature in cephcsi 3.0

**Comment by nixpanic** [comment]
@Madhu-1 is there an Issue for that? #914 could then be closed with a pointer to it.

**Comment by Madhu-1** [comment]
https://github.com/ceph/ceph-csi/issues/725 this is the one

**Comment by Madhu-1** [comment]
@nixpanic closing as e2e already added for rbd ROX.

**Pull request closed without merging**
