### PR TITLE
Migrate to k8s.io/klog from glog.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@rootfs ptal :)

**Comment by humblec** [comment]
@rootfs will add vendor and rebase.

**Comment by humblec** [comment]
@rootfs csi-v1.0 branch already has `klog` , so no need to add it. Rebased the pr to resolve conflict.

**Comment by humblec** [comment]
@rootfs but I dont see `klog` in Gopkg.toml as in https://github.com/ceph/ceph-csi/blob/csi-v1.0/Gopkg.toml . But, its in vendor https://github.com/ceph/ceph-csi/tree/csi-v1.0/vendor/k8s.io/klog

**Comment by rootfs** [comment]
if it is used by other vendor pkg, then we don't need it in Gopkg.toml. 

btw, does cli option still work with klog, e.g. `--v=5`?

**Comment by rootfs** [comment]
@humblec can rebase?

**Comment by alfredodeza** [comment]
Why is this migrating away from glog? Can we get issues to track changes like this?

**Comment by humblec** [comment]
> @humblec can rebase?

Sure, was on pto last week , so the delay. Doing the same.

**Comment by humblec** [comment]
> Why is this migrating away from glog? Can we get issues to track changes like this?

1.13 kube has done this migration to overcome some of the limitation of glog. So adopting the same here.

**Comment by humblec** [comment]
@rootfs @gman0 Spurious build failure.

```
gometalinter: command not found
The command "gometalinter --deadline=10m -j 4  --enable=megacheck --enable=misspell  --vendor ./..." exited with 127.
```

**Comment by rootfs** [comment]
@humblec can you rebase and trigger the CI again? Want to make sure the gomegalinter issue is fixed. Thanks

**Comment by humblec** [comment]
@rootfs rebased and its working!

**Pull request merged**
