### PR TITLE
cleanup: resolves gofumpt issues of internal codes

### PR DESCRIPTION
**Pull request by yati1998**
This PR runs gofumpt for internal folder.

Updates: #1586

Signed-off-by: Yati Padia <ypadia@redhat.com>

### CODE REVIEW

**Review by Madhu-1 — APPROVED** [review]

**Review by Madhu-1 — CHANGES_REQUESTED** [review]
Ci failure

`  > [line 25 : column 2] - "github.com/ceph/ceph-csi/internal/journal" imported but not used
`

**Review by nixpanic — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Review by pkalever — APPROVED** [review]
LGTM

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.21

Failed to deploy rook ([logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.21/detail/mini-e2e-helm_k8s-1.21/300/pipeline)):
```
Checking CEPH cluster state: [Creating]
Wait for rook deploy... 45s
Error from server: etcdserver: request timed out
```

**Pull request merged**
