### PR TITLE
ci: remove feature gates

### PR DESCRIPTION
**Pull request by Madhu-1**
Remove the feature gates as they are not required anymore as they are already in beta and few removed in 1.31.0

### CODE REVIEW

**Review by Rakshith-R — APPROVED** [review]

**Review by iPraveenParihar — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio queue

**Comment by nixpanic** [comment]
@mergifyio requeue

**Pull request merged**
