### PR TITLE
update templates to support e2e for kubernetes 1.28

### LINKED ISSUE #4052: update kubernetes dependency to 1.28
Kubernetes 1.28 is released https://kubernetes.io/blog/2023/08/15/kubernetes-v1-28-release/ let's make use of it in cephcsi

- [x]  Make Kubernetes E2E test mandatory in CI Run
- [x] Update Mergify rules to consider tests on kube 1.28
- [x] go dependency update
- [x] Readme update

### PR DESCRIPTION
**Pull request by Madhu-1**
Updated github action to run kubernetes 1.28 tests and also consider test result to merge the PR (via mergify)

depends-on #4056

closes #4052

### CODE REVIEW

**Review by riya-singhal31 — APPROVED** [review]

**Comment by nixpanic** [comment]
Should we remove testing for Kubernetes 1.25? I guess that version is not maintained anymore since 1.28 is released?

**Comment by Madhu-1** [comment]
@nixpanic as per official doc it's not reached eol yet https://kubernetes.io/releases/

**Comment by nixpanic** [comment]
> @nixpanic as per official doc it's not reached eol yet https://kubernetes.io/releases/

Maybe we should consider testing with different Kubernetes versions for different branches? The GitHub Commenter action that we use with `ok-to-test`  might be able to support comments depending on the branch? It would speed up the e2e a little, as test jobs for 4 Kubernetes versions will take quite some time (not sure if they can all run in parallel due to CI quota).

**Review by nixpanic — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio queue

**Comment by Madhu-1** [comment]
As the mergify configuration is changed, merging this one manually

**Pull request merged**
