### PR TITLE
rbd: remove dummy image workaround

### PR DESCRIPTION
**Pull request by Madhu-1**
To address the problem that snapshot schedules are triggered for volumes that are promoted, a dummy image was
disabled/enabled for replication. This was done as a workaround, because the promote operation was not triggering the schedules for the image being promoted.

The bugs related to the same have been fixed in RBD mirroring functionality and hence the workaround #2656 can be removed from the code base.

ceph tracker https://tracker.ceph.com/issues/53914

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Review by Rakshith-R — DISMISSED** [review]

**Comment by humblec** [comment]
In case the ceph csi is with this PR/Fix in place and ceph cluster version running is without the https://tracker.ceph.com/issues/53914, this could be a problem , Isnt it ?

**Comment by Madhu-1** [comment]
> In case the ceph csi is with this PR/Fix in place and ceph cluster version running in the cluster is without the https://tracker.ceph.com/issues/53914, this could be a problem , Isnt it ?

Dont have plan to support those clusters this is not a nice workaround going forward removing it, if someone wants to DR then can use pool mode.

**Comment by Madhu-1** [comment]
> > In case the ceph csi is with this PR/Fix in place and ceph cluster version running in the cluster is without the https://tracker.ceph.com/issues/53914, this could be a problem , Isnt it ?
> 
> Dont have plan to support those clusters this is not a nice workaround going forward removing it, if someone wants to DR then can use pool mode.

or use older version of cephcsi

**Comment by idryomov** [comment]
> In case the ceph csi is with this PR/Fix in place and ceph cluster version running in the cluster is without the https://tracker.ceph.com/issues/53914, this could be a problem , Isnt it ?

This fix was backported all the way to octopus.  I don't think we need to worry about that case.

**Comment by idryomov** [comment]
> > Dont have plan to support those clusters this is not a nice workaround going forward removing it, if someone wants to DR then can use pool mode.
> 
> or use older version of cephcsi

To clarify: pool mode isn't supported with snapshot-based mirroring.  But, as I said, just assuming that the fix for https://tracker.ceph.com/issues/53914 is present is fine.

**Review by idryomov — APPROVED** [review]
Ack from the RBD perspective

**Review by nixpanic — DISMISSED** [review]

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
github action are not started on this PR, manually pushing to the PR to get it started

**Review by Rakshith-R — APPROVED** [review]

**Comment by nixpanic** [comment]
> github action are not started on this PR, manually pushing to the PR to get it started

That was reported by others at actions/checkout#948 as well. Failures seem to have cleared up now.

**Review by nixpanic — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio refresh

**Pull request merged**
