### PR TITLE
cephfs: upgrade fscrypt version to fix concurrency issue (backport #4609)

### PR DESCRIPTION
**Pull request by NymanRobin**
Mergify bot could not resolve a conflict in #4612  when cherry-picking the commit from #4609
So here is cherry-pick manually

### CODE REVIEW

**Review by Madhu-1 — DISMISSED** [review]

**Comment by Madhu-1** [comment]
@NymanRobin can you use `git cherry-pick` which helps us to keep track of the changes?

**Comment by NymanRobin** [comment]
Sure @Madhu-1, I think now it should be cherry-picked properly :D 
First time just upgraded fscrypt manually to avoid having to solve conflicts, but let's do it the right way :+1:

**Comment by Madhu-1** [comment]
> Sure @Madhu-1, I think now it should be cherry-picked properly :D First time just upgraded fscrypt manually to avoid having to solve conflicts, but let's do it the right way 👍

@NymanRobin can you use `-x` to indicate which commit this change was cherry-picked from?

**Comment by NymanRobin** [comment]
Hopefully third time is the charm :crossed_fingers:

**Review by Madhu-1 — APPROVED** [review]

**Comment by Madhu-1** [comment]
> Hopefully third time is the charm 🤞

yes , this looks good, Thanks for taking care of it!

**Comment by Madhu-1** [comment]
@mergifyio queue

**Comment by iPraveenParihar** [comment]
@Madhu-1, I think we need to back-port https://github.com/ceph/ceph-csi/pull/4589 to `release-v3.11` to exclude the 1.26 tests?

**Pull request merged**
