### PR TITLE
Correct `watch` verb in topology rbac and groupversion in csidriver chart

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Review by Madhu-1 — APPROVED** [review]

**Review by Yuggupta27 — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
@humblec this seems to be a bug, should it get backported?

**Comment by humblec** [comment]
> @humblec this seems to be a bug, should it get backported?

@nixpanic  Yeah, thats true, but we are in escape path on topology rbac because we dont support it in d/s and upstream its in `alpha`, the csi driver check we have an escape route with the versions of cluster in place. regardless  I think its good to backport ..

**Comment by humblec** [comment]
@Merjifyio rebase

**Comment by humblec** [comment]
@Mergifyio rebase

**Comment by humblec** [comment]
Failed :

```
Aug 16 07:53:07.252: INFO: >>> kubeConfig: /root/.kube/config
Aug 16 07:53:07.508: INFO: attach command running after restart, runningAttachCmd: rbd-nbd --id cephcsi-rbd-node -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789 --keyfile=/tmp/csi/keys/keyfile-436519115 attach replicapool/csi-vol-85311795-fe5e-11eb-8069-b28ecd7fd6e0 --device /dev/nbd0 --try-netlink --reattach-timeout=300

Aug 16 07:53:07.512: INFO: ExecWithOptions {Command:[/bin/sh -c echo 'Hello World' > /var/lib/www/html/test] Namespace:rbd-694 PodName:csi-rbd-demo-pod ContainerName:web-server Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
Aug 16 07:53:07.512: INFO: >>> kubeConfig: /root/.kube/config
Aug 16 07:53:09.660: INFO: stdErr occurred: /bin/sh: 1: cannot create /var/lib/www/html/test: Read-only file system

Aug 16 07:53:09.660: FAIL: failed to write IO, err: command terminated with exit code 2, stdErr: /bin/sh: 1: cannot create /var/lib/www/html/test: Read-only file system
 ```

**Comment by humblec** [comment]
Failure due to: #2362

**Pull request merged**
