### PR TITLE
Update HELM  to latest avaliable version

### PR DESCRIPTION
**Pull request by humblec**
- [x] Helm version v3.8.2

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Review by yati1998 — COMMENTED** [review]
@humblec maybe we need to resolve the golangci lint errors. Are you planning to do it in separate PR

**Comment by humblec** [comment]
> @humblec maybe we need to resolve the golangci lint errors. Are you planning to do it in separate PR

let me try here itself.. thanks!

**Comment by nixpanic** [comment]
> > @humblec maybe we need to resolve the golangci lint errors. Are you planning to do it in separate PR
> 
> let me try here itself.. thanks!

Ideally run tests locally, so that the CI resources can be used for PRs that are expected to pass.

**Comment by nixpanic** [comment]
it seems **golangci-lint** failed gain, please run the test locally first

**Comment by nixpanic** [comment]
Marked as **Draft** for unneeded failures.

Also wondering why Helm rebase and testing improvements are done in a single PR?

**Comment by humblec** [comment]
> Also wondering why Helm rebase and testing improvements are done in a single PR?

Kept only HELM update in this PR.

**Review by Madhu-1 — APPROVED** [review]

**Comment by humblec** [comment]
@nixpanic ptal. thanks.

**Review by yati1998 — APPROVED** [review]

**Pull request merged**
