### PR TITLE
doc: fix helm doc of ceph-csi deployment

### PR DESCRIPTION
**Pull request by astraw99**
To make the doc better.

# Describe what this PR does #

Fix helm doc of ceph-csi deployment.

### CODE REVIEW

**Comment by nixpanic** [comment]
Hi @astraw99, thanks for the PR! Could you update the commit message and add `doc: ` as prefix to the subject of the commit? That way the **commitlint** CI job will pass, and tags will be added.

**Comment by astraw99** [comment]
> Hi @astraw99, thanks for the PR! Could you update the commit message and add `doc: ` as prefix to the subject of the commit? That way the **commitlint** CI job will pass, and tags will be added.

Updated, PTAL thanks.

**Review by Rakshith-R — COMMENTED** [review]
Can make the same changes in rbd helm readme too ? 

https://github.com/ceph/ceph-csi/blob/ddcf88722beb280d0dd12c52ec1ce04150ae5ec4/charts/ceph-csi-rbd/README.md#install-chart

**Review by Madhu-1 — APPROVED** [review]

**Comment by astraw99** [comment]
> Can make the same changes in rbd helm readme too ?
> 
> https://github.com/ceph/ceph-csi/blob/ddcf88722beb280d0dd12c52ec1ce04150ae5ec4/charts/ceph-csi-rbd/README.md#install-chart

Done, PTAL thanks.

**Review by Rakshith-R — APPROVED** [review]
Thanks !

**Comment by nixpanic** [comment]
@mergifyio queue

**Comment by nixpanic** [comment]
@mergifyio rebase

**Review by nixpanic — APPROVED** [review]

**Review by riya-singhal31 — APPROVED** [review]

**Pull request merged**
