### PR TITLE
rbd: correct the code comment for ErrFlattenInProgress

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Review by nixpanic — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Comment by humblec** [comment]
@Merjify rebase

**Comment by humblec** [comment]
@Mergifyio rebase

**Comment by nixpanic** [comment]
This has the `[ci/skip/e2e]` label, so it should not try to run minikube. It only seems to abort a part of the jobs and continues with running the tests now. This needs to be addressed in the CI configuration :cry:

**Comment by humblec** [comment]
> This has the `[ci/skip/e2e]` label, so it should not try to run minikube. It only seems to abort a part of the jobs and continues with running the tests now. This needs to be addressed in the CI configuration cry

@nixpanic I was wondering why this is not going in :facepalm:

**Comment by nixpanic** [comment]
> @nixpanic I was wondering why this is not going in facepalm

Instead of just re-testing, please check the logs of the CI jobs that failed. When in doubt, ask in #ci on the Slack channel and others may have an idea.

This should get fixed with #1609. Once that is merged and deployed in Jenkins, this PR can be re-tested again.

**Comment by humblec** [comment]
> > @nixpanic I was wondering why this is not going in facepalm
> 
> Instead of just re-testing, please check the logs of the CI jobs that failed. When in doubt, ask in #ci on the Slack channel and others may have an idea.
> 
> This should get fixed with #1609. Once that is merged and deployed in Jenkins, this PR can be re-tested again.

@nixpanic  fyi , Indeed I was checking the logs for last few hours.. the error  looked like an intermittent failure (404)..etc, so the retest attempt

**Comment by pkalever** [comment]
Wondering why we need tests for a typo fix in comments?

**Review by pkalever — APPROVED** [review]

**Comment by nixpanic** [comment]
> @nixpanic fyi , Indeed I was checking the logs for last few hours.. the error looked like an intermittent failure (404)..etc, so the retest attempt

The errors were while deploying Kubernetes with minikube, see #1588. Downloading the checksum files works fine manually, minikube fails to do so (but only for releases that were done very recently).

As the `[ci/skip/e2e]` label was already added, the tests should never have gotten that far in the 1st place.

**Comment by nixpanic** [comment]
> Wondering why we need tests for a typo fix in comments?

These tests do not run any functional tests when the `[ci/skip/e2e]` label is added to a PR. The CI job just returns success when the label is detected. (But that failed since yesterday, due to #1604.)

**Comment by pkalever** [comment]
> > Wondering why we need tests for a typo fix in comments?
> 
> These tests do not run any functional tests when the `[ci/skip/e2e]` label is added to a PR. The CI job just returns success when the label is detected. (But that failed since yesterday, due to #1604.)

Got it now, thanks for the details @nixpanic

**Comment by nixpanic** [comment]
@mergifyio refresh

**Pull request merged**
