### PR TITLE
update ceph-csi to build and use a single docker image

### PR DESCRIPTION
**Pull request by Madhu-1**
currently, we have 3 docker files(cephcsi,rbd,cephfs) in the ceph-csi repo. [commit ](https://github.com/ceph/ceph-csi/commit/85e121ebfe3cf2ee94bf7a8d37ad793ecb43c455) added by John to build a single image which can act as rbd or cephfs based on the input configuration.

This PR updates the makefile and kubernetes templates to use the unified image and also its deletes the other two dockerfiles.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
@phlogistonjohn PTAL

**Comment by humblec** [comment]
@Madhu-1 My understanding is that we deliberately kept the seperate images if someone want to play with one of it.

**Comment by Madhu-1** [comment]
> is that we deliberately kept the seperate images if someone want to play with one of it.

@humblec not sure what's the reason to have 3 dockerfile in ceph-csi repo?

**Comment by humblec** [comment]
>@humblec not sure what's the reason to have 3 dockerfile in ceph-csi repo?

The reason for that was, dont break or surprise the existing users if they look for seperate images in the registry or while they build it.  But, one interesting thing is that from next version `1.1` onwards any way we are going to surprise existing users or bringing breaking changes. In that way, I am fine to take this in.

**Comment by Madhu-1** [comment]
> > @humblec not sure what's the reason to have 3 dockerfile in ceph-csi repo?
> 
> The reason for that was, dont break or surprise the existing users if they look for seperate images in the registry or while they build it. But, one interesting thing is that from next version `1.1` onwards any way we are going to surprise existing users or bringing breaking changes. In that way, I am fine to take this in.

Agreed!

**Comment by humblec** [comment]
@ShyamsundarR what about this ? any further comments ?

**Comment by Madhu-1** [comment]
@ShyamsundarR PTAL

**Pull request merged**
