### PR TITLE
ci: update minikube to v1.29.0

### PR DESCRIPTION
**Pull request by Madhu-1**
update minikube to the latest available release https://github.com/kubernetes/minikube/releases/tag/v1.29.0.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
ci/centos/mini-e2e/k8s-1.26

**Review by nixpanic — APPROVED** [review]

**Review by Rakshith-R — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

**Pull request merged**
