### PR TITLE
doc: few corrections or typo fixing in design documentation

### PR DESCRIPTION
**Pull request by humblec**
- Fixes spelling mistakes.
- Grammatical error correction.
- Wrapping the text at 80 line count..etc

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Review by nixpanic — DISMISSED** [review]
The lint failure should have been caught by running `make containerized-test` before posting the PR.

**Comment by Madhu-1** [comment]
>Wrapping the text at 80 line count..etc

It's hard to maintain this one unless this check is introduced in the CI

**Comment by humblec** [comment]
> > Wrapping the text at 80 line count..etc
> 
> It's hard to maintain this one unless this check is introduced in the CI

true, I can add that to CI. wdyt ?

**Comment by Madhu-1** [comment]
> > > Wrapping the text at 80 line count..etc
> > 
> > 
> > It's hard to maintain this one unless this check is introduced in the CI
> 
> true, I can add that to CI. wdyt ?

That's great 👍

**Comment by humblec** [comment]
> > > > Wrapping the text at 80 line count..etc
> > > 
> > > 
> > > It's hard to maintain this one unless this check is introduced in the CI
> > 
> > 
> > true, I can add that to CI. wdyt ?
> 
> That's great +1

but that may need changes in all documentation files once the rule in place, so may be as a follow up PR.

**Review by Madhu-1 — APPROVED** [review]

**Review by yati1998 — APPROVED** [review]

**Pull request merged**
