### PR TITLE
deploy: update CSI sidecars to latest versions available

### LINKED ISSUE #4570: Update all the kubernetes sidecar to latest release
It looks like we have the latest release for a few sidecars that we use, Let's update the sidecar to the latest available releases.

### PR DESCRIPTION
**Pull request by iPraveenParihar**
# Describe what this PR does #

Below sidecars are updated with latest available versions

csi-node-driver-registrar: v2.10.1
csi-resizer: v1.10.1
csi-provisioner: v4.0.1
csi-attacher: v4.5.1
csi-snapshotter: v7.0.2

## Related issues ##

Closes: #4570 

**Checklist:**

* [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#commit-messages).
* [x] Reviewed the developer guide on [Submitting a Pull Request](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#development-workflow)
* [x] [Pending release notes](https://github.com/ceph/ceph-csi/blob/devel/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next major release.
* [x] Documentation has been updated, if necessary.
* [x] Unit tests have been added, if necessary.
* [x] Integration tests have been added, if necessary.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

* `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

### CODE REVIEW

**Review by Madhu-1 — CHANGES_REQUESTED** [review]
update here as well https://github.com/ceph/ceph-csi/blob/51d1d46dd23f88779418422bbf99d03a45885637/build.env#L32-L61

**Comment by iPraveenParihar** [comment]
> update here as well
> 
> https://github.com/ceph/ceph-csi/blob/51d1d46dd23f88779418422bbf99d03a45885637/build.env#L32-L61

I have updated.
probably you have missed it. :)

**Review by Madhu-1 — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio queue

**Pull request merged**
