### PR TITLE
ci: update CSI_UPGRADE_VERSION to v3.12.1

### PR DESCRIPTION
**Pull request by iPraveenParihar**
# Describe what this PR does #

This commit updates `CSI_UPGRADE_VERSION` to latest
 
**Checklist:**

* [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#commit-messages).
* [x] Reviewed the developer guide on [Submitting a Pull Request](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#development-workflow)
* [x] [Pending release notes](https://github.com/ceph/ceph-csi/blob/devel/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next major release.
* [x] Documentation has been updated, if necessary.
* [x] Unit tests have been added, if necessary.
* [x] Integration tests have been added, if necessary.

Depends-on: #4783

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

* `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

### CODE REVIEW

**Review by Madhu-1 — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Comment by iPraveenParihar** [comment]
@Madhu-1, can we skip e2e?

**Comment by Madhu-1** [comment]
> @Madhu-1, can we skip e2e?

@iPraveenParihar we need to run e2e to ensure upgrade passes

**Comment by Madhu-1** [comment]
@mergifyio queue

**Comment by iPraveenParihar** [comment]
> > @Madhu-1, can we skip e2e?
> 
> @iPraveenParihar we need to run e2e to ensure upgrade passes

I thought of running just the upgrade test alone, instead of running all regular runs.

**Comment by Madhu-1** [comment]
> > > @Madhu-1, can we skip e2e?
> > 
> > 
> > @iPraveenParihar we need to run e2e to ensure upgrade passes
> 
> I thought of running just the upgrade test alone, instead of running all regular runs.

Yes that is also fine, we can do that one

**Comment by Madhu-1** [comment]
@mergifyio unqueue

**Comment by Madhu-1** [comment]
@iPraveenParihar run the upgrade manually and if all the required test passes, we can add skip label and add this to queue.

**Comment by nixpanic** [comment]
CI jobs failed with this:
```
  I0820 11:11:28.375162 80996 dump.go:53] At 2024-08-20 11:01:35 +0000 UTC - event for csi-rbdplugin-provisioner-b6bb4d8bb-9phtk: {kubelet minikube} BackOff: Back-off pulling image "quay.io/cephcsi/cephcsi:v3.12.1"
```

The image should be available now.

**Comment by nixpanic** [comment]
> /test ci/centos/upgrade-tests

Both passed:

 - **upgrade-tests-rbd**  https://jenkins-ceph-csi.apps.ocp.cloud.ci.centos.org/blue/organizations/jenkins/upgrade-tests-rbd/detail/upgrade-tests-rbd/8118/pipeline
 - **upgrade-tests-cephfs** https://jenkins-ceph-csi.apps.ocp.cloud.ci.centos.org/blue/organizations/jenkins/upgrade-tests-cephfs/detail/upgrade-tests-cephfs/8149/pipeline

**Comment by nixpanic** [comment]
@mergifyio requeue

**Pull request merged**
