### PR TITLE
ci: run snapshot tests and expand tests

### PR DESCRIPTION
**Pull request by Madhu-1**
enabling snapshot,pvc clone tests, and the expand tests to see if everything works fine.

### CODE REVIEW

**Comment by Madhu-1** [comment]
ci/centos/k8s-e2e-external-storage/1.29

**Comment by nixpanic** [comment]
Looks good, I think. Would be nice to re-run a test once #4546 is merged.

**Comment by Madhu-1** [comment]
> Looks good, I think. Would be nice to re-run a test once #4546 is merged.

Merged #4546, lets rerun the test and see

**Review by nixpanic — APPROVED** [review]

**Review by Rakshith-R — APPROVED** [review]

**Comment by Rakshith-R** [comment]
@mergifyio queue

**Comment by nixpanic** [comment]
@mergifyio dequeue

**Comment by nixpanic** [comment]
@mergifyio queue

Somehow CI jobs were not started. #4499 was fully tested and pending on this to get merged, but it seems it needed a rebase as well :disappointed:

**Comment by nixpanic** [comment]
@mergifyio refresh

**Comment by nixpanic** [comment]
@mergifyio requeue

**Comment by nixpanic** [comment]
@mergifyio queue

Lets try that again, it should get rebased+merged once the other is done.

**Pull request merged**
