### PR TITLE
fix helm value pullPolicy mismatch bug

### PR DESCRIPTION
**Pull request by MiaoZhou**
This is a port of the changes in PR #334.
I'm a little confused about the chart version bump policy.
In `master` branch, the version was bumped to `0.5.3`. In `csi-v1.0` branch was still `0.5.1` when i made the fix.
In PR #334 , i have bumped version to `0.6.0`.
How should i determine the version in this PR? The same? @ShyamsundarR

### CODE REVIEW

**Comment by Madhu-1** [comment]
@MiaoZhou please update the version to `0.6.1`  as we already have `0.6.0` version. 
@ShyamsundarR @humblec we need to make master as the default branch, and I think we should not continue to work on csiv1.0 branch. any thoughts?

only from the master, we should push the latest helm chats.

**Comment by humblec** [comment]
>@ShyamsundarR @humblec we need to make master as the default branch, and I think we should not continue to work on csiv1.0 branch. any thoughts?

only from the master, we should push the latest helm chats.
>

Completely agree, lets get that done.

**Comment by ShyamsundarR** [comment]
> > @ShyamsundarR @humblec we need to make master as the default branch, and I think we should not continue to work on csiv1.0 branch. any thoughts?
> > only from the master, we should push the latest helm chats.
> 
> Completely agree, lets get that done.

For the helm charts issue #362 is the way to proceed, and not stopping helm chart updates from all branches other than master IMO. As, we need the charts from other versions as well to be posted.

For master being the default branch, yes it should be. I have been attempting to nudge #308 along sometime now but without success.

**Comment by Madhu-1** [comment]
@MiaoZhou please resolve merge conflict

**Comment by Madhu-1** [comment]
the only change in this PR is the helm chat version
@MiaoZhou as other changes are already present in master I think we can close this one.

**Comment by MiaoZhou** [comment]
@Madhu-1 ok

**Pull request closed without merging**
