### PR TITLE
e2e: run thick-provisioning test with rbd-nbd

### PR DESCRIPTION
**Pull request by nixpanic**
This e2e test is expected to fail until #2171 is fixed.

Updates: #2171
CC: @pkalever 

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

**Comment by pkalever** [comment]
@Madhu-1 @nixpanic can we close this based on https://github.com/ceph/ceph-csi/pull/2589 ?

**Comment by Madhu-1** [comment]
@pkalever Thanks for keeping track of it. yes makes sense to close this one.

**Comment by pkalever** [comment]
Closing this now based on previous discussions above, feel free to reopen if needed. Thanks!

**Pull request closed without merging**
