### PR TITLE
[WIP] Implement controller publish in rbd

### PR DESCRIPTION
**Pull request by Madhu-1**
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

# Describe what this PR does #
 yet to update

## Is there anything that requires special attention ##

Do you have any questions?

Is the change backward compatible?

Are there concerns around backward compatibility?

Provide any external context for the change, if any.

For example:

* Kubernetes links that explain why the change is required
* CSI spec related changes/catch-up that necessitates this patch
* golang related practices that necessitates this change

## Related issues ##

Mention any github issues relevant to this PR. Adding below line
will help to auto close the issue once the PR is merged.

Fixes: #issue_number

## Future concerns ##

List items that are not part of the PR and do not impact it's
functionality, but are work items that can be taken up subsequently.

### CODE REVIEW

**Comment by Madhu-1** [comment]
@travisn @leseb 

anything recently changes  in rook master related  to toolbox pod

cephcsi CI failing with below error message

everything  was  working earlier, we are seeing this issue from few  days
```
Aug 30 09:25:35.321: INFO: ExecWithOptions {Command:[/bin/sh -c ceph fsid] Namespace:rook-ceph PodName:rook-ceph-tools-7cf4cc7568-qwn5v ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true}
Aug 30 09:25:35.321: INFO: >>> kubeConfig: /home/travis/.kube/config
Aug 30 09:25:35.633: INFO: stdErr occurred 
%!(EXTRA string=unable to get monitor info from DNS SRV with service name: ceph-mon
[errno 2] error connecting to the cluster
```

**Comment by Madhu-1** [comment]
with this  changes facing issue during mount

```
[ 7236.964577] rbd: rbd0: failed to acquire lock: -16
[ 7236.966859] rbd: rbd0: no lock owners detected
[ 7236.981520] rbd: rbd0: locked by external mechanism, tag 
[ 7236.985336] rbd: rbd0: failed to acquire lock: -16
[ 7236.988472] rbd: rbd0: no lock owners detected
[ 7236.999294] rbd: rbd0: locked by external mechanism, tag 
[ 7237.001193] rbd: rbd0: failed to acquire lock: -16
[ 7237.005788] rbd: rbd0: no lock owners detected
[ 7237.012359] rbd: rbd0: locked by external mechanism, tag 
[ 7237.016813] rbd: rbd0: failed to acquire lock: -16
[ 7237.022463] rbd: rbd0: no lock owners detected
[ 7237.031866] rbd: rbd0: locked by external mechanism, tag 
[ 7237.033104] rbd: rbd0: failed to acquire lock: -16
[ 7237.039432] rbd: rbd0: no lock owners detected
```

**Comment by leseb** [comment]
> @travisn @leseb
> 
> anything recently changes in rook master related to toolbox pod
> 
> cephcsi CI failing with below error message
> 
> everything was working earlier, we are seeing this issue from few days
> 
> ```
> Aug 30 09:25:35.321: INFO: ExecWithOptions {Command:[/bin/sh -c ceph fsid] Namespace:rook-ceph PodName:rook-ceph-tools-7cf4cc7568-qwn5v ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true}
> Aug 30 09:25:35.321: INFO: >>> kubeConfig: /home/travis/.kube/config
> Aug 30 09:25:35.633: INFO: stdErr occurred 
> %!(EXTRA string=unable to get monitor info from DNS SRV with service name: ceph-mon
> [errno 2] error connecting to the cluster
> ```

Hum, the ceph.conf could malformed, can you access a toolbox and print its ceph.conf?

**Comment by Madhu-1** [comment]
let me print it.

**Comment by travisn** [comment]
@Madhu-1 Any more clues for connecting from the toolbox? Perhaps a clean install was needed with all the changes happening?

**Comment by Madhu-1** [comment]
@travisn will test it today, ceph-csi CI always pulls the latest master and deploys rook and ceph cluster

**Comment by Madhu-1** [comment]
closing as we are not implementing Controller Publish and unPublish RPC

**Pull request closed without merging**
