### PR TITLE
Fix golint

### PR DESCRIPTION
**Pull request by Madhu-1**
This PR fixes most of the issues found during go static check

@rootfs PTAL. please don't merge this PR testing is pending.

### CODE REVIEW

**Comment by rootfs** [comment]
thanks, let me know when you are ready

**Comment by Madhu-1** [comment]
@rootfs can you point to some document which might help me to setup kube+ceph to test CSI driver patches in a faster way?

**Comment by rootfs** [comment]
i stand up k8s through [local-up-cluster.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh) on my laptop, and run rook to stand up a ceph cluster. From there, you get all your need to start deploying csi driver.

**Comment by humblec** [comment]
@Madhu-1 or use any mechanism to bring your kube cluster up and use rook .

**Comment by Madhu-1** [comment]
@rootfs am getting some authentication issue while creating the PVC

```
ceph-fuse[36]: starting ceph client
ceph-fuse[36]: ceph mount failed with (22) Invalid argument
2019-01-22 17:28:24.756814 7fe9ed09f0c0 -1 client.0 authentication failed: (22) Invalid argument
W0122 17:28:24.763955       1 controller.go:686] Retrying syncing claim "default/csi-cephfs-pvc" because failures 2 < threshold 15
E0122 17:28:24.763970       1 controller.go:701] error syncing claim "default/csi-cephfs-pvc": failed to provision volume with StorageClass "csi-cephfs": rpc error: code = Internal desc = error mounting ceph root: cephfs: ceph-fuse failed:
cephfs: ceph-fuse output: 2019-01-22 17:28:24.753745 7fe9ed09f0c0 -1 init, newargv = 0x55a4af9c9e30 newargc=11
ceph-fuse[36]: starting ceph client
ceph-fuse[36]: ceph mount failed with (22) Invalid argument
2019-01-22 17:28:24.756814 7fe9ed09f0c0 -1 client.0 authentication failed: (22) Invalid argument
I0122 17:28:24.764169       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"csi-cephfs-pvc", UID:"16447f07-1e6b-11e9-8331-52540035463f", APIVersion:"v1", ResourceVersion:"47589", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "csi-cephfs": rpc error: code = Internal desc = error mounting ceph root: cephfs: ceph-fuse failed:
cephfs: ceph-fuse output: 2019-01-22 17:28:24.753745 7fe9ed09f0c0 -1 init, newargv = 0x55a4af9c9e30 newargc=11
ceph-fuse[36]: starting ceph client
ceph-fuse[36]: ceph mount failed with (22) Invalid argument
2019-01-22 17:28:24.756814 7fe9ed09f0c0 -1 client.0 authentication failed: (22) Invalid argument
I0122 17:28:29.126992       1 reflector.go:357] github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:603: Watch close - *v1.PersistentVolumeClaim total 10 items received
```

can you tell me what could be the issue?

secret
```
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: default
data:
  # Required if provisionVolume is set to true
  adminID: YWRtaW4=
  adminKey: QVFCWmcwVmNSVU5JR3hBQUNtU1BNbVRJODl2ZEFFU0JJb2lxaFE9PQ==
```
got admin key from `ceph auth get-key client.admin | base64`

**Comment by rootfs** [comment]
what's in your cephfsplugin log?

**Comment by Madhu-1** [comment]
@rootfs  cephplugin logs
```
I0122 18:13:45.973533       1 utils.go:98] GRPC request: {"capacity_range":{"required_bytes":5368709120},"name":"pvc-2f1edd71-1e71-11e9-8331-52540035463f","parameters":{"csiNodeStageSecretName":"csi-cephfs-secret","csiNodeStageSecretNamespace":"default","csiProvisionerSecretName":"csi-cephfs-secret","csiProvisionerSecretNamespace":"default","monitors":"rook-ceph-mon-b.rook-ceph.svc.cluster.local:6790","pool":"cephfs_data","provisionVolume":"true"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":5}}]}
I0122 18:13:45.981097       1 util.go:41] cephfs: EXEC ceph-fuse [/var/lib/kubelet/plugins_registry/csi-cephfsplugin/controller/volumes/root-csi-cephfs-pvc-2f1edd71-1e71-11e9-8331-52540035463f -c /etc/ceph/ceph.share.csi-cephfs-pvc-2f1edd71-1e71-11e9-8331-52540035463f.conf -n client.admin --keyring /etc/ceph/ceph.share.csi-cephfs-pvc-2f1edd71-1e71-11e9-8331-52540035463f.client.admin.keyring -r / -o nonempty]
E0122 18:13:46.057936       1 controllerserver.go:76] failed to create volume pvc-2f1edd71-1e71-11e9-8331-52540035463f: error mounting ceph root: cephfs: ceph-fuse failed:
cephfs: ceph-fuse output: 2019-01-22 18:13:46.048451 7fd37e9cb0c0 -1 init, newargv = 0x55db90a69e30 newargc=11
ceph-fuse[56]: starting ceph client
ceph-fuse[56]: ceph mount failed with (22) Invalid argument
2019-01-22 18:13:46.052968 7fd37e9cb0c0 -1 client.0 authentication failed: (22) Invalid argument
E0122 18:13:46.057953       1 utils.go:101] GRPC error: rpc error: code = Internal desc = error mounting ceph root: cephfs: ceph-fuse failed:
cephfs: ceph-fuse output: 2019-01-22 18:13:46.048451 7fd37e9cb0c0 -1 init, newargv = 0x55db90a69e30 newargc=11
ceph-fuse[56]: starting ceph client
ceph-fuse[56]: ceph mount failed with (22) Invalid argument
```

**Comment by rootfs** [comment]
@Madhu-1 you also need to create a ceph filesystem

https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/filesystem.yaml

**Comment by Madhu-1** [comment]
@rootfs Thanks, I will try it out.

**Comment by Madhu-1** [comment]
@rootfs Thanks for the help, tested this patch. we can merge this one

```
[🎩︎]mrajanna@localhost cephfs $]kube get pvc
NAME              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
csi-cephfs-pvc    Bound    pvc-2f9623c0-207f-11e9-a1e9-52540088830b   5Gi        RWX            csi-cephfs     98s
csi-cephfs-pvc2   Bound    pvc-dbde1db9-2077-11e9-a1e9-52540088830b   5Gi        RWX            csi-cephfs     54m
rbd-pvc           Bound    pvc-aa394dc4-207e-11e9-a1e9-52540088830b   1Gi        RWO            csi-rbd        5m22s
```

**Comment by Madhu-1** [comment]
```
[🎩︎]mrajanna@localhost cephfs $]kube get po
NAME                             READY   STATUS    RESTARTS   AGE
csi-cephfsplugin-4924m           2/2     Running   0          8m1s
csi-cephfsplugin-attacher-0      1/1     Running   1          106m
csi-cephfsplugin-m2jdq           2/2     Running   0          8m20s
csi-cephfsplugin-provisioner-0   1/1     Running   1          106m
csi-cephfsplugin-xjlkn           2/2     Running   0          8m41s
csi-rbdplugin-attacher-0         1/1     Running   0          54m
csi-rbdplugin-b6vjf              2/2     Running   0          8m55s
csi-rbdplugin-jn2mq              2/2     Running   0          9m12s
csi-rbdplugin-mjmxt              2/2     Running   0          9m41s
csi-rbdplugin-provisioner-0      1/1     Running   0          54m
csicephfs-demo-pod               1/1     Running   0          4m25s
csirbd-demo-pod                  1/1     Running   0          8m10s
```
Mount was successful

**Comment by Madhu-1** [comment]
@gman0 am planning to add gometalinter to the CI. but still, I need to do some more changes.

i will add static tests in upcoming PR

**Comment by gman0** [comment]
Cool, thanks!

**Comment by Madhu-1** [comment]
@gman0 @rootfs can we merge this one?

**Pull request merged**
