### PR TITLE
doc: update  readme for v3.1.0 and RBD ROX support

### PR DESCRIPTION
**Pull request by Madhu-1**
Updated readme for v3.1.0 release and added missing RBD ROX support to the matrix.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Review by Yuggupta27 — APPROVED** [review]
Looks Good.

**Review by pkalever — APPROVED** [review]

**Comment by humblec** [comment]
@Madhu-1 we disabled it now , Isnt it ?

**Comment by Madhu-1** [comment]
> @Madhu-1 we disabled it now , Isnt it ?

Empty Rox is disabled not complete rox support this doc need update

**Comment by Madhu-1** [comment]
> > @Madhu-1 we disabled it now , Isnt it ?
> 
> Empty Rox is disabled not complete rox support this doc need update

@humblec Doc is updated now PTAL

**Review by humblec — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Pull request merged**
