### PR TITLE
connect to provisioner socket

### PR DESCRIPTION
**Pull request by Madhu-1**
# Describe what this PR does #

in current deployment, liveness container is connecting to csi.sock socket which is exposed by node plugin, not to the provisioner listening on csi-provisioner.sock. the liveness container inside the provisioner pod should connect to the provisioner socket, not the node plugin socket

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

## Related issues ##

Fixes: #619

### CODE REVIEW

**Comment by Madhu-1** [comment]
> I am assuming the Helm changes will come in through the other PR that @wilmardo is working on.

yes @ShyamsundarR that's the plan, so thats why I have not done any changes to helm chat

**Comment by humblec** [comment]
@Madhu-1 this should be backported to `1.2.0` , Isnt it ?

**Comment by Madhu-1** [comment]
@humblec yes this need to be backported once PR is merged will send backport PR

**Comment by Madhu-1** [comment]
@humblec PTAL

**Comment by humblec** [comment]
@Madhu-1 PR description has to be updated.

**Comment by Madhu-1** [comment]
> @Madhu-1 PR description has to be updated.

@humblec didnt get what changes i need to make?

**Comment by humblec** [comment]
> > @Madhu-1 PR description has to be updated.
> 
> @humblec didnt get what changes i need to make?





~~~
Is there anything that requires special attention
Do you have any questions?

Is the change backward compatible?

Are there concerns around backward compatibility?

Provide any external context for the change, if any.

For example:

Kubernetes links that explain why the change is required
CSI spec related changes/catch-up that necessitates this patch
golang related practices that necessitates this change
Related issues
Mention any github issues relevant to this PR. Adding below line
will help to auto close the issue once the PR is merged.
~~~
Above can be removed from the PR description @Madhu-1

**Comment by Madhu-1** [comment]
@humblec done

**Comment by humblec** [comment]
LGTM. Approved.

**Pull request merged**
