### PR TITLE
cleanup: make godot warnings fixed in our source repo

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@Madhu-1  @nixpanic  @Yuggupta27 ptal

**Comment by Yuggupta27** [comment]
Were these godot warnings reported by golangci? Afaik, only `Top level comments should end in a period`. Comments inside a block don't need to satisfy this condition.

**Comment by humblec** [comment]
> Were these godot warnings reported by golangci? Afaik, only `Top level comments should end in a period`. Comments inside a block don't need to satisfy this condition.
> For reference see: [b7e4794](https://github.com/ceph/ceph-csi/commit/b7e4794713cd6ad7f6b11b81d7eba0d3a750eaa7)
True.. let me correct it .. Thanks :+1:

**Comment by Madhu-1** [comment]
we don't need this one, just verified it with `godot` tool.

**Pull request closed without merging**
