### PR TITLE
rebase: use minikube v1.18

### PR DESCRIPTION
**Pull request by nixpanic**
Minikube v1.18 has been released. This conains a fix for our `losetup`
workaround, so that can be removed now.

Updates: #1840

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

**Review by Madhu-1 — APPROVED** [review]

**Review by humblec — APPROVED** [review]

**Comment by nixpanic** [comment]
**ci/centos/containerized-tests** failed while building the image with dependencies for testing:

```
cd /opt/build/go/src/github.com/ceph/ceph-csi && make containerized-test TARGET=mod-check CONTAINER_CMD=podman ENV_CSI_IMAGE_NAME=registry-ceph-csi.apps.ocp.ci.centos.org/ceph-csi USE_PULLED_IMAGE=no'
Warning: Permanently added 'n28.crusty.ci.centos.org,172.19.2.28' (ECDSA) to the list of known hosts.
cephcsi image settings: registry-ceph-csi.apps.ocp.ci.centos.org/ceph-csi version canary
[ ! -f .test-container-id ] || podman rmi registry-ceph-csi.apps.ocp.ci.centos.org/ceph-csi:test
podman build  -t registry-ceph-csi.apps.ocp.ci.centos.org/ceph-csi:test -f ./scripts/Dockerfile.test .
STEP 1: FROM registry.fedoraproject.org/fedora:latest
Getting image source signatures
Copying blob sha256:157ab801145489f145f258148bd135102a3294e420f1859a39e824e7cda56b2f
Copying config sha256:9f2a56037643a68ea81711a8eeb4501428eefd40b000c866ad9745a581c0464d
Writing manifest to image destination
Storing signatures
STEP 2: ARG GOPATH=/go
--> Using cache 31de5ecfc421c7d12748a3c3cf48a2cd6bbd77b588e4b753e1d79d3cf39ceb2e
--> 31de5ecfc42
STEP 3: ENV  GOPATH=${GOPATH}  GO111MODULE=on  PATH="${GOPATH}/bin:/opt/commitlint/node_modules/.bin:${PATH}"
Error: error checking if cached image exists from a previous build: error getting history of "4770638bf2e01c123662b7dade27aaf1925fc2fe473628834729a4309b2d4131": error creating new image from reference to image "4770638bf2e01c123662b7dade27aaf1925fc2fe473628834729a4309b2d4131": error locating item named "manifest" for image with ID "4770638bf2e01c123662b7dade27aaf1925fc2fe473628834729a4309b2d4131": file does not exist
make: *** [Makefile:207: .test-container-id] Error 125
script returned exit code 2
```

Not sure what the problem can be, it seems something related to `podman` or maybe the fedora image?

**Comment by nixpanic** [comment]
> **ci/centos/containerized-tests** failed while building the image with dependencies for testing:
> 
> ```
> cd /opt/build/go/src/github.com/ceph/ceph-csi && make containerized-test TARGET=mod-check CONTAINER_CMD=podman ENV_CSI_IMAGE_NAME=registry-ceph-csi.apps.ocp.ci.centos.org/ceph-csi USE_PULLED_IMAGE=no'
> Warning: Permanently added 'n28.crusty.ci.centos.org,172.19.2.28' (ECDSA) to the list of known hosts.
> cephcsi image settings: registry-ceph-csi.apps.ocp.ci.centos.org/ceph-csi version canary
> [ ! -f .test-container-id ] || podman rmi registry-ceph-csi.apps.ocp.ci.centos.org/ceph-csi:test
> podman build  -t registry-ceph-csi.apps.ocp.ci.centos.org/ceph-csi:test -f ./scripts/Dockerfile.test .
> STEP 1: FROM registry.fedoraproject.org/fedora:latest
> Getting image source signatures
> Copying blob sha256:157ab801145489f145f258148bd135102a3294e420f1859a39e824e7cda56b2f
> Copying config sha256:9f2a56037643a68ea81711a8eeb4501428eefd40b000c866ad9745a581c0464d
> Writing manifest to image destination
> Storing signatures
> STEP 2: ARG GOPATH=/go
> --> Using cache 31de5ecfc421c7d12748a3c3cf48a2cd6bbd77b588e4b753e1d79d3cf39ceb2e
> --> 31de5ecfc42
> STEP 3: ENV  GOPATH=${GOPATH}  GO111MODULE=on  PATH="${GOPATH}/bin:/opt/commitlint/node_modules/.bin:${PATH}"
> Error: error checking if cached image exists from a previous build: error getting history of "4770638bf2e01c123662b7dade27aaf1925fc2fe473628834729a4309b2d4131": error creating new image from reference to image "4770638bf2e01c123662b7dade27aaf1925fc2fe473628834729a4309b2d4131": error locating item named "manifest" for image with ID "4770638bf2e01c123662b7dade27aaf1925fc2fe473628834729a4309b2d4131": file does not exist
> make: *** [Makefile:207: .test-container-id] Error 125
> script returned exit code 2
> ```
> 
> Not sure what the problem can be, it seems something related to `podman` or maybe the fedora image?

This problem should get addressed with #1900 . Once that one is merged and the CI jobs are updated, a `/retest` can be attempted.

**Pull request merged**
