### PR TITLE
Fix incorrect make command

### PR DESCRIPTION
**Pull request by Madhu-1**
update v1.0.0-canary tag to canary tag

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
@humblec @phlogistonjohn PTAL

**Comment by ShyamsundarR** [comment]
Please update docs under the `doc/` directory to change build instructions as well. Other changes look good.

**Comment by Madhu-1** [comment]
@ShyamsundarR yeah missed to update doc section

@humblec @ShyamsundarR updated PR.

**Comment by humblec** [comment]
LGTM. Thanks @Madhu-1

**Pull request merged**
