### PR TITLE
ci: allow passing USE_PULLED_IMAGE=yes to use pre-pulled images

### PR DESCRIPTION
**Pull request by nixpanic**
When passing USE_PULLED_IMAGE=yes to the containerized-test or
containerized-build make targets, it is now possible to use pre-pulled
container images. This saves time as the container images will not get
created from scratch.

updates: #1628

### CODE REVIEW

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.18

CI failure for **ci/centos/mini-e2e-helm/k8s-1.18** has been reported in #1636.

**Review by Madhu-1 — APPROVED** [review]

**Pull request merged**
