### PR TITLE
 fix helm value pullPolicy mismatch bug

### PR DESCRIPTION
**Pull request by MiaoZhou**
change all `imagePullPolicy` to `pullPolicy` for consistency

### CODE REVIEW

**Comment by kfox1111** [comment]
Agree on the version bump, but this is an incompatible change, so at least a minor version bump, not patch please.

**Comment by ShyamsundarR** [comment]
> Agree on the version bump, but this is an incompatible change, so at least a minor version bump, not patch please.

Interesting, I need to learn more about incompatible changes. @kfox1111 poking you for a quick explanation of why this is an incompatible change?

**Comment by kfox1111** [comment]
The helm folks convention likes to stick closish to semver but seem to have relaxed it a little bit in practice...

They usually do:
Major is large change.
Minor is a technically breaking change, though very minor. So, like this, changing the pull policy variable is a user facing breaking change, but its tiny and won't effect most people.
Patch, totally safe to go from one patch release to another without the user noticing.

Proper semver interpretation would be to bump the major version for this change as it really is an api change. That is technically the right thing to do.

**Comment by MiaoZhou** [comment]
`pullPolicy` is the only key used in current two `values.yaml` file

Helm template engine will produce an empty `imagePullPolicy: ` for those *.yaml files.
Then k8s automatically set it to `IfNotPresent`, because it is the default pull policy in k8s.

No matter what value user sets for `pullPolicy`, no effect.

**Comment by ShyamsundarR** [comment]
> `pullPolicy` is the only key used in current two `values.yaml` file
> 
> Helm template engine will produce an empty `imagePullPolicy: ` for those *.yaml files.
> Then k8s automatically set it to `IfNotPresent`, because it is the default pull policy in k8s.
> 
> No matter what value user sets for `pullPolicy`, no effect.

Considering this we would need to update the patch number at least? @MiaoZhou @kfox1111 

Interestingly I hit the same issue yesterday, and yes it is defaulted to `IfNotPresent` when the variable is missing from the template.

**Comment by kfox1111** [comment]
Oh, I didn't realize that the issue was the api was actually broken (values not matching whats used in the templates). I was thinking it was a rename of the values. As it never worked, there shouldn't be users of it, so its not a breaking change to actually fix it. So bumping the patch version might be considered ok as its a pure bug fix. Or you could look at it as adding a new feature that didn't exist before (because it was broken) and then it would be a minor version bump. I'm good with either.

**Comment by rootfs** [comment]
@kfox1111 thanks @MiaoZhou let's go with a minor version bump (so it can be pushed to helm hub)

**Comment by ShyamsundarR** [comment]
@MiaoZhou request a port of the changes to master branch as well or, let me know and I can ensure the same. Thanks!

**Comment by kfox1111** [comment]
hmm.... what is the difference  between master and csi-v1.0 at this point?

**Comment by ShyamsundarR** [comment]
master is the forward looking branch, and csi-v1.0 is the current 1.0.0 branch. So master needs to have all fixes, for future releases to not miss out any.

At this point afaik functionally the both should be equal, but 2 PRs are missing against master.

Issue to change the default branch to master is still open #308

**Comment by MiaoZhou** [comment]
@ShyamsundarR got it, i'll create another PR.

**Comment by humblec** [comment]
>@ShyamsundarR got it, i'll create another PR.
@MiaoZhou this is taken care by https://github.com/ceph/ceph-csi/pull/363

**Pull request merged**
