### PR TITLE
Default to 2 approvals for a patch to get in

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@Madhu-1 @gman0 PTAL :)

**Comment by Madhu-1** [comment]
@ShyamsundarR @rootfs @leseb

**Comment by ShyamsundarR** [comment]
I have an additional suggestion, this patch itself proving to be the example for the same.

Is there a way to check age of a patch before it is merged? IOW, wait for 48h/72h before it is merged, so that folks have had a chance to look at it and state any comments if need be.

Current scheme makes it so that every patch should be looked at asap, which is not easy to do in all situations.

**Comment by Madhu-1** [comment]
@ShyamsundarR i don't see a rule in `mergify.io` to wait for 48/72 hours. please let me know if something like that is present we can update `mergify` rules.

**Comment by leseb** [comment]
@ShyamsundarR 2 approvals should be enough at this point and we can't delay the merge on purpose so that **everyone** can look at it. If you're looking for someone's attention, in particular, you can ask them a review of the GitHub interface. Or at the last resort, you can apply the DNM label so that mergify won't merge it.

**Comment by ShyamsundarR** [comment]
> @ShyamsundarR 2 approvals should be enough at this point and we can't delay the merge on purpose so that **everyone** can look at it. If you're looking for someone's attention, in particular, you can ask them a review of the GitHub interface. Or at the last resort, you can apply the DNM label so that mergify won't merge it.

It is not about **everyone** or lack of enough approvals here, but giving others a chance (in this case time) at least to look at things before a merge. The way it is setup now, merges can happen in minutes.

Getting someone's attention is orthogonal to the problem I have, which is being interested or wanting to pay attention, so what you suggest around tagging others is always a possibility, but not what I am looking for. For example, I was tagged on this, but never got a chance to speak up (now if I do not speak up in time 't' then that is my doing, and the PR should not wait for the same is right)

Finally, critical patches or patches that are deemed to be merged ASAP can always be done my maintainer (IMO) outside the scope of the auto-merge engine, i.e manually.

BUT, if current status is what maintainers prefer, I am not going to push my point (also we do not have an merge engine that can honor time yet to make it happen).

**Comment by leseb** [comment]
@ShyamsundarR I understand, what about applying the DNM label then?

**Comment by ShyamsundarR** [comment]
> @ShyamsundarR I understand, what about applying the DNM label then?

That is a useful way to temporarily block a merge, and possibly clarifying (with a comment) that you need a day or 2 to review and are interested. It does not prevent things from being merged when you are asleep though :) but, that needs to be tackled opening a new issue or such, to deal with the review/disagreement.

But, **I** cannot apply these labels, as I do not have enough rights in this project, but as long as other who have the rights agree, it is fine by me.

NOTE: As an aside, any auto-merge engine is not going to run 'cron' like jobs to detect age and merge (unless we run our own Jenkins instance (say) to auto-merge, which seems a bit too much to solve this problem), it is mostly going to act on triggers that are generated by events on a patch, and age is not one such event afaict, so I do not expect the various github integrated auto-merge engines out there to have this feature in the first place. Hence, merge based on age may not be an option to begin with.

**Pull request merged**
