### PR TITLE
Update templates for v3.5.1 release

### LINKED ISSUE #2803: Release 3.5.1 plan
This issue is to track the 3.5.1 release which includes a couple of enhancements backported to the release-3.5 branch

backported PR's list
- [ ] https://github.com/ceph/ceph-csi/pull/2790
- [ ] https://github.com/ceph/ceph-csi/pull/2802
- [ ] https://github.com/ceph/ceph-csi/issues/2521 includes fix for parallel PVC creation issue.

Planned release date:- 21/01/2021

cc @ceph/ceph-csi-maintainers

### PR DESCRIPTION
**Pull request by Madhu-1**
This PR updates the required template changes for the v3.5.1 release.

closes: #2803 

Depends-On: #2802 

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Review by Rakshith-R — APPROVED** [review]

**Review by yati1998 — APPROVED** [review]

**Review by Yuggupta27 — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Comment by Madhu-1** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.22


```
[],Capacity:ResourceList{},Conditions:[]PersistentVolumeClaimCondition{},AllocatedResources:ResourceList{},ResizeStatus:nil,},} to be in Bound state

Jan 21 14:32:57.367: INFO: waiting for PVC rbd-13185 (0 seconds elapsed)

Cannot contact cico-workspace-8lpsn: hudson.remoting.RequestAbortedException: java.nio.channels.ClosedChannelException
``` 
CI problem

**Comment by Madhu-1** [comment]
> /retest all

due to Jenkins restart all tests are kind of stuck

**Comment by nixpanic** [comment]
> /retest ci/centos/k8s-e2e-external-storage/1.22

Failed to connect to Jenkins.

**Comment by Madhu-1** [comment]
> /test ci/centos/mini-e2e-helm/k8s-1.21

```
Jan 21 17:16:18.264: backend images not matching kubernetes resource count,image count 22 kubernetes resource count 21

    backend image Info:

     [csi-vol-c17ba725-7add-11ec-a1f6-16c445a80310 csi-vol-c338f1cf-7add-11ec-a1f6-16c445a80310 csi-vol-c338f1cf-7add-11ec-a1f6-16c445a80310-temp csi-vol-c36f8d01-7add-11ec-a1f6-16c445a80310 csi-vol-c36f8d01-7add-11ec-a1f6-16c445a80310-temp csi-vol-c38f12e6-7add-11ec-a1f6-16c445a80310-temp csi-vol-c3c80975-7add-11ec-a1f6-16c445a80310 csi-vol-c3c80975-7add-11ec-a1f6-16c445a80310-temp csi-vol-c4037d52-7add-11ec-a1f6-16c445a80310 csi-vol-c4037d52-7add-11ec-a1f6-16c445a80310-temp csi-vol-c41f7365-7add-11ec-a1f6-16c445a80310 csi-vol-c41f7365-7add-11ec-a1f6-16c445a80310-temp csi-vol-c6fc8c3b-7add-11ec-a1f6-16c445a80310 csi-vol-c6fc8c3b-7add-11ec-a1f6-16c445a80310-temp csi-vol-c739d91c-7add-11ec-a1f6-16c445a80310 csi-vol-c739d91c-7add-11ec-a1f6-16c445a80310-temp csi-vol-c7568ee9-7add-11ec-a1f6-16c445a80310 csi-vol-c7568ee9-7add-11ec-a1f6-16c445a80310-temp csi-vol-c77ebf3d-7add-11ec-a1f6-16c445a80310 csi-vol-c77ebf3d-7add-11ec-a1f6-16c445a80310-temp csi-vol-caf6ba68-7add-11ec-a1f6-16c445a80310 csi-vol-caf6ba68-7add-11ec-a1f6-16c445a80310-temp]

```

**Comment by Madhu-1** [comment]
@mergifyio refresh

**Pull request merged**
