### PR TITLE
ci: prepare for 3.12.3 release

### PR DESCRIPTION
**Pull request by Madhu-1**
This commit is a preparation for the 3.12.3 release

### CODE REVIEW

**Review by yati1998 — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
it seems 512bba485b needs to be backported to address the protobuf installation

**Comment by Madhu-1** [comment]
@mergifyio queue

**Comment by Madhu-1** [comment]
@mergifyio queue

**Comment by Madhu-1** [comment]
@mergifyio refresh

**Pull request merged**
