### PR TITLE
Add xfs fstype as default type in storageclass

### PR DESCRIPTION
**Pull request by Madhu-1**
we have seen better performance in device format and mounting by setting the fstype to xfs from default ext4.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

Fixes: #507

Note: #537 will be used for testing CI

### CODE REVIEW

**Comment by Madhu-1** [comment]
not a good idea to default it in code, we should give the flexibility to use to select ext4 or xfs or other formats, as in storage class will ask the user to use xfs for better performance.

**Comment by humblec** [comment]
LGTM. Approved.

**Comment by ShyamsundarR** [comment]
> not a good idea to default it in code, we should give the flexibility to use to select ext4 or xfs or other formats, as in storage class will ask the user to use xfs for better performance.

I meant change the current default in code from `ext4` to `xfs`, we will still retain the ability to mention either or totally another file system in its place.

It avoids the need to mention this in the storageclass as we are overriding the default.

**Comment by Madhu-1** [comment]
> > not a good idea to default it in code, we should give the flexibility to use to select ext4 or xfs or other formats, as in storage class will ask the user to use xfs for better performance.
> 
> I meant change the current default in code from `ext4` to `xfs`, we will still retain the ability to mention either or totally another file system in its place.
> 
> It avoids the need to mention this in the storageclass as we are overriding the default.

in code where? rbd nodeplugin?

**Comment by ShyamsundarR** [comment]
> > > not a good idea to default it in code, we should give the flexibility to use to select ext4 or xfs or other formats, as in storage class will ask the user to use xfs for better performance.
> > 
> > 
> > I meant change the current default in code from `ext4` to `xfs`, we will still retain the ability to mention either or totally another file system in its place.
> > It avoids the need to mention this in the storageclass as we are overriding the default.
> 
> in code where? rbd nodeplugin?

Yes, currently we do not check if passed in fsType is empty and set a default, leaving the mount package to set it for us (which defaults to ext4). Instead if we wanted **our** default to be xfs, and not miss it in case users failed to specify the same in the storage class, we could add it to our code.

In any case, please note that I am not nack'ing this PR, it is a suggestion to set favorable defaults for rbd instead of pushing the onus to the user.

**Comment by humblec** [comment]
@ShyamsundarR it was actually discussed and agree that, if we can make  `xfs` from our code as default, lets handle it.

**Comment by Madhu-1** [comment]
fstype is set to ext4 if not passed either by Kube or  sidecar container, I can't remember Kube code check  sidecar code https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/controller/controller.go#L437

**Comment by Madhu-1** [comment]
@humblec @ShyamsundarR i sure that we will get ext4 as default during nodestage volume.  if you want I can test and confirm that

**Comment by ShyamsundarR** [comment]
> @humblec @ShyamsundarR i sure that we will get ext4 as default during nodestage volume. if you want I can test and confirm that

Looks like there is no option to control this in the sidecar, maybe this is a case to request addition of on in the kubernetes csi repository for use?

**Comment by humblec** [comment]
> @humblec @ShyamsundarR i sure that we will get ext4 as default during nodestage volume. if you want I can test and confirm that>

Sure. I think I was not clear in my last comment. The external provisioner definitely set it to `ext4` as we discussed and verified from code. What I was trying to convey here was, afacit, setting the SC parameter with `xfs` as the default option is the only option we could use, which this PR does.

**Comment by humblec** [comment]
@Madhu-1 can you open an issue in external provisioner with a request that, is there any way SP can set this regardless or by neglecting SC option ? I see less possibility to get it acked though.

**Comment by ShyamsundarR** [comment]
> @Madhu-1 can you open an issue in external provisioner with a request that, is there any way SP can set this regardless or by neglecting SC option ? I see less possibility to get it acked though.

I am not stating to **neglect** the SC option, that should be honored and not ignored. I am stating we ask for an option to set the default fsType and not default to xfs in the sidecar.

**Comment by Madhu-1** [comment]
> @Madhu-1 can you open an issue in external provisioner with a request that, is there any way SP can set this regardless or by neglecting SC option ? I see less possibility to get it acked though.

same here let's see if Kube-csi accepts.

**Comment by humblec** [comment]
> > @Madhu-1 can you open an issue in external provisioner with a request that, is there any way SP can set this regardless or by neglecting SC option ? I see less possibility to get it acked though.
> 
> same here let's see if Kube-csi accepts.

Yeah.. may be an arg to sidecar as we have `--timeout`, but I doubt it will be accepted as there will be many options which can be configured this way, but we can not have cli args for everything.  But. lets give a try :)

**Pull request merged**
