### PR TITLE
refact: namespace all labels in the helm charts

### PR DESCRIPTION
**Pull request by wilmardo**
# Describe what this PR does #

* Removes heritage and release label
* Renames:
  * app > app.kubernetes.io/name
   * chart > helm.sh/chart:
   * component > app.kubernetes.io/component
* Adds:
   * app.kubernetes.io/managed-by label
  * app.kubernetes.io/managed-by

This results in the following labels:

```yaml
    labels:
      app.kubernetes.io/component: provisioner
      app.kubernetes.io/instance: ceph-csi-rbd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ceph-csi-rbd
      app.kubernetes.io/version: canary
      helm.sh/chart: ceph-csi-rbd-1.3.0-canary
```

## Is there anything that requires special attention ##

The change isn't backwards compatible, helm upgrade will fail since labels are immutable after an deployment:
```console
# helm upgrade ceph-csi-rbd charts/ceph-csi-rbd --namespace storing
Error: UPGRADE FAILED: cannot patch "ceph-csi-rbd-nodeplugin" with kind DaemonSet: DaemonSet.apps "ceph-csi-rbd-nodeplugin" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"nodeplugin", "app.kubernetes.io/instance":"ceph-csi-rbd", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"ceph-csi-rbd", "app.kubernetes.io/version":"canary"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && cannot patch "ceph-csi-rbd-provisioner" with kind Deployment: Deployment.apps "ceph-csi-rbd-provisioner" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"provisioner", "app.kubernetes.io/instance":"ceph-csi-rbd", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"ceph-csi-rbd", "app.kubernetes.io/version":"canary"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

Can be resolved by uninstalling the current release and redeploying with the same values but this should be mentioned and this must be a major Helm chart release.

## Related issues ##

Fixes: #612

### CODE REVIEW

**Comment by Madhu-1** [comment]
if you are using cephfs fuse client or rbd-nbd driver, This could be an issue as we need to delete the daemonset of both cephfs and rbd (all mounts inside the daemonset container will be gone  you will see transport endpoint not connected issues) https://github.com/ceph/ceph-csi/issues/703

we need to document the step on how to do upgrade for the same

**Comment by wilmardo** [comment]
@Madhu-1 Are the upgrade scenarios described in #770?

**Comment by Madhu-1** [comment]
@wilmardo we need to add a document for the upgrade with helm charts

**Comment by humblec** [comment]
@wilmardo can you rebase this PR ?

**Comment by wilmardo** [comment]
@humblec Will do in the next couple days :)

**Comment by humblec** [comment]
@wilmardo I hope we are progressing on this :) .

**Comment by wilmardo** [comment]
@Madhu-1 Thanks for the reminder, working on it as we speak. Rebased to current master but found some missed values when reviewing myself, on it as we speak!

**Comment by humblec** [comment]
@wilmardo Thanks ! :) , iic the last comment was for me .

**Comment by humblec** [comment]
@wilmardo may be little more efforts to make CI happy ? :)

**Comment by wilmardo** [comment]
@humblec Done, didn't notice that the CI failed :+1:

**Comment by humblec** [comment]
> @humblec Done, didn't notice that the CI failed +1

Cool. thanks . The PR looks good to me ! LGTM.

**Comment by humblec** [comment]
@Madhu-1 ptal .

**Comment by Madhu-1** [comment]
This is a breaking change, we need upgrade doc for this one and we cannot track this for 2.1.0

**Comment by Madhu-1** [comment]
this is a breaking change we need to see what we can do on this one. @nixpanic any suggestion from your side on this one?

**Comment by nixpanic** [comment]
@wilmardo could you write down your recommendation for upgrading a current deployment to the new label/format?

**Comment by humblec** [comment]
@wilmardo ping .. revisit?

**Comment by wilmardo** [comment]
Yeah busy with work and not that much time for open source at the moment. 

Don't know if there is an casual upgrade path for this, Kubernetes sees these labels as immutable so it will error on trying to upgrade.
I don't know if it is feasible to remove and reinstall for user?

**Comment by Madhu-1** [comment]
> Yeah busy with work and not that much time for open source at the moment.
> 
> Don't know if there is an casual upgrade path for this, Kubernetes sees these labels as immutable so it will error on trying to upgrade.
> I don't know if it is feasible to remove and reinstall for user?

Thanks for the reply @wilmardo even I have the same concern as it's not feasible to reinstall the whole cluster

**Comment by wilmardo** [comment]
Might be something for the 3.x.x release then?
I deleted and redeployed my ceph pods without problems in the past, since the PV and PVC keep existing for the current pods I had no downtime.
Needs testing though, it has been sometime since I have done that so my memory might be incorrect.

**Comment by Madhu-1** [comment]
> Might be something for the 3.x.x release then?
> I deleted and redeployed my ceph pods without problems in the past, since the PV and PVC keep existing for the current pods I had no downtime.
> Needs testing though, it has been sometime since I have done that so my memory might be incorrect.

looks like we can do it. but it will be a  downtime for the user. application pods cannot use PVC during the upgrade as we are deleting and recreating all the cephcsi pods. if we can add documentation for the upgrade we can do it. 
as you said we need good testing for it for  both cephfs and rbd.

**Comment by Madhu-1** [comment]
moved this out of release-v3.0.0 milestone

**Comment by Madhu-1** [comment]
> > Might be something for the 3.x.x release then?
> > I deleted and redeployed my ceph pods without problems in the past, since the PV and PVC keep existing for the current pods I had no downtime.
> > Needs testing though, it has been sometime since I have done that so my memory might be incorrect.
> 
> looks like we can do it. but it will be a downtime for the user. application pods cannot use PVC during the upgrade as we are deleting and recreating all the cephcsi pods. if we can add documentation for the upgrade we can do it.
> as you said we need good testing for it for both cephfs and rbd.

@wilmardo any comment on this one?

**Pull request closed without merging**
