### PR TITLE
helm: Allow templating of RBD striping parameters

### PR DESCRIPTION
**Pull request by KingJ**
# Describe what this PR does #

PR https://github.com/ceph/ceph-csi/pull/3132 added support for specifying `stripeUnit`, `stripeCount` and `objectSize` as storageClass parameters. However, these parameters were not added to storageClass templated by the Helm Chart at the time. A user who uses the Helm Chart to deploy `ceph-csi-rbd` could therefore only set these parameters if they managed the storageClass separately. 

This PR therefore adds optional support for specifying `stripeUnit`, `stripeCount` and `objectSize` as parameters to the storageClass templated by the `ceph-csi-rbd` Helm Chart.

The descriptions for each option are taken from the "Available volume parameters" section of the [RBD deployment docs](https://github.com/ceph/ceph-csi/blob/devel/docs/deploy-rbd.md), and extended slightly to reference the upstream Ceph documentation.

## Is there anything that requires special attention ##

I've tried to keep the ordering of the new Helm Values similar to the ordering in the RBD deployment docs, however there are already a few inconsistencies. I'm happy to adjust the ordering if needed.

**Checklist:**

* [x] **Commit Message Formatting**: Commit titles and messages follow
  guidelines in the [developer guide](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#commit-messages).
* [x] Reviewed the developer guide on [Submitting a Pull Request](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#development-workflow)
* [ ] [Pending release notes](https://github.com/ceph/ceph-csi/blob/devel/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next major release.
* [ ] Documentation has been updated, if necessary.
* [ ] Unit tests have been added, if necessary.
* [ ] Integration tests have been added, if necessary.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

* `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

### CODE REVIEW

**Review by Rakshith-R — APPROVED** [review]

**Review by riya-singhal31 — APPROVED** [review]

**Comment by riya-singhal31** [comment]
@Mergifyio queue

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio queue

**Comment by nixpanic** [comment]
@mergifyio requeue

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio queue

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e/k8s-1.26

unrelated failure:
```
  [FAILED] failed to validate rbd images in pool replicapool trash: failed to list images in trash 2023-11-09T08:10:35.922+0000 7fbabb115700 -1 monclient: handle_auth_reply_more no authorizer?
```
[logs](https://jenkins-ceph-csi.apps.ocp.cloud.ci.centos.org/job/mini-e2e_k8s-1.26/687/display/redirect)

**Comment by nixpanic** [comment]
@mergifyio requeue

**Pull request merged**
