### PR TITLE
ci: improve rules for commitlint

### PR DESCRIPTION
**Pull request by pkalever**
# Describe what this PR does #
Add a few more rules, like:
* subject cannot be empty
* body shouldn't be empty
* avoid body line length over 80 characters (warning only)
* always sign-off the commit msg
* disable scopes rule

Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

### CODE REVIEW

**Comment by nixpanic** [comment]
Something isn't right here:
```
$ commitlint-travis

⧗   input: ci: fix typo in commitlintrc.yml

fix typo at code comments in commitlintrc.yml

Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

✖   subject must be empty [subject-empty]

✖   found 1 problems, 0 warnings

ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

⧗   input: ci: disable scope-empty rule in commitlint

we do not use scopes for commit messages

Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

✖   subject must be empty [subject-empty]

✖   found 1 problems, 0 warnings

ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

⧗   input: ci: improve rules for commitlint

Add few more rules, like:

* subject cannot be empty

* body shouldn't be empty

* avoid body line length over 80 characters (warning only)

* always sign-off the commit msg

Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

✖   subject must be empty [subject-empty]

✖   found 1 problems, 0 warnings

ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

**Comment by nixpanic** [comment]
You can also run this locally: `make containerized-test TARGET=commitlint`

**Comment by pkalever** [comment]
> You can also run this locally: `make containerized-test TARGET=commitlint`

Thanks @nixpanic will run locally and fix.

**Comment by pkalever** [comment]
JFYI: @nixpanic `body-min-length` is not working as I expect it to be :-(

```
<type>[optional scope]: <subject>

<optional body>

<optional footer>
```

I wanted it to error out if the body is empty. But it is trying to find minimum body **line** length rather than minimum body length.

**Comment by Madhu-1** [comment]
@pkalever DCO bot is already validating the sign-off do we need to do it again?

**Comment by nixpanic** [comment]
> @pkalever DCO bot is already validating the sign-off do we need to do it again?

I think it does not hurt, and we might want to move to a full commitlint job at one point, removing some load from Travis CI. This requires the container image that we use for testing to be built once )with an OpenShift BuildConfig+ImageStream), and reused instead of building it for each job though.

**Review by nixpanic — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Pull request merged**
