### PR TITLE
ci: update minikube to v1.28.0

### PR DESCRIPTION
**Pull request by Madhu-1**
update minikube to the latest available release.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Review by nixpanic — DISMISSED** [review]

**Review by humblec — DISMISSED** [review]

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by humblec** [comment]
@Madhu-1 I dont see any change in the last push. What caused the refresh?

**Review by humblec — APPROVED** [review]

**Comment by Madhu-1** [comment]
> @Madhu-1 I dont see any change in the last push. What caused the refresh?

GitHub actions were not started, needed a force push

**Comment by Madhu-1** [comment]
Will rebase this one https://github.com/ceph/ceph-csi/pull/3505 is merged

**Review by Rakshith-R — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Pull request merged**
