### PR TITLE
rebase: update minikube to v1.20.0

### PR DESCRIPTION
**Pull request by nixpanic**
No major changes, but adds support for Kubernetes v1.22.0-alpha-1.

See-also: https://github.com/kubernetes/minikube/releases/tag/v1.20.0

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

**Review by Madhu-1 — APPROVED** [review]

**Comment by humblec** [comment]
> No major changes, but adds support for Kubernetes v1.22.0-alpha-1.
> 
> See-also: https://github.com/kubernetes/minikube/releases/tag/v1.20.0
> Show available bot commands

hmmm.. just to put on a thought, do we need to add a version which support alpha?

**Comment by Madhu-1** [comment]
> > No major changes, but adds support for Kubernetes v1.22.0-alpha-1.
> > See-also: https://github.com/kubernetes/minikube/releases/tag/v1.20.0
> > Show available bot commands
> 
> hmmm.. just to put on a thought, do we need to add a version which support alpha?

AFAIK we are not adding E2E for the alpha Kubernetes version as mandatory for all PR's, as this is a release in minikube this is getting added (it might have bug fixes and enhancements, alpha support is not the main reason but good to have as we can have some admin started E2E to test early releases of 1.22 to make sure everything is working fine.)

**Comment by humblec** [comment]
> > > No major changes, but adds support for Kubernetes v1.22.0-alpha-1.
> > > See-also: https://github.com/kubernetes/minikube/releases/tag/v1.20.0
> > > Show available bot commands
> > 
> > 
> > hmmm.. just to put on a thought, do we need to add a version which support alpha?
> 
> AFAIK we are not adding E2E for the alpha Kubernetes version as mandatory for all PR's, as this is a release in minikube this is getting added (it might have bug fixes and enhancements, alpha support is not the main reason but good to have as we can have some admin started E2E to test early releases of 1.22 to make sure everything is working fine.)

But PR title dont say about many major changes/bug fixes, rather the only mention of alpha support.

**Comment by Madhu-1** [comment]
> > > > No major changes, but adds support for Kubernetes v1.22.0-alpha-1.
> > > > See-also: https://github.com/kubernetes/minikube/releases/tag/v1.20.0
> > > > Show available bot commands
> > > 
> > > 
> > > hmmm.. just to put on a thought, do we need to add a version which support alpha?
> > 
> > 
> > AFAIK we are not adding E2E for the alpha Kubernetes version as mandatory for all PR's, as this is a release in minikube this is getting added (it might have bug fixes and enhancements, alpha support is not the main reason but good to have as we can have some admin started E2E to test early releases of 1.22 to make sure everything is working fine.)
> 
> But PR title dont say about many major changes/bug fixes, rather the only mention of alpha support.

usually, we don't mention the bug fixes/changes when we update any dependency. if there are any major releases we update the version to be on the latest releases.

**Comment by humblec** [comment]
> > > > > No major changes, but adds support for Kubernetes v1.22.0-alpha-1.
> > > > > See-also: https://github.com/kubernetes/minikube/releases/tag/v1.20.0
> > > > > Show available bot commands
> > > > 
> > > > 
> > > > hmmm.. just to put on a thought, do we need to add a version which support alpha?
> > > 
> > > 
> > > AFAIK we are not adding E2E for the alpha Kubernetes version as mandatory for all PR's, as this is a release in minikube this is getting added (it might have bug fixes and enhancements, alpha support is not the main reason but good to have as we can have some admin started E2E to test early releases of 1.22 to make sure everything is working fine.)
> > 
> > 
> > But PR title dont say about many major changes/bug fixes, rather the only mention of alpha support.
> 
> usually, we don't mention the bug fixes/changes when we update any dependency. if there are any major releases we update the version to be on the latest releases.

The E2E is yet to be enabled or adopted 1.21 version, not sure why we have to be hurry on this. More or less, imo, the dependency update of libraries or components here has to follow some method, as it has been zig zag model in the past with questions/exceptions here and there. :).

**Comment by nixpanic** [comment]
> hmmm.. just to put on a thought, do we need to add a version which support alpha?

Yes, I would like to have that as an optional job. We did not run tests with Kubernetes 1.21 early enough, and now we need to catchup for **ci/centos/k8s-e2e-external-storage/1.21** (see #2017).

Once this is merged, we can at least manually run e2e tests with the upcoming Kubernetes version.

**Comment by nixpanic** [comment]
Manually started a run with Kubernetes 1.22, this might fail deploying with Minikube as this PR is not merged yet.

https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.20/detail/mini-e2e_k8s-1.20/826/pipeline/17

**Review by humblec — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
> /retest ci/centos/upgrade-tests-rbd

#1969 was hit

**Pull request merged**
