### PR TITLE
build: update kube dependency to v1.19.0

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

Note for reviewer: We could either update to the latest version of 1.18 or I can adopt 1.19 as soon as the release is out.  Let me know the choice accordingly I will update the PR.

### CODE REVIEW

**Comment by humblec** [comment]
@Madhu-1 sure. will get on 1.19.

**Comment by nixpanic** [comment]
> @Madhu-1 sure. will get on 1.19.

Please also add CI jobs for 1.19 when it is out.

**Comment by Madhu-1** [comment]
>go test -tags=octopus -mod=vendor -c ./e2e
# k8s.io/kubernetes/pkg/serviceaccount
vendor/k8s.io/kubernetes/pkg/serviceaccount/claims.go:93:27: cannot use jwt.NewNumericDate(now.Add(time.Duration(warnafter) * time.Second)) (type *jwt.NumericDate) as type jwt.NumericDate in assignment

CI failure

**Pull request closed without merging**
