### PR TITLE
build: remove travis CI scripts for functest and helm

### PR DESCRIPTION
**Pull request by humblec**
considering we have moved out of travis and replaced github action, this commit remove the functional test and helmtest scripts.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Review by Rakshith-R — APPROVED** [review]

**Comment by Madhu-1** [comment]
@humblec We can run only a few parallel CI jobs in centos. please dont add `ok-to-test` labels on any of the PR until it's rebased/very critical/ have required 2 approvals to avoid a CI outage.

**Review by Madhu-1 — APPROVED** [review]

**Pull request merged**
