### PR TITLE
rebase: update go-ceph version to v0.11.0

### PR DESCRIPTION
**Pull request by humblec**
This lift the go-ceph dependency to v0.11.0.
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Review by nixpanic — DISMISSED** [review]
not sure why there are references removed from `go.sum`, but as long as the `mod-verify` CI tests  do not complain, it should be fine.

**Review by yati1998 — APPROVED** [review]

**Review by Madhu-1 — DISMISSED** [review]

**Comment by humblec** [comment]
Adding `DNM` just to get in kube dependency PR first which can introduce conflicts here.

**Comment by nixpanic** [comment]
Dropping `[DNM]` as `Depends-on: ` in the PR description creates the merge dependency.

**Review by nixpanic — APPROVED** [review]

**Comment by humblec** [comment]
@Madhu-1 can you please bring back the lgtm ?

**Comment by humblec** [comment]
@nixpanic considering this is just a rebase, may be add `ready-to-merge` label here ?

**Review by Madhu-1 — APPROVED** [review]

**Pull request merged**
