### PR TITLE
cephfs: fix logic to call ceph fs resize

### LINKED ISSUE #1732: CephFS CSI Resize feature not working (again ;(
# Describe the bug #

Change storage size in pvc from 5G to 7G, pv and pvc object in kubernetes changed

```
k get pvc -n default
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS    AGE
csi-cephfs-pvc   Bound    pvc-397b10cf-c546-45e2-9a3d-55a888e55456   7Gi        RWX            csi-cephfs-sc   83m

k get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                    STORAGECLASS    REASON   AGE
pvc-397b10cf-c546-45e2-9a3d-55a888e55456   7Gi        RWX            Delete           Bound       default/csi-cephfs-pvc   csi-cephfs-sc            83m
```

but quota on cephfs directory not changed
```
getfattr -n ceph.quota.max_bytes 6733a289-beb6-4446-8c3d-c5422b4876f1/
# file: 6733a289-beb6-4446-8c3d-c5422b4876f1/
ceph.quota.max_bytes="5368709120"
```

# Environment details #

- Image/version of Ceph CSI driver :
    image: quay.io/cephcsi/cephcsi:v3.1.2
- Helm chart version :
ceph-csi-cephfs-3.1.2   v3.1.2
- Kernel version :
Centos 7, 4.20.13-1.el7.elrepo.x86_64
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its  `krbd` or `rbd-nbd`) :
kernel
- Kubernetes cluster version :
v 1.18.3
- Ceph cluster version :
14.2.9

# Steps to reproduce #

install csi cephfs driver from helm chart 3.1.2
config storage class
create pvc, wait for pv
change request storage size in pvc - look on cephfs quotas

# Actual results #

quota on cephfs directory not changed

# Expected behavior #

Quota must set to 7G

# Logs #

csi-resizer logs look fine:
```
I1129 11:03:57.196526       1 controller.go:225] Started PVC processing "default/csi-cephfs-pvc"
I1129 11:03:57.211663       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"csi-cephfs-pvc", UID:"397b10cf-c546-45e2-9a3d-55a888e55456", APIVersion:"v1", ResourceVersion:"11514", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-397b10cf-c546-45e2-9a3d-55a888e55456
I1129 11:03:57.219248       1 connection.go:182] GRPC call: /csi.v1.Controller/ControllerExpandVolume
I1129 11:03:57.219261       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":7516192768},"secrets":"***stripped***","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["debug"]}},"access_mode":{"mode":5}},"volume_id":"0001-0024-ad2326f4-56f8-4c32-9dd3-fa0b20ff2137-0000000000000001-1544255a-3232-11eb-bc25-e28d5116787b"}
I1129 11:03:59.035498       1 leaderelection.go:283] successfully renewed lease ceph-csi-cephfs/external-resizer-cephfs-csi-ceph-com
I1129 11:03:59.488737       1 connection.go:185] GRPC response: {"capacity_bytes":7516192768}
I1129 11:03:59.489756       1 connection.go:186] GRPC error: <nil>
I1129 11:03:59.489774       1 controller.go:364] Resize volume succeeded for volume "pvc-397b10cf-c546-45e2-9a3d-55a888e55456", start to update PV's capacity
I1129 11:03:59.503991       1 controller.go:370] Update capacity of PV "pvc-397b10cf-c546-45e2-9a3d-55a888e55456" to 7Gi succeeded
I1129 11:03:59.509733       1 controller.go:399] Resize PVC "default/csi-cephfs-pvc" finished
I1129 11:03:59.509768       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"csi-cephfs-pvc", UID:"397b10cf-c546-45e2-9a3d-55a888e55456", APIVersion:"v1", ResourceVersion:"11514", FieldPath:""}): type: 'Normal' reason: 'VolumeResizeSuccessful' Resize volume succeeded
```

*csi-cephfsplugin* log is very interesting !

```
I1129 11:03:57.222577       1 utils.go:159] ID: 23 Req-ID: 0001-0024-ad2326f4-56f8-4c32-9dd3-fa0b20ff2137-0000000000000001-1544255a-3232-11eb-bc25-e28d5116787b GRPC call: /csi.v1.Controller/ControllerExpandVolume
I1129 11:03:57.225676       1 utils.go:160] ID: 23 Req-ID: 0001-0024-ad2326f4-56f8-4c32-9dd3-fa0b20ff2137-0000000000000001-1544255a-3232-11eb-bc25-e28d5116787b GRPC request: {"capacity_range":{"required_bytes":7516192768},"secrets":"***stripped***","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["debug"]}},"access_mode":{"mode":5}},"volume_id":"0001-0024-ad2326f4-56f8-4c32-9dd3-fa0b20ff2137-0000000000000001-1544255a-3232-11eb-bc25-e28d5116787b"}
I1129 11:03:57.756015       1 cephcmds.go:59] ID: 23 Req-ID: 0001-0024-ad2326f4-56f8-4c32-9dd3-fa0b20ff2137-0000000000000001-1544255a-3232-11eb-bc25-e28d5116787b command succeeded: ceph [-m 172.19.212.5:6789,172.19.212.6:6789,172.19.212.7:6789 --id fs --keyfile=***stripped*** -c /etc/ceph/ceph.conf fs dump --format=json]
I1129 11:03:58.200630       1 cephcmds.go:59] ID: 23 Req-ID: 0001-0024-ad2326f4-56f8-4c32-9dd3-fa0b20ff2137-0000000000000001-1544255a-3232-11eb-bc25-e28d5116787b command succeeded: ceph [-m 172.19.212.5:6789,172.19.212.6:6789,172.19.212.7:6789 --id fs --keyfile=***stripped*** -c /etc/ceph/ceph.conf fs ls --format=json]
I1129 11:03:58.202369       1 omap.go:84] ID: 23 Req-ID: 0001-0024-ad2326f4-56f8-4c32-9dd3-fa0b20ff2137-0000000000000001-1544255a-3232-11eb-bc25-e28d5116787b got omap values: (pool="cephfs_metadata", namespace="csi", name="csi.volume.1544255a-3232-11eb-bc25-e28d5116787b"): map[csi.imagename:csi-vol-1544255a-3232-11eb-bc25-e28d5116787b csi.volname:pvc-397b10cf-c546-45e2-9a3d-55a888e55456]
I1129 11:03:58.630651       1 cephcmds.go:53] ID: 23 Req-ID: 0001-0024-ad2326f4-56f8-4c32-9dd3-fa0b20ff2137-0000000000000001-1544255a-3232-11eb-bc25-e28d5116787b an error (exit status 22) and stdError (no valid command found; 10 closest matches:
fs subvolume ls <vol_name> [<group_name>]
fs subvolume create <vol_name> <sub_name> [<size:int>] [<group_name>] [<pool_layout>] [<uid:int>] [<gid:int>] [<mode>]
fs subvolume rm <vol_name> <sub_name> [<group_name>] [--force]
fs subvolume getpath <vol_name> <sub_name> [<group_name>]
fs subvolume snapshot ls <vol_name> <sub_name> [<group_name>]
fs subvolume snapshot create <vol_name> <sub_name> <snap_name> [<group_name>]
fs subvolume snapshot rm <vol_name> <sub_name> <snap_name> [<group_name>] [--force]
fs subvolume resize <vol_name> <sub_name> <new_size> [<group_name>] [--no-shrink]
fs subvolume snapshot protect <vol_name> <sub_name> <snap_name> [<group_name>]
fs subvolume snapshot unprotect <vol_name> <sub_name> <snap_name> [<group_name>]
Error EINVAL: invalid command
) occurred while running ceph args: [fs subvolume info cephfs csi-vol-1544255a-3232-11eb-bc25-e28d5116787b --group_name csi -m 172.19.212.5:6789,172.19.212.6:6789,172.19.212.7:6789 -c /etc/ceph/ceph.conf -n client.fs --keyfile=***stripped***]
E1129 11:03:58.630686       1 volume.go:109] ID: 23 Req-ID: 0001-0024-ad2326f4-56f8-4c32-9dd3-fa0b20ff2137-0000000000000001-1544255a-3232-11eb-bc25-e28d5116787b failed to get subvolume info csi-vol-1544255a-3232-11eb-bc25-e28d5116787b in fs cephfs with Error: an error (exit status 22) and stdError (no valid command found; 10 closest matches:
fs subvolume ls <vol_name> [<group_name>]
fs subvolume create <vol_name> <sub_name> [<size:int>] [<group_name>] [<pool_layout>] [<uid:int>] [<gid:int>] [<mode>]
fs subvolume rm <vol_name> <sub_name> [<group_name>] [--force]
fs subvolume getpath <vol_name> <sub_name> [<group_name>]
fs subvolume snapshot ls <vol_name> <sub_name> [<group_name>]
fs subvolume snapshot create <vol_name> <sub_name> <snap_name> [<group_name>]
fs subvolume snapshot rm <vol_name> <sub_name> <snap_name> [<group_name>] [--force]
fs subvolume resize <vol_name> <sub_name> <new_size> [<group_name>] [--no-shrink]
fs subvolume snapshot protect <vol_name> <sub_name> <snap_name> [<group_name>]
fs subvolume snapshot unprotect <vol_name> <sub_name> <snap_name> [<group_name>]
Error EINVAL: invalid command
) occurred while running ceph args: [fs subvolume info cephfs csi-vol-1544255a-3232-11eb-bc25-e28d5116787b --group_name csi -m 172.19.212.5:6789,172.19.212.6:6789,172.19.212.7:6789 -c /etc/ceph/ceph.conf -n client.fs --keyfile=***stripped***]. stdError: no valid command found; 10 closest matches:
fs subvolume ls <vol_name> [<group_name>]
fs subvolume create <vol_name> <sub_name> [<size:int>] [<group_name>] [<pool_layout>] [<uid:int>] [<gid:int>] [<mode>]
fs subvolume rm <vol_name> <sub_name> [<group_name>] [--force]
fs subvolume getpath <vol_name> <sub_name> [<group_name>]
fs subvolume snapshot ls <vol_name> <sub_name> [<group_name>]
fs subvolume snapshot create <vol_name> <sub_name> <snap_name> [<group_name>]
fs subvolume snapshot rm <vol_name> <sub_name> <snap_name> [<group_name>] [--force]
fs subvolume resize <vol_name> <sub_name> <new_size> [<group_name>] [--no-shrink]
fs subvolume snapshot protect <vol_name> <sub_name> <snap_name> [<group_name>]
fs subvolume snapshot unprotect <vol_name> <sub_name> <snap_name> [<group_name>]
Error EINVAL: invalid command
I1129 11:03:59.086690       1 cephcmds.go:59] ID: 23 Req-ID: 0001-0024-ad2326f4-56f8-4c32-9dd3-fa0b20ff2137-0000000000000001-1544255a-3232-11eb-bc25-e28d5116787b command succeeded: ceph [fs subvolume getpath cephfs csi-vol-1544255a-3232-11eb-bc25-e28d5116787b --group_name csi -m 172.19.212.5:6789,172.19.212.6:6789,172.19.212.7:6789 -c /etc/ceph/ceph.conf -n client.fs --keyfile=***stripped***]
I1129 11:03:59.487838       1 cephcmds.go:59] ID: 23 Req-ID: 0001-0024-ad2326f4-56f8-4c32-9dd3-fa0b20ff2137-0000000000000001-1544255a-3232-11eb-bc25-e28d5116787b command succeeded: ceph [fs subvolume create cephfs csi-vol-1544255a-3232-11eb-bc25-e28d5116787b 7516192768 --group_name csi --mode 777 -m 172.19.212.5:6789,172.19.212.6:6789,172.19.212.7:6789 -c /etc/ceph/ceph.conf -n client.fs --keyfile=***stripped***]
I1129 11:03:59.488396       1 utils.go:165] ID: 23 Req-ID: 0001-0024-ad2326f4-56f8-4c32-9dd3-fa0b20ff2137-0000000000000001-1544255a-3232-11eb-bc25-e28d5116787b GRPC response: {"capacity_bytes":7516192768}
```

# Additional context #
1. Command `fs subvolume info` added in 14.2.10, but my version of Ceph is 14.2.9

2. To change size of cephfs volume driver send command `fs subvolume create cephfs`, but for my ceph version command should be `fs subvolume resize` https://github.com/ceph/ceph-csi/issues/1002#issuecomment-624400342

### PR DESCRIPTION
**Pull request by Madhu-1**
clusterAdditionalInfo map is holding a localClusterState for checking ceph cluster supports resize and subvolumegroup is created or not, currently we are checking if the key is present in a map and localClusterStatelocalClusterState.resizeSupported
is set to false to call `ceph fs subvolume resize` to check command is supported or not, if a structure is initialized all its members
are set to the default value. so we will never be going to check the `ceph fs subvolume  resize` command is supported in the backend or not, we are always using ceph fs subvolume create to resize subvolume. in some ceph version,`ceph fs subvolume create` won't work to resize a subvolume. This commit changes the resizeSupported from bool to *bool for proper handling of this scenario.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

closes #1732

### CODE REVIEW

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Review by nixpanic — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by phlogistonjohn** [comment]
I stumbled across this a bit too late, but since I know everyone loves unsolicited advice I'll comment anyway:

In the future when you have to do something like this I suggest creating a "tri-state" enum like: (UNKNOWN, UNSUPPORTED, SUPPORTED) rather than using a pointer just to indicate "missing-ness".
As you saw in your patch changing the type to a pointer needs a bunch of type changes elsewhere in the code. An enum only means you need to change the rhs of the assignments and gives you more descriptive values!

**Comment by Madhu-1** [comment]
> I stumbled across this a bit too late, but since I know everyone loves unsolicited advice I'll comment anyway:
> 
> In the future when you have to do something like this I suggest creating a "tri-state" enum like: (UNKNOWN, UNSUPPORTED, SUPPORTED) rather than using a pointer just to indicate "missing-ness".
> As you saw in your patch changing the type to a pointer needs a bunch of type changes elsewhere in the code. An enum only means you need to change the rhs of the assignments and gives you more descriptive values!

Thanks for the suggestion @phlogistonjohn will rework this with enum.

**Pull request merged**
