### PR TITLE
ci: do not assume Docker is availble on the minikube host

### PR DESCRIPTION
**Pull request by nixpanic**
Instead of using the Docker command to push the image to to minikube VM,
read the image from stdin over ssh and load it with the Docker command
that is available inside the VM.

See-also: #1515

### CODE REVIEW

**Review by Madhu-1 — APPROVED** [review]

**Review by Yuggupta27 — APPROVED** [review]

**Comment by nixpanic** [comment]
The CI job fails with:
```
copying the kubernetes sidecar images
'docker' not found
```
#1517 is created to address this.

**Review by pkalever — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio refresh

**Comment by Madhu-1** [comment]
@mergifyio backport release-v3.1

**Comment by Madhu-1** [comment]
@nixpanic looks like we need manual backport

**Pull request merged**
