### PR TITLE
deploy: update templates to v3.10.0

### PR DESCRIPTION
**Pull request by Rakshith-R**
# Describe what this PR does #

This commit updates templates to new
v3.10.0 release.

depends-on: #4293

### CODE REVIEW

**Review by nixpanic — DISMISSED** [review]

**Review by yati1998 — DISMISSED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio queue

**Comment by nixpanic** [comment]
This is strange... even with commit 4e46e3b3d6dc7e8d6f342731c280e1ab9d0c259c the pr-commenter does not want to comment in the release-v3.10 branch. The workflow file that is linked in the GitHub Action does list `release-v3.10`, and not `release-v3.8` anymore. Probably there is something cached in some GitHub CI infrastructure that causes the old configuration for the pr-commenter to be used :shrug:

**Review by nixpanic — APPROVED** [review]

**Review by riya-singhal31 — APPROVED** [review]

**Comment by riya-singhal31** [comment]
@Mergifyio rebase

**Comment by riya-singhal31** [comment]
@Mergifyio requeue

**Comment by riya-singhal31** [comment]
@Mergifyio queue

**Comment by nixpanic** [comment]
@mergifyio refresh

**Review by yati1998 — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio refresh

**Comment by nixpanic** [comment]
@mergifyio requeue

**Comment by nixpanic** [comment]
@mergifyio queue

**Comment by nixpanic** [comment]
Kubernetes 1.28 does not seem to be required for release-v3.10 yet, instead it expects Kubernretes 1.25 still. That should be addressed with #4295.

**Comment by nixpanic** [comment]
@mergifyio requeue

**Comment by nixpanic** [comment]
@mergifyio queue

**Comment by nixpanic** [comment]
I'm, trying to figure out whats wrong, but haven't found the problem yet. For some reason the `base` is not detected as `release-v*` by Mergify, all other checks have passed.

image

**Comment by nixpanic** [comment]
@mergifyio refresh

**Comment by nixpanic** [comment]
Trying to fix the automatic merging with #4295 . Let's refresh/requeue  this PR once the configuration is updated.

**Comment by Rakshith-R** [comment]
@mergifyio refresh

**Pull request merged**
