### PR TITLE
ci: fix codespell and shell check failures

### PR DESCRIPTION
**Pull request by riya-singhal31**
This commit fixes the codespell and shell check ci failure.

### CODE REVIEW

**Comment by Madhu-1** [comment]
@riya-singhal31 Thanks for the PR can you also fix shell check failures?

**Comment by nixpanic** [comment]
Thanks! Do you also want to address the ShellCheck errors with a 2nd commit in this PR?

**Comment by riya-singhal31** [comment]
Sure, I'll add the fix for shell check failure as well.
Thanks, 
@Madhu-1 @nixpanic

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

**Review by Madhu-1 — APPROVED** [review]

**Comment by Rakshith-R** [comment]
@mergifyio refresh

**Pull request merged**
