### PR TITLE
make necessary changes for release-v3.8.1

### PR DESCRIPTION
**Pull request by Rakshith-R**
# Describe what this PR does #

- ci: template changes for v3.8.1 release
- doc: update documentation for v3.8.1 release

## Related issues ##

Updates: #3960 

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

### CODE REVIEW

**Review by Madhu-1 — DISMISSED** [review]

**Review by yati1998 — DISMISSED** [review]

**Review by nixpanic — APPROVED** [review]

**Comment by Rakshith-R** [comment]
upgrade test passed
https://jenkins-ceph-csi.apps.ocp.cloud.ci.centos.org/blue/organizations/jenkins/upgrade-tests-rbd/detail/upgrade-tests-rbd/7298/pipeline/

**Review by riya-singhal31 — APPROVED** [review]

**Comment by saranyareddy24** [comment]
Will it be possible to get a tagged branch v3.8.1?

**Comment by saranyareddy24** [comment]
Also may I know when it will be released?

**Comment by Rakshith-R** [comment]
> Will it be possible to get a tagged branch v3.8.1?

yes, this pr is for preparation to tag and release v3.8.1

> Also may I know when it will be released?

It will be released by EOD.

**Comment by saranyareddy24** [comment]
Thank you @Rakshith-R

**Pull request merged**
