### PR TITLE
Revert "deploy: Template changes for release v2.1.2"

### PR DESCRIPTION
**Pull request by Madhu-1**
This reverts commit a03675e3aeea093a48c389c5795730445356f3e1. which was done to release v2.1.2 as now the release is done, we are reverting back the templates and image tag for v2.1-canary

### CODE REVIEW

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
@humblec please review this PR on priority

**Comment by nixpanic** [comment]
> @Mergifyio rebase

Ah, I thought #1149 was merged by now... but it isn't. The rebase did not change anything and testing will continue to fail.

**Comment by Madhu-1** [comment]
> > @Mergifyio rebase
> 
> Ah, I thought #1149 was merged by now... but it isn't. The rebase did not change anything and testing will continue to fail.

Nope, its not merged yet to avoid building of release images and helm charts. will merge #1149 after  this one

**Comment by Madhu-1** [comment]
Merging this one as its having one approval and CI is passed.

**Pull request merged**
