### PR TITLE
Update kube dependency to v1.18.0

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@nixpanic @Madhu-1 @ShyamsundarR ptal.

**Comment by nixpanic** [comment]
It seems I missed something in my previous update, some files have been added under `./vendor` and those were not included in the diffstat. But with only 20 files modified, it does not come close to the 55 in this PR.

```
$ git diff --stat HEAD~1
 go.mod                                                                       |  57 +++++++++++++++++++++-----------------------
 go.sum                                                                       |  76 +++++++++++++++++++++++++++++------------------------------
 vendor/golang.org/x/crypto/blowfish/block.go                                 | 159 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 vendor/golang.org/x/crypto/blowfish/cipher.go                                |  99 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 vendor/golang.org/x/crypto/blowfish/const.go                                 | 199 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 vendor/golang.org/x/crypto/ssh/internal/bcrypt_pbkdf/bcrypt_pbkdf.go         |  93 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 vendor/golang.org/x/crypto/ssh/keys.go                                       | 198 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------
 vendor/golang.org/x/crypto/ssh/terminal/terminal.go                          |  13 ++++++++--
 vendor/gopkg.in/yaml.v2/scannerc.go                                          |  47 ++++++++++++++++--------------------
 vendor/gopkg.in/yaml.v2/yamlh.go                                             |   1 +
 vendor/k8s.io/client-go/util/connrotation/connrotation.go                    |  10 ++++----
 vendor/k8s.io/cloud-provider/cloud.go                                        |   4 ++++
 vendor/k8s.io/cloud-provider/go.mod                                          |  12 +++++-----
 vendor/k8s.io/cloud-provider/go.sum                                          |  14 +++++------
 vendor/k8s.io/csi-translation-lib/go.mod                                     |  14 +++++------
 vendor/k8s.io/csi-translation-lib/go.sum                                     |  14 +++++------
 vendor/k8s.io/kubernetes/pkg/apis/core/v1/conversion.go                      |  12 ++++++----
 vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/util/util.go |   7 ++++++
 vendor/k8s.io/kubernetes/pkg/scheduler/util/utils.go                         |  13 +++-------
 vendor/modules.txt                                                           |  34 +++++++++++++++-----------
 20 files changed, 889 insertions(+), 187 deletions(-)
```

**Comment by humblec** [comment]
@nixpanic not sure why the difference was occurring. any way I have updated to `1.18.0` as its available now. 
@Madhu-1 updated to `1.18.0`.

**Comment by humblec** [comment]
Looking into the CI failure
```
# github.com/ceph/ceph-csi/pkg/util

pkg/util/k8scmcache.go:88:66: not enough arguments in call to k8scm.Client.CoreV1().ConfigMaps(k8scm.Namespace).Get

	have (string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions)

	want (context.Context, string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions)

pkg/util/k8scmcache.go:98:68: not enough arguments in call to k8scm.Client.CoreV1().ConfigMaps(k8scm.Namespace).List

	have ("k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions)

	want (context.Context, "k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions)

pkg/util/k8scmcache.go:145:67: not enough arguments in call to k8scm.Client.CoreV1().ConfigMaps(k8scm.Namespace).Create

	have (*"k8s.io/api/core/v1".ConfigMap)

	want (context.Context, *"k8s.io/api/core/v1".ConfigMap, "k8s.io/apimachinery/pkg/apis/meta/v1".CreateOptions)

pkg/util/k8scmcache.go:177:65: not enough arguments in call to k8scm.Client.CoreV1().ConfigMaps(k8scm.Namespace).Delete

	have (string, nil)

	want (context.Context, string, "k8s.io/apimachinery/pkg/apis/meta/v1".DeleteOptions)

```

**Comment by humblec** [comment]
@Madhu-1 test is panicking.. 

```
error:

exit status 1

Mar 31 05:22:51.202: INFO: Running '/usr/local/bin/kubectl --server=https://10.20.0.194:8443 --kubeconfig=/home/travis/.kube/config --namespace=cephcsi-e2e-178 -f -'

Mar 31 05:22:51.253: INFO: rc: 1

Mar 31 05:22:51.253: INFO: failed to create rbd provisioner error running /usr/local/bin/kubectl --server=https://10.20.0.194:8443 --kubeconfig=/home/travis/.kube/config --namespace=cephcsi-e2e-178 -f -:

Command stdout:

stderr:

Error: unknown shorthand flag: 'f' in -f

```

May be  an update in our CI setup with latest version of kube can solve it . @Madhu-1 what do you think? if yes, I can send the PR for the same.

**Comment by Madhu-1** [comment]
looks like the error is something else
```text
Mar 31 05:22:51.149: INFO: failed to delete provisioner rbac ../deploy/rbd/kubernetes/csi-provisioner-rbac.yaml error running /usr/local/bin/kubectl --server=https://10.20.0.194:8443 --kubeconfig=/home/travis/.kube/config --namespace=cephcsi-e2e-178 delete -f -:
Command stdout:
stderr:
error: unable to decode "STDIN": json: cannot unmarshal string into Go value of type unstructured.detector
error:
exit status 1
Mar 31 05:22:51.149: INFO: Running '/usr/local/bin/kubectl --server=https://10.20.0.194:8443 --kubeconfig=/home/travis/.kube/config --ignore-not-found=true --namespace=cephcsi-e2e-178 -f -'
Mar 31 05:22:51.201: INFO: rc: 1
Mar 31 05:22:51.201: INFO: failed to delete nodeplugin rbac ../deploy/rbd/kubernetes/csi-nodeplugin-rbac.yaml error running /usr/local/bin/kubectl --server=https://10.20.0.194:8443 --kubeconfig=/home/travis/.kube/config --ignore-not-found=true --namespace=cephcsi-e2e-178 -f -:
Command stdout:
stderr:
Error: unknown flag: --ignore-not-found
Basic Commands (Beginner):
  create         Create a resource from a file or from stdin.
  expose         Take a replication controller, service, deployment or pod and expose it as a new Kubernetes Service
  run            Run a particular image on the cluster
  set            Set specific features on objects
```

**Comment by humblec** [comment]
@Madhu-1 `--ignore-not-found` and `-f` are the 2 issues I found in the logs. May be removing the first one should solve the second issue.

**Comment by humblec** [comment]
> @Madhu-1 `--ignore-not-found` and `-f` are the 2 issues I found in the logs. May be removing the first one should solve the second issue.

Currently we install kubectl `1.14` which is old. Thats why I was thinking we can use latest verion of `kubectl ` and it could help. 

````
The command "make image-cephcsi || travis_terminate 1;" exited with 0.

$ scripts/travis-functest.sh v1.14.10 || travis_terminate 1;




Installing minikube. Version: v1.6.0

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100 43.4M  100 43.4M    0     0   126M      0 --:--:-- --:--:-- --:--:--  126M

Installing kubectl. Version: v1.14.10
```

**Comment by Madhu-1** [comment]
we install kubectl to match the kubernetes version
```text
$ scripts/travis-functest.sh v1.17.0 || travis_terminate 1;
Installing minikube. Version: v1.6.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 43.4M  100 43.4M    0     0  95.7M      0 --:--:-- --:--:-- --:--:-- 95.9M
Installing kubectl. Version: v1.17.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 41.4M  100 41.4M    0     0  91.8M      0 --:--:-- --:--:-- --:--:-- 91.7M
```
```text
$ scripts/travis-functest.sh v1.15.6 || travis_terminate 1;
Installing minikube. Version: v1.6.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 43.4M  100 43.4M    0     0   115M      0 --:--:-- --:--:-- --:--:--  115M
Installing kubectl. Version: v1.15.6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 41.0M  100 41.0M    0     0   116M      0 --:--:-- --:--:-- --:--:--  115M
```

```text
$ scripts/travis-functest.sh v1.14.10 || travis_terminate 1;
Installing minikube. Version: v1.6.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 43.4M  100 43.4M    0     0   126M      0 --:--:-- --:--:-- --:--:--  126M
Installing kubectl. Version: v1.14.10
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

**Comment by humblec** [comment]
closing ths as other PR already cover this.

**Pull request closed without merging**
