### PR TITLE
Promote sidecars to latest available version tags.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@Madhu-1 PTAL

**Comment by Madhu-1** [comment]
I think https://github.com/ceph/ceph-csi/pull/397/files#diff-66fbd4d3ee3df68958b726127b6467b2R107  has to be done here as this PR updating the sidecar container images

**Comment by humblec** [comment]
@Madhu-1 this looks to be working!

**Comment by humblec** [comment]
Thanks @Madhu-1 .. Merging this based on based the approval.

**Pull request merged**
