### PR TITLE
ci: update minikube to latest v1.25.2 release

### PR DESCRIPTION
**Pull request by nixpanic**
This version addresses several bugs and includes other improvements.

See-also: https://github.com/kubernetes/minikube/releases/tag/v1.25.2

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

**Review by yati1998 — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Comment by humblec** [comment]
tests are failing @nixpanic

**Comment by nixpanic** [comment]
It seems kubernetes/minikube#13539 moved the `kubectl` binary, so the CI script `single-node-k8s.sh` needs to check that as well.

**Comment by nixpanic** [comment]
#2943 has been created for addressing this. Tests can be restarted once that is merged.

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio refresh

**Comment by Rakshith-R** [comment]
@mergifyio rebase

**Pull request merged**
