### PR TITLE
cleanup: resolves gofumpt for cmd

### PR DESCRIPTION
**Pull request by yati1998**
This commit resolves gofumpt linter for
cmd folder

Updates: 1586

Signed-off-by: Yati Padia <ypadia@redhat.com>

### CODE REVIEW

**Review by nixpanic — APPROVED** [review]

**Comment by yati1998** [comment]
@Madhu-1 need your review here.

**Comment by yati1998** [comment]
@Madhu-1 need your review here.

**Review by Madhu-1 — APPROVED** [review]

**Review by pkalever — APPROVED** [review]

**Pull request merged**
