### PR TITLE
build: update for 3.10.2 release

### PR DESCRIPTION
**Pull request by Madhu-1**
This PR contains the required doc and template updates for cephcsi 3.10.2 release

### CODE REVIEW

**Review by yati1998 — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio queue

**Comment by nixpanic** [comment]
I don't get any errors while using the CI registry from my laptop. Hopefully infrastructure issues have been resolved.

**Comment by nixpanic** [comment]
@requeue

**Comment by nixpanic** [comment]
@mergifyio requeue

**Pull request merged**
