### PR TITLE
rbd-nbd: support and qualify volume encryption

### LINKED ISSUE #2235: rbd-nbd: volume encryption support
# Describe the feature you'd like to have #

Tracker issue to implement the missing bits and qualify volume encryption backed by the rbd-nbd mounter

### PR DESCRIPTION
**Pull request by pkalever**
# Describe what this PR does #

Qualify volume encryption via rbd-nbd

* Updates the documentation
* Adds required test cases

Fixes: #2235

Signed-off-by: Prasanna Kumar Kalever \<prasanna.kalever@redhat.com\>

### CODE REVIEW

**Comment by pkalever** [comment]
@Mergifyio rebase

**Comment by pkalever** [comment]
@Mergifyio rebase

**Comment by pkalever** [comment]
@Mergifyio rebase

**Comment by pkalever** [comment]
@nixpanic @Madhu-1 request for reveiw.

**Review by Madhu-1 — DISMISSED** [review]

**Review by nixpanic — DISMISSED** [review]

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by pkalever** [comment]
/retest ci/centos/mini-e2e/k8s-1.21

```
Aug 10 07:33:26.865: INFO: will run kubectl (create) args ([]) again (11 seconds elapsed)
Aug 10 07:33:26.865: FAIL: failed to create provisioner psp with error failed to run kubectl: error running /usr/bin/kubectl --server=https://192.168.39.115:8443 --kubeconfig=/root/.kube/config --namespace=cephcsi-e2e-89032996 create -f -:
Command stdout:

stderr:
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Error from server (AlreadyExists): error when creating "STDIN": podsecuritypolicies.policy "rbd-csi-provisioner-psp" already exists
Error from server (AlreadyExists): error when creating "STDIN": roles.rbac.authorization.k8s.io "rbd-csi-provisioner-psp" already exists
Error from server (AlreadyExists): error when creating "STDIN": rolebindings.rbac.authorization.k8s.io "rbd-csi-provisioner-psp"
```

**Comment by pkalever** [comment]
@Madhu-1 @nixpanic please help restore the acks, there was a merge conflict in docs/rbd-nbd.md because of https://github.com/ceph/ceph-csi/pull/2283, which needed manual resolution.

**Review by nixpanic — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Comment by pkalever** [comment]
Most of the tests stuck after 'return bare-metal machine' state.

**Pull request merged**
