### PR TITLE
plugin script csidriver added

### PR DESCRIPTION
**Pull request by Informize**
micro change , the helper scripts have to csidriver included for cephfs. (#3309 fix when using the helper scripts)

### CODE REVIEW

**Comment by Madhu-1** [comment]
@Informize Thanks for the PR can you please fix DCO and commitlint, please refer to https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#code-contribution-workflow

**Comment by humblec** [comment]
@Informize thanks for the PR. 
DCO test fails here because of missing "signed-off" in the commit ehttps://github.com/ceph/ceph-csi/pull/3504/checks?check_run_id=9362568065. Can you correct the same ?

**Comment by nixpanic** [comment]
@mergifyio rebase

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
Hi @Informize, could you squash the commits into a single one? Ideally change the subject of the commit to have a prefix like `deploy: ` and include your `Signed-off-by:` line.

We use Mergify for rebasing PRs on top of the last `devel` branch before merging. This requires that your branch can be updated by the bot. It failed earlier, so maybe you need to open up the permissions on the PR on the right side of the page.

**Pull request closed without merging**
