### PR TITLE
deploy: update csi sidecar images

### PR DESCRIPTION
**Pull request by agarwal-mudit**
This PR makes the changes in csi templates and
upgrade documentation required for updating
csi sidecar images.

Signed-off-by: Mudit Agarwal <muagarwa@redhat.com>

Fixes: #1472
Fixes: #1471

### CODE REVIEW

**Review by Madhu-1 — COMMENTED** [review]
@agarwal-mudit please check do we have any latest releases of kubernetes-csi

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Review by Madhu-1 — COMMENTED** [review]
@agarwal-mudit anything we need to udpate the upgrade doc? based on kubernetes versions we need to use different sidecars

**Comment by agarwal-mudit** [comment]
> @agarwal-mudit anything we need to udpate the upgrade doc? based on kubernetes versions we need to use different sidecars

Added an upgrade doc here: https://github.com/ceph/ceph-csi/pull/1767

**Review by Madhu-1 — APPROVED** [review]

**Comment by Madhu-1** [comment]
@nixpanic PTAL

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@agarwal-mudit does this close #1472? If so, add `Fixes: #1472` to the description of the PR (not needed in the commit message).

**Comment by nixpanic** [comment]
> @agarwal-mudit does this close #1472? If so, add `Fixes: #1472` to the description of the PR (not needed in the commit message).

And maybe #1471 as well?

**Comment by Madhu-1** [comment]
>ci/centos/mini-e2e/k8s-1.19

@nixpanic E2E is running from last 1 hour, normally e2e takes around 40  minutes. anything wrong in the CI?

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e/k8s-1.19

Jenkins Slave container disappeared for some unknown reason:
```
cico-workspace-dn7m3 was marked offline: Connection was broken: java.nio.channels.ClosedChannelException
```

**Pull request merged**
