### PR TITLE
revert: remove explicit size setting of cloned volume

### LINKED ISSUE #2719: cephfs: inconsistent size when we create bigger PVC from a snapshot
When i create a empty pvc (1Gib) and take a snapshot of it and restore it to a new PVC (5Gib)  everything works fine am able to see the new PVC size is actually 5 Gib

When i create a pvc (1Gib) and write some data take a snapshot of it and restore it to a new PVC (5Gib) new PVC size in backend still remains the same and this is inconsistent with the  request made by the user.

steps to reproduce it

* create PVC and application and write some data to it

```
[root@dhcp53-170 cephfs]# kubectl create -f pvc.yaml 
persistentvolumeclaim/cephfs-pvc created
[root@dhcp53-170 cephfs]# 
[root@dhcp53-170 cephfs]# kubectl get pvc
NAME         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cephfs-pvc   Bound    pvc-4c68ad6e-fb8a-43fd-82fd-57f638bc2ed5   1Gi        RWO            rook-cephfs    7s
[root@dhcp53-170 cephfs]# 
[root@dhcp53-170 cephfs]# kubectl create -f pod.yaml 
pod/csi-cephfs-demo-pod-1 created
[root@dhcp53-170 cephfs]# kubectl get po
NAME                    READY   STATUS    RESTARTS   AGE
csi-cephfs-demo-pod-1   1/1     Running   0          2m23s
snapshot-controller-0   1/1     Running   0          4m1s
[root@dhcp53-170 cephfs]# kubectl exec -it csi-cephfs-demo-pod-1 -- sh                                                                                                              2.9G     0  2.9G   0% /sys/firmware
sh-4.4# cd /var/lib/www/html
sh-4.4# dd if=/dev/zero of=testfile bs=1024 count=102400
102400+0 records in
102400+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 0.471175 s, 223 MB/s
sh-4.4#                                                                                                             2.9G     0  2.9G   0% /sys/firmware
sh-4.4# ls
testfile
sh-4.4# mv testfile testfile1 
sh-4.4# 
sh-4.4# dd if=/dev/zero of=testfile bs=1024 count=102400
102400+0 records in
102400+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 0.448942 s, 234 MB/s
sh-4.4# 
sh-4.4# 
sh-4.4# df -h
Filesystem                                                                                                          Size  Used Avail Use% Mounted on
overlay                                                                                                              17G  4.2G   12G  26% /
tmpfs                                                                                                                64M     0   64M   0% /dev
tmpfs                                                                                                               2.9G     0  2.9G   0% /sys/fs/cgroup
/dev/vda1                                                                                                            17G  4.2G   12G  26% /etc/hosts
shm                                                                                                                  64M     0   64M   0% /dev/shm
192.168.121.72:6789:/volumes/csi/csi-vol-5f0ee9ae-614f-11ec-ada9-0242ac110006/4d02562c-18e5-41f9-889c-d8063cad4e8b  1.0G  180M  844M  18% /var/lib/www/html
tmpfs                                                                                                               5.7G   12K  5.7G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                                                                                               2.9G     0  2.9G   0% /proc/acpi
tmpfs                                                                                                               2.9G     0  2.9G   0% /proc/scsi
tmpfs                                                                                                               2.9G     0  2.9G   0% /sys/firmware
sh-4.4# sync
```
* Create snapshot and restore it as a new PVC of size 5Gib
```
[root@dhcp53-170 cephfs]# kubectl create -f snapshotclass.yaml 
volumesnapshotclass.snapshot.storage.k8s.io/csi-cephfsplugin-snapclass created
[root@dhcp53-170 cephfs]# kubectl create -f snapshot.yaml 
volumesnapshot.snapshot.storage.k8s.io/cephfs-pvc-snapshot created
[root@dhcp53-170 cephfs]# kubectl get volumesnapshot
NAME                  READYTOUSE   SOURCEPVC    SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS                SNAPSHOTCONTENT                                    CREATIONTIME   AGE
cephfs-pvc-snapshot   true         cephfs-pvc                           1Gi           csi-cephfsplugin-snapclass   snapcontent-f0acec70-c54b-4e0c-82f2-728df369be81   5s             5s
[root@dhcp53-170 cephfs]# 
[root@dhcp53-170 cephfs]# kubectl create -f^C
[root@dhcp53-170 cephfs]# vi pvc-restore.yaml 
[root@dhcp53-170 cephfs]# kubectl create -f pvc-restore.yaml 
persistentvolumeclaim/cephfs-pvc-restore created
[root@dhcp53-170 cephfs]# kubectl get pvc
NAME                 STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cephfs-pvc           Bound     pvc-4c68ad6e-fb8a-43fd-82fd-57f638bc2ed5   1Gi        RWO            rook-cephfs    4m48s
cephfs-pvc-restore   Pending                                                                        rook-cephfs    3s
[root@dhcp53-170 cephfs]# kubectl get pvc
NAME                 STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cephfs-pvc           Bound     pvc-4c68ad6e-fb8a-43fd-82fd-57f638bc2ed5   1Gi        RWO            rook-cephfs    4m50s
cephfs-pvc-restore   Pending                                                                        rook-cephfs    5s
[root@dhcp53-170 cephfs]# kubectl get pvc
NAME                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cephfs-pvc           Bound    pvc-4c68ad6e-fb8a-43fd-82fd-57f638bc2ed5   1Gi        RWO            rook-cephfs    5m24s
cephfs-pvc-restore   Bound    pvc-9d829bd0-c077-4c0a-96a4-a9006d5a7ec3   5Gi        RWX            rook-cephfs    39s
[root@dhcp53-170 cephfs]# 
[root@dhcp53-170 cephfs]# kubectl get pv/pvc-9d829bd0-c077-4c0a-96a4-a9006d5a7ec3 -oyaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rook-ceph.cephfs.csi.ceph.com
  creationTimestamp: "2021-12-20T04:48:19Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-9d829bd0-c077-4c0a-96a4-a9006d5a7ec3
  resourceVersion: "3977"
  uid: 0defb20e-7012-4555-bfc3-6ff6cfa03326
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: cephfs-pvc-restore
    namespace: default
    resourceVersion: "3943"
    uid: 9d829bd0-c077-4c0a-96a4-a9006d5a7ec3
  csi:
    controllerExpandSecretRef:
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      fsName: myfs
      pool: myfs-data0
      storage.kubernetes.io/csiProvisionerIdentity: 1639975347218-8081-rook-ceph.cephfs.csi.ceph.com
      subvolumeName: csi-vol-08a81804-6150-11ec-ada9-0242ac110006
      subvolumePath: /volumes/csi/csi-vol-08a81804-6150-11ec-ada9-0242ac110006/66b8b595-db07-480c-9390-969855d11259
    volumeHandle: 0001-0009-rook-ceph-0000000000000001-08a81804-6150-11ec-ada9-0242ac110006
  persistentVolumeReclaimPolicy: Delete
  storageClassName: rook-cephfs
  volumeMode: Filesystem
status:
  phase: Bound
```

* check subvolume size in the backend
```
sh-4.4# ceph fs subvolume info myfs csi-vol-08a81804-6150-11ec-ada9-0242ac110006 csi
{
    "atime": "2021-12-20 04:43:26",
    "bytes_pcent": "16.02",
    "bytes_quota": 1073741824,
    "bytes_used": 171966464,
    "created_at": "2021-12-20 04:48:11",
    "ctime": "2021-12-20 04:48:17",
    "data_pool": "myfs-data0",
    "features": [
        "snapshot-clone",
        "snapshot-autoprotect",
        "snapshot-retention"
    ],
    "gid": 0,
    "mode": 16895,
    "mon_addrs": [
        "192.168.121.72:6789"
    ],
    "mtime": "2021-12-20 04:47:13",
    "path": "/volumes/csi/csi-vol-08a81804-6150-11ec-ada9-0242ac110006/66b8b595-db07-480c-9390-969855d11259",
    "pool_namespace": "",
    "state": "complete",
    "type": "clone",
    "uid": 0
}
```

### LINKED ISSUE #2720: cephfs: inconsistent size when we create bigger PVC from a PVC
When I create an empty pvc (1Gib) and create new bigger size PVC (5Gib) everything works fine. am able to see the new PVC size is actually 5 Gib

When I create a pvc (1Gib) and write some data and create a new PVC (5Gib) from it.  The new PVC size in the backend still remains the same and this is inconsistent with the request made by the user.

steps to reproduce it

* create PVC and application and write some data to it

```
[root@dhcp53-170 cephfs]# kubectl create -f pvc.yaml 
persistentvolumeclaim/cephfs-pvc created
[root@dhcp53-170 cephfs]# 
[root@dhcp53-170 cephfs]# kubectl get pvc
NAME         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cephfs-pvc   Bound    pvc-4c68ad6e-fb8a-43fd-82fd-57f638bc2ed5   1Gi        RWO            rook-cephfs    7s
[root@dhcp53-170 cephfs]# 
[root@dhcp53-170 cephfs]# kubectl create -f pod.yaml 
pod/csi-cephfs-demo-pod-1 created
[root@dhcp53-170 cephfs]# kubectl get po
NAME                    READY   STATUS    RESTARTS   AGE
csi-cephfs-demo-pod-1   1/1     Running   0          2m23s
snapshot-controller-0   1/1     Running   0          4m1s
[root@dhcp53-170 cephfs]# kubectl exec -it csi-cephfs-demo-pod-1 -- sh                                                                                                              2.9G     0  2.9G   0% /sys/firmware
sh-4.4# cd /var/lib/www/html
sh-4.4# dd if=/dev/zero of=testfile bs=1024 count=102400
102400+0 records in
102400+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 0.471175 s, 223 MB/s
sh-4.4#                                                                                                             2.9G     0  2.9G   0% /sys/firmware
sh-4.4# ls
testfile
sh-4.4# mv testfile testfile1 
sh-4.4# 
sh-4.4# dd if=/dev/zero of=testfile bs=1024 count=102400
102400+0 records in
102400+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 0.448942 s, 234 MB/s
sh-4.4# 
sh-4.4# 
sh-4.4# df -h
Filesystem                                                                                                          Size  Used Avail Use% Mounted on
overlay                                                                                                              17G  4.2G   12G  26% /
tmpfs                                                                                                                64M     0   64M   0% /dev
tmpfs                                                                                                               2.9G     0  2.9G   0% /sys/fs/cgroup
/dev/vda1                                                                                                            17G  4.2G   12G  26% /etc/hosts
shm                                                                                                                  64M     0   64M   0% /dev/shm
192.168.121.72:6789:/volumes/csi/csi-vol-5f0ee9ae-614f-11ec-ada9-0242ac110006/4d02562c-18e5-41f9-889c-d8063cad4e8b  1.0G  180M  844M  18% /var/lib/www/html
tmpfs                                                                                                               5.7G   12K  5.7G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                                                                                               2.9G     0  2.9G   0% /proc/acpi
tmpfs                                                                                                               2.9G     0  2.9G   0% /proc/scsi
tmpfs                                                                                                               2.9G     0  2.9G   0% /sys/firmware
sh-4.4# sync
```
* create a new clone and check the size in PVC and backend
```
[root@dhcp53-170 cephfs]# kubectl get pvc
NAME                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cephfs-pvc           Bound    pvc-4c68ad6e-fb8a-43fd-82fd-57f638bc2ed5   1Gi        RWO            rook-cephfs    15m
cephfs-pvc-clone     Bound    pvc-442d78c8-12a8-4fea-8ef2-a490a6f7390d   2Gi        RWX            rook-cephfs    2m51s
cephfs-pvc-restore   Bound    pvc-9d829bd0-c077-4c0a-96a4-a9006d5a7ec3   5Gi        RWX            rook-cephfs    10m
[root@dhcp53-170 cephfs]# kubectl get pv/pvc-442d78c8-12a8-4fea-8ef2-a490a6f7390d -oyaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rook-ceph.cephfs.csi.ceph.com
  creationTimestamp: "2021-12-20T04:55:42Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-442d78c8-12a8-4fea-8ef2-a490a6f7390d
  resourceVersion: "5020"
  uid: a2f13c55-e703-4a6d-9306-b2087b254c6d
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: cephfs-pvc-clone
    namespace: default
    resourceVersion: "4999"
    uid: 442d78c8-12a8-4fea-8ef2-a490a6f7390d
  csi:
    controllerExpandSecretRef:
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      fsName: myfs
      pool: myfs-data0
      storage.kubernetes.io/csiProvisionerIdentity: 1639975347218-8081-rook-ceph.cephfs.csi.ceph.com
      subvolumeName: csi-vol-1328d521-6151-11ec-ada9-0242ac110006
      subvolumePath: /volumes/csi/csi-vol-1328d521-6151-11ec-ada9-0242ac110006/9ab1fa72-7b1e-4b80-9e73-9046b3aef033
    volumeHandle: 0001-0009-rook-ceph-0000000000000001-1328d521-6151-11ec-ada9-0242ac110006
  persistentVolumeReclaimPolicy: Delete
  storageClassName: rook-cephfs
  volumeMode: Filesystem
status:
  phase: Bound
```
* subvolume info output
```
sh-4.4# ceph fs subvolume info myfs csi-vol-1328d521-6151-11ec-ada9-0242ac110006 csi
{
    "atime": "2021-12-20 04:43:26",
    "bytes_pcent": "19.53",
    "bytes_quota": 1073741824,
    "bytes_used": 209715200,
    "created_at": "2021-12-20 04:55:38",
    "ctime": "2021-12-20 04:55:42",
    "data_pool": "myfs-data0",
    "features": [
        "snapshot-clone",
        "snapshot-autoprotect",
        "snapshot-retention"
    ],
    "gid": 0,
    "mode": 16895,
    "mon_addrs": [
        "192.168.121.72:6789"
    ],
    "mtime": "2021-12-20 04:47:13",
    "path": "/volumes/csi/csi-vol-1328d521-6151-11ec-ada9-0242ac110006/9ab1fa72-7b1e-4b80-9e73-9046b3aef033",
    "pool_namespace": "",
    "state": "complete",
    "type": "clone",
    "uid": 0
}
```

### LINKED ISSUE #2721: cephfs: inconsistent size when we create PVC from a PVC
When a PVC clone is created from a PVC with the same size in ceph cluster 15.2.4 the size is not consistent with the PVC size rather the PVC size is of the cluster, not the subvolume

* ceph version
```
sh-4.4# ceph version
ceph version 15.2.4 (7447c15c6ff58d7fce91843b705a268a1917325c) octopus (stable)
```

* create PVC and create a clone from the PVC
```
 kubectl get pvc
NAME               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cephfs-pvc         Bound    pvc-adffa953-df68-437e-bd1a-8c02a422592e   1Gi        RWO            rook-cephfs    5m3s
cephfs-pvc-clone   Bound    pvc-5632ab5f-3fbd-4ee2-8615-b53bde0781e6   1Gi        RWX            rook-cephfs    2m21s
```

* check the subvolume info output on the ceph cluster
```
sh-4.4# ceph fs subvolume ls myfs csi
[
    {
        "name": "csi-vol-e359712a-616b-11ec-b3c4-0242ac110006"
    },
    {
        "name": "csi-vol-82f3b2ce-616b-11ec-b3c4-0242ac110006"
    }
]

sh-4.4# ceph fs subvolume info myfs csi-vol-e359712a-616b-11ec-b3c4-0242ac110006 csi
{
    "atime": "2021-12-20 08:04:52",
    "bytes_pcent": "undefined",
    "bytes_quota": "infinite",
    "bytes_used": 0,
    "created_at": "2021-12-20 08:07:34",
    "ctime": "2021-12-20 08:07:34",
    "data_pool": "myfs-data0",
    "gid": 0,
    "mode": 16895,
    "mon_addrs": [
        "192.168.121.77:6789"
    ],
    "mtime": "2021-12-20 08:04:52",
    "path": "/volumes/csi/csi-vol-e359712a-616b-11ec-b3c4-0242ac110006/6fd0def6-db26-4877-bf77-b9450182d51b",
    "pool_namespace": "",
    "type": "clone",
    "uid": 0
}

sh-4.4# ceph fs subvolume info myfs csi-vol-82f3b2ce-616b-11ec-b3c4-0242ac110006 csi
{
    "atime": "2021-12-20 08:04:52",
    "bytes_pcent": "0.00",
    "bytes_quota": 1073741824,
    "bytes_used": 0,
    "created_at": "2021-12-20 08:04:52",
    "ctime": "2021-12-20 08:07:35",
    "data_pool": "myfs-data0",
    "gid": 0,
    "mode": 16895,
    "mon_addrs": [
        "192.168.121.77:6789"
    ],
    "mtime": "2021-12-20 08:04:52",
    "path": "/volumes/csi/csi-vol-82f3b2ce-616b-11ec-b3c4-0242ac110006/f3350aab-a868-4e11-857a-178738716699",
    "pool_namespace": "",
    "type": "subvolume",
    "uid": 0
}
```

* df output of the pod using cloned PVC
```
sh-4.4# df -h
Filesystem                                                                                                          Size  Used Avail Use% Mounted on
overlay                                                                                                              17G  5.2G   11G  33% /
tmpfs                                                                                                                64M     0   64M   0% /dev
tmpfs                                                                                                               2.9G     0  2.9G   0% /sys/fs/cgroup
/dev/vda1                                                                                                            17G  5.2G   11G  33% /etc/hosts
shm                                                                                                                  64M     0   64M   0% /dev/shm
192.168.121.77:6789:/volumes/csi/csi-vol-e359712a-616b-11ec-b3c4-0242ac110006/6fd0def6-db26-4877-bf77-b9450182d51b   47G     0   47G   0% /var/lib/www/html
tmpfs                                                                                                               5.7G   12K  5.7G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                                                                                               2.9G     0  2.9G   0% /proc/acpi
tmpfs                                                                                                               2.9G     0  2.9G   0% /proc/scsi
tmpfs                                                                                                               2.9G     0  2.9G   0% /sys/firmware

```

Note: - the `df -h` output is showing 47Gib as the storage space as the PVC size is 1Gib only

### LINKED ISSUE #2722: cephfs: inconsistent size when we create PVC from a snapshot
When a PVC clone is created from a snapshot with the same size in ceph cluster 15.2.4 the size is not consistent with the PVC size rather the PVC size is of the cluster, not the subvolume

* ceph version
```
sh-4.4# ceph version
ceph version 15.2.4 (7447c15c6ff58d7fce91843b705a268a1917325c) octopus (stable)
```
* create a snapshot of a PVC
```
[root@dhcp53-170 cephfs]# kubectl create -f snapshot.yaml 
volumesnapshot.snapshot.storage.k8s.io/cephfs-pvc-snapshot created
[root@dhcp53-170 cephfs]# kubectl get volumesnapshot
NAME                  READYTOUSE   SOURCEPVC    SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS                SNAPSHOTCONTENT                                    CREATIONTIME   AGE
cephfs-pvc-snapshot   true         cephfs-pvc                           1Gi           csi-cephfsplugin-snapclass   snapcontent-0346736e-b131-4be8-94b5-a384f64a636a   3s             4s

```
* restore the snapshot to a new PVC of the same size
```
[root@dhcp53-170 cephfs]# kubectl get pvc
NAME                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cephfs-pvc           Bound    pvc-adffa953-df68-437e-bd1a-8c02a422592e   1Gi        RWO            rook-cephfs    11m
cephfs-pvc-restore   Bound    pvc-e9335d07-ff97-4817-9ca1-71fafc75a133   1Gi        RWX            rook-cephfs    17s
```
* check subvolume info output
```
sh-4.4# ceph fs subvolume info myfs csi-vol-2368ae50-616d-11ec-b3c4-0242ac110006 csi
{
    "atime": "2021-12-20 08:04:52",
    "bytes_pcent": "undefined",
    "bytes_quota": "infinite",
    "bytes_used": 0,
    "created_at": "2021-12-20 08:16:31",
    "ctime": "2021-12-20 08:16:31",
    "data_pool": "myfs-data0",
    "gid": 0,
    "mode": 16895,
    "mon_addrs": [
        "192.168.121.77:6789"
    ],
    "mtime": "2021-12-20 08:04:52",
    "path": "/volumes/csi/csi-vol-2368ae50-616d-11ec-b3c4-0242ac110006/2f70a661-b224-4ed0-9fc1-a1e7aaf19135",
    "pool_namespace": "",
    "type": "clone",
    "uid": 0
}
```

* check `df` output
```
[root@dhcp53-170 cephfs]# kubectl exec -it pod/csi-cephfs-demo-pod-2 -- sh
sh-4.4# df -h
Filesystem                                                                                                          Size  Used Avail Use% Mounted on
overlay                                                                                                              17G  5.2G   11G  33% /
tmpfs                                                                                                                64M     0   64M   0% /dev
tmpfs                                                                                                               2.9G     0  2.9G   0% /sys/fs/cgroup
/dev/vda1                                                                                                            17G  5.2G   11G  33% /etc/hosts
shm                                                                                                                  64M     0   64M   0% /dev/shm
192.168.121.77:6789:/volumes/csi/csi-vol-2368ae50-616d-11ec-b3c4-0242ac110006/2f70a661-b224-4ed0-9fc1-a1e7aaf19135   47G     0   47G   0% /var/lib/www/html
tmpfs                                                                                                               5.7G   12K  5.7G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                                                                                               2.9G     0  2.9G   0% /proc/acpi
tmpfs                                                                                                               2.9G     0  2.9G   0% /proc/scsi
tmpfs                                                                                                               2.9G     0  2.9G   0% /sys/firmware
sh-4.4# 

```

Note: - the `df -h` output is showing 47Gib as the storage space as the PVC size is 1Gib only

The issue exists only in the canary image.

### PR DESCRIPTION
**Pull request by Madhu-1**
The ceph changes are done on the both server and the client-side this change is not enough to remove setting the size of cloned volumes.
this caused the regression like #2719 #2720 #2721 #2722.

This reverts commit 3565a342d5ff2006e61ca1641d788547efac4b53.

fixes #2719
fixes #2720
fixes #2721
fixes #2722

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
@humblec PTAL

**Comment by humblec** [comment]
@Madhu-1 just a question here, previously we had to set the size explictly, but then the parent size adoption was implemented in CephFS, iic, that change got backported to most of the Ceph Versions. Ceph versions equal or above - v16.0.0, v15.2.9, v14.2.12. Now are we reverting it to make it work with older releases ?

**Comment by Madhu-1** [comment]
> @Madhu-1 just a question here, previously we had to set the size explictly, but then the parent size adoption was implemented in CephFS, iic, that change got backported to most of the Ceph Versions. Ceph versions equal or above - v16.0.0, v15.2.9, v14.2.12. Now are we reverting it to make it work with older releases ?

Yes without it we cannot do clone and snapshot on older versions and also it's leading to other problems with bigger size clone and restore which was working in earlier release

**Review by humblec — APPROVED** [review]

**Comment by humblec** [comment]
Thanks .. :+1:

**Comment by Madhu-1** [comment]
>X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute

CI failed for above error

**Review by yati1998 — APPROVED** [review]

**Pull request merged**
