### PR TITLE
add optional TARGET=.. parameter for 'make containerized-test'

### PR DESCRIPTION
**Pull request by nixpanic**
Running the containerized-tests is relatively time consuming as it runs
all the tests. By adding a TARGET=.. option to the Makefile, it is now
possible to run a selected test, for example:

    make containerized-test TARGET=static-check

This reduces the time the tests take, so it is more friendly to the
developers while addressing problems.

When no TARGET=.. parameter is passed, the default tests are run.

### CODE REVIEW

**Comment by humblec** [comment]
@nixpanic spell check `optinal` to `optional` in the PR description :)

**Comment by Madhu-1** [comment]
@nixpanic updated PR title. please update commit message

**Comment by nixpanic** [comment]
Subject of the commit message has been updated!

**Comment by nixpanic** [comment]
@humblec @Madhu-1 I made the requested commit message typo correction, please +1 this again. Thanks!

**Comment by humblec** [comment]
@nixpanic need a rebase.

**Comment by nixpanic** [comment]
@humblec wrote:
> @nixpanic need a rebase.

Done!

**Pull request merged**
