### PR TITLE
csi-rbdplugin: Install xfsprogs to support fsType: xfs

### PR DESCRIPTION
**Pull request by Cynerva**
Proposed fix for https://github.com/ceph/ceph-csi/issues/87

I haven't tested this yet, but I'll see what I can do.

### CODE REVIEW

**Comment by rootfs** [comment]
thank you!

**Comment by Cynerva** [comment]
Thanks for the merge @rootfs. Any idea when this might make it out to a new release of the container?

**Comment by rootfs** [comment]
@Cynerva latest rbd image quay.io/cephcsi/rbdplugin:v0.3.0 has the fix

**Comment by Cynerva** [comment]
Ah my bad, should have checked. Thanks!

**Pull request merged**
