### PR TITLE
reject block volume creation in cephfs

### PR DESCRIPTION
**Pull request by Madhu-1**
update validate create volume request to reject block volume creation.

### CODE REVIEW

**Comment by rootfs** [comment]
thanks, a csi-v1.0 PR is appreciated too.

**Comment by Madhu-1** [comment]
@rootfs anyone is working on moving towards v1.0.0?

**Comment by rootfs** [comment]
yes, we have been working on standing up csi 1.0 driver on k8s using csi-v1.0 branch.

**Comment by rootfs** [comment]
@Madhu-1 @humblec this is csi v1.0 branch (using csi 1.0 spec and for k8s 1.13) https://github.com/ceph/ceph-csi/tree/csi-v1.0

**Pull request merged**
