### PR TITLE
Bring  attacher controller to latest version

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@Madhu-1 @nixpanic ptal.

**Comment by humblec** [comment]
> AFAIK Old Snapshot won't work if you update the provision

hmmm.. CI should fail without delay then :(

**Comment by Madhu-1** [comment]
> > AFAIK Old Snapshot won't work if you update the provision
> 
> hmmm.. CI should fail without delay then :(

In ci we have disabled snapshot testing. So it won't fail

**Comment by humblec** [comment]
> > > AFAIK Old Snapshot won't work if you update the provision
> > 
> > 
> > hmmm.. CI should fail without delay then :(
> 
> In ci we have disabled snapshot testing. So it won't fail

Oh.. yeah..

**Comment by humblec** [comment]
@Madhu-1 removed the provisioner update in the PR. PTAL.

**Comment by nixpanic** [comment]
On Wed, Mar 18, 2020 at 02:43:46AM -0700, Madhu Rajanna wrote:
> > > AFAIK Old Snapshot won't work if you update the provision
> > 
> > hmmm.. CI should fail without delay then :(
> 
> In ci we have disabled snapshot testing. So it won't fail

Is there an issue with the reason why it is disabled? If we want to
provide support for it, it is critical that automated tests are executed
regulary.

**Comment by Madhu-1** [comment]
> On Wed, Mar 18, 2020 at 02:43:46AM -0700, Madhu Rajanna wrote: > > AFAIK Old Snapshot won't work if you update the provision > > hmmm.. CI should fail without delay then :( In ci we have disabled snapshot testing. So it won't fail
> Is there an issue with the reason why it is disabled? If we want to provide support for it, it is critical that automated tests are executed regulary.

we had faced some issue in Travis CI when operating on the snapshots, as I am working on the reimplementing the snapshots I will enable it again.

**Comment by humblec** [comment]
> please update PR title and commit message

Done. PTAL @Madhu-1 @nixpanic

**Pull request merged**
