### PR TITLE
update sidecars to latest release compatible with kubernetes  v1.23

### PR DESCRIPTION
**Pull request by humblec**
This PR updates below sidecars:
- [x] csi-provisioner: v3.1.0:
Reference # https://github.com/kubernetes-csi/external-provisioner/blob/release-3.1/CHANGELOG/CHANGELOG-3.1.md 
- [x] node-driver-registrar:v2.4.0
Reference: https://github.com/kubernetes-csi/node-driver-registrar/blob/release-2.4/CHANGELOG/CHANGELOG-2.4.md
- [x] csi-attacher: v3.4.0
Reference: https://github.com/kubernetes-csi/external-attacher/blob/release-3.4/CHANGELOG/CHANGELOG-3.4.md

Additional note: This sidecar update is required for in-tree migration feature to work. 

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
Requesting review as it is required for the features  like intree migration to work..  The sidecar external provisioner was released few hours back .

**Review by nixpanic — APPROVED** [review]
it would really be good to have a link to the release notes in each commit

**Comment by humblec** [comment]
> it would really be good to have a link to the release notes in each commit

sure.. will keep that in mind..

**Review by yati1998 — APPROVED** [review]

**Comment by nixpanic** [comment]
> > it would really be good to have a link to the release notes in each commit
> 
> sure.. will keep that in mind..

You can still update at least the PR description pointing to the release notes :wink:

**Comment by humblec** [comment]
> > > it would really be good to have a link to the release notes in each commit
> > 
> > 
> > sure.. will keep that in mind..
> 
> You can still update at least the PR description pointing to the release notes wink

Added it :+1:

**Comment by humblec** [comment]
@Mergifyio refresh

**Comment by humblec** [comment]
@Mergifyio rebase

**Comment by humblec** [comment]
@Mergifyio refresh

**Pull request merged**
