### PR TITLE
Fix image builder in the Makefile

### PR DESCRIPTION
**Pull request by gouthampacha**
The binary name has a typo.

### CODE REVIEW

**Comment by gouthampacha** [comment]
I think this fix is appropriate to the branch csi-v1.0 as well. Please let me know, and I'll propose it there.

**Comment by gouthampacha** [comment]
PTAL @humblec @Madhu-1 @gman0

**Comment by Madhu-1** [comment]
@gouthampacha Thanks for the PR

**Comment by Madhu-1** [comment]
> I think this fix is appropriate to the branch csi-v1.0 as well. Please let me know, and I'll propose it there.

we will be working on the master branch and discarding csiv1.0 branch in a few days

**Pull request merged**
