### PR TITLE
Remove mount cache for cephfs

### PR DESCRIPTION
**Pull request by Madhu-1**
PR #282 introduces the mount cache to solve cephfs fuse mount issue when cephfs plugin pod
restarts. This is not working as intended. This PR removes the code for maintainability.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

## Related issues ##

Mention any github issues relevant to this PR. Adding below line
will help to auto close the issue once the PR is merged.

Updates  #824

### CODE REVIEW

**Comment by humblec** [comment]
> As the commit has "Fixes" keyword for the issue, it will close it automatically, we may want to track the issue to remove the deprecated option in the next release. I would suggest "Updates" as the keyword referencing the issue hence.

@madhu-1 can you address this ?  rest looks good to me. Thanks !

**Comment by Madhu-1** [comment]
@humblec done

**Comment by jianglingxia** [comment]
can somebody see the issue https://github.com/ceph/ceph-csi/issues/836
that v1.2.0 csi version used the cephfs and the mount-cache-dir function why only remounted one volume when csiplugin existed? but in the minion has many mountpath,thanks all!

**Comment by jianglingxia** [comment]
@Madhu-1  
can you help me ? now i found that when plugin restart the remountCachedVolumes function only remount one volume,cause the monion mount path transport endpoint is not connected

the code bug that follow 
func (nc *NodeCache) ForAll(pattern string, destObj interface{}, f ForAllFunc) error {
	err := nc.EnsureCacheDirectory(nc.CacheDir)
	if err != nil {
		return errors.Wrap(err, "node-cache: couldn't ensure cache directory exists")
	}
	files, err := ioutil.ReadDir(path.Join(nc.BasePath, nc.CacheDir))
	if err != nil {
		return errors.Wrapf(err, "node-cache: failed to read %s folder", nc.BasePath)
	}
	cachePath := path.Join(nc.BasePath, nc.CacheDir)
	for _, file := range files {
		err = decodeObj(cachePath, pattern, file, destObj)
		if err == errDec {
			continue
		} else if err == nil {
			if err = f(strings.TrimSuffix(file.Name(), filepath.Ext(file.Name()))); err != nil {
				return err
			}
		}
		return err   ----?this line?

	}
	return nil
}

**Pull request merged**
