### PR TITLE
rbd: use go-ceph to get mirroring info

### LINKED ISSUE #2558: rbd: rewrite `updateVolWithImageInfo()` to use go-ceph
ceph/go-ceph#448 (part of upcoming go-ceph v0.12) adds support for `GetImageMirrorMode()` which can be used to rewrite

https://github.com/ceph/ceph-csi/blob/8ebc0659ab706f1b033876327d2b5c96dc74d9c5/internal/rbd/rbd_util.go#L1478-L1509

Using go-ceph instead of the `rbd` command will reduce the chance on hitting resource limits and running into undefined behaviour.

### PR DESCRIPTION
**Pull request by Madhu-1**
use go-ceph API to get image mirroring info.

closes #2558

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Review by yati1998 — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Comment by Madhu-1** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.22

`Error from server: error when creating "https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.0.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml": etcdserver: request timed out`

**Review by humblec — APPROVED** [review]

**Comment by Madhu-1** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.22

`Error from server: error when creating "https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.0.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml": etcdserver: request timed out`

**Pull request merged**
