### PR TITLE
rebase: workaround missing redirect

### PR DESCRIPTION
**Pull request by Madhu-1**
This fix is needed because we were hitting:
```
vbom.ml/util@v0.0.0-20180919145318-efcd4e0f9787:
unrecognized import path "vbom.ml/util":
reading https://vbom.ml/util?go-get=1: 503 Service Unavailable
```

Source for the workaround:
golang/dep#1169

The fix consists in simply enforcing what the redirect was supposed to do.
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by Yuggupta27** [comment]
E2E is catching the issues which is corrected by https://github.com/ceph/ceph-csi/pull/1368 ... Does the PR need rebasing?                       
```internal/rbd/rbd_util.go:556:52: undefined: csiConfigFile
internal/rbd/rbd_util.go:629:51: undefined: csiConfigFile
internal/rbd/rbd_util.go:713:51: undefined: csiConfigFile```

**Comment by Madhu-1** [comment]
@MergifyIO rebase

**Comment by Madhu-1** [comment]
@humblec @nixpanic containerized tests passed :partying_face:

**Comment by Madhu-1** [comment]
>[1;36mSummary:[0m
   Files: 53
   Lines: 13046
   Nosec: 18
  Issues: [1;32m0[0m

running: go mod verify
all modules verified

https://jenkins-ceph-csi.apps.ocp.ci.centos.org/job/containerized-tests/324/console

**Comment by Madhu-1** [comment]
> does this really not include any changed files under `vendor/`? that is hard to believe

No it doesn't include any file changes in vendor directory , can you please test it out locally if am missing anything

**Comment by Madhu-1** [comment]
> does this really not include any changed files under `vendor/`? that is hard to believe

In that case I expect ci to fail

**Pull request merged**
