### PR TITLE
ci: do not assume Docker is availble on the minikube host

### PR DESCRIPTION
**Pull request by nixpanic**
This is a backport of #1516 which depends on #1453. Mergify failed to backport #1516 automatically.

### CODE REVIEW

**Review by Madhu-1 — APPROVED** [review]

**Comment by nixpanic** [comment]
@Madhu-1 ah, this does not get merged by Mergify because I created this backport PR. It seems to require manual merging (or updated Mergify rules).

**Comment by Madhu-1** [comment]
> @Madhu-1 ah, this does not get merged by Mergify because I created this backport PR. It seems to require manual merging (or updated Mergify rules).

I merged it manually.

**Pull request merged**
