### PR TITLE
feat: Implement helm lint

### PR DESCRIPTION
**Pull request by wilmardo**
# Describe what this PR does #

Run helm lint against the helm charts

## Is there anything that requires special attention ##

Moved the helm charts to a sub directory otherwise helm lint errors on:

```
==> Linting deploy/cephfs/kubernetes/v1.13/helm/ceph-csi-cepfs
[ERROR] Chart.yaml: directory name (ceph-csi-cepfs) and chart name (ceph-csi-cephfs) must be the same
```

Thought about fixing this by using sed to change the chart name temporarily but that felt way more hack then necessary.

### CODE REVIEW

**Comment by Madhu-1** [comment]
@wilmardo can you add helm lint testing in CI?

**Comment by wilmardo** [comment]
@Madhu-1 It is already see:
https://travis-ci.org/ceph/ceph-csi/jobs/572233234#L483

I added it to `scripts/lint-text.sh` (scroll past all the move changes)

**Comment by Madhu-1** [comment]
@wilmardo didn't notice, Thanks for the Fix.

**Comment by Madhu-1** [comment]
@humblec PTAL

**Comment by humblec** [comment]
LGTM. Thanks @wilmardo !

**Pull request merged**
