### PR TITLE
Add nil check for process

### PR DESCRIPTION
**Pull request by Madhu-1**
# Describe what this PR does #

Add nil check for process
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

## Related issues ##
Fixes: https://github.com/ceph/ceph-csi/issues/455

### CODE REVIEW

**Comment by humblec** [comment]
@Madhu-1 whats missing in this fix ? Can you update the PR title on whats pending?

**Comment by Madhu-1** [comment]
@humblec nothing missing from the ceph-csi side, but during testing, we need to increase the pid count and check

updated partial Fix to Fix

**Comment by Madhu-1** [comment]
@nixpanic can you let us know how to increase the pid count?

**Comment by humblec** [comment]
@Madhu-1 For example :`ulimit -u 16384` or change the values in `limits.conf` will do .

**Comment by nixpanic** [comment]
The `ulimit` command will likely not work. The pid limit is configured by the container runtime (Docker, CRI-O, ..). Privileged containers can adjust the configuration through cgroups. A similar 'workaround' was done for containers that run many gluster volumes/processes (gluster/gluster-containers@05f7eb8a8750008f8c2f2f55ca873cc040e09d80).

**Comment by Madhu-1** [comment]
@ekuric can you try the step given by @nixpanic to configure pid limit

**Pull request merged**
