### PR TITLE
ci: prevent ERR trap inheritance for kubectl_retry

### PR DESCRIPTION
**Pull request by nixpanic**
`bash -E` causes inheritance of the ERR trap into shell functions,
command substitutions, and commands executed in a subshell environment.
Because the `kubectl_retry` function depends on detection an error of a
subshell, the ERR trap is not needed to be executed. The trap contains
extra logging, and exits the script in the `rook.sh` case. The aborting
of the script is not wanted when a retry is expected to be done.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

**Comment by nixpanic** [comment]
Somehow the `kubectl_retry` function still aborts early, sometimes, after a 1st failure. Trying to find out what the cause could be.

**Comment by nixpanic** [comment]
**ci/centos/mini-e2e-helm/k8s-1.22** failed with
```
Apr 28 14:30:36.425: backend images not matching kubernetes resource count,image count 23 kubernetes resource count 21
```

**Comment by nixpanic** [comment]
> /retest all

Rook deployment succeeded for all CI jobs, lets try a 2nd time

**Comment by nixpanic** [comment]
All tests passed nicely, at least one of the jobs required a retry while deploying Rook:
https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/k8s-e2e-external-storage-1.22/detail/k8s-e2e-external-storage-1.22/2244/pipeline/73#step-80-log-962

**Review by Rakshith-R — APPROVED** [review]

**Review by humblec — APPROVED** [review]

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.21

Failed with
```
May  4 05:50:18.857: FAIL: backend images not matching kubernetes resource count,image count 22 kubernetes resource count 21
```

**Comment by nixpanic** [comment]
@mergifyio requeue

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.22

Failed with
```
May  4 11:11:30.507: backend images not matching kubernetes resource count,image count 23 kubernetes resource count 21
```

**Comment by Madhu-1** [comment]
@mergifyio refresh

**Comment by Madhu-1** [comment]
@Mergifyio requeue

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Pull request merged**
