### PR TITLE
cephfs: upgrade fscrypt version to fix concurrency issue

### LINKED ISSUE #4592: Concurrency issue when provisioning multiple encrypted CephFS instances
When creating multiple pods with separate PVC's the ceph-csi might fail to provision some of the encrypted cephfs instances.

The error from the pods logs is the following:

```
MountVolume.SetUp failed for volume "pvc-443ef844-03ce-4b87-affe-a802009aa915" : rpc error: code = Internal desc = no fscrypt policy set on directory "/var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com/32418680d66053d8dac8f56697397c8f91f36ca386dbb8d0a0d642bb76609721/globalmount/ceph-csi-encrypted": file or directory "/var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com/32418680d66053d8dac8f56697397c8f91f36ca386dbb8d0a0d642bb76609721/globalmount/ceph-csi-encrypted" is not encrypted   
```

From this it seems setting up the encryption fails in the ceph-csi from the cephfs-csi plugin logs this can be seen, which makes me suspect a concurrency issue:
```
E0426 12:53:04.134079       1 fscrypt.go:262] ID: 9782 Req-ID: 0001-0009-rook-ceph-0000000000000002-a3186144-9960-42dd-9fce-4cc125117e1a fscrypt: Failed to apply protector (see also kernel log): %!w(*actions.ErrDifferentFilesystem=&{0xc00157b130 0xc00208a140}) 
```

### Environment

This problem is reproducible in the rook development environment from master and kernel support can be setup for example by following the instructions that was provided in this PR #3460

The following bash script can be executed and the problem should be seen at least for me it happens every time without exception only variance is how many pods fail to deploy

```
#!/bin/bash

for i in {1..10}
do
    # Generate unique names for the pod and PVC using the counter variable
    pod_name="pod-$i"
    pvc_name="pvc-$i"

    echo "${pvc_name}"
    echo "${pod_name}"

    # Your command to create a pod and PVC with unique names
    cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: $pod_name
spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - mountPath: /var/myVolume
      name: my-volume
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: $pvc_name
EOF

    cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: $pvc_name
spec:
 storageClassName: rook-cephfs
 accessModes:
    - ReadWriteOnce
 resources:
    requests:
      storage: 1Gi
EOF
    # If sleep is uncommented this code runs without problems!
    # sleep 10 
done
```

I will try to debug this further but if anyone has any ideas or pointer regarding it I am all ears or if anyone has seen this by chance and has some ideas, thanks!

### PR DESCRIPTION
**Pull request by NymanRobin**
In older versions of fscrypt there is a race condition when multiple encrypted cephfs instances are deployed simultaneously.
This PR upgrades the fscrypt version to the latest version that contains a fix to the concurrency issue, used the commit sha as we cannot know when the next official release will happen from fscrypt side.

This PR fixes: #4592

### CODE REVIEW

**Review by Rakshith-R — DISMISSED** [review]
Thanks

**Review by Madhu-1 — DISMISSED** [review]

**Comment by Madhu-1** [comment]
@mergifyio queue

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
> > rebase
> 
> #### ❌ Pull request can't be updated with latest base branch changes
> Mergify needs the author permission to update the base branch of the pull request. @Nordix needs to [authorize modification on its head branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

@NymanRobin can you please check this one?

**Comment by NymanRobin** [comment]
Sure, I will check @Madhu-1

**Comment by NymanRobin** [comment]
I did a manual rebase, do you think that will do it? @Madhu-1

**Comment by Madhu-1** [comment]
@mergifyio queue

**Comment by Madhu-1** [comment]
> I did a manual rebase, do you think that will do it? @Madhu-1

i triggered bot, lets see how it goes :)

**Review by Madhu-1 — APPROVED** [review]

**Review by Rakshith-R — APPROVED** [review]

**Comment by Rakshith-R** [comment]
@Mergifyio queue

**Comment by NymanRobin** [comment]
Looks like there was a failure related to the network in one of [tests](https://jenkins-ceph-csi.apps.ocp.cloud.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.28/detail/mini-e2e_k8s-1.28/681/pipeline)? Would it be possible to retrigger it?

```
Error: Error downloading packages:
  Curl error (7): Couldn't connect to server for http://mirrorlist.centos.org/?release=8-stream&arch=x86_64&repo=AppStream&infra=ec2 [Failed to connect to mirrorlist.centos.org port 80: Connection refused]
script returned exit code 1
```

EDIT: Seems there was also another [test failure](https://jenkins-ceph-csi.apps.ocp.cloud.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.27/detail/mini-e2e_k8s-1.27/996/pipeline) that I am not exactly sure of what caused it

**Comment by Rakshith-R** [comment]
@iPraveenParihar please check and restart the tests

**Pull request merged**
