### PR TITLE
rebase: update Kubernetes modules to v1.27.4

### PR DESCRIPTION
**Pull request by nixpanic**
**Dependabot** complains about  Ceph-CSI being vulnerable to https://github.com/advisories/GHSA-f4w6-3rh6-6q4q . This is an old and addressed CSI sidecar issue, not related to the `k8s.io/kubernetes` module listed in `go.mod`. Is it possible that updating the Kubernetes modules helps?

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

### CODE REVIEW

**Review by Madhu-1 — DISMISSED** [review]
Not sure it helps but good to get the dependency to latest.

**Comment by nixpanic** [comment]
It doesn't seem to be enough. I also dismissed the warning, but that isn't sufficient either it seems.

**Comment by Rakshith-R** [comment]
> It doesn't seem to be enough. I also dismissed the warning, but that isn't sufficient either it seems.

It seems to be a glitch somewhere I think, 
as dependency check is not required by mergifyio rules, we should still be able to merge this pr.

**Review by Rakshith-R — DISMISSED** [review]

**Review by riya-singhal31 — DISMISSED** [review]

**Comment by Rakshith-R** [comment]
> This pull request now has conflicts with the target branch. Could you please resolve conflicts and force push the corrected changes? 

@nixpanic ^

**Review by Rakshith-R — APPROVED** [review]

**Review by riya-singhal31 — APPROVED** [review]

**Pull request merged**
