### PR TITLE
deploy: Add pod anti-affinity for provisioner deployments

### PR DESCRIPTION
**Pull request by nberlee**
Add pod anti-affinity for provisioner deployments so the operators pods are always spread across the cluster and thereby reducing node failure impact for csi-cephfsplugin-provisioner and csi-rbdplugin-provisioner

### CODE REVIEW

**Comment by nberlee** [comment]
```
Sep 21 07:35:31.245: INFO: deployment status: expected replica count 3 running replica count 1
```
In a one node cluster, like the ci-test, I would expect this.  If it is a hard requirement for a <3 node cluster to run with `replicas: 3` I can change the antiaffinity rule to `preferredDuringSchedulingIgnoredDuringExecution`.

But this will have a lesser effect.
Imagine running in 3 worker node, this would schedule the pods on all three. Now drain & cordon one, and uncordon it later
with `requiredDuringSchedulingIgnoredDuringExecution`: this will get 1 pod unscheduled, and let it run on the uncordoned node later.
with `preferredDuringSchedulingIgnoredDuringExecution`: 2 pods will be scheduled on one node, and this will not change anymore after uncordoning.

**Comment by Madhu-1** [comment]
> ```
> Sep 21 07:35:31.245: INFO: deployment status: expected replica count 3 running replica count 1
> ```
> 
> In a one node cluster, like the ci-test, I would expect this. If it is a hard requirement for a <3 node cluster to run with `replicas: 3` I can change the antiaffinity rule to `preferredDuringSchedulingIgnoredDuringExecution`.
> 
> But this will have a lesser effect.
> Imagine running in 3 worker node, this would schedule the pods on all three. Now drain & cordon one, and uncordon it later
> with `requiredDuringSchedulingIgnoredDuringExecution`: this will get 1 pod unscheduled, and let it run on the uncordoned node later.
> with `preferredDuringSchedulingIgnoredDuringExecution`: 2 pods will be scheduled on one node, and this will not change anymore after uncordoning.

We can update our E2E to wait for one replica count (as its enough to serve requests)

**Comment by humblec** [comment]
@nberlee this is a good change. We should not worry much about E2E. Also, adjusting the replica count as @Madhu-1 mentioned can be applied on e2e template too. Thats fine.. Can you please revisit this patch?

**Comment by nberlee** [comment]
@humblec  Great, I will revisit this patch today (end of the day)

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
Ci fails with the following error:
```
Error: template: ceph-csi-cephfs/templates/provisioner-deployment.yaml:28:7: executing "ceph-csi-cephfs/templates/provisioner-deployment.yaml" at <gt .Values.provisioner.replicaCount 1.0>: error calling gt: incompatible types for comparison
```

**Comment by nberlee** [comment]
> Ci fails with the following error:
> 
> ```
> Error: template: ceph-csi-cephfs/templates/provisioner-deployment.yaml:28:7: executing "ceph-csi-cephfs/templates/provisioner-deployment.yaml" at <gt .Values.provisioner.replicaCount 1.0>: error calling gt: incompatible types for comparison
> ```

Sorry i should have tested this, helm set `.Values.provisioner.replicaCount` as a float from `values.yaml` and as int from `--set` param. I will

**Review by nixpanic — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Pull request merged**
