### PR TITLE
deploy: update CSI sidecars to latest versions available

### PR DESCRIPTION
**Pull request by iPraveenParihar**
Below sidecars are updated with latest available versions

csi-node-driver-registrar: v2.9.1
csi-resizer: v1.9.2
csi-provisioner: v3.6.2
csi-attacher: v4.4.2
csi-snapshotter: v6.3.2

### CODE REVIEW

**Review by Rakshith-R — APPROVED** [review]
Thanks

**Comment by Rakshith-R** [comment]
@mergifyio rebase
@mergifyio queue

**Review by riya-singhal31 — APPROVED** [review]

**Pull request merged**
