### PR TITLE
deploy: remove unnecessary aggregate clusterroles

### PR DESCRIPTION
**Pull request by Madhu-1**
The aggregate clusterrole was designed for the scenario where the rules are not completely owned by one component.
the aggregate rules can be removed and simplify certain issues around upgrades.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
@travisn PTAL

**Comment by Madhu-1** [comment]
@Mergifyio rebase

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
Rebased PR manually

**Comment by nixpanic** [comment]
With Travis' +1, adding `[ready-to-merge]`.

**Pull request merged**
