### PR TITLE
travis: split static checks and continue with tests in case one fails

### PR DESCRIPTION
**Pull request by nixpanic**
Run all `make static-checks`, even in case one fails.

### CODE REVIEW

**Comment by nixpanic** [comment]
Well, that contradicts with the `make static-check` target. It has a list of checks, and it will abort execution in case one test fails. Shall we split that up in multiple executions then?

**Comment by Madhu-1** [comment]
> Well, that contradicts with the `make static-check` target. It has a list of checks, and it will abort execution in case one test fails. Shall we split that up in multiple executions then?

Yes we can split it

**Comment by nixpanic** [comment]
Updated to split the `make static-checks`, and run them all in case one fails.

**Comment by humblec** [comment]
LGTM..thanks

**Pull request merged**
