### PR TITLE
ci: Update golangci-lint to v1.46.2

### PR DESCRIPTION
**Pull request by Madhu-1**
Update golangci-lint to v1.46.2 skipped a few complicated checks which need more time to fix and fixed all other linter errors.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Review by yati1998 — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Review by humblec — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergify requeue

**Comment by Madhu-1** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.23

```
 Jun  1 18:10:12.573: backend images not matching kubernetes resource count,image count 23 kubernetes resource count 21

    backend image Info:

     [csi-vol-939cf562-e1cd-11ec-a4a1-46d5376161c4 csi-vol-95f8c6c2-e1cd-11ec-a4a1-46d5376161c4 csi-vol-95f8c6c2-e1cd-11ec-a4a1-46d5376161c4-temp csi-vol-96172620-e1cd-11ec-a4a1-46d5376161c4 csi-vol-96172620-e1cd-11ec-a4a1-46d5376161c4-temp csi-vol-96357a03-e1cd-11ec-a4a1-46d5376161c4 csi-vol-96357a03-e1cd-11ec-a4a1-46d5376161c4-temp csi-vol-9654290f-e1cd-11ec-a4a1-46d5376161c4 csi-vol-9654290f-e1cd-11ec-a4a1-46d5376161c4-temp csi-vol-96728f24-e1cd-11ec-a4a1-46d5376161c4 csi-vol-96728f24-e1cd-11ec-a4a1-46d5376161c4-temp csi-vol-998f59bd-e1cd-11ec-a4a1-46d5376161c4 csi-vol-998f59bd-e1cd-11ec-a4a1-46d5376161c4-temp csi-vol-99b0625b-e1cd-11ec-a4a1-46d5376161c4 csi-vol-99b0625b-e1cd-11ec-a4a1-46d5376161c4-temp csi-vol-99e56035-e1cd-11ec-a4a1-46d5376161c4 csi-vol-99e56035-e1cd-11ec-a4a1-46d5376161c4-temp csi-vol-9a0c8c54-e1cd-11ec-a4a1-46d5376161c4 csi-vol-9a0c8c54-e1cd-11ec-a4a1-46d5376161c4-temp csi-vol-9a3e3576-e1cd-11ec-a4a1-46d5376161c4 csi-vol-9a3e3576-e1cd-11ec-a4a1-46d5376161c4-temp csi-vol-a494911e-e1cd-11ec-a4a1-46d5376161c4 csi-vol-a494911e-e1cd-11ec-a4a1-46d5376161c4-temp]
```

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
@mergifyio requeue

**Comment by Madhu-1** [comment]
> /retest ci/centos/mini-e2e/k8s-1.23

Rook deployment [failure](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.23/detail/mini-e2e_k8s-1.23/1849/pipeline)

**Comment by pkalever** [comment]
@mergifyio refresh

**Pull request merged**
