### PR TITLE
deploy: update templates to v3.10.1

### PR DESCRIPTION
**Pull request by riya-singhal31**
This commit updates templates to new
v3.10.1 release.

### CODE REVIEW

**Review by nixpanic — CHANGES_REQUESTED** [review]
Please update the README.md with the new version too

**Comment by riya-singhal31** [comment]
> Please update the README.md with the new version too

Updated, thanks.
PTAL.

**Review by nixpanic — APPROVED** [review]
LGTM, @Rakshith-R can you check this too?

**Comment by nixpanic** [comment]
@mergifyio rebase

**Review by yati1998 — APPROVED** [review]

**Comment by riya-singhal31** [comment]
@Mergifyio rebase

**Comment by riya-singhal31** [comment]
@Mergifyio queue

**Pull request merged**
