### PR TITLE
e2e: retry getting the Services for Ceph MON on failures

### PR DESCRIPTION
**Pull request by nixpanic**
In case listing the Kubernetes Services fails, the following error is
returned immediately:

    failed to create configmap with error failed to list services: etcdserver: request timed out

Wrapping the listing of the Services in a PollImmediate() routine, adds
a retry in case of common temporary issues.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

**Review by yati1998 — COMMENTED** [review]
LGTM

**Review by pkalever — APPROVED** [review]

**Review by Madhu-1 — DISMISSED** [review]

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.20

Failed to start minikube #2264

**Comment by nixpanic** [comment]
@mergifyio rebase

**Review by Madhu-1 — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

e2e failures fixed with #2349

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.21

Also failed with #2264

**Pull request merged**
