### PR TITLE
helm: align seLinuxMount option w/ deploy folder

### PR DESCRIPTION
**Pull request by sebhoss**
# Describe what this PR does #

This aligns the CSIDriver configuration in the helm charts with the change introduced by c0201e493b7052cb1ec6ef2cecffd8e4cdb49157

## Is there anything that requires special attention ##

This change is necessary for https://kubernetes.io/blog/2023/04/18/kubernetes-1-27-efficient-selinux-relabeling-beta/ to work while using the helm chart.

## Related issues ##

Relates to #3855

## Future concerns ##

**Checklist:**

* [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#commit-messages).
* [ ] Reviewed the developer guide on [Submitting a Pull Request](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#development-workflow)
* [ ] [Pending release notes](https://github.com/ceph/ceph-csi/blob/devel/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next major release.
* [ ] Documentation has been updated, if necessary.
* [ ] Unit tests have been added, if necessary.
* [ ] Integration tests have been added, if necessary.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

* `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

### CODE REVIEW

**Review by Rakshith-R — DISMISSED** [review]
Thanks!

**Review by riya-singhal31 — DISMISSED** [review]

**Comment by riya-singhal31** [comment]
@Mergifyio queue

**Comment by sebhoss** [comment]
@riya-singhal31 thanks for review & triggering the merge. The failed job said:

> Unable to update: user sebhoss is unknown.
> 
> Please make sure sebhoss has logged in Mergify dashboard.

So I logged into Mergify & it should work now? Can you re-trigger this to try again?

**Comment by riya-singhal31** [comment]
@Mergifyio queue

**Comment by riya-singhal31** [comment]
@mergifyio refresh

**Comment by sebhoss** [comment]
Rebased on latest devel branch

**Review by Rakshith-R — APPROVED** [review]

**Comment by Rakshith-R** [comment]
@mergifyio rebase

**Review by riya-singhal31 — APPROVED** [review]

**Comment by riya-singhal31** [comment]
@mergifyio queue

**Comment by sebhoss** [comment]
The failing tests all got a timeout while talking to a container registry. I'm guessing that this is not related to the change in this PR. @Rakshith-R / @riya-singhal31: Can you retrigger these tests once more? :cold_sweat:

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio queue

**Pull request merged**
