### PR TITLE
cleanup: Remove support for Delete and Unmounting v1.1.0 PVC

### LINKED ISSUE #882: Remove support for PVC created by v1.0.0 CSI driver
currently, we have support for the mounting and deleting the PVC created by v1.0.0 CSI driver. we need to drop the support for the same.

we are yet to decide in which release we are deprecating and removing it

### PR DESCRIPTION
**Pull request by Madhu-1**
as v1.0.0 is deprecated we need to remove the support for it in the Next coming (v3.0.0) release. This PR removes the support for the same.

closes #882

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

as per @gman0 request https://github.com/ceph/ceph-csi/issues/882#issuecomment-609925244 we are keeping the support to specify the `rootpath` and `monitors` in cephfs NodeStage.

### CODE REVIEW

**Comment by Madhu-1** [comment]
> Looks good to me. Definitely needs mentioning in the release notes!

will take care of it. Thanks

**Comment by Madhu-1** [comment]
Added dnm so that @gman0 @ShyamsundarR can take a look at it.

**Comment by gman0** [comment]
@Madhu-1 thanks! I'll have a look in a bit.

**Comment by gman0** [comment]
I've tested Node{Stage,Publish}Volume locally with `mounter` and `rootPath` in volume context, everything seems to be working fine.

The code looks ok as well, but I have a suggestion. [internal/cephfs/volumeoptions.go](https://github.com/Madhu-1/ceph-csi/blob/remove-v1.0.0-sup/internal/cephfs/volumeoptions.go) implements, besides other things, functions for creating `volumeOptions`/`volumeIdentifier` from following sources:
* CSI's `CreateVolumeRequest`: [`newVolumeOptions`](https://github.com/Madhu-1/ceph-csi/blob/0a0dad37726d24592d14f1492d804e0d1ed19eb2/internal/cephfs/volumeoptions.go#L146)
* volume ID: [`newVolumeOptionsFromVolID`](https://github.com/Madhu-1/ceph-csi/blob/0a0dad37726d24592d14f1492d804e0d1ed19eb2/internal/cephfs/volumeoptions.go#L222)
* static volume: [`newVolumeOptionsFromStaticVolume`](https://github.com/Madhu-1/ceph-csi/blob/0a0dad37726d24592d14f1492d804e0d1ed19eb2/internal/cephfs/volumeoptions.go#L366)
* and lastly, v1 context: [`newVolumeOptionsFromVersion1Context`](https://github.com/Madhu-1/ceph-csi/blob/0a0dad37726d24592d14f1492d804e0d1ed19eb2/internal/cephfs/volumeoptions.go#L313)

Now that support for v1 is discontinued, name of the function `newVolumeOptionsFromVersion1Context` IMHO loses its meaning. Maybe if not now, it surely will in the future. Would it make sense to rename it to something more descriptive? It creates `volumeOptions` based on the presence of list of monitor addresses in the volume context - so how about `newVolumeOptionsFromMonitorList` or something like that? A year from now it might not be all that clear what those options in v1 volume context were, so a better name would definitely help, and also it would guard against accidental deletion of this function during some cleaning of legacy code.

If you agree, then those two comments [here](https://github.com/Madhu-1/ceph-csi/blob/0a0dad37726d24592d14f1492d804e0d1ed19eb2/internal/cephfs/nodeserver.go#L97-L105) could use an update: `newVolumeOptionsFromStaticVolume` gets mon IPs from the supplied cluster info, and `newVolumeOptionsFromVersion1Context` (or rather `newVolumeOptionsFromMonitorList`) retrieves those IPs directly from volume context.

**Comment by Madhu-1** [comment]
Thanks for confirming @gman0, will get this in and will send a patch to rename the functions.

**Comment by gman0** [comment]
@Madhu-1 super, thank you!

**Comment by ShyamsundarR** [comment]
lgtm! Not scoring as I did not do a detailed review, changes and removal looks fine. Thanks.

**Pull request merged**
