### PR TITLE
add validation to check if stagingPath exists

### PR DESCRIPTION
**Pull request by Madhu-1**
# Describe what this PR does #

It's CO responsibility to create the staging path as per the CSI spec.

The CO SHALL ensure  that the path is directory and that the process serving the request has `read` and `write` permission to that directory. The CO SHALL be responsible for creating the directory if it does not exist.
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

Fixes: #485

### CODE REVIEW

**Comment by humblec** [comment]
@Madhu-1 can you cleanup the PR description. Rest looks good to me.

**Comment by Madhu-1** [comment]
@humblec done

**Comment by humblec** [comment]
Thanks . LGTM.

**Comment by humblec** [comment]
@ShyamsundarR @poornimag  PTAL .

**Comment by Madhu-1** [comment]
@humblec I have added some more validation PTAL

**Comment by Madhu-1** [comment]
@humblec @ShyamsundarR @poornimag rebased PTAL

**Comment by Madhu-1** [comment]
@ShyamsundarR in the CSI spec  I didn't find anything related to ` CO's responsibility to delete the stagingPath`. so deleting it

**Comment by ShyamsundarR** [comment]
> @ShyamsundarR in the CSI spec I didn't find anything related to ` CO's responsibility to delete the stagingPath`. so deleting it

If it is not the plugin's responsibility to create it, it is not the plugins responsibility to delete it as well. I would hence suggest we fix the deletion in unstage as well.

**Comment by Madhu-1** [comment]
@ShyamsundarR done PTAL

**Comment by Madhu-1** [comment]
@ShyamsundarR PTAL

**Comment by humblec** [comment]
@ShyamsundarR Can you please review this ?

**Pull request merged**
