### PR TITLE
Fix CI failure for gometalinter

### PR DESCRIPTION
**Pull request by Madhu-1**
Signed-off-by: Madhu Rajanna <mrajanna@redhat.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
https://github.com/ceph/ceph-csi/pull/156#issuecomment-460260765

**Comment by Madhu-1** [comment]
@rootfs PTAL, this fixes CI failure

**Comment by rootfs** [comment]
indeed :)

**Comment by leseb** [comment]
@rootfs you should have approuved and mergify would have merged it for you :-)

**Pull request merged**
