### PR TITLE
deploy: allow mkfsOptions

### PR DESCRIPTION
**Pull request by Sea-you**
# Describe what this PR does #
- Allows configuration of `mkfsOptions` parameter in the ceph-csi-rbd chart.

## Is there anything that requires special attention ##

Do you have any questions? False

Is the change backward compatible? True

Are there concerns around backward compatibility? False

Provide any external context for the change, if any.

For example:

*  It was present in the examples, but was missing from the chart.

## Related issues ##

N/A
## Future concerns ##

List items that are not part of the PR and do not impact it's
functionality, but are work items that can be taken up subsequently.

**Checklist:**

* [x] **Commit Message Formatting**: Commit titles and messages follow
  guidelines in the [developer
  guide](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#commit-messages).
* [x] Reviewed the developer guide on [Submitting a Pull
  Request](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#development-workflow)
* [ ] [Pending release
  notes](https://github.com/ceph/ceph-csi/blob/devel/PendingReleaseNotes.md)
  updated with breaking and/or notable changes for the next major release.
* [x] Documentation has been updated, if necessary.
* [ ] Unit tests have been added, if necessary.
* [ ] Integration tests have been added, if necessary.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

* `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

### CODE REVIEW

**Review by Madhu-1 — APPROVED** [review]

**Review by riya-singhal31 — APPROVED** [review]

**Comment by riya-singhal31** [comment]
@Mergifyio queue

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio queue

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.27

Unrelated(?) failure:
```
  Nov  9 12:43:03.487: INFO: Waiting for PV pvc-df79f100-e412-408e-af7a-b8e3c8d443cf to bind to PVC rbd-pvc
  Nov  9 12:43:03.487: INFO: Waiting up to timeout=10m0s for PersistentVolumeClaims [rbd-pvc] to have phase Bound
  Nov  9 12:43:03.489: INFO: PersistentVolumeClaim rbd-pvc found and phase=Bound (1.875492ms)
  Nov  9 12:43:03.489: INFO: Waiting up to 10m0s for PersistentVolume pvc-df79f100-e412-408e-af7a-b8e3c8d443cf to have phase Bound
  Nov  9 12:43:03.491: INFO: PersistentVolume pvc-df79f100-e412-408e-af7a-b8e3c8d443cf found and phase=Bound (1.794611ms)
  W1109 12:43:03.499504   91009 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "web-server" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "web-server" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "web-server" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "web-server" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
  Nov  9 12:43:03.499: INFO: Waiting up to csi-rbd-demo-pod to be in Running state
  Nov  9 12:53:03.500: INFO: failed to write data in the pod: context deadline exceeded
  Nov  9 12:53:03.500: INFO: >>> kubeConfig: /root/.kube/config
  [38;5;9m[FAILED][0m in [It] - /go/src/github.com/ceph/ceph-csi/e2e/utils.go:1125 [38;5;243m@ 11/09/23 12:53:03.507[0m
```

[logs](https://jenkins-ceph-csi.apps.ocp.cloud.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.27/detail/mini-e2e-helm_k8s-1.27/536/pipeline)

**Comment by nixpanic** [comment]
@mergifyio requeue

**Pull request merged**
