### PR TITLE
deploy: update external resizer to v1.5.0

### PR DESCRIPTION
**Pull request by humblec**
Refer#
https://github.com/kubernetes-csi/external-resizer/releases/tag/v1.5.0

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
Image is yet to be available.. so please hold the review

**Comment by humblec** [comment]
@Mergifyio rebase

**Review by Madhu-1 — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
Please only add the **ci/retry/e2e** label to a single PR at the time, don't burn unneeded CI resources

**Comment by humblec** [comment]
> Please only add the **ci/retry/e2e** label to a single PR at the time, don't burn unneeded CI resources

noted. sure.. thanks

**Pull request merged**
