### PR TITLE
util: fix logging in ExecuteCommandWithNSEnter

### PR DESCRIPTION
**Pull request by Madhu-1**
log the nsenter and its argument after executing the command with the nsenter CLI.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

Note:- Skipping E2E as this function will not get hit in E2E tests.

### CODE REVIEW

**Review by Rakshith-R — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio refresh

**Comment by Madhu-1** [comment]
@mergifyio refresh

**Comment by Madhu-1** [comment]
@mergifyio refresh

**Pull request merged**
