### PR TITLE
remove deployment.yaml

### PR DESCRIPTION
**Pull request by Madhu-1**
currently, we have `pvc.yaml` for creating PVC and `pod.yaml` to show to mount PVC to an app. removing deployment.yaml in favor of `pvc.yaml` and `pod.yaml`

### CODE REVIEW

**Comment by Madhu-1** [comment]
@gman0 PTAL

**Comment by humblec** [comment]
@Madhu-1 I am bit skeptical here. That said, imo, having or keeping deployment yaml in this repo is good.

**Comment by Madhu-1** [comment]
> @Madhu-1 I am bit skeptical here. That said, imo, having or keeping deployment yaml in this repo is good.

@humblec what advantage we are going to get if we keep deployment.yaml?

IMO in the current deployment and pod files, the usage of PVC seems to be the same for me.  there is no difference in it

**Comment by humblec** [comment]
> > @Madhu-1 I am bit skeptical here. That said, imo, having or keeping deployment yaml in this repo is good.
> 
> @humblec what advantage we are going to get if we keep deployment.yaml?
> 
The deployment is actually the way of bringing a workload to kubernetes. That said, in a cluster someone will deploy pod via deployment artifact compared to pod artifact.

**Comment by rootfs** [comment]
I believe it makes sense to keep both Pod and Deployment here: Pod example can be used to build e.g. StatefulSet and DaemonSet, while Deployment itself is such an example.

**Comment by Madhu-1** [comment]
closing as per the comments.

**Pull request closed without merging**
